/* RECOUNT QUEST — REAL EVENTS (Factual Recount): smong, cleanup, rescue.
   Each text is based on the sources listed in RQ.sources (data.js). Content revision 1. */
(function () {
  "use strict";
  var q = RQ.q, E = RQ.data.episodes;

  /* ================================================================= 1. WHEN THE GROUND STARTED TO SHAKE */
  E.push({
    id: "smong", world: "factual", icon: "🏝️", title: "When the Ground Started to Shake", theme: "Disaster preparedness", rev: 1,
    badge: {"icon":"🌊","name":"Prepared Reader"},
    focus: ["Factual recount","Cause and effect","Inference","Main idea"],
    visual: {"type":"timeline","title":"The smong story","caption":"Important moments in the story of smong on Simeulue.","items":[{"e":"🌊","y":"1907","l":"A tsunami hits Simeulue"},{"e":"🗣️","y":"After 1907","l":"Survivors tell the smong stories"},{"e":"🌍","y":"26 Dec 2004","l":"A very strong earthquake"},{"e":"⛰️","y":"26 Dec 2004","l":"People move to higher ground"},{"e":"📜","y":"Oct 2005","l":"UN gives a Certificate of Merit"}]},
    paras: [
      "Simeulue is an island off the coast of Aceh, in the north of Sumatra. It lies in the Indian Ocean. On 26 December 2004, a very strong earthquake shook the sea near Sumatra. It caused a huge tsunami in the Indian Ocean. More than 200,000 people died in 14 countries. Aceh was one of the worst-hit places.",
      "The people of Simeulue already knew about big tsunamis. In 1907, a tsunami hit the island and killed many people. The survivors did not write the story in books. They told it to their children and grandchildren. On Simeulue, the word for tsunami is smong. The smong stories gave a clear warning. After a strong earthquake, if the sea pulls back, go to higher ground at once.",
      "On the morning of 26 December 2004, the ground on Simeulue shook strongly. Many people remembered the smong stories. They left the coast and moved to higher ground. Soon after, the tsunami hit the island.",
      "Because people moved to higher ground, almost everyone on Simeulue survived. Fewer than ten people on the island died. In other parts of Aceh, many more people died. Researchers later studied how the island’s people had stayed safe.",
      "In October 2005, the United Nations gave the Simeulue community a Certificate of Merit. It praised community leaders for keeping people aware of disaster risks and ready for them. Today, people on Simeulue still share the smong message, for example in songs. Some people on the island say that it must be passed on to young people. The story of smong shows that traditional knowledge can protect lives."
    ],
    vocab: [{"w":"tsunami","m":"a very big wave caused by an earthquake under the sea"},{"w":"survivors","m":"people who stay alive after a disaster"},{"w":"warning","m":"something that tells people about danger"},{"w":"higher ground","m":"land that is higher than the area around it"},{"w":"traditional","m":"passed down from older people to younger people"},{"w":"certificate","m":"an official paper that shows a person or group has achieved something"}],
    track: { intro: "Put these events in the order they happened.", why: "The story starts with the 1907 tsunami, moves to the earthquake of 2004 and ends with the United Nations certificate.",
      events: [{"t":"A tsunami hit Simeulue and killed many people.","clue":"This is the earliest event: 1907."},{"t":"The survivors told their children and grandchildren what happened.","clue":"This happened after the 1907 tsunami."},{"t":"A very strong earthquake shook the ground on Simeulue.","clue":"26 December 2004, in the morning."},{"t":"People left the coast and moved to higher ground.","clue":"They did this after the shaking."},{"t":"The tsunami hit the island.","clue":"“Soon after…”"},{"t":"The United Nations gave the community a Certificate of Merit.","clue":"October 2005."}] },
    details: [
      q.mcq("explicit", "What does the text say people on Simeulue call a tsunami?", ["Smong","Simeulue","Aceh","Sumatra"], 0, "Paragraph 2: “On Simeulue, the word for tsunami is smong.”"),
      q.mcq("explicit", "In which year did an earlier tsunami hit Simeulue?", ["1907","1917","2004","2005"], 0, "Paragraph 2: “In 1907, a tsunami hit the island and killed many people.”"),
      q.tf("The survivors of the 1907 tsunami wrote their story in books.", false, "Paragraph 2: “The survivors did not write the story in books. They told it to their children and grandchildren.”"),
      q.tf("Fewer than ten people on Simeulue died in the 2004 tsunami.", true, "Paragraph 4: “Fewer than ten people on the island died.”"),
      q.ma("explicit", "Which TWO things did the smong warning describe?", ["A strong earthquake","The sea pulling back","A very high wave","A loud noise from the sea"], [0, 1], "Paragraph 2: “After a strong earthquake, if the sea pulls back, go to higher ground at once.”"),
      q.match("Match each time with the event.", [["1907","A tsunami killed many people on Simeulue"],["26 December 2004","A very strong earthquake shook the sea near Sumatra"],["October 2005","The United Nations gave the community a Certificate of Merit"],["Today","People on Simeulue still share the smong message"]], "Each time is stated in the text."),
      q.mcq("visual", "Look at the timeline. What happened after the 1907 tsunami and before the 2004 earthquake?", ["Survivors told the smong stories.","People moved to higher ground.","The United Nations gave a certificate.","Researchers studied the island."], 0, "The timeline shows the smong stories between 1907 and 2004.", {"viz":true})
    ],
    detective: [
      q.para("Reorientation", 5, [2,3,4,5], "Paragraph 5 looks back and says what the story shows today."),
      q.sort("Simeulue is an island off the coast of Aceh, in the north of Sumatra.", "O"),
      q.sort("The story of smong shows that traditional knowledge can protect lives.", "R"),
      q.mcq("reference", "In the second sentence, “They” refers to…", ["The survivors","The books","The children","The researchers"], 0, "The sentence before is about the survivors. They told the story to their children and grandchildren.", {"quote":"The survivors did not write the story in books. They told it to their children and grandchildren."}),
      q.mcq("vocab", "The word “survivors” is closest in meaning to…", ["people who stay alive after a disaster","people who study a disaster later","people who help after a disaster","people who leave an island by boat"], 0, "The 1907 survivors lived through the tsunami and told the story afterwards.", {"quote":"The survivors did not write the story in books."}),
      q.mcq("evidence", "Which sentence best shows that smong was passed from older to younger people?", ["They told it to their children and grandchildren.","In 1907, a tsunami hit the island and killed many people.","On Simeulue, the word for tsunami is smong.","Researchers later studied how the island’s people had stayed safe."], 0, "Telling the story to children and grandchildren is passing it on."),
      q.mcq("signal", "Which phrase tells us when the strong shaking happened?", ["On the morning of 26 December 2004","In 1907, long before the earthquake","In October 2005, after the tsunami","Today, many years after the tsunami"], 0, "Paragraph 3: “On the morning of 26 December 2004, the ground on Simeulue shook strongly.”")
    ],
    deeper: [
      q.mcq("inference", "Why did almost everyone on Simeulue survive?", ["They remembered the old warning and moved uphill.","They lived far away from the coast of the island.","They heard a warning from a siren in the village.","They left the island in boats before the waves came."], 0, "Many people remembered the smong stories and moved to higher ground. The text does not mention sirens or boats."),
      q.mcq("evidence", "Which sentence best shows that people remembered the old warning?", ["Many people remembered the smong stories.","Aceh was one of the worst-hit places.","In 1907, a tsunami hit the island and killed many people.","Researchers later studied how the island’s people had stayed safe."], 0, "This sentence shows the old warning was remembered in 2004."),
      q.mcq("cause", "Why was the smong warning still known in 2004?", ["Survivors of 1907 told it to later generations.","It was printed in school books on the island.","Scientists taught it to the islanders in 2004.","The government announced it on the radio in 2004."], 0, "Paragraph 2: the survivors told the story to their children and grandchildren."),
      q.mcq("inference", "What can we infer about the smong warning?", ["It was clear and easy to act on.","It was too complicated for children.","It was known to a few families.","It came from a modern warning system."], 0, "The warning says exactly what to do: go to higher ground at once."),
      q.mcq("inference", "What can we infer from the United Nations Certificate of Merit?", ["People saw the community’s preparation as important.","The tsunami did not reach the coast of Simeulue.","Simeulue built a new warning system for Aceh.","The community received money for new houses."], 0, "The text says the certificate praised community leaders for keeping people aware of disaster risks and ready for them.")
    ],
    challenge: [
      q.mcq("main", "What is the main idea of this text?", ["An old warning helped people on Simeulue survive in 2004.","A huge tsunami destroyed the whole island of Simeulue.","Scientists built a warning system for the coast of Aceh.","People left Simeulue for good after the 2004 tsunami."], 0, "The text shows how the smong warning helped people to survive."),
      q.mcq("main", "Which sentence best sums up paragraph 2?", ["People on Simeulue knew about tsunamis and had a clear warning.","A very strong earthquake caused a huge tsunami in the Indian Ocean.","Most people on Simeulue survived the huge tsunami of 2004.","The United Nations praised the Simeulue community in 2005."], 0, "Paragraph 2 is about the 1907 tsunami and the smong stories."),
      q.mcq("purpose", "Why was this text written?", ["To inform readers about a real event and its lesson","To entertain readers with a story about an island","To persuade readers to travel to Aceh and Simeulue","To explain how scientists measure earthquakes"], 0, "It reports a real event with dates and facts."),
      q.mcq("purpose", "Why does the writer include paragraph 2?", ["To explain the tradition that later helped people","To describe the damage in other parts of Aceh","To report what the United Nations said in 2005","To explain how researchers studied the island"], 0, "Paragraph 2 explains the 1907 tsunami and the smong stories that helped in 2004."),
      q.mcq("cause", "Why did many people leave the coast after the earthquake?", ["They remembered the smong stories.","They were told to leave by village leaders.","They had practised a drill at school.","They heard a loud noise from the sea."], 0, "Paragraph 3: “Many people remembered the smong stories. They left the coast and moved to higher ground.”"),
      q.mcq("cause", "What was the effect of people moving to higher ground?", ["Almost everyone on Simeulue survived.","The tsunami did not reach the island.","The houses on the island were not damaged.","Everyone in Aceh was safe."], 0, "Paragraph 4: “Because people moved to higher ground, almost everyone on Simeulue survived.”"),
      q.mcq("sequence", "Which event happened first?", ["A tsunami hit Simeulue in 1907.","A very strong earthquake shook Simeulue.","The United Nations gave a certificate.","Researchers studied the island."], 0, "The 1907 tsunami came long before the other events."),
      q.mcq("vocab", "In paragraph 2, “warning” means…", ["something that tells people about danger","something that people write in a book","something that people build near the sea","something that people sing at festivals"], 0, "The smong stories told people what to do when danger came.", {"quote":"The smong stories gave a clear warning."}),
      q.mcq("inference", "What can we infer about the people of Simeulue?", ["They trusted the knowledge of older people.","They did not believe in old stories.","They wanted to leave the island after 1907.","They kept away from the sea."], 0, "They remembered and used the story told by earlier generations.")
    ]
  });

  /* ================================================================= 2. ONE DAY, MILLIONS OF HANDS */
  E.push({
    id: "cleanup", world: "factual", icon: "🧹", title: "One Day, Millions of Hands", theme: "Environmental action", rev: 1,
    badge: {"icon":"♻️","name":"Clean-up Reader"},
    focus: ["Factual recount","Chronology","Evidence","Purpose"],
    visual: {"type":"timeline","title":"World Cleanup Day","caption":"Important moments in the story of the first World Cleanup Day.","items":[{"e":"🇪🇪","y":"2008","l":"Estonians clean up their country"},{"e":"🌍","y":"15 Sep 2018","l":"First World Cleanup Day"},{"e":"🏖️","y":"15 Sep 2018","l":"Cleanup at Padang Galak Beach, Bali"},{"e":"📣","y":"After the event","l":"Organisers say Indonesia had the most volunteers"},{"e":"🔁","y":"Since 2018","l":"The event continues every year"}]},
    paras: [
      "On 15 September 2018, people in many countries joined the first World Cleanup Day. It was a Saturday. On this day, volunteers picked up rubbish together. The idea began in Estonia. In 2008, more than 50,000 volunteers there cleaned up their country in one day. They collected about 10,000 tons of illegal waste.",
      "After that, an organisation based in Estonia invited people around the world to clean up on the same day. In 2018, millions of volunteers took part in more than 100 countries. In each country, local volunteers and partners organised the cleanups. In Indonesia, many groups helped to organise cleanups. They included government offices, environmental groups and local communities.",
      "On 15 September, cleanups took place at the same time in 34 provinces of Indonesia. Volunteers cleaned up cities, towns and coastal areas. In Bali, volunteers and officials collected rubbish at Padang Galak Beach. The officials came from the Ministry of Marine Affairs and Fisheries and the Bali provincial government. They worked with Ocean Conservancy, an international environmental organisation. Hundreds of volunteers were expected to join them. The volunteers also recorded what kinds of rubbish they found in a database.",
      "After the event, the organisers said that more people joined in Indonesia than in any other country. According to them, this was the largest group of volunteers in the world.",
      "World Cleanup Day has continued every year since 2018. One day of cleaning cannot solve the problem of waste. However, the event showed that millions of people were ready to act together."
    ],
    vocab: [{"w":"volunteers","m":"people who do a job to help others without being paid"},{"w":"rubbish","m":"things that people throw away"},{"w":"illegal","m":"against the law"},{"w":"organisation","m":"a group of people who work together for a purpose"},{"w":"officials","m":"people who have important jobs in government"},{"w":"organisers","m":"the people who plan and run an event"}],
    track: { intro: "Put these events in the order they happened.", why: "The idea began in Estonia in 2008, spread to the world, and the organisers reported the results afterwards.",
      events: [{"t":"More than 50,000 people in Estonia cleaned up their country in one day.","clue":"The idea began here, in 2008."},{"t":"An organisation in Estonia invited people around the world to clean up on the same day.","clue":"“After that…”"},{"t":"Volunteers in many countries joined the first World Cleanup Day.","clue":"15 September 2018."},{"t":"Volunteers and officials collected rubbish at Padang Galak Beach in Bali.","clue":"This was on the day of the event."},{"t":"The organisers said that more people joined in Indonesia than in any other country.","clue":"“After the event…”"},{"t":"World Cleanup Day continued every year.","clue":"Since 2018."}] },
    details: [
      q.mcq("explicit", "On which date was the first World Cleanup Day?", ["15 September 2018","15 September 2008","15 May 2018","15 September 2019"], 0, "Paragraph 1: “On 15 September 2018, people in many countries joined the first World Cleanup Day.”"),
      q.mcq("explicit", "In which country did the idea begin?", ["Estonia","Latvia","Sweden","Indonesia"], 0, "Paragraph 1: “The idea began in Estonia.”"),
      q.tf("In 2008, volunteers in Estonia collected about 10,000 tons of illegal waste.", true, "Paragraph 1: “They collected about 10,000 tons of illegal waste.”"),
      q.tf("Padang Galak Beach is in Jakarta.", false, "Paragraph 3: the beach is in Bali."),
      q.ma("explicit", "Which TWO groups did the officials in Bali come from?", ["The Ministry of Marine Affairs and Fisheries","The Bali provincial government","The Ministry of Education and Culture","The national government of Estonia"], [0, 1], "Paragraph 3: “The officials came from the Ministry of Marine Affairs and Fisheries and the Bali provincial government.”"),
      q.match("Match each time with the event.", [["2008","More than 50,000 volunteers in Estonia cleaned up their country"],["15 September 2018","The first World Cleanup Day"],["After the event","The organisers spoke about volunteers in Indonesia"],["Since 2018","World Cleanup Day has continued every year"]], "Each time is stated in the text."),
      q.mcq("visual", "Look at the timeline. Which event happened in 2008?", ["Estonians cleaned up their country.","The first World Cleanup Day took place.","Volunteers cleaned Padang Galak Beach.","The organisers spoke about Indonesia."], 0, "The timeline shows the Estonian cleanup in 2008.", {"viz":true})
    ],
    detective: [
      q.para("Reorientation", 5, [2,3,4,5], "Paragraph 5 looks back and says what the event showed."),
      q.sort("It was a Saturday.", "O"),
      q.sort("However, the event showed that millions of people were ready to act together.", "R"),
      q.mcq("reference", "In the second sentence, “They” refers to…", ["The volunteers in Estonia","The volunteers in Indonesia","The organisers in Estonia","The officials in Bali"], 0, "The sentence before is about the 50,000 volunteers in Estonia.", {"quote":"In 2008, more than 50,000 volunteers there cleaned up their country in one day. They collected about 10,000 tons of illegal waste."}),
      q.mcq("vocab", "The word “volunteers” is closest in meaning to…", ["people who help without being paid","people who work for a government office","people who sell things to visitors","people who plan a big event"], 0, "Volunteers picked up rubbish together to help; the text does not say they were paid.", {"quote":"On this day, volunteers picked up rubbish together."}),
      q.mcq("evidence", "Which sentence shows that an international group helped in Bali?", ["They worked with Ocean Conservancy, an international environmental organisation.","The officials came from the Ministry of Marine Affairs and Fisheries and the Bali provincial government.","Hundreds of volunteers were expected to join them.","Volunteers cleaned up cities, towns and coastal areas."], 0, "Ocean Conservancy is described as an international environmental organisation."),
      q.mcq("signal", "Which phrase at the start of paragraph 2 shows that something happened later than the Estonian cleanup?", ["After that","In each country","In Indonesia","On this day"], 0, "“After that” points back to the cleanup in Estonia.")
    ],
    deeper: [
      q.mcq("inference", "Why does the writer use the words “According to them” in paragraph 4?", ["To show that this is what the organisers said","To show that the writer counted the volunteers","To show that the government wrote the report","To show that the report was not important"], 0, "The claim comes from the organisers, so the writer attributes it to them."),
      q.mcq("evidence", "Which sentence best supports the idea that many different groups worked together in Indonesia?", ["They included government offices, environmental groups and local communities.","In 2008, more than 50,000 volunteers there cleaned up their country in one day.","The volunteers also recorded what kinds of rubbish they found in a database.","World Cleanup Day has continued every year since 2018."], 0, "The sentence lists three kinds of groups."),
      q.mcq("cause", "How was it possible for cleanups to happen in many countries on the same day?", ["Local volunteers and partners organised them in each country.","One organisation did the cleanups in each country alone.","Each government paid workers to clean up the beaches.","Estonian volunteers travelled to each country to help."], 0, "Paragraph 2: “In each country, local volunteers and partners organised the cleanups.”"),
      q.mcq("inference", "What can we infer about the cleanup in Bali?", ["Several groups worked together there.","Government workers did all the cleaning there.","It was organised by Estonian volunteers.","It took place on a different day from the other cleanups."], 0, "Officials, Ocean Conservancy and hundreds of volunteers all took part."),
      q.mcq("inference", "What does “One day of cleaning cannot solve the problem of waste” suggest?", ["People need to keep working on the problem.","The cleanup was too small to matter.","Waste is not a problem for most countries.","Volunteers should stop cleaning up rubbish."], 0, "The word “However” in the next sentence shows the event still mattered, but the problem needs more work.")
    ],
    challenge: [
      q.mcq("main", "What is the main idea of this text?", ["Millions of volunteers joined the first World Cleanup Day.","Estonia cleaned up its country in one day in 2008.","The Indonesian government started World Cleanup Day in Bali.","Ocean Conservancy organised the cleanup at Padang Galak Beach."], 0, "The text is about the first World Cleanup Day and the volunteers who joined, including in Indonesia."),
      q.mcq("main", "Which sentence best sums up paragraph 3?", ["Cleanups took place in Indonesia, including at a beach in Bali.","The idea for World Cleanup Day began in Estonia in 2008.","The organisers said that Indonesia had the most volunteers.","World Cleanup Day has continued every year since 2018."], 0, "Paragraph 3 describes what happened in Indonesia on 15 September."),
      q.mcq("purpose", "Why was this text written?", ["To inform readers about a real environmental event","To entertain readers with a funny story about rubbish","To persuade readers to join a cleanup next year","To explain how to separate rubbish at home"], 0, "It reports a real event with dates, places and groups."),
      q.mcq("purpose", "Why does the writer include paragraph 5?", ["To show what the event meant and what happened next","To describe the first cleanup in Estonia in 2008","To list the groups that helped at the beach in Bali","To explain how to collect rubbish in a safe way"], 0, "Paragraph 5 looks back: the event continued every year and showed that many people were ready to act."),
      q.mcq("cause", "Why could World Cleanup Day be called a global event?", ["People in many countries took part on the same day.","It was held in one large country on one day.","It was organised by the United Nations in 2018.","It started in Estonia and stayed there."], 0, "Paragraphs 1 and 2: volunteers in more than 100 countries cleaned up on the same day."),
      q.mcq("cause", "What was the result of the Estonian organisation’s invitation?", ["Millions of volunteers in over 100 countries took part.","A few more countries joined in the following year.","Estonia’s cleanup of 2008 was held again in 2018.","The cleanup was moved from September to May."], 0, "Paragraph 2: after the invitation, millions of volunteers took part in more than 100 countries."),
      q.mcq("sequence", "Which event happened first?", ["Estonian volunteers cleaned up their country.","Volunteers cleaned up Padang Galak Beach.","The organisers spoke about Indonesia.","World Cleanup Day continued every year."], 0, "The Estonian cleanup was in 2008, long before the others."),
      q.mcq("vocab", "In paragraph 1, “illegal” means…", ["against the law","very dangerous","very old","hard to see"], 0, "Illegal waste is waste that people throw away against the law.", {"quote":"They collected about 10,000 tons of illegal waste."}),
      q.mcq("inference", "What can we infer about the organisers’ aim for World Cleanup Day?", ["They wanted many people in different countries to act together.","They wanted to solve the problem of waste in a single day.","They wanted volunteers in Estonia to take part.","They wanted the government to pay for the cleanups."], 0, "The text says millions of people took part in many countries on the same day, but one day cannot solve the problem of waste.")
    ]
  });

  /* ================================================================= 3. A CAVE, A TEAM, A WHOLE WORLD */
  E.push({
    id: "rescue", world: "factual", icon: "🔦", title: "A Cave, a Team, a Whole World", theme: "Community and cooperation", rev: 1,
    badge: {"icon":"🤝","name":"Teamwork Reader"},
    focus: ["Factual recount","Sequence","Cooperation","Inference"],
    visual: {"type":"timeline","title":"The Tham Luang rescue","caption":"Important days in the Tham Luang rescue.","items":[{"e":"⚽","y":"23 Jun 2018","l":"Team and coach enter the cave"},{"e":"🌧️","y":"23 Jun 2018","l":"Flood water traps them"},{"e":"🔦","y":"2 Jul 2018","l":"Two British divers find all 13 alive"},{"e":"🕊️","y":"6 Jul 2018","l":"Saman Kunan dies helping the rescue"},{"e":"🤿","y":"8–9 Jul 2018","l":"Eight boys are brought out"},{"e":"✅","y":"10 Jul 2018","l":"The last four boys and coach come out"}]},
    paras: [
      "The Wild Boars were a youth football team in northern Thailand. The team had 12 boys, aged 11 to 16, and an assistant coach who was 25 years old.",
      "On 23 June 2018, after football practice, the boys and their coach went to explore the Tham Luang cave. Heavy rain began, and flood water filled the cave tunnels. The group was trapped and could not get out. The next day, people began to search for them.",
      "Many people came to help. Thai Navy SEALs, divers and other rescue workers came from Thailand and other countries. People pumped water out of the cave. Some farmers let the water flow onto their rice fields. Local people cooked meals for the rescue teams, and others washed their clothes. After nine days, on 2 July, two British divers found all 13 people alive.",
      "The rescue was very dangerous. On 6 July, a former Thai Navy SEAL named Saman Kunan died. He was helping to place air tanks in the cave. On 8 July, divers began to bring the boys out. They took out four boys on 8 July and four more on 9 July. On 10 July, the last four boys and their coach came out. All 13 people were rescued.",
      "The rescue took 17 days, from the day the group went into the cave until the last person came out. Teams from many countries worked with Thai rescuers, soldiers and local volunteers. The Tham Luang rescue shows what people can do when they work together."
    ],
    vocab: [{"w":"trapped","m":"not able to leave a place"},{"w":"flood","m":"a large amount of water that covers land or fills a space"},{"w":"rescue","m":"to save someone from danger"},{"w":"divers","m":"people who swim under water with special equipment"},{"w":"pumped","m":"moved water from one place to another with a machine"},{"w":"former","m":"in the past, but not now"}],
    track: { intro: "Put these events in the order they happened.", why: "The group went into the cave and was trapped, was found after nine days, and then the boys and their coach came out over three days.",
      events: [{"t":"The boys and their coach went into the Tham Luang cave.","clue":"23 June 2018, after football practice."},{"t":"Flood water filled the tunnels, and the group could not get out.","clue":"This happened because of heavy rain."},{"t":"Two British divers found all 13 people alive.","clue":"2 July, after nine days."},{"t":"Saman Kunan died while helping to place air tanks in the cave.","clue":"6 July."},{"t":"Divers took four boys out of the cave.","clue":"8 July, the first day of the rescue."},{"t":"The last four boys and their coach came out.","clue":"10 July, the third day of the rescue."}] },
    details: [
      q.mcq("explicit", "How many boys were in the Wild Boars team in this story?", ["12","11","13","16"], 0, "Paragraph 1: “The team had 12 boys, aged 11 to 16.”"),
      q.mcq("explicit", "On which date did the group go into the Tham Luang cave?", ["23 June 2018","2 July 2018","6 July 2018","10 July 2018"], 0, "Paragraph 2: “On 23 June 2018, after football practice…”"),
      q.tf("The group was found on 2 July.", true, "Paragraph 3: “…on 2 July, two British divers found all 13 people alive.”"),
      q.tf("The last boys came out of the cave on 8 July.", false, "Paragraph 4: the last four boys and their coach came out on 10 July."),
      q.ma("explicit", "Which TWO things did local people do to help?", ["Some farmers let water flow onto their rice fields.","Some people cooked meals for the rescue teams.","Some people carried the boys out of the cave.","Some people drove the boys to the hospital by car."], [0, 1], "Paragraph 3 describes the farmers and the people who cooked and washed clothes."),
      q.match("Match each date with the event.", [["23 June","The group went into the cave"],["2 July","Two British divers found all 13 people"],["6 July","Saman Kunan died"],["10 July","The last four boys and their coach came out"]], "Each date is stated in the text."),
      q.mcq("visual", "Look at the timeline. What happened between 2 July and 10 July?", ["A former SEAL named Saman Kunan died.","The group went into the Tham Luang cave.","Flood water filled the tunnels in the cave.","The first search began the next day."], 0, "The timeline shows Saman Kunan’s death on 6 July.", {"viz":true})
    ],
    detective: [
      q.para("Reorientation", 5, [2,3,4,5], "Paragraph 5 sums up the rescue and says what it shows."),
      q.sort("The Wild Boars were a youth football team in northern Thailand.", "O"),
      q.sort("The Tham Luang rescue shows what people can do when they work together.", "R"),
      q.mcq("reference", "In the last sentence, “them” refers to…", ["The boys and their coach","The Thai Navy SEALs","The farmers and cooks","The families at the cave"], 0, "The sentences before are about the group that could not get out.", {"quote":"The group was trapped and could not get out. The next day, people began to search for them."}),
      q.mcq("vocab", "The word “trapped” is closest in meaning to…", ["not able to leave a place","not able to see in a place","not able to sleep in a place","not able to find a place"], 0, "The group could not get out of the cave.", {"quote":"The group was trapped and could not get out."}),
      q.mcq("evidence", "Which sentence shows that many different people helped the rescue?", ["Thai Navy SEALs, divers and other rescue workers came from Thailand and other countries.","On 23 June 2018, after football practice, the boys and their coach went to explore the Tham Luang cave.","The team had 12 boys, aged 11 to 16, and an assistant coach who was 25 years old.","On 10 July, the last four boys and their coach came out."], 0, "The sentence lists different kinds of helpers from different countries."),
      q.mcq("signal", "Which phrase in paragraph 3 shows how long the search took?", ["After nine days","On 2 July","The next day","Before the rain"], 0, "Paragraph 3: “After nine days, on 2 July…”")
    ],
    deeper: [
      q.mcq("inference", "Why did people pump water out of the cave?", ["To lower the flood water for the rescuers","To bring water to the rice fields near the cave","To wash the muddy floor of the cave tunnels","To find the football equipment of the team"], 0, "Flood water had filled the tunnels, so removing the water helped rescuers."),
      q.mcq("evidence", "Which sentence best shows that flood water was a problem in the cave?", ["Heavy rain began, and flood water filled the cave tunnels.","The team had 12 boys, aged 11 to 16, and an assistant coach who was 25 years old.","Teams from many countries worked with Thai rescuers, soldiers and local volunteers.","The next day, people began to search for them."], 0, "It shows that the water was the main problem in the cave."),
      q.mcq("cause", "Why did the group become trapped in the cave?", ["Heavy rain flooded the tunnels.","A rock fell across the entrance.","The group lost the way out in the dark.","The cave was closed by park rangers."], 0, "Paragraph 2: “Heavy rain began, and flood water filled the cave tunnels.”"),
      q.mcq("inference", "What does “The rescue was very dangerous” help us understand?", ["Rescuers took great risks, and one of them died.","The boys were not in danger during the rescue.","The rescue was easy for the experienced divers.","The farmers made the rescue harder for everyone."], 0, "The next sentences say that Saman Kunan died while helping."),
      q.mcq("inference", "What can we infer about the rescue?", ["It needed many people with different skills.","It was done by divers working alone in the cave.","It was planned many months before the rain.","It was finished in one day by a small team."], 0, "The text names SEALs, divers, rescue workers, farmers, cooks and others.")
    ],
    challenge: [
      q.mcq("main", "What is the main idea of this text?", ["People from many places worked together to rescue the team.","A youth football team lost its way in northern Thailand.","Thai Navy SEALs trained divers for a rescue.","Farmers lost their rice fields in a flood."], 0, "The text follows the rescue and ends with the idea of working together."),
      q.mcq("main", "Which sentence best sums up paragraph 4?", ["The rescue was dangerous, and all 13 people were brought out over three days.","The team went into the cave after football practice and could not get out.","Many people came to help with pumps, food and clean clothes for the teams.","The rescue took 17 days, and teams from many countries helped Thai rescuers."], 0, "Paragraph 4 is about the dangers and the three days when the boys and coach came out."),
      q.mcq("purpose", "Why was this text written?", ["To inform readers about a real rescue","To entertain readers with a cave adventure","To persuade readers to explore caves","To explain how to dive safely"], 0, "It reports real events with dates and facts."),
      q.mcq("purpose", "Why does the writer include paragraph 5?", ["To sum up the rescue and say what it shows","To describe the first day of the search","To explain how the pumps removed water","To introduce the football team and coach"], 0, "Paragraph 5 looks back on the whole rescue and gives the writer’s comment."),
      q.mcq("cause", "Why did water flow onto some rice fields?", ["Some farmers let the pumped water flow there.","The river next to the cave burst its banks.","The pumps were broken and leaked onto the land.","Heavy rain fell on the fields during the rescue."], 0, "Paragraph 3: people pumped water out of the cave, and some farmers let it flow onto their fields."),
      q.mcq("cause", "What was the result of the rescue work on 8, 9 and 10 July?", ["All 13 people were rescued.","Four boys stayed in the cave.","The rescue stopped for a week.","The coach came out first, before the boys."], 0, "Paragraph 4: “All 13 people were rescued.”"),
      q.mcq("sequence", "Which of these events came first after the group was found on 2 July?", ["Saman Kunan died on 6 July.","Divers began to bring the boys out.","The last boys and the coach came out.","People began to search for the group."], 0, "After 2 July, the next event in the text is the death on 6 July."),
      q.mcq("vocab", "In paragraph 3, “pumped” means…", ["moved water with a machine","cleaned water with a filter","carried water in buckets","stopped water from entering the cave"], 0, "People used pumps to move water out of the cave.", {"quote":"People pumped water out of the cave."}),
      q.mcq("inference", "What can we infer about the farmers who let water flow onto their fields?", ["They were willing to give up something to help.","They hoped to be paid a lot of money.","They were afraid of the rescue workers.","They did not know about the flood in the cave."], 0, "They let the water flow onto their own fields so the rescue could go on.")
    ]
  });
})();
