/* RECOUNT QUEST — REAL STORIES (Factual Recount): habibie, kartini, drill */
(function () {
  "use strict";
  var q = RQ.q, E = RQ.data.episodes;

  /* ================================================================= 4. B.J. HABIBIE */
  E.push({
    id: "habibie", world: "factual", icon: "✈️", title: "B.J. Habibie: A Dream That Took Flight", theme: "Perseverance",
    badge: { icon: "✈️", name: "Inspiring Lives" },
    focus: ["Biography", "Chronology", "Evidence", "Inference"],
    visual: { type: "timeline", title: "Habibie’s life timeline", caption: "Important moments in the life of B.J. Habibie.",
      items: [{ e: "👦", y: "1936", l: "Born in Parepare" }, { e: "🇩🇪", y: "1955", l: "Goes to Germany" }, { e: "🎓", y: "1960", l: "Engineering degree" }, { e: "📜", y: "1965", l: "Doctorate" }, { e: "🛬", y: "1974", l: "Returns to Indonesia" }, { e: "🏛️", y: "1978", l: "Minister of State for Research and Technology" }, { e: "✈️", y: "1995", l: "N250 first flight" }, { e: "🇮🇩", y: "1998", l: "Becomes President" }, { e: "🕊️", y: "2019", l: "Dies in Jakarta" }] },
    paras: [
      "Bacharuddin Jusuf Habibie, better known as B.J. Habibie, was born on 25 June 1936 in Parepare, South Sulawesi. As a boy, he was interested in machines and aircraft. When he was a teenager, his father died. His mother supported him so that he could continue his education.",
      "In 1955, Habibie went to Germany to study aircraft engineering at a university in Aachen. He studied very hard. He finished his engineering degree in 1960, and he received his doctorate in 1965. Then he worked for an aircraft company in Germany and did research on aircraft structures.",
      "In 1974, Habibie returned to Indonesia after President Suharto asked him to help develop the country’s technology and aircraft industry. Back home, he worked with Indonesian engineers to build the country’s own aircraft industry. In 1978, he became the Minister of State for Research and Technology. He held this position until 1998.",
      "One of his best-known projects was the N250, a passenger aircraft developed in Indonesia. It made its first flight on 10 August 1995. It was designed for short flights between cities, and it was built by Indonesian engineers in Bandung. Many Indonesians were proud of this achievement because it showed that the country could design its own aircraft.",
      "In 1998, Habibie became the third President of Indonesia, and he served until 1999. He died on 11 September 2019 in Jakarta at the age of 83. Many people remember him as a scientist who worked hard for Indonesia’s science and technology. His life continues to inspire young people to follow their dreams."
    ],
    vocab: [{ w: "aircraft", m: "a plane or other flying vehicle" }, { w: "engineering", m: "the study of designing and building machines or structures" }, { w: "doctorate", m: "the highest university degree" }, { w: "research", m: "careful study to find new information" }, { w: "achievement", m: "something important that someone has done successfully" }, { w: "inspire", m: "to make someone want to do something good" }],
    track: { intro: "Put these events from Habibie’s life in the order they happened.", why: "The text follows his life from birth to the Presidency.",
      events: [{ t: "Habibie was born in Parepare.", clue: "1936" }, { t: "Habibie went to Germany to study.", clue: "1955" }, { t: "Habibie finished his engineering degree.", clue: "1960" }, { t: "Habibie returned to Indonesia.", clue: "1974" }, { t: "The N250 made its first flight.", clue: "1995" }, { t: "Habibie became President of Indonesia.", clue: "1998" }] },
    details: [
      q.mcq("explicit", "Where was Habibie born?", ["Parepare, South Sulawesi", "Makassar, South Sulawesi", "Bandung, West Java", "Surabaya, East Java"], 0, "Paragraph 1: “born on 25 June 1936 in Parepare, South Sulawesi.”"),
      q.mcq("explicit", "Why did Habibie go to Germany in 1955?", ["To study aircraft engineering", "To work as a minister", "To fly the N250", "To visit his father"], 0, "Paragraph 2: “Habibie went to Germany to study aircraft engineering.”"),
      q.tf("Habibie received his doctorate before he finished his engineering degree.", false, "He finished his degree in 1960 and received his doctorate in 1965."),
      q.tf("The N250 was developed in Indonesia.", true, "Paragraph 4: “the N250, a passenger aircraft developed in Indonesia.”"),
      q.ma("explicit", "Which TWO positions in Indonesia are mentioned in the text?", ["Minister of State for Research and Technology", "President of Indonesia", "Governor of South Sulawesi", "Minister of Education"], [0, 1], "Paragraph 3 mentions the Minister position, and paragraph 5 says he became President."),
      q.match("Match each year with the event.", [["1955", "Went to Germany to study"], ["1974", "Returned to Indonesia"], ["1978", "Became Minister of State for Research and Technology"], ["1995", "The N250 made its first flight"]], "Each year is stated in the text."),
      q.mcq("visual", "Look at the timeline. Which event happened between 1965 and 1978?", ["He returned to Indonesia.", "He was born in Parepare.", "The N250 made its first flight.", "He became President."], 0, "On the timeline, 1974 comes between 1965 and 1978.", { viz: true })
    ],
    detective: [
      q.para("Reorientation", 5, [2, 3, 4, 5], "Paragraph 5 looks back at his life and says why people remember him."),
      q.sort("In 1974, Habibie returned to Indonesia after President Suharto asked him to help develop the country’s technology and aircraft industry.", "E"),
      q.sort("His life continues to inspire young people to follow their dreams.", "R"),
      q.mcq("reference", "In the second sentence, “this position” refers to…", ["Minister of State for Research and Technology", "President of Indonesia", "a manager in a German aircraft company", "a professor at a university"], 0, "The sentence before it says he became the Minister of State for Research and Technology.", { quote: "In 1978, he became the Minister of State for Research and Technology. He held this position until 1998." }),
      q.mcq("vocab", "The word “research” is closest in meaning to…", ["careful study to find new information", "a long trip to another country", "a job in a school", "a prize for scientists"], 0, "He studied aircraft structures to learn more about them.", { quote: "Then he worked for an aircraft company in Germany and did research on aircraft structures." }),
      q.mcq("evidence", "Which sentence best shows that Habibie was successful in his studies?", ["He finished his engineering degree in 1960, and he received his doctorate in 1965.", "In 1955, Habibie went to Germany to study aircraft engineering at a university in Aachen.", "His mother supported him so that he could continue his education.", "As a boy, he was interested in machines and aircraft."], 0, "A degree and a doctorate are results of successful study."),
      q.mcq("signal", "Which word in paragraph 2 shows that Habibie started working after he finished his studies?", ["Then", "When", "Before", "Until"], 0, "“Then” shows the next event in the sequence.", { quote: "Then he worked for an aircraft company in Germany and did research on aircraft structures." })
    ],
    deeper: [
      q.mcq("inference", "What can we infer about Habibie’s attitude toward learning?", ["He was serious and determined to learn.", "He studied only because his mother asked him.", "He found study easy and never worked hard.", "He was not interested in practical work."], 0, "He studied very hard and gained a degree and a doctorate."),
      q.mcq("evidence", "Which sentence best supports your answer?", ["He studied very hard.", "He held this position until 1998.", "He died on 11 September 2019 in Jakarta at the age of 83.", "One of his best-known projects was the N250, a passenger aircraft developed in Indonesia."], 0, "“He studied very hard” directly shows his attitude to learning."),
      q.mcq("cause", "Why did Habibie return to Indonesia in 1974?", ["President Suharto asked him to help develop technology and the aircraft industry.", "He lost his job in Germany and had no other place to work.", "He wanted to become the President of Indonesia as soon as possible.", "His mother asked him to come home after his doctorate was finished."], 0, "Paragraph 3: he returned “after President Suharto asked him to help develop the country’s technology and aircraft industry.”"),
      q.mcq("inference", "What can we infer about Habibie’s feelings toward Indonesia?", ["He wanted to use his knowledge to help his country.", "He wanted to leave Indonesia for ever.", "He did not like technology.", "He returned only to rest."], 0, "He came back to help develop the country’s technology and later worked as a minister."),
      q.mcq("message", "What message about Habibie’s life does the last paragraph give?", ["Hard work and big dreams can lead to great achievements.", "Scientists should not work for the government.", "It is better to study only in Indonesia.", "Success comes quickly to clever people."], 0, "The text says his life “continues to inspire young people to follow their dreams.”")
    ],
    challenge: [
      q.mcq("main", "What is the main idea of this text?", ["It tells the main stages of B.J. Habibie’s life and achievements.", "Habibie built the first aircraft in the world with German engineers.", "Habibie spent his whole life in Germany and never came back.", "Habibie was President of Indonesia for more than twenty years."], 0, "The text follows his life from birth to the Presidency and his legacy."),
      q.mcq("purpose", "Why was this text written?", ["To inform readers about the life of a real person", "To entertain readers with an imaginary story", "To persuade readers to study in Germany", "To explain how to build an aircraft"], 0, "It reports real events and dates in order."),
      q.mcq("sequence", "Which event happened before Habibie returned to Indonesia?", ["He received his doctorate.", "He became Minister of State for Research and Technology.", "The N250 made its first flight.", "He became President."], 0, "He received his doctorate in 1965 and returned in 1974. The other events came later."),
      q.mcq("cause", "Why were many Indonesians proud of the N250?", ["It showed that Indonesia could design its own aircraft.", "It was painted in the national colours of Indonesia.", "It was flown by Habibie himself on its first flight.", "It was built in Germany by a famous aircraft company."], 0, "Paragraph 4: “…because it showed that the country could design its own aircraft.”"),
      q.mcq("vocab", "In paragraph 4, “achievement” means…", ["something important that someone has done successfully", "a difficult exam that students take at school", "a type of aircraft that carries many passengers", "a sad event that people want to forget"], 0, "People were proud of the N250 because it was a success.", { quote: "Many Indonesians were proud of this achievement because it showed that the country could design its own aircraft." }),
      q.mcq("reference", "In the second sentence, “It” refers to…", ["the N250", "Habibie", "Indonesia", "the aircraft company in Germany"], 0, "The sentence before introduces the N250.", { quote: "One of his best-known projects was the N250, a passenger aircraft developed in Indonesia. It made its first flight on 10 August 1995." }),
      q.mcq("visual", "Look at the timeline. How many years passed between 1955 and 1974?", ["19 years", "9 years", "14 years", "29 years"], 0, "1974 − 1955 = 19 years.", { viz: true }),
      q.tf("Habibie became Minister of State for Research and Technology before he became President.", true, "He became Minister in 1978 and President in 1998."),
      q.mcq("inference", "What can we infer about Habibie’s life from the text?", ["He worked for Indonesia’s progress in science and technology.", "He lived only for politics and did not like science.", "He never studied abroad and stayed in South Sulawesi.", "He disliked young people and did not want to inspire them."], 0, "The last paragraph says he worked hard for Indonesia’s science and technology.")
    ]
  });

  /* ================================================================= 5. R.A. KARTINI */
  E.push({
    id: "kartini", world: "factual", icon: "✉️", title: "R.A. Kartini: Letters That Inspired Change", theme: "Education and courage",
    badge: { icon: "📜", name: "History Tracker" },
    focus: ["Biography", "Chronology", "Evidence", "Inference"],
    visual: { type: "timeline", title: "Kartini’s life timeline", caption: "Important moments in the life of R.A. Kartini.",
      items: [{ e: "👧", y: "1879", l: "Born in Jepara" }, { e: "📕", y: "About age 12", l: "Has to stop going to school" }, { e: "🏫", y: "1903", l: "Starts a small school for girls" }, { e: "💍", y: "1903", l: "Marries and moves to Rembang" }, { e: "🕊️", y: "1904", l: "Dies at the age of 25" }, { e: "📚", y: "1911", l: "Letters published as a book" }] },
    paras: [
      "Raden Ajeng Kartini, known as R.A. Kartini, was born on 21 April 1879 in Jepara, Central Java. Her father was the regent of Jepara, so she grew up in a noble family. As a child, she was clever and loved reading. She went to a Dutch-language primary school, where she learned to speak Dutch.",
      "When Kartini was about twelve years old, she had to stop going to school. At that time, according to custom, girls from noble families stayed at home until they married. Kartini was very sad because she wanted to study more.",
      "Kartini did not stop learning. At home, she read Dutch books, newspapers and magazines. She also wrote letters in Dutch to friends in the Netherlands. In her letters, she shared her ideas about education and about the problems that girls and women faced. She believed that girls should have the same chance to learn as boys.",
      "In 1903, Kartini started a small school for girls in Jepara. Her school was small, but it gave local girls a chance to learn. Later that year, she married the regent of Rembang and moved to Rembang. Sadly, Kartini died on 17 September 1904, when she was only 25 years old.",
      "After her death, a Dutch official who knew her collected her letters and published them as a book in 1911. The book showed many readers why education for girls was important. In Indonesian, it is known as Habis Gelap Terbitlah Terang. Today, Indonesians celebrate Kartini Day on 21 April to remember her ideas about education."
    ],
    vocab: [{ w: "regent", m: "a local leader who governed an area in the past" }, { w: "noble", m: "from an important family with a high position" }, { w: "custom", m: "a traditional way of doing things in a society" }, { w: "published", m: "printed and sold so that people can read it" }, { w: "ideas", m: "thoughts or plans" }],
    track: { intro: "Put these events from Kartini’s life in the order they happened.", why: "The text follows Kartini’s life, and then what happened to her letters after her death.",
      events: [{ t: "Kartini was born in Jepara.", clue: "21 April 1879" }, { t: "Kartini went to a Dutch-language primary school.", clue: "This was in her childhood." }, { t: "Kartini had to stop going to school.", clue: "She was about twelve years old." }, { t: "Kartini wrote letters to friends in the Netherlands.", clue: "She did this while she was at home." }, { t: "Kartini started a small school for girls.", clue: "1903" }, { t: "Kartini’s letters were published as a book.", clue: "1911, after her death" }] },
    details: [
      q.mcq("explicit", "Where was Kartini born?", ["Jepara, Central Java", "Rembang, Central Java", "Bandung, West Java", "Surabaya, East Java"], 0, "Paragraph 1: “born on 21 April 1879 in Jepara, Central Java.”"),
      q.mcq("explicit", "Which language did Kartini use to write to her friends in the Netherlands?", ["Dutch", "Javanese", "English", "Indonesian"], 0, "Paragraph 3: “she also wrote letters in Dutch to friends in the Netherlands.”"),
      q.tf("Kartini continued going to school after she was about twelve years old.", false, "Paragraph 2: “she had to stop going to school.”"),
      q.tf("Kartini started a small school for girls in Jepara.", true, "Paragraph 4: “In 1903, Kartini started a small school for girls in Jepara.”"),
      q.ma("explicit", "Which TWO topics did Kartini write about in her letters?", ["Education", "The problems that girls and women faced", "Sports competitions", "Travelling around Europe"], [0, 1], "Paragraph 3: “her ideas about education and about the problems that girls and women faced.”"),
      q.match("Match each date or age with the event.", [["21 April 1879", "Kartini was born"], ["About twelve years old", "Kartini had to stop going to school"], ["17 September 1904", "Kartini died"], ["1911", "Her letters were published as a book"]], "Each date or age is stated in the text."),
      q.mcq("visual", "Look at the timeline. What else happened in the same year that Kartini started her school?", ["She married and moved to Rembang.", "She was born.", "Her letters were published.", "She died."], 0, "The timeline shows two events in 1903: the school and her marriage.", { viz: true })
    ],
    detective: [
      q.para("Orientation", 1, [1, 2, 3, 5], "Paragraph 1 tells who Kartini was, when and where she was born, and her childhood."),
      q.sort("Raden Ajeng Kartini, known as R.A. Kartini, was born on 21 April 1879 in Jepara, Central Java.", "O"),
      q.sort("In 1903, Kartini started a small school for girls in Jepara.", "E"),
      q.mcq("reference", "In the sentence, “them” refers to…", ["her letters", "her friends", "the Dutch officials", "her schools"], 0, "The official collected her letters and published them.", { quote: "After her death, a Dutch official who knew her collected her letters and published them as a book in 1911." }),
      q.mcq("vocab", "The word “custom” is closest in meaning to…", ["a traditional way of doing things in a society", "a school rule that students must follow", "a type of letter sent to friends abroad", "a new law made by the regent of Jepara"], 0, "Girls from noble families stayed at home because it was the tradition at that time.", { quote: "At that time, according to custom, girls from noble families stayed at home until they married." }),
      q.mcq("evidence", "Which sentence shows what Kartini DID to keep learning at home?", ["At home, she read Dutch books, newspapers and magazines.", "Kartini was very sad because she wanted to study more.", "Her father was the regent of Jepara, so she grew up in a noble family.", "Sadly, Kartini died on 17 September 1904, when she was only 25 years old."], 0, "Reading books, newspapers and magazines is an action that helped her learn."),
      q.mcq("signal", "Which expression shows that something happened after Kartini’s death?", ["After her death", "When Kartini was about twelve years old", "Later that year", "At that time"], 0, "“After her death” introduces the events of 1911.")
    ],
    deeper: [
      q.mcq("feelings", "What does the text suggest about Kartini after she left school?", ["She was sad, but she did not give up learning.", "She was happy to stay at home and stopped reading.", "She was angry with her father and left Jepara.", "She was afraid and forgot everything she had learned."], 0, "She was very sad, but she read books and wrote letters."),
      q.mcq("inference", "Why were Kartini’s letters important?", ["They shared her ideas about education for girls with many readers.", "They told readers how to build schools in every town.", "They were the first books ever written in the Dutch language.", "They made her a regent in Rembang after her marriage."], 0, "The published letters showed many readers why education for girls mattered."),
      q.mcq("inference", "What can we infer about Kartini’s character?", ["She was determined and believed in the power of ideas.", "She was afraid of other people.", "She cared only about her family’s wealth.", "She wanted to stay at home all her life."], 0, "She kept learning, wrote about her ideas and started a school."),
      q.mcq("evidence", "Which sentence best supports your answer?", ["Kartini did not stop learning.", "Sadly, Kartini died on 17 September 1904, when she was only 25 years old.", "Later that year, she married the regent of Rembang and moved to Rembang.", "In Indonesian, it is known as Habis Gelap Terbitlah Terang."], 0, "This sentence shows her determination to continue learning."),
      q.mcq("message", "Why do Indonesians celebrate Kartini Day?", ["To remember Kartini’s ideas about education", "To celebrate the end of a war", "To honour her father", "To remember the first Dutch school"], 0, "Paragraph 5: “to remember her ideas about education.”")
    ],
    challenge: [
      q.mcq("main", "What is the main idea of this text?", ["Kartini used reading, letters and a small school to support education for girls.", "Kartini became the first Indonesian regent and led the government of Jepara.", "Kartini travelled to the Netherlands to study at a Dutch university.", "Kartini wrote the first Dutch dictionary for students in Indonesia."], 0, "The text shows how she kept learning, wrote about education and started a school."),
      q.mcq("purpose", "Why was this text written?", ["To inform readers about the life and ideas of a real person", "To entertain readers with an imaginary story", "To explain how to write a letter", "To persuade readers to learn Dutch"], 0, "It reports real events from Kartini’s life in order."),
      q.mcq("sequence", "Which event happened first?", ["Kartini went to a Dutch-language primary school.", "Kartini started a small school for girls in Jepara.", "Kartini’s letters were published as a book in 1911.", "Kartini married the regent of Rembang and moved there."], 0, "It happened when she was a child. The other events came later."),
      q.mcq("cause", "Why did Kartini have to stop going to school at about twelve?", ["Custom said that girls from noble families stayed at home until they married.", "Her school closed down, and there was no other school to join in Jepara.", "She moved to the Netherlands to live with her Dutch friends and study.", "She did not like reading books, so she wanted to stay and work at home."], 0, "Paragraph 2 explains the custom."),
      q.mcq("vocab", "In paragraph 5, “published” means…", ["printed and sold so that people can read it", "hidden in a box so that nobody can find it", "changed into numbers so that a machine can read it", "burnt in a fire so that nobody can read it"], 0, "The letters became a book that many readers could read.", { quote: "After her death, a Dutch official who knew her collected her letters and published them as a book in 1911." }),
      q.mcq("reference", "In the last paragraph, “it” in “it is known as Habis Gelap Terbitlah Terang” refers to…", ["the book", "Kartini Day", "the school", "a letter"], 0, "The sentence before talks about the book.", { quote: "The book showed many readers why education for girls was important. In Indonesian, it is known as Habis Gelap Terbitlah Terang." }),
      q.mcq("visual", "Look at the timeline. How many years after Kartini’s death were her letters published as a book?", ["7 years", "10 years", "17 years", "25 years"], 0, "1911 − 1904 = 7 years.", { viz: true }),
      q.tf("Kartini died when she was 25 years old.", true, "Paragraph 4: “when she was only 25 years old.”"),
      q.mcq("message", "Which message does this recount give for students today?", ["Education is important, and ideas can inspire change.", "Only girls from noble families need to go to school.", "Letters are always better than books or newspapers.", "Schools should always be small and have few students."], 0, "Kartini’s ideas about education are still remembered today.")
    ]
  });

  /* ================================================================= 6. WHEN THE GROUND STARTED TO SHAKE */
  E.push({
    id: "drill", world: "factual", icon: "🚨", title: "When the Ground Started to Shake", theme: "Earthquake preparedness",
    badge: { icon: "🚨", name: "Safety Reporter" },
    focus: ["School report", "Sequence", "Cause and effect", "Evidence"],
    note: "A model school report. The school name is fictional; teachers may replace it with their own school.",
    visual: { type: "scene", bg: "school", caption: "The earthquake drill: from the classroom to the assembly point.",
      items: [{ e: "🏫", x: 20, y: 42, s: 3.4, l: "School building" }, { e: "➡️", x: 45, y: 48, s: 1.8, l: "" }, { e: "➡️", x: 57, y: 48, s: 1.8, l: "" }, { e: "👥", x: 80, y: 50, s: 2.8, l: "Assembly point" }, { e: "🌳", x: 91, y: 22, s: 2, l: "" }, { e: "🌳", x: 66, y: 22, s: 1.6, l: "" }],
      legend: ["Drop, cover and hold on under the desk", "Leave the classroom and stay away from the windows", "Walk in two lines to the school field", "Teachers count the students at the assembly point"] },
    paras: [
      "On Wednesday, 12 March, SMP Nusantara Jaya held an earthquake drill for all students and teachers. The school organised the drill because Indonesia often experiences earthquakes, and everyone needs to know what to do. Altogether, 480 students and 30 teachers took part. The drill began at 9.30 a.m.",
      "First, the head teacher rang a long bell, which was the signal for an earthquake. Students in the classrooms immediately dropped to the floor, covered their heads and necks under their desks, and held the desk legs. They stayed in this position for one minute while the teachers counted slowly from one to sixty.",
      "After the shaking stopped, the teachers checked that the classroom doors were open and told the students to leave their bags behind. Then the students walked, not ran, in two lines to the school field, which was the assembly point. The students on the second floor used the wide stairs on the left side of the building and stayed away from the windows.",
      "At the assembly point, each class teacher called the names of the students and counted them. For a few minutes, one student, Raka, was missing from Class 8B. The teacher soon found out that he was helping a classmate with a sore ankle, who was walking slowly. A few minutes later, they joined the class, and all 480 students were accounted for.",
      "The drill finished at 9.50 a.m. The head teacher, Mrs. Sari, thanked everyone and said that the school would practise again next semester. Many students said that the drill helped them stay calm. Mrs. Sari reminded them that in a real earthquake they must drop, cover and hold on, and then walk calmly to a safe open space."
    ],
    vocab: [{ w: "drill", m: "a practice of what to do in an emergency" }, { w: "signal", m: "a sign that tells people what to do" }, { w: "assembly point", m: "a place where people meet in an emergency" }, { w: "accounted for", m: "checked and found safe" }, { w: "semester", m: "half of a school year" }],
    track: { intro: "Put these events from the drill in the order they happened.", why: "The bell started the drill, and the school finished with thanks and a reminder.",
      events: [{ t: "The head teacher rang a long bell.", clue: "This was the signal at the start." }, { t: "Students dropped, covered their heads and held on for one minute.", clue: "They did this immediately after the bell." }, { t: "Teachers checked that the classroom doors were open.", clue: "This happened after the shaking stopped." }, { t: "Students walked in two lines to the school field.", clue: "“Then the students walked…”" }, { t: "Class teachers counted the students at the assembly point.", clue: "This happened at the school field." }, { t: "The head teacher thanked everyone.", clue: "This happened when the drill finished." }] },
    details: [
      q.mcq("explicit", "How many students took part in the drill?", ["480", "430", "30", "510"], 0, "Paragraph 1: “Altogether, 480 students and 30 teachers took part.”"),
      q.mcq("explicit", "What was the signal for an earthquake?", ["A long bell", "A loud whistle", "A radio message", "A siren from the city"], 0, "Paragraph 2: “the head teacher rang a long bell, which was the signal for an earthquake.”"),
      q.tf("The students ran quickly to the school field.", false, "Paragraph 3: “the students walked, not ran, in two lines.”"),
      q.tf("The students left their bags behind.", true, "Paragraph 3: the teachers “told the students to leave their bags behind.”"),
      q.ma("explicit", "Which TWO things did students do under their desks?", ["They covered their heads and necks.", "They held the desk legs.", "They called their parents.", "They opened the windows."], [0, 1], "Paragraph 2: they “covered their heads and necks under their desks, and held the desk legs.”"),
      q.match("Match each person or group with what they did.", [["The head teacher", "Rang the long bell"], ["Class teachers", "Called the names at the assembly point"], ["Raka", "Helped a classmate with a sore ankle"], ["Students on the second floor", "Used the wide stairs on the left side"]], "Each action is stated in the text."),
      q.mcq("visual", "Look at the picture. What is the fourth step in the drill?", ["Teachers count the students at the assembly point.", "Drop, cover and hold on.", "Walk in two lines to the school field.", "Leave the classroom."], 0, "The picture lists the steps in order. The fourth is counting at the assembly point.", { viz: true })
    ],
    detective: [
      q.para("Reorientation", 5, [2, 3, 4, 5], "Paragraph 5 ends the report with the finish, thanks and a reminder for the future."),
      q.sort("On Wednesday, 12 March, SMP Nusantara Jaya held an earthquake drill for all students and teachers.", "O"),
      q.sort("Then the students walked, not ran, in two lines to the school field, which was the assembly point.", "E"),
      q.mcq("reference", "In the last sentence, “they” refers to…", ["Raka and his classmate", "The class teachers", "All 480 students", "The students on the second floor"], 0, "The sentence before is about Raka and the classmate with a sore ankle.", { quote: "The teacher soon found out that he was helping a classmate with a sore ankle, who was walking slowly. A few minutes later, they joined the class, and all 480 students were accounted for." }),
      q.mcq("vocab", "The words “assembly point” mean…", ["a place where people meet in an emergency", "a place where students eat during the break", "a room where teachers have their meetings", "a space where bicycles are parked every day"], 0, "The school field was where everyone gathered after leaving the classrooms.", { quote: "Then the students walked, not ran, in two lines to the school field, which was the assembly point." }),
      q.mcq("evidence", "Which sentence tells us why the school held the drill?", ["The school organised the drill because Indonesia often experiences earthquakes, and everyone needs to know what to do.", "The students on the second floor used the wide stairs on the left side of the building and stayed away from the windows.", "Students in the classrooms immediately dropped to the floor, covered their heads and necks under their desks, and held the desk legs.", "The head teacher, Mrs. Sari, thanked everyone and said that the school would practise again next semester."], 0, "The word “because” introduces the reason."),
      q.mcq("signal", "Which word in paragraph 3 shows what happened next, after the teachers checked the doors?", ["Then", "First", "Altogether", "Soon"], 0, "“Then” shows the next step.", { quote: "Then the students walked, not ran, in two lines to the school field, which was the assembly point." })
    ],
    deeper: [
      q.mcq("inference", "Why did the class teachers count the students at the assembly point?", ["To make sure that everyone was safe", "To give the students a test", "To choose a class leader", "To close the school field"], 0, "After the drill, the teachers “accounted for” all students."),
      q.mcq("evidence", "Which sentence best supports your answer?", ["At the assembly point, each class teacher called the names of the students and counted them.", "The head teacher, Mrs. Sari, thanked everyone and said that the school would practise again next semester.", "After the shaking stopped, the teachers checked that the classroom doors were open and told the students to leave their bags behind.", "They stayed in this position for one minute while the teachers counted slowly from one to sixty."], 0, "Calling the names and counting show that the teachers checked every student."),
      q.mcq("inference", "Why were the students told to leave their bags behind?", ["So that they could leave quickly and safely", "So that the bags would not get wet", "Because the bags were too heavy for the stairs", "So that the teachers could check their books"], 0, "In an emergency, carrying bags would slow people down."),
      q.mcq("inference", "Why did the students walk instead of run?", ["Running could cause accidents and panic.", "Walking is faster than running.", "The field was very far away.", "The head teacher did not like running."], 0, "Walking calmly keeps people safe and avoids falls and panic."),
      q.mcq("inference", "What can we infer about Raka?", ["He cares about other people.", "He was afraid of the drill.", "He did not follow the teachers’ instructions.", "He wanted to leave his class."], 0, "He was missing because he was helping a classmate with a sore ankle.")
    ],
    challenge: [
      q.mcq("main", "What is the main idea of this text?", ["Students and teachers practised what to do in an earthquake.", "A real earthquake damaged the school and the students left.", "The head teacher changed all the school rules this year.", "Raka won a prize for helping his classmate in Class 8B."], 0, "The whole report describes the earthquake drill from start to finish."),
      q.mcq("purpose", "Why was this text written?", ["To report what happened during a school earthquake drill", "To entertain readers with an imaginary story", "To persuade readers to join a club", "To explain how to build a safe school"], 0, "It reports real events in time order, with a time, a date and numbers."),
      q.mcq("sequence", "What happened immediately after the bell rang?", ["Students dropped, covered their heads and held on.", "Students walked in two lines to the school field.", "Teachers called the names and counted the students.", "The head teacher thanked everyone for taking part."], 0, "Paragraph 2: students “immediately dropped to the floor”."),
      q.mcq("vocab", "In paragraph 2, “signal” means…", ["a sign that tells people what to do", "a kind of earthquake that happens at night", "a school uniform that all students wear", "a loud song that students sing together"], 0, "The long bell told everyone to start the drill.", { quote: "First, the head teacher rang a long bell, which was the signal for an earthquake." }),
      q.mcq("reference", "In paragraph 3, “which” refers to…", ["the school field", "the building", "the stairs", "the second floor"], 0, "“…to the school field, which was the assembly point.”", { quote: "Then the students walked, not ran, in two lines to the school field, which was the assembly point." }),
      q.mcq("cause", "Why was Raka missing from the class for a few minutes?", ["He was helping a classmate with a sore ankle.", "He was hiding behind the building during the drill.", "He had left his bag behind in the classroom.", "He was calling a teacher to open the door."], 0, "Paragraph 4 explains the reason."),
      q.mcq("inference", "What can we infer about the school’s attitude to safety?", ["The school takes safety seriously and plans to practise again.", "The school wants to stop teaching.", "The school thinks drills are not useful.", "The school is afraid of earthquakes only in March."], 0, "The head teacher said that the school would practise again next semester."),
      q.tf("The drill lasted more than one hour.", false, "It began at 9.30 a.m. and finished at 9.50 a.m., so it lasted about 20 minutes."),
      q.mcq("message", "Which advice from the text is the most useful in a real earthquake?", ["Drop, cover and hold on, then walk calmly to a safe open space.", "Run outside as fast as possible and stay near the windows.", "Stay in the classroom and wait until the bell rings again.", "Take your bags with you and walk to the nearest street."], 0, "Mrs. Sari gave this advice at the end of the report.")
    ]
  });
})();
