/* THE BRAVE WAY — levels, challengers and questions.
   Every text is [Bahasa Indonesia, English]. Each question has 4 options (ok = index of the right one)
   and a short explanation for every option. */
window.AB = window.AB || {};
AB.npcNames = {
  persuader:["Si Pembujuk","The Persuader"], trickster:["Si Pengelabui","The Trickster"], stranger:["Si Orang Asing","The Stranger"],
  rumor:["Si Penyebar Kabar","The Rumor Spreader"], final:["Penantang Terakhir","The Final Challenger"]
};
AB.npcRole = {
  persuader:["Suka membujuk","Loves to pressure"], trickster:["Memberi info yang menyesatkan","Gives misleading info"], stranger:["Membuat tawaran mencurigakan","Makes suspicious offers"],
  rumor:["Menyebar mitos","Spreads myths"], final:["Gabungan semua tantangan","All challenges in one"]
};
const Q = (cat,mod,say,q,opts,ok,fb,hint) => ({cat,mod,say,q,opts,ok,fb,hint});

AB.levels = [
/* ───────────── LEVEL 1 ───────────── */
{ id:1, badge:"shield", mod:1, theme:"stone", cells:[6,4], seed:74, loops:0, stars:6,
  title:["Jalur Sehat","Healthy Path"],
  obj:["Kumpulkan kunci emas, kalahkan 3 penantang, lalu keluar lewat gerbang EXIT!","Collect the golden key, beat 3 challengers, then escape through the EXIT gate!"],
  focus:["Kebiasaan sehat dan mengenali risiko","Healthy habits and recognising risks"],
  npcs:[
   {type:"trickster", qs:[ Q("safety",4,
     ["Psst! Kamu nggak perlu tidur kalau minum minuman manis berenergi. Percaya deh!","Psst! You don't need sleep if you drink a sweet energy drink. Trust me!"],
     ["Apa tanggapanmu?","What is your reply?"],
     [["Tidur cukup tetap penting untuk otak dan tubuhku, jadi aku tetap tidur cukup.","Enough sleep is still important for my brain and body, so I'll still sleep enough."],
      ["Benar, aku akan begadang setiap malam.","True, I'll stay up every night."],
      ["Minuman manis bisa menggantikan tidur.","Sweet drinks can replace sleep."],
      ["Tidur itu buang-buang waktu.","Sleeping is a waste of time."]],0,
     [["Tepat! Tidur cukup membantu tubuh pulih dan pikiran fokus.","Right! Enough sleep helps your body recover and your mind focus."],
      ["Begadang terus membuat lelah dan sulit mengendalikan emosi.","Staying up all the time makes you tired and makes feelings harder to control."],
      ["Tidak ada minuman yang bisa menggantikan tidur.","No drink can replace sleep."],
      ["Tidur justru bagian penting dari hidup sehat.","Sleep is actually an important part of a healthy life."]],
     ["Hidup sehat: tidur cukup, makan seimbang, bergerak aktif.","Healthy living: enough sleep, balanced food, active movement."]) ]},
   {type:"persuader", qs:[ Q("safety",4,
     ["Ayo, nggak usah olahraga atau ikut klub. Main HP semalaman jauh lebih seru!","Come on, skip sports and clubs. Playing on your phone all night is way more fun!"],
     ["Apa yang kamu lakukan?","What do you do?"],
     [["Aku main sebentar, tapi tetap olahraga, ikut klub, dan tidur cukup.","I'll play for a bit, but I'll still exercise, join a club and sleep enough."],
      ["Oke, aku main HP sampai pagi.","Okay, I'll play on my phone until morning."],
      ["Olahraga itu memalukan.","Exercise is embarrassing."],
      ["Aku ikut saja supaya tidak dijauhi.","I'll just go along so nobody leaves me out."]],0,
     [["Bagus! Kamu mengatur waktu dan menjaga keseimbangan.","Good! You managed your time and kept a balance."],
      ["Begadang main HP membuat tubuh dan pikiran lelah.","Playing all night makes your body and mind tired."],
      ["Olahraga membuat tubuh kuat dan suasana hati lebih baik.","Exercise keeps you strong and lifts your mood."],
      ["Ikut-ikutan bukan alasan yang baik. Pilihan sehat itu milikmu.","Going along is not a good reason. A healthy choice is yours to make."]],
     ["Kendali diri: atur waktu dan pilih yang menyehatkan.","Self-control: manage your time and choose what keeps you healthy."]) ]},
   {type:"rumor", qs:[ Q("safety",1,
     ["Katanya benda tak dikenal yang ditawarkan teman itu pasti aman. Aku pernah lihat sendiri!","They say an unknown item a friend offers is always safe. I saw it myself!"],
     ["Mitos atau fakta? Apa jawabanmu?","Myth or fact? What is your answer?"],
     [["Itu mitos. Aku tidak bisa tahu benda itu aman, jadi aku menolaknya.","That's a myth. I can't know it's safe, so I refuse it."],
      ["Kalau teman yang menawarkan, pasti aman.","If a friend offers it, it must be safe."],
      ["Coba sedikit saja untuk mengecek.","Try just a little to check."],
      ["Tanya rasanya seperti apa, lalu putuskan.","Ask what it tastes like, then decide."]],0,
     [["Tepat! Benda tak dikenal tidak boleh dicoba, siapa pun yang menawarkan.","Right! Never try an unknown item, no matter who offers it."],
      ["Teman pun bisa keliru atau tidak tahu isinya.","Friends can be wrong or not know what is inside."],
      ["Mencoba sedikit pun tetap berisiko.","Even a little is still risky."],
      ["Cerita rasa tidak membuktikan keamanan.","A description of the taste does not prove safety."]],
     ["Zat atau benda yang tidak dikenal tidak boleh dicoba.","Unknown items or substances must never be tried."]) ]}
 ]},

/* ───────────── LEVEL 2 ───────────── */
{ id:2, badge:"voice", mod:2, theme:"hedge", cells:[7,4], seed:137, loops:1, stars:7,
  title:["Berani Bilang Tidak!","Say No!"],
  obj:["Hadapi 3 penantang dengan suara beranimu, ambil kunci emas, lalu kabur lewat EXIT!","Face 3 challengers with your brave voice, grab the golden key and escape through the EXIT!"],
  focus:["Menolak dengan tegas dan tekanan teman","Assertive refusal and peer pressure"],
  npcs:[
   {type:"persuader", qs:[ Q("voice",2,
     ["Ayo bolos pelajaran sekali saja! Semua anak keren ikut!","Let's skip class just once! All the cool kids are going!"],
     ["Jawaban mana yang paling tegas dan sopan?","Which answer is the most firm and polite?"],
     [["Tidak, terima kasih. Aku mau tetap di kelas.","No, thank you. I'm staying in class."],
      ["Hmm… mungkin lain kali.","Hmm… maybe next time."],
      ["Oke, tapi sebentar saja.","Okay, but just for a little while."],
      ["Kalian semua payah!","You're all lame!"]],0,
     [["Tepat! Jelas, tenang, dan sopan.","Right! Clear, calm and polite."],
      ["\"Mungkin\" membuka pintu untuk bujukan berikutnya.","\"Maybe\" opens the door to more pressure."],
      ["Itu berarti kamu sudah menyerah pada tekanan.","That means you gave in to the pressure."],
      ["Menghina bukan ketegasan; tolak tanpa menyakiti.","Insulting isn't being assertive; refuse without hurting."]],
     ["Ciri tegas: jelas, tenang, sopan, tidak ragu.","Assertive means clear, calm, polite and not hesitant."]) ]},
   {type:"trickster", qs:[ Q("voice",2,
     ["Kalau kamu menolak, kamu bukan temanku lagi. Teman sejati ikut apa pun!","If you say no, you're not my friend anymore. True friends join in on anything!"],
     ["Apa tanggapanmu?","How do you respond?"],
     [["Teman sejati menghormati pilihanku. Aku tetap menolak, tapi kita bisa main hal lain.","True friends respect my choice. I still say no, but we can do something else."],
      ["Baiklah, supaya tetap berteman aku ikut.","Fine, I'll join so we stay friends."],
      ["Aku akan membalasmu nanti.","I'll get back at you later."],
      ["Aku diam saja dan menuruti.","I'll say nothing and follow."]],0,
     [["Tepat! Kamu tegas dan tetap menawarkan alternatif yang positif.","Right! You were firm and still offered a positive alternative."],
      ["Berteman tidak berarti harus melanggar aturan.","Friendship does not mean breaking rules."],
      ["Mengancam hanya memperkeruh keadaan.","Threats only make things worse."],
      ["Diam bisa dianggap setuju. Ucapkan pilihanmu.","Silence can look like agreement. Say what you choose."]],
     ["Teman sejati menghormati keputusanmu.","True friends respect your decisions."]) ]},
   {type:"rumor", qs:[ Q("voice",2,
     ["Orang berani itu pasti mau mencoba apa saja. Yang menolak itu penakut!","Brave people try anything. Anyone who says no is a coward!"],
     ["Apa pendapatmu tentang berani?","What do you think being brave means?"],
     [["Berani itu mempertahankan pilihan yang aman, bukan menuruti tantangan.","Being brave means sticking to a safe choice, not following a dare."],
      ["Berani itu melanggar aturan.","Being brave means breaking rules."],
      ["Berani itu ikut semua ajakan.","Being brave means accepting every invitation."],
      ["Berani itu menantang semua orang.","Being brave means challenging everyone."]],0,
     [["Tepat! Menolak hal yang tidak aman justru butuh keberanian.","Right! Refusing something unsafe takes real courage."],
      ["Melanggar aturan tidak membuktikan apa-apa.","Breaking rules proves nothing."],
      ["Ikut-ikutan bukan keberanian.","Following along is not courage."],
      ["Berani bukan mencari musuh.","Courage is not looking for enemies."]],
     ["Kamu tidak perlu membuktikan apa pun dengan hal berisiko.","You don't need to prove anything with something risky."]) ]}
 ]},

/* ───────────── LEVEL 3 ───────────── */
{ id:3, badge:"smart", mod:3, theme:"brick", cells:[8,5], seed:23, loops:2, stars:8,
  title:["Paket Rahasia","Secret Package"],
  obj:["Waspadai 4 penantang yang mencurigakan, temukan kunci emas, lalu keluar lewat EXIT!","Watch out for 4 suspicious challengers, find the golden key and head for the EXIT!"],
  focus:["Tawaran mencurigakan dan melapor dengan aman","Suspicious offers and safe reporting"],
  npcs:[
   {type:"stranger", qs:[ Q("safety",3,
     ["Hai! Titip paket kecil ini ke gerbang belakang, ya. Upahnya Rp100.000. Jangan bilang siapa-siapa!","Hi! Take this small package to the back gate. You'll get Rp100,000. Don't tell anyone!"],
     ["Apa yang kamu lakukan?","What do you do?"],
     [["Maaf, aku tidak membawa barang yang tidak kuketahui. Aku akan memberi tahu guru.","Sorry, I don't carry things I know nothing about. I'll tell a teacher."],
      ["Oke, lumayan uangnya.","Okay, the money is nice."],
      ["Buka dulu paketnya untuk melihat isinya.","Open the package first to see what's inside."],
      ["Bawa saja, tapi tidak usah bilang siapa-siapa.","Take it, but tell nobody."]],0,
     [["Tepat! Menolak dan melapor adalah langkah yang aman.","Right! Refusing and reporting is the safe step."],
      ["Upah besar untuk tugas kecil adalah tanda bahaya.","A big reward for a small task is a warning sign."],
      ["Memegang atau membuka barang tak dikenal tidak aman.","Handling or opening an unknown item is not safe."],
      ["Rahasia dari orang dewasa adalah tanda bahaya.","Secrecy from adults is a warning sign."]],
     ["Tolak, jangan bawa barang asing, dan laporkan.","Refuse, don't carry strange items, and report it."]) ]},
   {type:"trickster", qs:[ Q("safety",3,
     ["Pesan masuk: \"Aku temannya kakakmu. Kirim alamatmu SEKARANG atau kamu menyesal!\"","New message: \"I'm your brother's friend. Send your address NOW or you'll regret it!\""],
     ["Apa langkahmu?","What is your next step?"],
     [["Tidak membalas dan menunjukkan pesan itu kepada orang tua atau guru.","Don't reply and show the message to a parent or teacher."],
      ["Mengirim alamat supaya aman.","Send the address to be safe."],
      ["Membalas dengan marah.","Reply angrily."],
      ["Menghapus pesan dan menyimpannya sendiri.","Delete the message and keep it to myself."]],0,
     [["Tepat! Orang dewasa tepercaya bisa membantu melindungimu.","Right! A trusted adult can help protect you."],
      ["Jangan pernah memberikan data pribadi kepada orang asing.","Never give personal data to strangers."],
      ["Membalas memberi tahu mereka bahwa nomormu aktif.","Replying tells them your number is active."],
      ["Orang dewasa perlu tahu agar bisa membantumu.","Adults need to know so they can help you."]],
     ["Pesan yang mengancam atau memaksa harus ditunjukkan ke orang dewasa.","A threatening or pushy message should be shown to an adult."]) ]},
   {type:"rumor", qs:[ Q("safety",3,
     ["Katanya mengantar paket seperti itu aman dan keren. Banyak anak sudah melakukannya!","They say delivering packages like that is safe and cool. Lots of kids already do it!"],
     ["Mitos atau fakta? Apa jawabanmu?","Myth or fact? What is your answer?"],
     [["Banyak yang melakukannya bukan berarti aman. Aku akan bertanya kepada guru.","Many people doing it doesn't make it safe. I'll ask a teacher."],
      ["Kalau banyak yang melakukan, pasti aman.","If many do it, it must be safe."],
      ["Aku ikut, supaya dibilang keren.","I'll join so people think I'm cool."],
      ["Aku cari sendiri siapa yang menyuruh.","I'll find out on my own who is behind it."]],0,
     [["Tepat! Jumlah orang tidak menentukan keamanan.","Right! Numbers don't decide whether something is safe."],
      ["Banyak orang melakukan sesuatu tidak membuatnya aman.","Many people doing something doesn't make it safe."],
      ["Ikut-ikutan demi terlihat keren bisa membahayakanmu.","Going along to look cool can put you in danger."],
      ["Jangan menyelidiki sendiri. Serahkan pada orang dewasa.","Don't investigate alone. Leave it to adults."]],
     ["Jangan menyelidiki sendiri; beri tahu orang dewasa tepercaya.","Don't investigate on your own; tell a trusted adult."]) ]},
   {type:"persuader", qs:[ Q("safety",3,
     ["Lihat, ada bungkusan aneh di loker! Buka yuk, siapa tahu isinya seru!","Look, a strange packet in the locker! Let's open it, it might be fun!"],
     ["Apa yang kamu lakukan?","What do you do?"],
     [["Jangan disentuh. Kita lapor ke guru atau satpam.","Don't touch it. Let's tell a teacher or the guard."],
      ["Buka sedikit saja.","Just open it a little."],
      ["Bawa pulang saja.","Take it home."],
      ["Tunggu dan lihat siapa yang mengambilnya.","Wait to see who comes for it."]],0,
     [["Tepat! Jangan sentuh, laporkan, lalu menjauh.","Right! Don't touch it, report it, then step away."],
      ["Membuka benda tak dikenal tidak aman.","Opening an unknown item is not safe."],
      ["Membawa pulang bisa membahayakan keluargamu.","Taking it home could put your family at risk."],
      ["Mengawasi sendiri bisa berbahaya. Itu tugas orang dewasa.","Watching on your own can be dangerous. That is the adults' job."]],
     ["Temukan benda mencurigakan? Jangan sentuh dan laporkan.","Found something suspicious? Don't touch it and report it."]) ]}
 ]},

/* ───────────── LEVEL 4 ───────────── */
{ id:4, badge:"caring", mod:3, theme:"library", cells:[8,6], seed:140, loops:3, stars:9,
  title:["Bantu Sahabat","Help a Friend"],
  obj:["Tunjukkan empatimu pada 4 penantang, ambil kunci emas, lalu keluar lewat EXIT!","Show empathy to 4 challengers, collect the golden key and go through the EXIT!"],
  focus:["Empati dan orang dewasa tepercaya","Empathy and trusted adults"],
  npcs:[
   {type:"rumor", qs:[ Q("empathy",3,
     ["Dito pendiam banget. Pasti dia pakai narkoba! Semua orang bilang begitu.","Dito is so quiet. He must be on drugs! Everyone says so."],
     ["Apa tanggapanmu?","How do you respond?"],
     [["Jangan menebak-nebak. Aku akan menyapanya, \"Aku di sini kalau kamu mau cerita.\"","Let's not guess. I'll say to him, \"I'm here if you want to talk.\""],
      ["Benar, kita ceritakan ke semua orang.","True, let's tell everyone."],
      ["Kita tanya langsung, \"Kamu pakai apa?\"","Let's ask him straight, \"What are you on?\""],
      ["Kita jauhi saja dia.","Let's just stay away from him."]],0,
     [["Tepat! Perubahan sikap bisa punya banyak sebab. Empati lebih baik daripada tebakan.","Right! Mood changes can have many causes. Empathy beats guessing."],
      ["Menyebarkan dugaan bisa mempermalukan dan keliru.","Spreading guesses can embarrass and be wrong."],
      ["Menuduh membuatnya merasa dihakimi.","Accusing makes him feel judged."],
      ["Menjauhi membuatnya makin sendirian.","Avoiding him makes him lonelier."]],
     ["Jangan berasumsi. Dengarkan tanpa menghakimi.","Don't assume. Listen without judging."]) ]},
   {type:"trickster", qs:[ Q("empathy",3,
     ["Kalau temanmu bercerita, jangan bilang orang dewasa. Itu mengkhianatinya!","If your friend tells you something, never tell an adult. That's betraying them!"],
     ["Apa tanggapanmu?","How do you respond?"],
     [["Jika keselamatannya terancam, melibatkan orang dewasa tepercaya itu bentuk peduli. Aku akan menemaninya.","If his safety is at risk, involving a trusted adult is a way of caring. I'll go with him."],
      ["Benar, aku akan simpan rahasia apa pun yang terjadi.","True, I'll keep any secret no matter what."],
      ["Aku akan menyelesaikannya sendiri.","I'll sort it out on my own."],
      ["Aku tidak peduli.","I don't care."]],0,
     [["Tepat! Rahasia yang membahayakan keselamatan tidak boleh dipendam sendirian.","Right! A secret that risks safety shouldn't be kept alone."],
      ["Berjanji menyimpan rahasia tidak berlaku bila keselamatan terancam.","A promise of secrecy doesn't apply when safety is at risk."],
      ["Masalah besar butuh bantuan orang dewasa tepercaya.","Big problems need help from a trusted adult."],
      ["Temanmu membutuhkan dukunganmu.","Your friend needs your support."]],
     ["Orang dewasa tepercaya: orang tua, guru, guru BK.","Trusted adults: parents, teachers, the school counselor."]) ]},
   {type:"persuader", qs:[ Q("empathy",4,
     ["Ayo kita tertawakan Dito yang lagi sedih. Biar dia jadi lebih kuat!","Let's laugh at Dito while he's sad. It'll make him stronger!"],
     ["Apa yang kamu lakukan?","What do you do?"],
     [["Menertawakan itu menyakiti. Aku akan mendengarkan dan mendukungnya.","Laughing hurts. I'll listen to him and support him."],
      ["Ikut tertawa supaya seru.","Join in the laughing for fun."],
      ["Mengambil foto dan mengunggahnya.","Take a photo and post it."],
      ["Berpura-pura tidak melihat.","Pretend I didn't see anything."]],0,
     [["Tepat! Dukungan hangat membuat teman merasa aman.","Right! Warm support makes friends feel safe."],
      ["Menertawakan teman yang sedih adalah perundungan.","Laughing at a sad friend is bullying."],
      ["Mengunggah foto mempermalukannya dan melanggar privasi.","Posting a photo embarrasses him and breaks his privacy."],
      ["Mengabaikan membuat temanmu merasa tidak ada yang peduli.","Ignoring it makes your friend feel nobody cares."]],
     ["Dengarkan dan dukung. Hormati perasaan teman.","Listen and support. Respect your friend's feelings."]) ]},
   {type:"stranger", qs:[ Q("empathy",3,
     ["Aku bisa bantu temanmu yang sedih! Kasih saja dia ini, dijamin langsung tenang.","I can help your sad friend! Just give him this and he'll calm down right away."],
     ["Apa tanggapanmu?","How do you respond?"],
     [["Terima kasih, tapi bantuan terbaik datang dari orang dewasa tepercaya seperti guru BK.","Thank you, but the best help comes from trusted adults like the school counselor."],
      ["Baik, aku berikan kepadanya.","Okay, I'll give it to him."],
      ["Aku coba dulu supaya yakin.","I'll try it first to be sure."],
      ["Simpan saja dulu di tasku.","I'll keep it in my bag for now."]],0,
     [["Tepat! Jangan menerima benda tak dikenal; ajak temanmu bertemu orang dewasa tepercaya.","Right! Never accept unknown items; invite your friend to meet a trusted adult."],
      ["Memberikan benda tak dikenal kepada teman bisa membahayakannya.","Giving an unknown item to a friend could harm him."],
      ["Mencoba benda tak dikenal tidak pernah aman.","Trying an unknown item is never safe."],
      ["Menyimpan benda tak dikenal juga berisiko.","Keeping an unknown item is risky too."]],
     ["Bantuan yang aman datang dari orang dewasa tepercaya.","Safe help comes from trusted adults."]) ]}
 ]},

/* ───────────── LEVEL 5 ───────────── */
{ id:5, badge:"champion", mod:5, theme:"festival", cells:[9,6], seed:253, loops:4, stars:10,
  title:["Pelarian Terakhir","Final Escape"],
  obj:["Kalahkan 4 penantang termasuk Penantang Terakhir, ambil kunci emas, lalu kabur lewat EXIT!","Beat 4 challengers including the Final Challenger, take the golden key and escape through the EXIT!"],
  focus:["Gabungan semua kompetensi pencegahan","All prevention skills combined"],
  npcs:[
   {type:"persuader", qs:[ Q("empathy",5,
     ["Kegiatan sekolah itu buang waktu. Nggak usah ikut apa-apa, di rumah saja!","School activities are a waste of time. Don't join anything, just stay home!"],
     ["Apa jawabanmu?","What is your answer?"],
     [["Kegiatan positif membuatku sehat dan punya teman baik. Aku ikut!","Positive activities keep me healthy and help me find good friends. I'm in!"],
      ["Benar, aku di rumah saja.","True, I'll just stay home."],
      ["Kegiatan itu hanya untuk anak tertentu.","Activities are only for certain kids."],
      ["Aku ikut kalau dipaksa.","I'll join only if I'm forced."]],0,
     [["Tepat! Olahraga, seni, dan literasi membangun sekolah yang aman.","Right! Sports, arts and reading build a safe school."],
      ["Kegiatan positif membantumu tumbuh dan punya teman baik.","Positive activities help you grow and find good friends."],
      ["Kegiatan sekolah terbuka untuk semua siswa.","School activities are open to every student."],
      ["Lebih baik ikut karena mau, bukan karena dipaksa.","It's better to join because you want to, not because you're forced."]],
     ["Kegiatan positif: olahraga, seni, literasi, relawan.","Positive activities: sports, arts, reading, volunteering."]) ]},
   {type:"trickster", qs:[ Q("empathy",5,
     ["Slogan terbaik untuk poster: \"Jauhi anak-anak itu, mereka berbahaya!\" Setuju, kan?","The best poster slogan: \"Stay away from those kids, they're dangerous!\" Agree?"],
     ["Slogan mana yang lebih baik?","Which slogan is better?"],
     [["\"Berani Menolak, Berani Melapor!\" karena positif dan tidak melabeli siapa pun.","\"Brave to Say No, Brave to Speak Up!\" because it's positive and labels nobody."],
      ["\"Awas, yang salah akan dipermalukan!\"","\"Beware, anyone at fault will be shamed!\""],
      ["\"Jauhi anak-anak itu!\"","\"Stay away from those kids!\""],
      ["Tidak usah pakai slogan.","No slogan needed."]],0,
     [["Tepat! Pesan yang merangkul membuat orang berani meminta bantuan.","Right! Inclusive messages make people brave enough to ask for help."],
      ["Mempermalukan membuat orang takut mencari bantuan.","Shaming makes people afraid to ask for help."],
      ["Melabeli orang itu tidak adil dan menyakitkan.","Labelling people is unfair and hurtful."],
      ["Pesan yang positif membantu semua siswa.","A positive message helps every student."]],
     ["Slogan yang baik: positif, akurat, dan mengajak.","A good slogan is positive, accurate and inviting."]) ]},
   {type:"rumor", qs:[ Q("safety",4,
     ["Katanya stres bisa hilang kalau kamu coba-coba sesuatu yang baru dan terlarang. Semua orang tahu itu!","They say stress goes away if you try something new and forbidden. Everyone knows that!"],
     ["Mitos atau fakta? Apa jawabanmu?","Myth or fact? What is your answer?"],
     [["Mitos. Cara sehat: bercerita, olahraga, hobi, atau bertemu guru BK.","Myth. Healthy ways: talk it out, exercise, hobbies or see the counselor."],
      ["Fakta, aku akan mencobanya.","Fact, I'll try it."],
      ["Fakta, tapi hanya sedikit.","Fact, but only a little."],
      ["Lebih baik dipendam sendiri.","Better to keep it all inside."]],0,
     [["Tepat! Stres dikelola dengan cara yang sehat dan aman.","Right! Stress is handled in healthy, safe ways."],
      ["Hal terlarang tidak mengatasi stres dan bisa menambah masalah.","Forbidden things don't solve stress and can add problems."],
      ["Sedikit pun tetap berisiko.","Even a little is still risky."],
      ["Memendam membuat beban lebih berat. Bercerita itu membantu.","Bottling it up makes the load heavier. Talking helps."]],
     ["Kelola stres: bercerita, bergerak, berkreasi, atau minta bantuan.","Handle stress by talking, moving, creating or asking for help."]) ]},
   {type:"final", qs:[
     Q("safety",1,
      ["Heh! Aku Penantang Terakhir. Tantangan pertama: seseorang menawarimu benda tak dikenal dan menyuruh merahasiakannya.","Ha! I'm the Final Challenger. Challenge one: someone offers you an unknown item and tells you to keep it secret."],
      ["Apa yang kamu lakukan?","What do you do?"],
      [["Menolak, menjauh, lalu memberi tahu orang dewasa tepercaya.","Refuse, step away, then tell a trusted adult."],
       ["Menerima dan menyimpannya.","Accept it and keep it."],
       ["Mencicipi sedikit saja.","Taste just a little."],
       ["Menyelidiki sendiri siapa yang menawarkannya.","Investigate on my own who offered it."]],0,
      [["Tepat! Tolak, menjauh, lapor. Tiga langkah aman!","Right! Refuse, leave, report. Three safe steps!"],
       ["Benda tak dikenal tidak boleh disimpan atau diterima.","Never accept or keep unknown items."],
       ["Mencicipi benda tak dikenal tidak pernah aman.","Tasting unknown items is never safe."],
       ["Menyelidiki sendiri bisa berbahaya. Serahkan pada orang dewasa.","Investigating alone can be dangerous. Leave it to adults."]],
      ["Tolak, menjauh, dan beri tahu orang dewasa.","Refuse, step away and tell an adult."]),
     Q("empathy",3,
      ["Tantangan kedua: temanmu bilang ada yang menekannya terus-menerus dan ia takut. Ia memintamu merahasiakannya.","Challenge two: your friend says someone keeps pressuring them and they're scared. They ask you to keep it secret."],
      ["Apa yang kamu lakukan?","What do you do?"],
      [["Mengucapkan terima kasih atas kepercayaannya, lalu menemaninya menemui guru BK.","Thank them for trusting me, then go with them to the counselor."],
       ["Berjanji merahasiakannya.","Promise to keep it secret."],
       ["Mendatangi orang itu dan menyuruhnya berhenti.","Go to that person and tell them to stop."],
       ["Menyuruh temanmu menghadapinya sendiri.","Tell my friend to deal with it alone."]],0,
      [["Tepat! Menemani dan melibatkan orang dewasa tepercaya menjaga temanmu tetap aman.","Right! Going with them and involving a trusted adult keeps your friend safe."],
       ["Rahasia yang membahayakan keselamatan tidak boleh dipendam.","A secret that risks safety shouldn't be kept."],
       ["Menghadapi sendiri bisa berbahaya.","Confronting alone can be dangerous."],
       ["Temanmu butuh dukungan, bukan ditinggalkan.","Your friend needs support, not to be left alone."]],
      ["Temani teman menemui orang dewasa tepercaya.","Go with your friend to a trusted adult."]),
     Q("voice",5,
      ["Tantangan terakhir: pesan apa yang paling baik untuk menutup kampanye sekolah?","Final challenge: which message is best to close the school campaign?"],
      ["Pilih pesan terbaik.","Choose the best message."],
      [["Berani Menolak. Berani Melapor. Berani Peduli.","Say No. Speak Up. Care for Others."],
       ["Pokoknya jangan coba-coba, titik!","Just don't ever try it, period!"],
       ["Siapa yang aneh harus dijauhi.","Anyone strange should be avoided."],
       ["Tidak perlu pesan apa-apa.","No message is needed."]],0,
      [["Hebat! Pesan yang positif, merangkul, dan mengajak bertindak. Kamu juara THE BRAVE WAY!","Excellent! A positive, inclusive message that invites action. You are a BRAVE WAY champion!"],
       ["Larangan tanpa solusi tidak memberi tahu ke mana mencari bantuan.","A ban without solutions doesn't say where to find help."],
       ["Pesan yang melabeli membuat orang takut meminta tolong.","Labelling messages make people afraid to ask for help."],
       ["Pesan positif membantu seluruh sekolah.","A positive message helps the whole school."]],
      ["Pesan terbaik: positif, merangkul, dan mengajak bertindak.","The best message is positive, inclusive and invites action."]) ]}
 ]}
];
