/* THE BRAVE WAY — Cocurricular Corner (Bangunlah Jiwa dan Raganya), DPL and My Brave Way Project.
   Every text is [Bahasa Indonesia, English]. */
window.AB = window.AB || {};
AB.corner = {
 title:["Pojok Kokurikuler","Cocurricular Corner"],
 theme:"Bangunlah Jiwa dan Raganya", themeGloss:["","Building a Healthy Body and Mind"],
 intro:["Tema kokurikuler ini mengajak kita menjaga tubuh yang sehat dan pikiran yang kuat. Semua pelajaran di THE BRAVE WAY adalah latihan kecil untuk itu. Pilih satu topik di bawah, lalu buka pelajarannya di LEARN YO!","This cocurricular theme invites us to care for a healthy body and a strong mind. Every lesson in THE BRAVE WAY is a small practice for that. Pick a topic below, then open its lesson in LEARN YO!"],
 linksTitle:["Pelajaran yang saling terhubung","How the lessons connect"],
 links:[
  {e:"💪",t:["Kesehatan fisik dan mental","Physical and mental health"],d:["Tidur cukup, makan seimbang, bergerak aktif, dan mengelola stres dengan cara yang sehat. Latih di Level 1.","Enough sleep, balanced food, active movement and healthy ways to handle stress. Practise it in Level 1."],mod:4},
  {e:"🤗",t:["Kebiasaan sehat dan pertemanan positif","Healthy habits and positive friendships"],d:["Pilih kegiatan dan teman yang saling mendukung, lalu temukan lingkungan yang positif.","Choose activities and friends that support each other, and find a positive circle."],mod:4},
  {e:"🧠",t:["Mengambil keputusan yang bertanggung jawab","Responsible decision-making"],d:["Kenali tanda bahaya, pikirkan akibatnya, lalu pilih langkah yang aman. Latih di Level 1 dan 3.","Spot warning signs, think about the results, then choose a safe step. Practise it in Levels 1 and 3."],mod:1},
  {e:"🗣️",t:["Komunikasi asertif","Assertive communication"],d:["Menolak dengan jelas, tenang, dan sopan tanpa menyakiti orang lain. Latih di Level 2.","Say no clearly, calmly and politely without hurting others. Practise it in Level 2."],mod:2},
  {e:"💛",t:["Empati dan mencari bantuan","Empathy and seeking help"],d:["Mendengarkan tanpa menghakimi dan mengajak teman bertemu orang dewasa tepercaya. Latih di Level 4.","Listen without judging and invite a friend to talk to a trusted adult. Practise it in Level 4."],mod:3}
 ],
 dplTitle:["Dimensi Profil Lulusan (DPL)","Graduate Profile Dimensions (DPL)"],
 dplIntro:["Permainan dan pelajaran ini membantu kamu berlatih lima dimensi berikut. Dimensi tumbuh sedikit demi sedikit lewat banyak kegiatan, jadi ini bukan tanda bahwa kamu sudah menguasainya.","This game and its lessons help you practise the five dimensions below. Dimensions grow little by little through many activities, so this does not mean you have already mastered them."],
 dpl:[
  {e:"💪",n:["Kesehatan","Health"],d:["Di Level 1 dan Modul 4, kamu berlatih kebiasaan sehat: tidur cukup, bergerak aktif, mengelola stres, dan meminta bantuan.","In Level 1 and Module 4, you practise healthy habits: enough sleep, active movement, handling stress and asking for help."]},
  {e:"🔍",n:["Penalaran Kritis","Critical Reasoning"],d:["Para penantang menyebar mitos dan info yang menyesatkan. Kamu berlatih memeriksa klaim dan memikirkan akibat sebelum memilih.","The challengers spread myths and misleading information. You practise checking claims and thinking about results before you choose."]},
  {e:"🧭",n:["Kemandirian","Independence"],d:["Kamu berlatih memilih langkah yang aman, mengendalikan diri dengan STOP, dan tahu kapan harus meminta bantuan orang dewasa.","You practise choosing safe steps, controlling yourself with STOP, and knowing when to ask a trusted adult for help."]},
  {e:"🤝",n:["Kolaborasi","Collaboration"],d:["Di Level 4 dan 5 serta Tantangan Bonus, kamu berlatih mendukung teman, berbagi peran, dan membuat kampanye bersama.","In Levels 4 and 5 and the Bonus Challenges, you practise supporting friends, sharing roles and building a campaign together."]},
  {e:"💬",n:["Komunikasi","Communication"],d:["Di Level 2 kamu berlatih kalimat penolakan yang tegas dan sopan, serta cara mendengarkan dan meminta bantuan.","In Level 2 you practise firm, polite refusal sentences, and how to listen and ask for help."]}
 ],
 projTitle:["Proyek My Brave Way","My Brave Way Project"],
 projIntro:["Pilih satu proyek untuk menunjukkan apa yang kamu pelajari. Kamu boleh mengerjakannya sendiri atau berkelompok, sesuai arahan gurumu.","Choose one project to show what you learned. You can work alone or in a group, as your teacher says."],
 privacy:["Kamu tidak perlu menceritakan pengalaman pribadi yang sensitif. Gunakan contoh umum, tokoh rekaan, atau situasi imajiner.","You do not need to share sensitive personal experiences. Use general examples, made-up characters or imaginary situations."],
 projects:[
  {e:"🖼️",t:["Poster Hidup Sehat","Healthy Living Poster"],d:["Buat poster digital yang mengajak teman menjaga kesehatan tubuh dan pikiran.","Create a digital poster that invites friends to care for their body and mind."],
   steps:[["Pilih satu pesan utama, misalnya tidur cukup, bergerak aktif, atau bercerita saat bingung.","Choose one main message, such as enough sleep, active movement or talking when you feel unsure."],["Buat poster di aplikasi desain pilihanmu (misalnya Canva atau PowerPoint) dengan gambar dan slogan yang positif.","Make the poster in a design app you like (for example Canva or PowerPoint) with positive pictures and a slogan."],["Tulis satu tindakan nyata yang bisa dilakukan teman setelah melihat postermu.","Write one real action a friend can take after seeing your poster."],["Kumpulkan posterumu dan bacakan pesannya kepada kelas.","Hand in your poster and share its message with the class."]],
   check:[["Ada satu pesan utama yang jelas","There is one clear main message"],["Slogan positif dan tidak menyalahkan siapa pun","The slogan is positive and blames nobody"],["Ada gambar atau ikon yang menarik","There are attractive pictures or icons"],["Ada satu tindakan nyata untuk teman","There is one real action for friends"]]},
  {e:"🎬",t:["Kampanye Setiap Pilihan Itu Penting","Every Choice Matters Campaign"],d:["Buat video pendek (30–60 detik) tentang pencegahan yang positif.","Make a short video (30–60 seconds) about positive prevention."],
   steps:[["Pilih satu pesan: berani menolak, berani melapor, atau berani peduli.","Choose one message: brave to say no, brave to speak up, or brave to care."],["Tulis naskah singkat dengan tokoh rekaan dan situasi imajiner.","Write a short script with made-up characters and an imaginary situation."],["Rekam videomu dengan teman atau sendiri, lalu tambahkan teks dan musik yang sopan.","Record your video with friends or alone, then add text and suitable music."],["Tutup dengan kalimat \"Setiap Pilihan Itu Penting\" dan tunjukkan ke mana mencari bantuan.","End with \"Every Choice Matters\" and show where to find help."]],
   check:[["Video berdurasi 30–60 detik","The video is 30–60 seconds long"],["Pesan positif dan tidak melabeli orang","The message is positive and labels nobody"],["Menunjukkan langkah aman atau cara meminta bantuan","It shows a safe step or how to ask for help"],["Suara dan teks mudah dipahami","Voice and text are easy to understand"]]},
  {e:"📋",t:["Tantangan Kebiasaan Sehatku","My Healthy Habits Challenge"],d:["Rancang dan catat rencana kebiasaan sehat pribadimu.","Design and record your own personal healthy habits plan."],
   steps:[["Pilih dua atau tiga kebiasaan sehat, misalnya minum air, berolahraga, atau tidur tepat waktu.","Choose two or three healthy habits, such as drinking water, exercising or sleeping on time."],["Tulis kapan dan bagaimana kamu akan melakukannya selama satu minggu.","Write when and how you will do them for one week."],["Catat setiap hari dengan centang atau foto, lalu tulis satu hal yang berhasil dan satu hal yang bisa diperbaiki.","Record each day with a tick or photo, then write one thing that worked and one thing to improve."],["Pilih satu orang dewasa tepercaya yang bisa kamu ajak bicara jika butuh dukungan.","Pick one trusted adult you could talk to if you need support."]],
   check:[["Ada 2–3 kebiasaan yang jelas","There are 2–3 clear habits"],["Ada jadwal untuk satu minggu","There is a plan for one week"],["Ada catatan harian","There is a daily record"],["Ada satu hal yang berhasil dan satu yang diperbaiki","There is one success and one thing to improve"]]}
 ],
 stepsLabel:["Langkah","Steps"], checkLabel:["Daftar periksa","Checklist"],
 reflectTitle:["Pertanyaan Refleksi","Reflection Questions"],
 reflect:[["Pilihan sehat apa yang ingin kamu lanjutkan, dan mengapa itu penting bagimu?","Which healthy choice do you want to keep doing, and why is it important to you?"],["Bagaimana proyekmu bisa membantu teman memilih dengan aman dan saling mendukung?","How can your project help friends choose safely and support each other?"]],
 rubricTitle:["Rubrik Penilaian Guru","Teacher Assessment Rubric"],
 rubricNote:["Rubrik ini membantu guru memberi umpan balik pada proyek, bukan menilai kehidupan pribadi murid.","This rubric helps teachers give feedback on the project, not judge students' private lives."],
 rubricCrit:["Kriteria","Criteria"],
 levels:[["1 · Perlu Bimbingan","1 · Needs Support"],["2 · Berkembang","2 · Developing"],["3 · Cakap","3 · Proficient"],["4 · Sangat Baik","4 · Excellent"]],
 rubric:[
  {c:["Isi dan pesan","Content and message"],lv:[["Pesan belum jelas atau belum sesuai pelajaran.","The message is unclear or does not match the lessons."],["Pesan cukup jelas, tetapi ada bagian yang kurang tepat.","The message is fairly clear, but some parts are not accurate."],["Pesan jelas, tepat, dan sesuai pelajaran.","The message is clear, accurate and matches the lessons."],["Pesan sangat jelas, tepat, dan memberi contoh yang kuat.","The message is very clear, accurate and gives strong examples."]]},
  {c:["Pilihan aman dan berpikir kritis","Safe choices and critical thinking"],lv:[["Belum menunjukkan pilihan aman.","Does not yet show safe choices."],["Menunjukkan sebagian pilihan aman dengan alasan singkat.","Shows some safe choices with a short reason."],["Menunjukkan pilihan aman dengan alasan yang masuk akal.","Shows safe choices with sensible reasons."],["Menunjukkan pilihan aman, alasan kuat, dan memikirkan akibatnya.","Shows safe choices, strong reasons and thinks about the results."]]},
  {c:["Kreativitas dan penyajian","Creativity and presentation"],lv:[["Penyajian belum rapi.","The presentation is not yet neat."],["Penyajian cukup rapi dengan sedikit ide kreatif.","The presentation is fairly neat with a few creative ideas."],["Penyajian rapi, menarik, dan mudah dipahami.","The presentation is neat, attractive and easy to understand."],["Penyajian sangat menarik, orisinal, dan mengajak teman bertindak.","The presentation is very attractive, original and invites friends to act."]]},
  {c:["Refleksi, komunikasi, dan kolaborasi","Reflection, communication and collaboration"],lv:[["Refleksi belum dijawab.","The reflection is not answered yet."],["Refleksi dijawab singkat; kerja sama masih perlu diarahkan.","The reflection is short; teamwork needs guidance."],["Refleksi jelas; berkomunikasi dan bekerja sama dengan baik.","The reflection is clear; communicates and works well with others."],["Refleksi mendalam; berkomunikasi dengan sopan dan memimpin kerja sama.","The reflection is thoughtful; communicates politely and helps lead teamwork."]]}
 ]
};
/* DPL labels used on the certificate (short) */
AB.dplCert = [["Kesehatan","Health"],["Penalaran Kritis","Critical Reasoning"],["Kemandirian","Independence"],["Kolaborasi","Collaboration"],["Komunikasi","Communication"]];
Object.assign(AB.ui,{
 cornerCard:["Bangunlah Jiwa dan Raganya: hubungan pelajaran, DPL, dan proyek kecil.","Bangunlah Jiwa dan Raganya: how the lessons connect, the DPL and a small project."],
 cornerOpen:["Buka","Open"], backToCorner:["Kembali ke Pojok Kokurikuler","Back to the Cocurricular Corner"], backToLearn:["Kembali ke LEARN YO!","Back to LEARN YO!"],
 dplHead:["DIMENSI PROFIL LULUSAN (DPL)","GRADUATE PROFILE DIMENSIONS"], dplSub:["Dimensi yang Dikembangkan","Developed Dimensions"],
 dplTheme:["Tema: Bangunlah Jiwa dan Raganya","Theme: Bangunlah Jiwa dan Raganya (Building a Healthy Body and Mind)"],
 certFor:["atas partisipasi dan keberhasilannya menyelesaikan permainan edukatif THE BRAVE WAY sebagai bagian dari pembelajaran bertema Bangunlah Jiwa dan Raganya.","for successfully completing THE BRAVE WAY educational game as part of learning activities under the theme Building a Healthy Body and Mind."],
 certNote:["Sertifikat ini menghargai penyelesaian permainan edukatif, bukan hasil penilaian resmi sekolah.","This certificate recognises completing an educational game. It is not an official school assessment result."]
});
AB.ui.certPre=["Diberikan kepada","Awarded to"];
