/* ==========================================================
   NARRATIVE QUEST — Story file
   Aji Saka (Myth · Java, Indonesia)
   The myth of the origin of the Javanese script (Hanacaraka).
   ========================================================== */
NQ.registerStory({
  id: "aji-saka",
  title: "Aji Saka",
  genre: "myths",
  origin: "indonesia",
  region: "Java, Indonesia",
  country: "Indonesia",
  level: "A2–B1",
  minutes: 30,
  cover: "img/stories/aji-saka/aji-saka-cover.webp",
  summary: "A brave young man defeats a cruel king with a clever trick, but one small mistake leads to a sad story that becomes the Javanese alphabet.",

  /* ---------- STORY PAGES ---------- */
  pages: [
    {
      text: "A long time ago, on the island of Majeti, there lived a wise and brave young man named Aji Saka. He had two loyal servants, Dora and Sembada, who obeyed him in everything. One day, he heard that the people of Java needed help and decided to travel there. Before he left, he gave his precious kris to Sembada. “Guard this kris,” he said. “Do not give it to anyone except me.”",
      vocab: ["loyal", "precious"],
      scene: { art: "img/stories/aji-saka/aji-saka-gives-kris.webp", fit: "contain", alt: "aji saka gives kris", tone: "day", fx: [] },
    },
    {
      text: "Aji Saka and Dora sailed to the kingdom of Medang Kamulan in Java. But the people there looked thin and frightened. An old man explained that their king, Dewata Cengkar, was cruel and greedy. He took their rice and animals, and every day he demanded a person from the village for his meals. “Nobody can stop him,” the old man whispered. “Tomorrow it is my daughter’s turn.”",
      vocab: ["frightened", "demanded"],
      scene: { art: "img/stories/aji-saka/people-of-medang-kamulan.webp", fit: "contain", alt: "people of medang kamulan", tone: "day", fx: [] },
    },
    {
      text: "Aji Saka did not run away. He went straight to the palace. “Your Majesty, I will be your meal today,” he said calmly. “But first, please give me some land. I only want land as wide as my headcloth.” Dewata Cengkar laughed loudly. “Such a small piece of land! I agree.” He thought the young man was foolish.",
      vocab: ["headcloth", "foolish"],
      scene: { art: "img/stories/aji-saka/aji-saka-faces-dewata.webp", fit: "contain", alt: "aji saka faces dewata", tone: "day", fx: [] },
    },
    {
      text: "Aji Saka took off his headcloth, gave one end to the king and began to open it. The cloth grew wider and wider. It covered the palace, the fields and the forests. The king held his end tightly, and the cloth pushed him further and further south. He reached the edge of the southern sea and fell into the water. Some say he became a white crocodile.",
      vocab: ["edge"],
      scene: { art: "img/stories/aji-saka/headcloth-pushes-king.webp", fit: "contain", alt: "headcloth pushes king", tone: "day", fx: [] },
    },
    {
      text: "The people of Medang Kamulan were free at last. They cheered and chose Aji Saka as their new king. He ruled wisely and fairly, and the kingdom became peaceful. Later, Aji Saka remembered his kris. He told Dora, “Go back to Majeti and bring my kris to me.” Dora bowed and left at once.",
      vocab: ["cheered"],
      scene: { art: "img/stories/aji-saka/aji-saka-becomes-king.webp", fit: "contain", alt: "aji saka becomes king", tone: "day", fx: [] },
    },
    {
      text: "On Majeti, Dora met Sembada. “Our master wants his kris,” Dora said. “Please give it to me.” But Sembada refused. “Our master told me not to give it to anyone except him. Why should I break my promise?” Dora insisted, “But now our master has given a new order!” Both servants were loyal, and both wanted to obey their master. Neither of them gave up, so they fought. They were equally strong, and both of them died.",
      vocab: ["refused", "insisted"],
      scene: { art: "img/stories/aji-saka/dora-sembada-fight.webp", fit: "contain", alt: "dora sembada fight", tone: "day", fx: [] },
    },
    {
      text: "When Dora did not return, Aji Saka went to Majeti and learned the sad news. He felt deep regret. “This was my mistake,” he said. “I gave them two different orders.” To remember his two loyal servants, he wrote a poem: Ha na ca ra ka (there were two messengers), da ta sa wa la (they had a fight), pa dha ja ya nya (they were equally strong), ma ga ba tha nga (and both of them died). This poem became the Javanese alphabet.",
      vocab: ["regret", "messengers"],
      scene: { art: "img/stories/aji-saka/aji-saka-writes-hanacaraka.webp", fit: "contain", alt: "aji saka writes hanacaraka", tone: "day", fx: [] },
    },
  ],

  /* ---------- VOCABULARY (highlighted while reading) ---------- */
  vocabulary: [
    { word: "loyal", forms: ["loyal"], meaning: "always faithful to someone and ready to support them" },
    { word: "precious", forms: ["precious"], meaning: "very valuable and important" },
    { word: "frightened", forms: ["frightened"], meaning: "afraid" },
    { word: "demanded", forms: ["demanded"], meaning: "asked for something strongly, like an order" },
    { word: "headcloth", forms: ["headcloth"], meaning: "a piece of cloth worn around the head" },
    { word: "foolish", forms: ["foolish"], meaning: "silly; not able to think well" },
    { word: "edge", forms: ["edge"], meaning: "the place where something ends" },
    { word: "cheered", forms: ["cheered"], meaning: "shouted happily" },
    { word: "refused", forms: ["refused"], meaning: "said no to something" },
    { word: "insisted", forms: ["insisted"], meaning: "said strongly that something must happen" },
    { word: "regret", forms: ["regret"], meaning: "a sad feeling about something you did wrong" },
    { word: "messengers", forms: ["messengers"], meaning: "people who carry news or things for someone" },
  ],

  /* ---------- CHARACTERS ---------- */
  characters: [
    { id: "ajisaka", name: "Aji Saka", img: "img/stories/aji-saka/aji-saka.webp", role: "Main character", traits: ["brave", "clever", "wise", "responsible"],
      evidence: "“Your Majesty, I will be your meal today,” he said calmly. “But first, please give me some land.”" },
    { id: "dewata", name: "Dewata Cengkar", img: "img/stories/aji-saka/dewata-cengkar.webp", role: "The cruel king of Medang Kamulan", traits: ["cruel", "greedy", "arrogant"],
      evidence: "He took their rice and animals, and every day he demanded a person from the village for his meals." },
    { id: "dora", name: "Dora", img: "img/stories/aji-saka/dora.webp", role: "Aji Saka’s servant", traits: ["loyal", "obedient"],
      evidence: "Dora bowed and left at once." },
    { id: "sembada", name: "Sembada", img: "img/stories/aji-saka/sembada.webp", role: "Aji Saka’s servant", traits: ["loyal", "faithful"],
      evidence: "“Our master told me not to give it to anyone except him. Why should I break my promise?”" },
  ],

  /* Personality words taught in Character Detective */
  traitWords: [
    { word: "brave", meaning: "not afraid to do something difficult or dangerous" },
    { word: "clever", meaning: "quick to think and good at finding answers" },
    { word: "wise", meaning: "able to make good decisions" },
    { word: "responsible", meaning: "ready to accept the results of your own actions" },
    { word: "loyal", meaning: "always faithful to someone" },
    { word: "obedient", meaning: "doing what you are told to do" },
    { word: "cruel", meaning: "happy to hurt people or animals" },
    { word: "greedy", meaning: "wanting more than you need" },
    { word: "arrogant", meaning: "thinking you are better than other people" },
    { word: "cowardly", meaning: "too afraid to do what is right" },
  ],

  /* ---------- GENERIC STRUCTURE ---------- */
  structure: {
    orientation: { pages: [1], summary: "Aji Saka, a wise and brave young man, lived on Majeti with his loyal servants. He left his kris with Sembada and travelled to Java." },
    complication: { pages: [2, 3], summary: "The cruel King Dewata Cengkar frightened his people and demanded a person every day. Aji Saka offered himself, but asked for land as wide as his headcloth." },
    resolution: { pages: [4, 5], summary: "The headcloth grew wider and pushed the king into the southern sea. The people chose Aji Saka as their new king." },
    coda: { pages: [6, 7], summary: "Afterwards, a second, smaller problem ended sadly: two different orders made his loyal servants fight, and both died. Aji Saka accepted his mistake and wrote a poem that became the Javanese alphabet." },
  },
  mainConflict: "The cruel King Dewata Cengkar frightened his people and demanded a person every day, and Aji Saka had to find a way to stop him.",
  sequence: [
    "Aji Saka left his kris with Sembada.",
    "Aji Saka offered to be the king’s meal.",
    "The headcloth pushed the king into the southern sea.",
    "The people chose Aji Saka as their new king.",
    "Dora and Sembada fought, and both of them died.",
    "Aji Saka wrote a poem to remember them.",
  ],
  grammarExamples: {
    regular: ["decide → decided", "sail → sailed", "cheer → cheered"],
    irregular: ["give → gave", "grow → grew", "write → wrote"],
    was: "Dewata Cengkar was cruel and greedy.",
    were: "The people of Medang Kamulan were free at last.",
    negative: "Aji Saka did not run away.",
    question: "Did Sembada give the kris to Dora?",
  },
  /* Portraits used for feedback bubbles */
  guides: { good: "img/stories/aji-saka/aji-saka.webp", hint: "img/stories/aji-saka/hanacaraka-scroll.webp" },
  pastVerbs: [
    { base: "live", past: "lived", type: "regular" }, { base: "obey", past: "obeyed", type: "regular" },
    { base: "decide", past: "decided", type: "regular" }, { base: "bow", past: "bowed", type: "regular" },
    { base: "sail", past: "sailed", type: "regular" }, { base: "explain", past: "explained", type: "regular" },
    { base: "demand", past: "demanded", type: "regular" }, { base: "push", past: "pushed", type: "regular" },
    { base: "cheer", past: "cheered", type: "regular" }, { base: "refuse", past: "refused", type: "regular" },
    { base: "give", past: "gave", type: "irregular" }, { base: "take", past: "took", type: "irregular" },
    { base: "grow", past: "grew", type: "irregular" }, { base: "hold", past: "held", type: "irregular" },
    { base: "fall", past: "fell", type: "irregular" }, { base: "choose", past: "chose", type: "irregular" },
    { base: "fight", past: "fought", type: "irregular" }, { base: "write", past: "wrote", type: "irregular" },
  ],

  /* =========================================================
     CHALLENGES
     ========================================================= */
  challenges: {
    /* ---------------- 🔮 WORD HUNTER ---------------- */
    word: [
      {
        type: "mcq", skill: "Meaning in context", ref: 1,
        quote: "He had two loyal servants, Dora and Sembada, who obeyed him in everything.",
        prompt: "What does <b>loyal</b> mean in this sentence?",
        options: ["always faithful to someone", "always afraid of someone", "always angry with someone", "always hiding from someone"], answer: 0,
        hint: "The servants “obeyed him in everything”. How do people feel about someone when they always support them?",
        feedback: { 1: "Not quite. They obeyed him, but the story does not say they were afraid of him." },
        explain: "<b>Loyal</b> = always faithful and ready to support someone. Dora and Sembada were loyal to Aji Saka.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 2,
        quote: "But the people there looked thin and frightened.",
        prompt: "The people had a cruel king. So <b>frightened</b> probably means…",
        options: ["afraid", "proud", "bored", "excited"], answer: 0,
        hint: "Their king took their food and demanded a person every day. How would you feel?",
        explain: "<b>Frightened</b> = afraid. The people were afraid of their cruel king.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 2,
        quote: "Every day he demanded a person from the village for his meals.",
        prompt: "The king <b>demanded</b> a person every day. This means he…",
        options: ["asked for one strongly, like an order.", "asked for one quietly, as a favour.", "gave one away freely, as a present.", "sent one away angrily, as a punishment."], answer: 0,
        hint: "The king was cruel and powerful. Did the people have a choice?",
        feedback: { 1: "A cruel king does not ask for favours. The people could not say no." },
        explain: "<b>Demand</b> = ask for something strongly, like an order that people must obey.",
      },
      {
        type: "mcq", skill: "Word with two meanings", ref: 2,
        quote: "“Tomorrow it is my daughter’s turn.”",
        prompt: "What does <b>turn</b> mean in this sentence?",
        options: ["the time when something must happen to someone", "a movement to the left or to the right", "a change of direction on a road", "a short walk around the village"], answer: 0,
        hint: "Many words have more than one meaning. The king took one person every day. Who was next?",
        feedback: { 1: "That is a real meaning of turn — but not in this sentence. The old man is talking about his daughter being next." },
        explain: "Here, <b>turn</b> = the time when something happens to someone. The old man’s daughter was the next person for the king.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 1, image: "img/stories/aji-saka/kris.webp",
        prompt: "Look at the picture. Before he left Majeti, Aji Saka gave his precious ___ to Sembada.",
        options: ["kris", "spear", "shield", "crown"], answer: 0,
        hint: "It is a small traditional weapon from Java. Aji Saka told Sembada to guard it and give it to nobody else.",
        explain: "A <b>kris</b> is a traditional dagger from Java. Aji Saka’s kris was <b>precious</b> to him, so he asked Sembada to guard it.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 7, image: "img/stories/aji-saka/hanacaraka-scroll.webp",
        prompt: "Look at the picture. To remember his two servants, Aji Saka wrote a ___.",
        options: ["poem", "map", "law", "list"], answer: 0,
        hint: "It begins with “Ha na ca ra ka…” and tells a short, sad story.",
        explain: "He wrote a <b>poem</b>, and its sounds became the Javanese alphabet.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 1,
        quote: "Before he left, he gave his precious kris to Sembada.",
        prompt: "Which word is closest in meaning to <b>precious</b>?",
        options: ["valuable", "broken", "ordinary", "heavy"], answer: 0,
        hint: "Aji Saka asked Sembada to guard the kris very carefully. Why?",
        explain: "<b>Precious</b> = very <b>valuable</b> and important.",
      },
      {
        type: "mcq", skill: "Antonym", ref: 3,
        quote: "He thought the young man was foolish.",
        prompt: "Which word is the <b>opposite</b> of <b>foolish</b>?",
        options: ["silly", "wise", "stupid", "careless"], answer: 1,
        hint: "Three of these words are close to <i>foolish</i>. Find the one that is different.",
        feedback: { 0: "Silly is close in meaning to foolish, not the opposite.", 2: "Stupid is close in meaning to foolish, not the opposite.", 3: "A careless person does not think carefully — that is close to foolish." },
        explain: "<b>Foolish</b> ↔ <b>wise</b>. The king thought Aji Saka was foolish, but Aji Saka was really wise.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 6,
        quote: "Dora insisted, “But now our master has given a new order!”",
        prompt: "What does <b>insisted</b> mean here?",
        options: ["said strongly that it must happen", "said quietly that he was sorry", "agreed happily with the other man", "forgot the words of his master"], answer: 0,
        hint: "Sembada said no. Did Dora stop asking?",
        explain: "To <b>insist</b> = to say strongly that something must happen and not accept “no”.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 7,
        quote: "He felt deep regret. “This was my mistake,” he said.",
        prompt: "What is <b>regret</b>?",
        options: ["a sad feeling about something you did wrong", "a happy feeling about something you did well", "an angry feeling about something others did", "a calm feeling after a long and busy day"], answer: 0,
        hint: "Read what Aji Saka said next: “This was my mistake.”",
        explain: "<b>Regret</b> = a sad feeling about something you did wrong and wish you had not done.",
      },
      {
        type: "sort", skill: "Word–meaning match", layout: "match", capacity: 1,
        prompt: "Drag each word to its meaning. <span class='tip'>(Or tap a word, then tap a meaning.)</span>",
        bins: [
          { id: "headcloth", label: "a piece of cloth worn around the head" },
          { id: "edge", label: "the place where something ends" },
          { id: "cheered", label: "shouted happily" },
          { id: "refused", label: "said no to something" },
          { id: "messengers", label: "people who carry news or things" },
          { id: "bowed", label: "bent the head or body to show respect" },
        ],
        cards: [
          { text: "headcloth", bin: "headcloth" }, { text: "edge", bin: "edge" }, { text: "cheered", bin: "cheered" },
          { text: "refused", bin: "refused" }, { text: "messengers", bin: "messengers" }, { text: "bowed", bin: "bowed" },
        ],
        hint: "Start with the words you are sure about. The people <i>cheered</i> when they were free; the king reached the <i>edge</i> of the southern sea.",
        explain: "Great word hunting! You matched all six words.",
      },
    ],

    /* ---------------- 🧩 STORY DETECTIVE ---------------- */
    structure: [
      {
        type: "sort", skill: "Sort the story",
        prompt: "Put each event card in the correct part of the narrative.",
        bins: [
          { id: "orientation", label: "Orientation", img: "img/st-orientation.webp", sub: "Who? Where? When?" },
          { id: "complication", label: "Complication", img: "img/st-complication.webp", sub: "What problem happened?" },
          { id: "resolution", label: "Resolution", img: "img/st-resolution.webp", sub: "How was it solved?" },
          { id: "coda", label: "Ending / Coda", img: "img/st-ending.webp", sub: "What happened afterward?" },
        ],
        cards: [
          { text: "A long time ago, a wise young man lived on the island of Majeti.", bin: "orientation" },
          { text: "He had two loyal servants called Dora and Sembada.", bin: "orientation" },
          { text: "A cruel king demanded a person from the village every day.", bin: "complication" },
          { text: "Aji Saka offered to be the king’s meal for the day.", bin: "complication" },
          { text: "The headcloth grew wider and pushed the king into the sea.", bin: "resolution" },
          { text: "The free people chose Aji Saka as their new king.", bin: "resolution" },
          { text: "Aji Saka felt deep regret about his two orders.", bin: "coda" },
          { text: "His poem became the Javanese alphabet.", bin: "coda" },
        ],
        hint: "Orientation introduces the characters and place. Complication = the problem with the cruel king. Resolution = the king is defeated. Coda = what happened later, at the very end, and the lesson.",
        explain: "The story moves from <b>introduction</b> → <b>problem</b> → <b>solution</b> → <b>ending and lesson</b>.",
      },
      {
        type: "mcq", skill: "Find the complication", ref: 2,
        prompt: "Which sentence shows the <b>beginning of the complication</b>?",
        options: [
          "“But the people there looked thin and frightened.”",
          "“He had two loyal servants, Dora and Sembada.”",
          "“They cheered and chose Aji Saka as their new king.”",
          "“This poem became the Javanese alphabet.”",
        ], answer: 0,
        hint: "Look for the small word that tells us the story is changing direction.",
        explain: "The word <b>But</b> and “thin and frightened” signal that a problem is starting.",
      },
      {
        type: "mcq", skill: "Find the main conflict", ref: 2,
        prompt: "What is the <b>main conflict</b> in <i>Aji Saka</i>?",
        options: [
          "A cruel king frightened his people, and Aji Saka had to stop him.",
          "Aji Saka and the king fought with swords to decide who should rule.",
          "Aji Saka lost his precious kris on the long journey to Java.",
          "The people of Java did not want a young man as their king.",
        ], answer: 0,
        hint: "The main conflict is the biggest problem the main character faces. Why did Aji Saka go to the palace?",
        feedback: {
          1: "Not quite. There was no sword fight — Aji Saka used a clever trick.",
          2: "Look again: the kris stayed safely on Majeti with Sembada.",
          3: "Not true — the people cheered and chose him as their king.",
        },
        explain: "The central problem: a <b>cruel king</b> was hurting his people, and Aji Saka had to find a way to <b>stop him</b>.",
      },
      {
        type: "order", skill: "Story sequence",
        prompt: "Put the events in the correct order. <span class='tip'>Tap an event to add it to the next empty step.</span>",
        items: [
          "Aji Saka left his kris with Sembada.",
          "Aji Saka offered to be the king’s meal.",
          "The headcloth pushed the king into the southern sea.",
          "The people chose Aji Saka as their new king.",
          "Dora and Sembada fought, and both of them died.",
          "Aji Saka wrote a poem to remember them.",
        ],
        hint: "Follow the story from Majeti → the palace → the sea → back to Majeti.",
        explain: "Perfect timeline! Narratives are told in <b>chronological order</b>.",
      },
      {
        type: "mcq", skill: "Cause & effect", ref: 6,
        prompt: "Why did Sembada refuse to give the kris to Dora?",
        options: [
          "Aji Saka had told him not to give it to anyone else.",
          "He wanted to keep the precious kris for himself.",
          "He did not believe that Dora was really Aji Saka’s servant.",
          "He was angry because Dora had travelled to Java without him.",
        ], answer: 0,
        hint: "Read page 1 again. What did Aji Saka say when he gave Sembada the kris?",
        feedback: { 1: "Sembada was loyal, not greedy. He was keeping a promise." },
        explain: "Cause: Aji Saka’s first order (“Do not give this kris to anyone except me”) → Effect: Sembada refused.",
      },
      {
        type: "sort", skill: "Cause & effect match", layout: "match", capacity: 1,
        prompt: "Match each <b>cause</b> with its <b>effect</b>.",
        bins: [
          { id: "c1", label: "The king was cruel and demanded a person every day.", kicker: "CAUSE" },
          { id: "c2", label: "The king thought a headcloth was very small.", kicker: "CAUSE" },
          { id: "c3", label: "The headcloth grew wider and wider.", kicker: "CAUSE" },
          { id: "c4", label: "Aji Saka gave his servants two different orders.", kicker: "CAUSE" },
        ],
        cards: [
          { text: "The people looked thin and frightened.", bin: "c1" },
          { text: "He laughed and agreed to Aji Saka’s request.", bin: "c2" },
          { text: "It pushed the king to the edge of the sea.", bin: "c3" },
          { text: "Dora and Sembada had a terrible fight.", bin: "c4" },
        ],
        hint: "Ask “What happened <i>because of</i> this?” for each cause.",
        explain: "Each event in a narrative causes the next one. That is how a plot works!",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 1, structureOptions: true,
        quote: "A long time ago, on the island of Majeti, there lived a wise and brave young man named Aji Saka. He had two loyal servants, Dora and Sembada, who obeyed him in everything.",
        prompt: "Which part of the narrative is this passage?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 0,
        hint: "Does it tell us who, where and when?",
        explain: "It introduces the characters, the place and the time: this is the <b>orientation</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 4, structureOptions: true,
        quote: "The king held his end tightly, and the cloth pushed him further and further south. He reached the edge of the southern sea and fell into the water.",
        prompt: "Which part of the narrative is this passage?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
        hint: "What happens to the cruel king here? Is the problem starting or ending?",
        explain: "The cruel king is defeated — the problem is <b>solved</b>. This is the <b>resolution</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 7, structureOptions: true,
        quote: "To remember his two loyal servants, he wrote a poem: Ha na ca ra ka (there were two messengers), da ta sa wa la (they had a fight), pa dha ja ya nya (they were equally strong), ma ga ba tha nga (and both of them died). This poem became the Javanese alphabet.",
        prompt: "Which part of the narrative is this passage?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 3,
        hint: "Is this about a problem, or about how the whole story ends and what still exists today?",
        explain: "It tells us what happened at the very end and why the story is remembered: the <b>ending / coda</b>.",
      },
      {
        type: "mcq", skill: "A second problem", ref: 5,
        prompt: "Later in the story, a <b>new problem</b> begins. What starts it?",
        options: [
          "Aji Saka sent Dora to bring back the kris.",
          "Aji Saka took off his headcloth at the palace.",
          "The people chose Aji Saka as their new king.",
          "An old man told Aji Saka about the cruel king.",
        ], answer: 0,
        hint: "Sembada had one order. Who arrived on Majeti with a different order?",
        explain: "When Aji Saka <b>sent Dora</b> for the kris, his two servants had <b>two different orders</b>. This led to the sad fight.",
      },
    ],

    /* ---------------- 🎭 CHARACTER DETECTIVE ---------------- */
    character: [
      {
        type: "mcq", skill: "Trait → Step 1", character: "ajisaka", ref: 3,
        prompt: "Character: <b>Aji Saka</b>. At the palace, which trait does he show <b>best</b>?",
        options: ["brave", "greedy", "arrogant", "cowardly"], answer: 0,
        hint: "Everyone was afraid of the king. What did Aji Saka do?",
        feedback: { 3: "A cowardly person runs away. Did Aji Saka run away?" },
        explain: "He went to the cruel king and offered himself: he was <b>brave</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "ajisaka", ref: 3,
        prompt: "You chose <b>brave</b>. Which event <b>best supports</b> your answer?",
        options: [
          "He offered to be the cruel king’s meal.",
          "He lived on the island of Majeti.",
          "He had two servants called Dora and Sembada.",
          "He travelled to Java with his servant Dora.",
        ], answer: 0,
        hint: "Evidence must <i>show</i> the trait. Which action was dangerous?",
        explain: "Character → Trait → <b>Evidence</b>. Going to a cruel king and offering himself proves he was brave.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "dewata", ref: 2,
        prompt: "Character: <b>Dewata Cengkar</b>. Which trait describes him best?",
        options: ["cruel", "loyal", "patient", "gentle"], answer: 0,
        hint: "How did he treat the people of his kingdom?",
        explain: "Taking a person from the village every day is <b>cruel</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "dewata", ref: 2,
        prompt: "Which evidence <b>best proves</b> that Dewata Cengkar was cruel?",
        options: [
          "He demanded a person from the village every day.",
          "He was the king of Medang Kamulan in Java.",
          "He lived in a palace in the middle of Java.",
          "He held one end of the headcloth tightly.",
        ], answer: 0,
        hint: "Three of these are just facts. Which one shows how he treated people?",
        explain: "Good evidence shows the trait through an <b>action</b>.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "sembada", ref: 6,
        prompt: "Character: <b>Sembada</b>. Which trait describes him best?",
        options: ["loyal", "greedy", "dishonest", "cowardly"], answer: 0,
        hint: "He kept the kris safe and remembered his master’s words.",
        feedback: { 1: "Sembada did not want the kris for himself. He was keeping it for someone else." },
        explain: "Sembada was <b>loyal</b>: he kept his promise to his master.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "sembada", ref: 6,
        prompt: "Which statement <b>best proves</b> that Sembada was loyal?",
        options: [
          "“Our master told me not to give it to anyone except him.”",
          "“Our master wants his kris. Please give it to me.”",
          "“Nobody can stop him,” the old man whispered.",
          "“Go back to Majeti and bring my kris to me.”",
        ], answer: 0,
        hint: "Find Sembada’s own words. Which words show that he remembered his master’s order?",
        feedback: { 1: "Those are Dora’s words, not Sembada’s." },
        explain: "Sembada remembered and kept his master’s order — that is <b>loyalty</b>.",
      },
      {
        type: "multi", skill: "Two best traits", character: "dewata", ref: 2, pick: 2,
        prompt: "Choose <b>TWO</b> traits that best describe <b>Dewata Cengkar</b>.",
        options: ["cruel", "wise", "greedy", "generous", "loyal", "gentle"], answer: [0, 2],
        hint: "Read page 2: “An old man explained that their king, Dewata Cengkar, was ___ and ___.”",
        explain: "The text says he was <b>cruel</b> and <b>greedy</b>: he took the people’s rice, their animals and even their lives.",
      },
      {
        type: "mcq", skill: "Who am I?",
        prompt: "<b>Who am I?</b><ul class='clues'><li>I travelled to Java with my master.</li><li>Later, I went back to Majeti.</li><li>I carried a new order from my master.</li></ul>",
        options: ["Dora", "Sembada", "Aji Saka", "Dewata Cengkar"], answer: 0,
        hint: "Which servant went with Aji Saka to Java?",
        feedback: { 1: "Sembada stayed on Majeti to guard the kris. He did not travel to Java." },
        explain: "<b>Dora</b> went to Java with Aji Saka and was later sent back to Majeti for the kris.",
      },
      {
        type: "sort", skill: "Trait match", layout: "match", capacity: 1,
        prompt: "Match each character with the word that fits best.",
        bins: [
          { id: "ajisaka", label: "Aji Saka", img: "img/stories/aji-saka/aji-saka.webp" },
          { id: "dewata", label: "Dewata Cengkar", img: "img/stories/aji-saka/dewata-cengkar.webp" },
          { id: "servants", label: "Dora and Sembada", img: "img/stories/aji-saka/dora.webp" },
          { id: "people", label: "The people of Medang Kamulan" },
        ],
        cards: [
          { text: "clever", bin: "ajisaka" }, { text: "greedy", bin: "dewata" },
          { text: "loyal", bin: "servants" }, { text: "frightened", bin: "people" },
        ],
        hint: "Who had a clever plan? Who took rice and animals? Who obeyed their master? Who looked thin and afraid?",
        explain: "Every word matches evidence from the text. (<i>Frightened</i> is a feeling, not a trait — the people felt it because of their king.)",
      },
      {
        type: "mcq", skill: "Character comparison", ref: 6,
        prompt: "How were <b>Dora</b> and <b>Sembada</b> similar?",
        options: [
          "Both were loyal and wanted to obey their master.",
          "Both wanted to keep the precious kris for themselves.",
          "Both were afraid of the cruel King Dewata Cengkar.",
          "Both wanted to become the new king of Medang Kamulan.",
        ], answer: 0,
        hint: "Read page 6: “Both servants were ___, and both wanted to…”",
        explain: "They were both <b>loyal</b>. Sadly, they were following two <b>different</b> orders from the same master.",
      },
      {
        type: "mcq", skill: "Inference: motives", ref: 3,
        prompt: "Why did Aji Saka ask for land as wide as his headcloth?",
        options: [
          "He had a clever plan to defeat the king.",
          "He wanted a small farm before he died.",
          "He wanted to sell the land for money.",
          "He wanted to build a house for Dora.",
        ], answer: 0,
        hint: "Think about what happened next when he opened the headcloth.",
        explain: "The story does not say it directly, but the headcloth grew and pushed the king into the sea. It was a <b>clever plan</b> from the start.",
      },
      {
        type: "mcq", skill: "Trait → Evidence", character: "ajisaka", ref: 7,
        quote: "“This was my mistake,” he said. “I gave them two different orders.”",
        prompt: "What do these words show about Aji Saka?",
        options: [
          "He was responsible and accepted his mistake.",
          "He was arrogant and blamed his servants.",
          "He was greedy and only wanted his kris.",
          "He was cruel and did not care about anyone.",
        ], answer: 0,
        hint: "Whose mistake did Aji Saka say it was?",
        explain: "A <b>responsible</b> person says “It was my fault.” Aji Saka did not blame Dora or Sembada.",
      },
    ],

    /* ---------------- ⏳ PAST TENSE LAB ---------------- */
    grammar: [
      {
        type: "verbs", skill: "Verb transform",
        prompt: "Type the <b>simple past</b> form of each verb from the story.",
        verbs: [
          { base: "sail", past: "sailed" }, { base: "decide", past: "decided" }, { base: "obey", past: "obeyed" },
          { base: "give", past: "gave" }, { base: "fight", past: "fought" }, { base: "write", past: "wrote" },
        ],
        hint: "Regular verbs add <b>-ed</b> (sail → sailed). Irregular verbs change form (write → w _ _ _ e).",
        explain: "<b>sailed, decided, obeyed</b> are regular. <b>gave, fought, wrote</b> are irregular.",
      },
      {
        type: "verbs", skill: "Verb transform",
        prompt: "More story verbs! Type the <b>simple past</b> form.",
        verbs: [
          { base: "explain", past: "explained" }, { base: "cheer", past: "cheered" }, { base: "refuse", past: "refused" },
          { base: "hold", past: "held" }, { base: "fall", past: "fell" }, { base: "choose", past: "chose" },
        ],
        hint: "Three are regular (-ed). For the others, look in the story: “held”, “fell” and “chose” all appear there.",
        explain: "Regular: <b>explained, cheered, refused</b>. Irregular: <b>held, fell, chose</b>.",
      },
      {
        type: "mcq", skill: "Choose the correct verb", ref: 4,
        prompt: "The headcloth ___ wider and wider.",
        options: ["grew", "grow", "grows", "growed"], answer: 0,
        hint: "The story happened in the past. <i>Grow</i> is an irregular verb.",
        feedback: { 3: "Grow is irregular — we don’t add -ed." },
        explain: "<b>grow → grew</b> (irregular).",
      },
      {
        type: "mcq", skill: "Was / were", ref: 5,
        prompt: "The people of Medang Kamulan ___ free at last.",
        options: ["was", "were", "is", "be"], answer: 1,
        hint: "“The people” is plural (more than one person). Which past form goes with plural subjects?",
        explain: "<b>were</b> for plural subjects (they, the people). <b>was</b> for I / he / she / it.",
      },
      {
        type: "mcq", skill: "Was / were", ref: 2,
        prompt: "Dewata Cengkar ___ cruel and greedy.",
        options: ["were", "was", "are", "been"], answer: 1,
        hint: "“Dewata Cengkar” = he (one person).",
        explain: "He / she / it → <b>was</b>.",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 1,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Aji Saka gived his precious kris to Sembada.",
        wrong: 2, options: ["gave", "given", "gives", "giving"], answer: 0,
        hint: "Find the verb. <i>Give</i> is irregular.",
        stage2: "Now choose the correct past form of <b>give</b>:",
        feedback2: { 1: "<b>given</b> is the past participle (have given). The simple past is different." },
        explain: "<b>give → gave</b>: “Aji Saka <b>gave</b> his precious kris to Sembada.”",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 4,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "The king held his end tightly, and the cloth push him south.",
        wrong: 9, options: ["pushed", "pushes", "pushing", "is pushing"], answer: 0,
        hint: "There are two verbs. One is correct (held). Check the other one.",
        stage2: "Choose the correct form of <b>push</b>:",
        explain: "<b>push → pushed</b>. Both verbs in the sentence must be in the past.",
      },
      {
        type: "fix", skill: "Negative challenge", ref: 6,
        prompt: "This negative sentence has a mistake. Tap the <b>incorrect</b> word.",
        sentence: "Sembada didn’t gave the kris to Dora.",
        wrong: 2, options: ["give", "gives", "giving", "given"], answer: 0,
        hint: "After <b>didn’t</b>, we use the base verb (V1).",
        stage2: "After <b>didn’t</b>, which form is correct?",
        explain: "<b>didn’t + base verb</b>: “Sembada didn’t <b>give</b> the kris to Dora.”",
      },
      {
        type: "mcq", skill: "Negative sentence", ref: 3,
        prompt: "Aji Saka ___ away from the cruel king.",
        options: ["didn’t run", "didn’t ran", "doesn’t run", "wasn’t run"], answer: 0,
        hint: "Past negative = did not (didn’t) + base verb.",
        feedback: { 1: "Almost! After didn’t, the verb goes back to the base form.", 2: "“doesn’t” is present. The story is in the past." },
        explain: "<b>didn’t + run</b> (base verb): “Aji Saka didn’t run away.”",
      },
      {
        type: "order", skill: "Sentence builder", inline: true, ref: 5,
        prompt: "Build the sentence in the simple past. <span class='tip'>One chunk is not needed.</span>",
        items: ["The people", "chose", "Aji Saka", "as their new king."],
        extras: ["choosed"],
        hint: "Start with “The people…”. <i>Choose</i> is irregular.",
        explain: "“The people <b>chose</b> Aji Saka as their new king.” — Subject + <b>V2</b> + object.",
      },
      {
        type: "order", skill: "Question challenge", inline: true, ref: 6,
        prompt: "Build a simple past <b>question</b>. <span class='tip'>One chunk is not needed.</span>",
        items: ["Did", "Sembada", "give", "the kris", "to Dora?"],
        extras: ["gave"],
        hint: "Question pattern: <b>Did + subject + base verb…?</b>",
        explain: "“<b>Did</b> Sembada <b>give</b> the kris to Dora?” — No, he didn’t.",
      },
      {
        type: "mcq", skill: "Question challenge", ref: 2,
        prompt: "“___ Dewata Cengkar a kind king?” — “No, he wasn’t.”",
        options: ["Was", "Did", "Were", "Does"], answer: 0,
        hint: "Look at the short answer: “No, he <b>wasn’t</b>.” There is no main verb in the question.",
        feedback: { 1: "We use Did with a main verb (Did he take…?). This question has no main verb, so we need a form of <i>be</i>." },
        explain: "With no main verb, use <b>Was</b> (one person): “Was Dewata Cengkar a kind king?”",
      },
    ],
  },

  /* ---------------- 🌟 MASTER THE STORY (final) ---------------- */
  final: [
    {
      type: "mcq", skill: "Vocabulary in context", ref: 6,
      quote: "Neither of them gave up, so they fought.",
      prompt: "What does “neither of them gave up” tell us?",
      options: ["Both of them kept trying.", "Both of them ran away.", "One of them stopped trying.", "One of them said sorry."], answer: 0,
      hint: "<b>Give up</b> = stop trying. <b>Neither</b> = not this one and not that one.",
      explain: "Neither Dora nor Sembada stopped. Both of them <b>kept trying</b>, so the fight went on.",
    },
    {
      type: "mcq", skill: "Simple past", ref: 7,
      prompt: "To remember his servants, Aji Saka ___ a poem.",
      options: ["wrote", "writes", "write", "written"], answer: 0,
      hint: "The story is in the past. <i>Write</i> is irregular.",
      explain: "<b>write → wrote</b>.",
    },
    {
      type: "mcq", skill: "Narrative structure", structureOptions: true, ref: 5,
      quote: "The people of Medang Kamulan were free at last. They cheered and chose Aji Saka as their new king.",
      prompt: "Which part of the narrative do these sentences belong to?",
      options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
      hint: "Is the problem with the cruel king starting or finished?",
      explain: "The people are free — the problem with the king is solved: <b>resolution</b>.",
    },
    {
      type: "order", skill: "Sequence of events",
      prompt: "Put these events in order.",
      items: [
        "Aji Saka and Dora sailed to Java.",
        "An old man told them about the cruel king.",
        "Dewata Cengkar laughed at Aji Saka’s request.",
        "Aji Saka sent Dora back to Majeti.",
      ],
      hint: "Journey → news → palace → a new job for Dora.",
      explain: "Great timeline memory!",
    },
    {
      type: "mcq", skill: "Main conflict", ref: 2,
      prompt: "Which sentence from the story <b>best shows</b> the central problem that Aji Saka had to solve in Java?",
      options: [
        "“Every day he demanded a person from the village for his meals.”",
        "“Aji Saka and Dora sailed to the kingdom of Medang Kamulan in Java.”",
        "“Dewata Cengkar laughed loudly. ‘Such a small piece of land! I agree.’”",
        "“He told Dora, ‘Go back to Majeti and bring my kris to me.’”",
      ], answer: 0,
      hint: "Why did the people look thin and frightened? Find the sentence about the king’s terrible demand.",
      feedback: { 3: "That starts a later, smaller problem on Majeti — not the problem Aji Saka came to Java to solve." },
      explain: "The king’s terrible demand — a person every day — was the <b>main conflict</b> that Aji Saka came to stop.",
    },
    {
      type: "mcq", skill: "Characterization", ref: 3,
      prompt: "Why can Dewata Cengkar be described as <b>arrogant</b>?",
      options: [
        "He laughed at Aji Saka and thought he was foolish.",
        "He gave one end of the headcloth to Aji Saka.",
        "He fell into the southern sea at the end.",
        "He asked his people to choose a new king.",
      ], answer: 0,
      hint: "An arrogant person thinks he is better than other people.",
      feedback: { 1: "Look again: it was Aji Saka who gave the king one end." },
      explain: "He laughed and thought the young man was <b>foolish</b> — he thought he was much smarter. That is <b>arrogant</b>.",
    },
    {
      type: "mcq", skill: "Cause & effect", ref: 7,
      prompt: "Why did Aji Saka go to Majeti near the end of the story?",
      options: [
        "Dora did not come back with the kris.",
        "He wanted to live on his island again.",
        "The people of Java did not want him as king.",
        "Sembada sent him a letter about the fight.",
      ], answer: 0,
      hint: "Read the first sentence of page 7: “When Dora did not…”",
      explain: "Cause: <b>Dora did not return</b> → Effect: Aji Saka went to Majeti and learned the sad news.",
    },
    {
      type: "mcq", skill: "Turning point", ref: 4,
      prompt: "Which event changed the direction of the story <b>most significantly</b>?",
      options: [
        "Aji Saka opened his headcloth, and it grew wider and wider.",
        "An old man told Aji Saka that his daughter was next.",
        "Aji Saka and Dora sailed to Java from their island.",
        "Dewata Cengkar laughed loudly at the request.",
      ], answer: 0,
      hint: "After which event were the people free from the cruel king?",
      feedback: { 1: "That event made Aji Saka act — but it did not change the people’s lives yet." },
      explain: "The growing headcloth defeated the cruel king. That was the <b>turning point</b>: from fear to freedom.",
    },
    {
      type: "mcq", skill: "Inference", ref: 4,
      prompt: "What can we infer about Aji Saka’s headcloth?",
      options: [
        "It had magic power.",
        "It was very old and weak.",
        "It was a gift from the king.",
        "It was made of gold.",
      ], answer: 0,
      hint: "A normal headcloth is small. What did this one do?",
      explain: "The story never says “magic”, but a headcloth that covers a palace, fields and forests must have <b>magic power</b>.",
    },
    {
      type: "mcq", skill: "Inference: motives", ref: 6,
      prompt: "Why did Dora decide to keep asking for the kris?",
      options: [
        "He wanted to obey his master’s new order.",
        "He wanted to keep the precious kris himself.",
        "He wanted to show that he was stronger.",
        "He wanted to stay on Majeti with Sembada.",
      ], answer: 0,
      hint: "Read Dora’s words: “But now our master has given a new order!”",
      feedback: { 1: "Dora was not greedy — he wanted to bring the kris to Aji Saka." },
      explain: "Dora was loyal too. He only wanted to <b>obey</b> Aji Saka’s new order.",
    },
    {
      type: "mcq", skill: "Character’s purpose", ref: 7,
      prompt: "Why did Aji Saka write a poem about Dora and Sembada?",
      options: [
        "So that people would always remember their loyalty.",
        "So that people would laugh at the two servants.",
        "So that the cruel king would read it in the sea.",
        "So that the people would choose a new king.",
      ], answer: 0,
      hint: "Read page 7: “To remember his two loyal servants…”",
      explain: "He wanted the <b>loyalty</b> of his servants to be remembered. Today, every Javanese child learns their story through the alphabet.",
    },
    {
      type: "mcq", skill: "Moral value",
      prompt: "What can readers learn from the sad ending of the story?",
      options: [
        "Leaders should give clear orders and think before they act.",
        "Servants should never keep a promise to their master.",
        "It is better to travel alone than with a friend.",
        "A clever trick can solve every problem in life.",
      ], answer: 0,
      hint: "Aji Saka said: “This was my mistake. I gave them two different orders.”",
      feedback: { 1: "Keeping promises is good! Sembada was right to be loyal — the problem was the two different orders." },
      explain: "The moral: be <b>loyal</b> and keep promises — but leaders must give <b>clear instructions</b> and think carefully before acting.",
    },
  ],
});
