/* ==========================================================
   NARRATIVE QUEST — Story file
   Anansi and the Pot of Wisdom (Myth / Folktale · Ghana, Ashanti)
   ----------------------------------------------------------
   Version: the common Ashanti telling in which Nyame gives Anansi
   a pot of all the world’s wisdom to share. Anansi tries to hide it
   at the top of a tall tree, his son Ntikuma gives better advice,
   the pot breaks and the wisdom spreads everywhere.
   ========================================================== */
NQ.registerStory({
  id: "anansi",
  title: "Anansi and the Pot of Wisdom",
  genre: "myths",
  origin: "world",
  region: "West Africa · Ghana (Ashanti)",
  country: "Ghana",
  level: "A2–B1",
  minutes: 30,
  cover: "img/covers/anansi.webp",
  summary: "Anansi the spider gets a pot with all the wisdom of the world. Will he share it — or keep it all for himself?",

  /* ---------- STORY PAGES ---------- */
  pages: [
    {
      text: "Long ago, in a village in the forests of Ghana, there lived a spider called Anansi. He was clever and loved to tell stories, and he always wanted to be the most important creature in the village. High above the clouds lived Nyame, the Sky God. One day, Nyame gave Anansi a clay pot. “Inside this pot is all the wisdom of the world,” he said kindly. “Please share it with everyone.”",
      vocab: ["wisdom", "share"],
      scene: { art: "img/stories/anansi/nyame-gives-pot.webp", fit: "contain", alt: "nyame gives pot", tone: "day", fx: [] },
    },
    {
      text: "Anansi hurried home and looked inside the pot. He was amazed. He learned how to plant crops, how to make tools and how to cure illnesses. Every idea was more wonderful than the last. But soon Anansi became greedy. “Why should I share this?” he thought. “If I keep all the wisdom, everyone will need me. I will be the wisest creature in the world!”",
      vocab: ["amazed", "cure", "greedy"],
      scene: { art: "img/stories/anansi/anansi-looks-in-pot.webp", fit: "contain", alt: "anansi looks in pot", tone: "day", fx: [] },
    },
    {
      text: "So Anansi decided to hide the pot at the top of the tallest tree in the forest, where no one could reach it. He didn’t tell anyone about his plan, not even his family. Early the next morning, he tied the pot to the front of his body with a long rope and walked quietly into the forest.",
      vocab: ["reach", "tied"],
      scene: { art: "img/stories/anansi/anansi-carries-pot.webp", fit: "contain", alt: "anansi carries pot", tone: "day", fx: [] },
    },
    {
      text: "Anansi started to climb, but the big round pot was in the way. He could not hold the tree properly, and he slipped down again and again. He tried for hours. His legs were tired, and he was very frustrated. He did not know that his young son, Ntikuma, had followed him. The boy was watching quietly from behind a bush.",
      vocab: ["slipped", "frustrated"],
      scene: { art: "img/stories/anansi/anansi-slips-ntikuma-watches.webp", fit: "contain", alt: "anansi slips ntikuma watches", tone: "day", fx: [] },
    },
    {
      text: "At last, Ntikuma called up to him, “Father, why don’t you tie the pot on your back? Then you can climb easily.” Anansi stopped. He had all the wisdom of the world, but a small boy had a better idea than he did! He felt angry and embarrassed. In his anger, he let go of the pot. It fell to the ground and broke into many pieces.",
      vocab: ["embarrassed"],
      scene: { art: "img/stories/anansi/pot-breaks.webp", fit: "contain", alt: "pot breaks", tone: "day", fx: [] },
    },
    {
      text: "Just then, a strong wind blew, and heavy rain began to fall. The wind picked up the wisdom and scattered it across the land. The rain washed it into the rivers, and the rivers carried it to the sea. Soon, small pieces of wisdom were everywhere in the world. Anansi looked at the broken pot for a long time. Then, slowly, he began to laugh.",
      vocab: ["scattered"],
      scene: { art: "img/stories/anansi/wisdom-scatters.webp", fit: "contain", alt: "wisdom scatters", tone: "day", fx: [] },
    },
    {
      text: "“You were right, Ntikuma,” he said, and he hugged his son. “Thank you. I was selfish and proud. Wisdom is not for one creature to keep. It is better that everyone has a little.” From that day on, Anansi listened to others, even the young ones. And that is why, the Ashanti people say, everyone in the world has some wisdom, but no one has all of it.",
      vocab: ["selfish"],
      scene: { art: "img/stories/anansi/anansi-hugs-ntikuma.webp", fit: "contain", alt: "anansi hugs ntikuma", tone: "day", fx: [] },
    },
  ],

  /* ---------- VOCABULARY (highlighted while reading) ---------- */
  vocabulary: [
    { word: "wisdom", forms: ["wisdom"], meaning: "knowledge and good sense about life" },
    { word: "share", forms: ["share"], meaning: "let other people have or use something too" },
    { word: "amazed", forms: ["amazed"], meaning: "very surprised" },
    { word: "cure", forms: ["cure"], meaning: "make a sick person well again" },
    { word: "greedy", forms: ["greedy"], meaning: "wanting more than you need; not wanting to give to others" },
    { word: "reach", forms: ["reach"], meaning: "get to something and touch it" },
    { word: "tied", forms: ["tied"], meaning: "fixed something in place with a rope or string" },
    { word: "slipped", forms: ["slipped"], meaning: "slid or fell by accident" },
    { word: "frustrated", forms: ["frustrated"], meaning: "annoyed because you cannot do something" },
    { word: "embarrassed", forms: ["embarrassed"], meaning: "uncomfortable because you look silly in front of others" },
    { word: "scattered", forms: ["scattered"], meaning: "spread in many different directions" },
    { word: "selfish", forms: ["selfish"], meaning: "thinking only about yourself" },
  ],

  /* ---------- CHARACTERS ---------- */
  characters: [
    { id: "nyame", name: "Nyame, the Sky God", img: "img/stories/anansi/nyame.webp", role: "The giver of wisdom", traits: ["generous", "wise"],
      evidence: "Nyame gave Anansi a clay pot. “Inside this pot is all the wisdom of the world. Please share it with everyone.”" },
    { id: "anansi", name: "Anansi the Spider", img: "img/stories/anansi/anansi.webp", role: "Main character", traits: ["greedy", "selfish", "proud", "humble (at the end)"],
      evidence: "But soon Anansi became greedy. “Why should I share this?” he thought. “If I keep all the wisdom, everyone will need me.”" },
    { id: "ntikuma", name: "Ntikuma (Anansi’s son)", img: "img/stories/anansi/ntikuma.webp", role: "Helper", traits: ["clever", "observant", "helpful"],
      evidence: "The boy was watching quietly. “Father, why don’t you tie the pot on your back? Then you can climb easily.”" },
  ],

  /* Personality words taught in Character Detective */
  traitWords: [
    { word: "greedy", meaning: "wanting more than you need" },
    { word: "selfish", meaning: "thinking only about yourself" },
    { word: "proud", meaning: "thinking you are better or more important than others" },
    { word: "humble", meaning: "not thinking you are better than others; ready to learn" },
    { word: "clever", meaning: "quick to understand and to find good ideas" },
    { word: "observant", meaning: "good at noticing things" },
    { word: "helpful", meaning: "happy to help other people" },
    { word: "generous", meaning: "happy to give things to others" },
    { word: "wise", meaning: "able to make good decisions" },
    { word: "lazy", meaning: "not wanting to work or try hard" },
  ],

  /* ---------- GENERIC STRUCTURE ---------- */
  structure: {
    orientation: { pages: [1], summary: "Anansi the spider lived in a forest village in Ghana. Nyame, the Sky God, gave him a pot with all the wisdom of the world to share." },
    complication: { pages: [2, 3, 4], summary: "Anansi became greedy and tried to hide the pot at the top of the tallest tree, but the pot was in the way and he kept slipping." },
    resolution: { pages: [5, 6], summary: "Ntikuma gave a better idea. Angry and embarrassed, Anansi let go of the pot. It broke, and the wind and rain carried the wisdom everywhere." },
    coda: { pages: [7], summary: "Anansi thanked his son and learned to listen to others. That is why everyone has some wisdom, but no one has all of it." },
  },
  mainConflict: "Anansi wanted to keep all the wisdom of the world for himself instead of sharing it.",
  sequence: [
    "Nyame gave Anansi a pot full of wisdom.",
    "Anansi decided to keep the wisdom for himself.",
    "Anansi tied the pot to the front of his body.",
    "Ntikuma told his father to tie the pot on his back.",
    "The pot fell and broke into many pieces.",
    "The wind and rain carried the wisdom all over the world.",
  ],
  grammarExamples: {
    regular: ["look → looked", "climb → climbed", "hurry → hurried"],
    irregular: ["give → gave", "fall → fell", "break → broke"],
    was: "Anansi was very frustrated.",
    were: "His legs were tired.",
    negative: "Anansi didn’t tell anyone about his plan.",
    question: "Did Ntikuma follow his father?",
  },
  /* Portraits used for feedback bubbles */
  guides: { good: "img/stories/anansi/anansi.webp", hint: "img/stories/anansi/nyame.webp" },
  pastVerbs: [
    { base: "live", past: "lived", type: "regular" }, { base: "look", past: "looked", type: "regular" },
    { base: "hurry", past: "hurried", type: "regular" }, { base: "decide", past: "decided", type: "regular" },
    { base: "tie", past: "tied", type: "regular" }, { base: "slip", past: "slipped", type: "regular" },
    { base: "try", past: "tried", type: "regular" }, { base: "follow", past: "followed", type: "regular" },
    { base: "stop", past: "stopped", type: "regular" }, { base: "hug", past: "hugged", type: "regular" },
    { base: "give", past: "gave", type: "irregular" }, { base: "become", past: "became", type: "irregular" },
    { base: "think", past: "thought", type: "irregular" }, { base: "feel", past: "felt", type: "irregular" },
    { base: "fall", past: "fell", type: "irregular" }, { base: "break", past: "broke", type: "irregular" },
    { base: "blow", past: "blew", type: "irregular" }, { base: "begin", past: "began", type: "irregular" },
    { base: "let", past: "let", type: "irregular" }, { base: "tell", past: "told", type: "irregular" },
  ],

  /* =========================================================
     CHALLENGES
     ========================================================= */
  challenges: {
    /* ---------------- 🔮 WORD HUNTER ---------------- */
    word: [
      {
        type: "mcq", skill: "Meaning in context", ref: 1,
        quote: "“Inside this pot is all the wisdom of the world,” he said kindly. “Please share it with everyone.”",
        prompt: "What does <b>wisdom</b> mean here?",
        options: ["knowledge and good sense", "gold and shiny jewels", "magic and secret power", "food and fresh water"], answer: 0,
        hint: "Read page 2. After Anansi looked inside the pot, he <i>learned</i> many things.",
        feedback: { 1: "The pot was special, but it did not hold treasure. What did Anansi learn from it?", 2: "Nyame is a god, but the pot taught Anansi how to plant crops and make tools — that is not magic." },
        explain: "<b>Wisdom</b> = knowledge and good sense. From the pot, Anansi learned how to plant crops, make tools and cure illnesses.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 4,
        quote: "He tried for hours. His legs were tired, and he was very frustrated.",
        prompt: "How did Anansi feel when he was <b>frustrated</b>?",
        options: ["annoyed because he kept failing", "happy because the view was lovely", "sleepy because it was very early", "scared because the tree was high"], answer: 0,
        hint: "He slipped down again and again and tried for hours. How do you feel when something doesn’t work many times?",
        feedback: { 3: "The story doesn’t say he was afraid. It says he tried again and again without success." },
        explain: "<b>Frustrated</b> = annoyed because you cannot do something, even after many tries.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 2,
        quote: "But soon Anansi became greedy. “Why should I share this?” he thought.",
        prompt: "What does <b>greedy</b> mean in this sentence?",
        options: ["wanting to keep everything for himself", "wanting to give everything to others", "feeling afraid of the other creatures", "feeling tired after a long day of work"], answer: 0,
        hint: "Look at the question Anansi asks himself right after this word.",
        feedback: { 1: "That is the opposite! Anansi asked, “Why should I share this?”" },
        explain: "A <b>greedy</b> person wants more than they need and does not want to share.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 2,
        quote: "He learned how to plant crops, how to make tools and how to cure illnesses.",
        prompt: "What does it mean to <b>cure</b> an illness?",
        options: ["make a sick person well again", "make a healthy person feel sick", "find out where sick people live", "count how many people are sick"], answer: 0,
        hint: "All the things Anansi learned were useful. Which meaning would help sick people?",
        explain: "To <b>cure</b> an illness = to make a sick person healthy again.",
      },
      {
        type: "mcq", skill: "Antonym", ref: 7,
        quote: "“Thank you. I was selfish and proud.”",
        prompt: "Which word is the <b>opposite</b> of <b>selfish</b>?",
        options: ["generous", "greedy", "unkind", "proud"], answer: 0,
        hint: "A selfish person keeps things. Which word describes a person who likes to give?",
        feedback: { 1: "Greedy is close in meaning to selfish, not the opposite.", 3: "Anansi said he was selfish <i>and</i> proud — these words go together, they are not opposites." },
        explain: "A <b>selfish</b> person thinks only about himself; a <b>generous</b> person is happy to give to others.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 6,
        quote: "The wind picked up the wisdom and scattered it across the land.",
        prompt: "What did the wind do with the wisdom?",
        options: ["It spread it in many directions.", "It kept it together in one place.", "It pushed it into a deep hole.", "It carried it back up to Nyame."], answer: 0,
        hint: "After this, the wisdom was <i>everywhere</i> in the world.",
        explain: "<b>Scatter</b> = spread things in many different directions.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 1,
        quote: "He was clever and loved to tell stories, and he always wanted to be the most important creature in the village.",
        prompt: "What does <b>creature</b> mean in this sentence?",
        options: ["any living animal or being", "a tall tree in the forest", "a village chief or leader", "a story about the past"], answer: 0,
        hint: "Anansi is a spider. Later he says, “Wisdom is not for one creature to keep.” What kind of thing can be a creature?",
        feedback: { 2: "Anansi <i>wanted</i> to be important — but the word <i>creature</i> itself only means a living being, not a leader." },
        explain: "A <b>creature</b> = any living animal or being. Anansi the spider is a creature.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 4, image: "img/stories/anansi/anansi.webp",
        prompt: "Look at the picture. Anansi tried to climb the tree for hours, so his eight ___ felt very tired.",
        options: ["legs", "wings", "tails", "horns"], answer: 0,
        hint: "Look at the picture and count. Which part of a spider’s body is there eight of? Then check page 4.",
        explain: "A spider has eight <b>legs</b>. After hours of trying to climb, Anansi’s legs were tired.",
      },
      {
        type: "mcq", skill: "Word with two meanings", ref: 3,
        quote: "So Anansi decided to hide the pot at the top of the tallest tree in the forest, where no one could reach it.",
        prompt: "What does <b>reach</b> mean in this sentence?",
        options: ["get to it and touch it", "arrive at the end of a trip", "send a message to it", "understand it clearly"], answer: 0,
        hint: "Many words have more than one meaning. The pot is high up in a tree. What could nobody do?",
        feedback: { 1: "That is a real meaning of <i>reach</i> (reach a city) — but here it is about something high up in a tree." },
        explain: "Here, <b>reach</b> = stretch or climb to get to something and touch it.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 5,
        quote: "He had all the wisdom of the world, but a small boy had a better idea than he did! He felt angry and embarrassed.",
        prompt: "Why did Anansi feel <b>embarrassed</b>?",
        options: ["He looked foolish next to a small boy.", "He was happy about his son’s idea.", "He was sick after falling from the tree.", "He was brave enough to try once more."], answer: 0,
        hint: "Anansi had all the wisdom, but who had the better idea?",
        feedback: { 1: "Later he thanked his son — but at this moment he felt angry, not happy." },
        explain: "<b>Embarrassed</b> = uncomfortable because you look silly. A child was smarter than the “wisest creature”!",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 4,
        quote: "He could not hold the tree properly, and he slipped down again and again.",
        prompt: "What does <b>slipped down</b> mean?",
        options: ["slid down by accident", "jumped down on purpose", "climbed down very slowly", "flew down very quickly"], answer: 0,
        hint: "He could not hold the tree. Did he want to go down?",
        explain: "To <b>slip</b> = to slide or fall by accident because you cannot hold on.",
      },
      {
        type: "sort", skill: "Word–meaning match", layout: "match",
        prompt: "Drag each word to its meaning. <span class='tip'>(Or tap a word, then tap a meaning.)</span>",
        bins: [
          { id: "share", label: "let other people have or use something too" },
          { id: "tied", label: "fixed something in place with a rope" },
          { id: "amazed", label: "very surprised" },
          { id: "selfish", label: "thinking only about yourself" },
          { id: "cure", label: "make a sick person well again" },
          { id: "scattered", label: "spread in many different directions" },
        ],
        cards: [
          { text: "share", bin: "share" }, { text: "tied", bin: "tied" }, { text: "amazed", bin: "amazed" },
          { text: "selfish", bin: "selfish" }, { text: "cure", bin: "cure" }, { text: "scattered", bin: "scattered" },
        ],
        capacity: 1,
        hint: "Start with the words you are sure about. Anansi <i>tied</i> the pot with a long rope; Nyame asked him to <i>share</i> it.",
        explain: "Great word hunting! You matched all six words.",
      },
    ],

    /* ---------------- 🧩 STORY DETECTIVE ---------------- */
    structure: [
      {
        type: "sort", skill: "Sort the story",
        prompt: "Put each event card in the correct part of the narrative.",
        bins: [
          { id: "orientation", label: "Orientation", img: "img/st-orientation.webp", sub: "Who? Where? When?" },
          { id: "complication", label: "Complication", img: "img/st-complication.webp", sub: "What problem happened?" },
          { id: "resolution", label: "Resolution", img: "img/st-resolution.webp", sub: "How was it solved?" },
          { id: "coda", label: "Ending / Coda", img: "img/st-ending.webp", sub: "What happened afterward?" },
        ],
        cards: [
          { text: "Long ago, a spider called Anansi lived in a forest village in Ghana.", bin: "orientation" },
          { text: "High above the clouds lived Nyame, the Sky God.", bin: "orientation" },
          { text: "Anansi decided to keep all the wisdom for himself.", bin: "complication" },
          { text: "The pot was in the way, and Anansi slipped down again and again.", bin: "complication" },
          { text: "The pot fell to the ground and broke into many pieces.", bin: "resolution" },
          { text: "The wind and rain carried the wisdom all over the world.", bin: "resolution" },
          { text: "From that day on, Anansi listened to others, even the young ones.", bin: "coda" },
          { text: "That is why everyone has some wisdom, but no one has all of it.", bin: "coda" },
        ],
        hint: "Orientation introduces the characters and place. Complication = the problem. Resolution = the problem ends. Coda = life afterward and the lesson.",
        explain: "The story moves from <b>introduction</b> → <b>greedy plan</b> → <b>broken pot</b> → <b>lesson</b>.",
      },
      {
        type: "mcq", skill: "Find the complication", ref: 2,
        prompt: "Which sentence shows the <b>beginning of the complication</b>?",
        options: [
          "“But soon Anansi became greedy.”",
          "“High above the clouds lived Nyame, the Sky God.”",
          "“Just then, a strong wind blew.”",
          "“From that day on, Anansi listened to others.”",
        ], answer: 0,
        hint: "Look for the word that tells us the story is changing direction and a problem is starting.",
        explain: "The word <b>But</b> and Anansi’s new greed signal that the problem is starting.",
      },
      {
        type: "mcq", skill: "Find the main conflict", ref: 2,
        prompt: "What is the <b>main conflict</b> in <i>Anansi and the Pot of Wisdom</i>?",
        options: [
          "Anansi wanted to keep all the wisdom for himself instead of sharing it.",
          "Anansi and Nyame argued about who was the real owner of the pot.",
          "Anansi could not find a tree tall enough to hide the pot of wisdom.",
          "Ntikuma wanted the pot of wisdom and tried to take it from his father.",
        ], answer: 0,
        hint: "The main conflict is the biggest problem. What did Nyame ask Anansi to do — and what did Anansi want to do?",
        feedback: {
          1: "Not quite. Nyame gave Anansi the pot kindly — they did not argue.",
          2: "Look again: he found the tallest tree. His problem was climbing it — and his greedy plan.",
          3: "Ntikuma didn’t try to take the pot. He gave his father an idea.",
        },
        explain: "The central problem: Nyame asked Anansi to <b>share</b>, but Anansi wanted to <b>keep</b> all the wisdom.",
      },
      {
        type: "order", skill: "Story sequence",
        prompt: "Put the events in the correct order. <span class='tip'>Tap an event to add it to the next empty step.</span>",
        items: [
          "Nyame gave Anansi a pot full of wisdom.",
          "Anansi decided to keep the wisdom for himself.",
          "Anansi tied the pot to the front of his body.",
          "Ntikuma told his father to tie the pot on his back.",
          "The pot fell and broke into many pieces.",
          "The wind and rain carried the wisdom all over the world.",
        ],
        hint: "Follow the pot: the sky → Anansi’s home → the tall tree → the ground → the whole world.",
        explain: "Perfect timeline! Narratives are told in <b>chronological order</b>.",
      },
      {
        type: "mcq", skill: "Cause & effect", ref: 4,
        prompt: "Why did Anansi keep slipping down the tree?",
        options: [
          "The pot on the front of his body was in the way.",
          "The tree was wet because of the heavy rain.",
          "Ntikuma was shaking the bottom of the tree.",
          "His legs were hurt after a long journey.",
        ], answer: 0,
        hint: "Read page 4 again. What stopped him from holding the tree properly?",
        feedback: { 1: "Look again — the rain started later, after the pot broke.", 3: "His legs became tired <i>after</i> hours of trying. That was not the reason he slipped." },
        explain: "Cause: the big round pot was in front of him → Effect: he could not hold the tree and slipped.",
      },
      {
        type: "sort", skill: "Cause & effect match", layout: "match", capacity: 1,
        prompt: "Match each <b>cause</b> with its <b>effect</b>.",
        bins: [
          { id: "c1", label: "Anansi wanted everyone to need him.", kicker: "CAUSE" },
          { id: "c2", label: "The pot was on the front of Anansi’s body.", kicker: "CAUSE" },
          { id: "c3", label: "A small boy had a better idea than Anansi.", kicker: "CAUSE" },
          { id: "c4", label: "The pot broke into many pieces.", kicker: "CAUSE" },
        ],
        cards: [
          { text: "He decided to keep all the wisdom for himself.", bin: "c1" },
          { text: "He slipped down the tree again and again.", bin: "c2" },
          { text: "Anansi felt angry and embarrassed.", bin: "c3" },
          { text: "The wind carried the wisdom across the land.", bin: "c4" },
        ],
        hint: "Ask “What happened <i>because of</i> this?” for each cause.",
        explain: "Each event in a narrative causes the next one. That is how a plot works!",
      },
      {
        type: "mcq", skill: "Key moment", ref: 5,
        prompt: "Which moment showed Anansi that he did <b>not</b> know everything?",
        options: [
          "When Ntikuma suggested tying the pot on his back.",
          "When Anansi looked inside the pot for the first time.",
          "When Anansi slipped down the tree again and again.",
          "When the rain washed the wisdom into the rivers.",
        ], answer: 0,
        hint: "Who had a better idea than the “wisest creature in the world”?",
        feedback: { 2: "He was frustrated then, but he still believed his plan was good. What made him stop?" },
        explain: "Ntikuma’s simple idea showed Anansi that even with all the wisdom, <b>he did not know everything</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 4, structureOptions: true,
        quote: "Anansi started to climb, but the big round pot was in the way. He could not hold the tree properly, and he slipped down again and again. He tried for hours. His legs were tired, and he was very frustrated.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
        hint: "Is the problem starting, getting worse, or being solved here?",
        explain: "Anansi’s plan is not working and his problem gets <b>worse</b> — this is the <b>complication</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 6, structureOptions: true,
        quote: "The wind picked up the wisdom and scattered it across the land. The rain washed it into the rivers, and the rivers carried it to the sea. Soon, small pieces of wisdom were everywhere in the world.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
        hint: "What happens to Anansi’s plan to keep all the wisdom?",
        explain: "The wisdom is now shared with the whole world, so Anansi’s greedy plan is over. This is the <b>resolution</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 7, structureOptions: true,
        quote: "From that day on, Anansi listened to others, even the young ones. And that is why, the Ashanti people say, everyone in the world has some wisdom, but no one has all of it.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 3,
        hint: "“From that day on…” and “that is why…” tell us about life <i>after</i> the problem.",
        explain: "It tells us what happened afterward and explains something about our world: this is the <b>ending / coda</b>.",
      },
    ],

    /* ---------------- 🎭 CHARACTER DETECTIVE ---------------- */
    character: [
      {
        type: "mcq", skill: "Trait → Step 1", character: "anansi", ref: 2,
        prompt: "Character: <b>Anansi</b>, in the middle of the story (pages 2–3). Choose the <b>best</b> trait.",
        options: ["greedy", "generous", "shy", "lazy"], answer: 0,
        hint: "Nyame asked him to share the wisdom. What did Anansi want to do with it?",
        feedback: { 3: "Anansi tried to climb for hours — that is not lazy. Think about what he wanted to do with the wisdom." },
        explain: "He wanted to keep all the wisdom for himself: he was <b>greedy</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "anansi", ref: 3,
        prompt: "You chose <b>greedy</b>. Which event <b>best supports</b> your answer?",
        options: [
          "He planned to hide the wisdom where no one could reach it.",
          "He hurried home and looked inside the pot of wisdom.",
          "He learned how to plant crops and how to make tools.",
          "He loved to tell stories to the creatures in his village.",
        ], answer: 0,
        hint: "Evidence must <i>show</i> the trait. Which action shows he wanted to keep everything?",
        explain: "Character → Trait → <b>Evidence</b>. Hiding the pot from everyone proves he was greedy.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "ntikuma", ref: 5,
        prompt: "Character: <b>Ntikuma</b>. Which trait describes him best?",
        options: ["clever", "greedy", "lazy", "proud"], answer: 0,
        hint: "His father could not solve the problem. What did Ntikuma do?",
        explain: "He found a simple, smart solution: he was <b>clever</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "ntikuma", ref: 5,
        prompt: "Which evidence <b>best proves</b> that Ntikuma was clever?",
        options: [
          "He told his father to tie the pot on his back.",
          "He was Anansi’s young son in the village.",
          "He followed his father into the forest.",
          "He watched quietly from behind a bush.",
        ], answer: 0,
        hint: "Three of these are facts about him. Which one shows a good idea?",
        feedback: { 2: "Following someone doesn’t show a good idea. Which action solved a problem?" },
        explain: "His advice solved the climbing problem — good evidence that he was <b>clever</b>.",
      },
      {
        type: "mcq", skill: "Evidence hunt", character: "nyame", ref: 1,
        prompt: "Nyame can be described as <b>generous</b>. Which evidence supports this?",
        options: [
          "He gave away all the wisdom of the world to be shared.",
          "He lived high above the clouds, far from the village.",
          "He was called the Sky God by the people of Ghana.",
          "He watched Anansi climb the tree from the sky.",
        ], answer: 0,
        hint: "A generous person is happy to give. Which option shows him giving?",
        explain: "Nyame gave the pot and asked Anansi to share it with <b>everyone</b> — that is generous.",
      },
      {
        type: "multi", skill: "Two best traits", character: "anansi", ref: 7, pick: 2,
        prompt: "Choose <b>TWO</b> traits that describe <b>Anansi before the pot broke</b>.",
        options: ["selfish", "generous", "proud", "lazy", "shy", "gentle"], answer: [0, 2],
        hint: "At the end, Anansi describes himself: “I was ___ and ___.”",
        explain: "Anansi said it himself: “I was <b>selfish</b> and <b>proud</b>.”",
      },
      {
        type: "mcq", skill: "Who am I?",
        prompt: "<b>Who am I?</b><ul class='clues'><li>I followed someone into the forest.</li><li>I watched quietly from behind a bush.</li><li>My idea was better than an idea from the “wisest creature”.</li></ul>",
        options: ["Ntikuma", "Anansi", "Nyame", "a villager"], answer: 0,
        hint: "Who called up to Anansi from below the tree?",
        explain: "<b>Ntikuma</b> followed his father, watched him, and gave him a better idea.",
      },
      {
        type: "sort", skill: "Trait match", layout: "match", capacity: 1,
        prompt: "Match each character with the personality adjective that fits best.",
        bins: [
          { id: "anansi1", label: "Anansi (with the pot)", img: "img/stories/anansi/anansi.webp" },
          { id: "anansi2", label: "Anansi (at the end)", img: "img/stories/anansi/anansi.webp" },
          { id: "ntikuma", label: "Ntikuma", img: "img/stories/anansi/ntikuma.webp" },
          { id: "nyame", label: "Nyame, the Sky God", img: "img/stories/anansi/nyame.webp" },
        ],
        cards: [
          { text: "greedy", bin: "anansi1" }, { text: "humble", bin: "anansi2" },
          { text: "clever", bin: "ntikuma" }, { text: "generous", bin: "nyame" },
        ],
        hint: "Remember the evidence: who gave the pot, who hid it, who had the idea, and who said “Thank you”?",
        explain: "Every trait matches evidence from the text. Anansi even has two — because he <b>changed</b>!",
      },
      {
        type: "mcq", skill: "Character comparison", ref: 5,
        prompt: "How was Ntikuma <b>different</b> from his father in the forest?",
        options: [
          "Ntikuma wanted to help; Anansi thought only of himself.",
          "Ntikuma was greedy, but Anansi was very generous.",
          "Ntikuma was proud, but Anansi was very humble.",
          "Ntikuma was older and stronger than Anansi.",
        ], answer: 0,
        hint: "Think about what each character wanted in the forest.",
        explain: "Ntikuma was <b>helpful</b> — he wanted to help his father. Anansi was <b>selfish</b> — he wanted all the wisdom.",
      },
      {
        type: "mcq", skill: "Inference: motive", ref: 5,
        quote: "He felt angry and embarrassed. In his anger, he let go of the pot.",
        prompt: "Why did Anansi let go of the pot?",
        options: [
          "His feelings were so strong that he stopped holding it.",
          "His son asked him to throw it down to the ground.",
          "The rope broke because the wind was very strong.",
          "He wanted to share the wisdom with the whole world.",
        ], answer: 0,
        hint: "Look for the words “In his anger…”. What was happening inside Anansi?",
        feedback: { 3: "Not at this moment. He understood the value of sharing <i>later</i>, after the pot broke." },
        explain: "Anansi was so <b>angry and embarrassed</b> that he let go. He did not plan it.",
      },
      {
        type: "sort", skill: "Character change", layout: "change",
        prompt: "How did <b>Anansi</b> change? Put each card in <b>BEFORE</b> or <b>AFTER</b> the pot broke.",
        bins: [
          { id: "before", label: "BEFORE", sub: "greedy and proud" },
          { id: "after", label: "AFTER", sub: "humble and thankful" },
        ],
        cards: [
          { text: "wanted all the wisdom for himself", bin: "before" },
          { text: "wanted everyone to need him", bin: "before" },
          { text: "thanked his son for his idea", bin: "after" },
          { text: "listened to others, even the young", bin: "after" },
        ],
        hint: "Before: think about his plan for the pot. After: think about what he said to Ntikuma.",
        explain: "Anansi changed from <b>greedy and proud</b> → <b>humble and thankful</b>. He learned that wisdom must be shared.",
      },
      {
        type: "mcq", skill: "Change → Evidence", ref: 7,
        prompt: "Which sentence <b>best shows</b> that Anansi changed at the end?",
        options: [
          "“It is better that everyone has a little.”",
          "“I will be the wisest creature in the world!”",
          "“Why should I share this?”",
          "“Please share it with everyone.”",
        ], answer: 0,
        hint: "Two of these are Anansi’s words from the beginning. One is Nyame’s. Which one did Anansi say at the end?",
        feedback: { 3: "These are Nyame’s words, not Anansi’s." },
        explain: "At the end, Anansi says it is <b>better</b> that everyone has some wisdom — the opposite of his old plan.",
      },
    ],

    /* ---------------- ⏳ PAST TENSE LAB ---------------- */
    grammar: [
      {
        type: "verbs", skill: "Verb transform",
        prompt: "Type the <b>simple past</b> form of each verb from the story.",
        verbs: [
          { base: "live", past: "lived" }, { base: "climb", past: "climbed" }, { base: "tie", past: "tied" },
          { base: "give", past: "gave" }, { base: "fall", past: "fell" }, { base: "break", past: "broke" },
        ],
        hint: "Regular verbs add <b>-ed</b> (climb → climbed). Irregular verbs change form (give → g _ v e).",
        explain: "<b>lived, climbed, tied</b> are regular. <b>gave, fell, broke</b> are irregular.",
      },
      {
        type: "verbs", skill: "Verb transform",
        prompt: "More story verbs! Type the <b>simple past</b> form.",
        verbs: [
          { base: "hurry", past: "hurried" }, { base: "stop", past: "stopped" }, { base: "blow", past: "blew" },
          { base: "think", past: "thought" }, { base: "feel", past: "felt" }, { base: "begin", past: "began" },
        ],
        hint: "Careful with spelling: hurry → hurr<b>ied</b>, stop → sto<b>pped</b>. The other four are irregular — find them in the story.",
        explain: "Regular: <b>hurried, stopped</b>. Irregular: <b>blew, thought, felt, began</b>.",
      },
      {
        type: "mcq", skill: "Choose the correct verb", ref: 1,
        prompt: "One day, Nyame ___ Anansi a clay pot.",
        options: ["gave", "give", "gives", "giving"], answer: 0,
        hint: "“One day” tells us this happened in the past. What is the past form of <i>give</i>?",
        explain: "<b>give → gave</b> (irregular).",
      },
      {
        type: "mcq", skill: "Was / were", ref: 4,
        prompt: "After hours of climbing, Anansi’s legs ___ tired.",
        options: ["were", "was", "is", "be"], answer: 0,
        hint: "“Anansi’s legs” = they (more than one).",
        explain: "Plural subjects (they, his legs) → <b>were</b>.",
      },
      {
        type: "mcq", skill: "Was / were", ref: 2,
        prompt: "Every idea in the pot ___ more wonderful than the last.",
        options: ["was", "were", "are", "be"], answer: 0,
        hint: "Careful! <b>Every</b> + singular noun (every idea) = it.",
        feedback: { 1: "It sounds like many ideas, but <i>every idea</i> is singular. Use the form for he / she / it." },
        explain: "<b>Every idea</b> is singular → <b>was</b>.",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 1,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Nyame gived Anansi a pot full of wisdom.",
        wrong: 1, options: ["gave", "given", "gives", "give"], answer: 0,
        hint: "Find the verb. Is <i>give</i> regular or irregular?",
        stage2: "Now choose the correct past form of <b>give</b>:",
        feedback2: { 1: "Careful! <b>given</b> needs <i>has</i> or <i>had</i> before it. The simple past is different." },
        explain: "<b>give → gave</b>: “Nyame <b>gave</b> Anansi a pot full of wisdom.”",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 5,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "The pot fell to the ground and break into many pieces.",
        wrong: 7, options: ["broke", "breaked", "broken", "breaks"], answer: 0,
        hint: "There are two verbs. One is correct (fell). Check the other one.",
        stage2: "Choose the correct past form of <b>break</b>:",
        feedback2: { 1: "Break is irregular — we don’t add -ed.", 2: "<b>broken</b> needs <i>has</i> or <i>had</i>. The simple past is different." },
        explain: "<b>break → broke</b>. Both verbs in the sentence must be past: fell … <b>broke</b>.",
      },
      {
        type: "fix", skill: "Negative challenge", ref: 3,
        prompt: "This negative sentence has a mistake. Tap the <b>incorrect</b> word.",
        sentence: "Anansi didn’t told anyone about his plan.",
        wrong: 2, options: ["tell", "tells", "telling", "to tell"], answer: 0,
        hint: "After <b>didn’t</b>, we use the base verb (V1).",
        stage2: "After <b>didn’t</b>, which form is correct?",
        explain: "<b>didn’t + base verb</b>: “Anansi didn’t <b>tell</b> anyone about his plan.”",
      },
      {
        type: "mcq", skill: "Negative sentence", ref: 2,
        prompt: "At first, Anansi ___ the wisdom with anyone.",
        options: ["didn’t share", "didn’t shared", "doesn’t share", "wasn’t share"], answer: 0,
        hint: "Past negative = did not (didn’t) + base verb.",
        feedback: { 1: "Almost! After didn’t, the verb goes back to the base form.", 2: "“doesn’t” is present. The story is in the past." },
        explain: "<b>didn’t + share</b> (base verb).",
      },
      {
        type: "order", skill: "Sentence builder", inline: true, ref: 3,
        prompt: "Build the sentence in the simple past. <span class='tip'>One word is not needed.</span>",
        items: ["Anansi", "tied", "the pot", "to the front of his body."],
        extras: ["tie"],
        hint: "Start with “Anansi…”. Which verb form shows the past?",
        explain: "“Anansi <b>tied</b> the pot to the front of his body.” — Subject + <b>V2</b> + object.",
      },
      {
        type: "order", skill: "Question challenge", inline: true, ref: 4,
        prompt: "Build a simple past <b>question</b>. <span class='tip'>One word is not needed.</span>",
        items: ["Did", "Ntikuma", "follow", "his father?"],
        extras: ["followed"],
        hint: "Question pattern: <b>Did + subject + base verb…?</b>",
        explain: "“<b>Did</b> Ntikuma <b>follow</b> his father?” — Yes, he did!",
      },
      {
        type: "mcq", skill: "Question challenge", ref: 5,
        prompt: "“___ Anansi angry and embarrassed?” — “Yes, he was.”",
        options: ["Was", "Did", "Were", "Does"], answer: 0,
        hint: "Look at the short answer: “Yes, he <b>was</b>.” There is no main verb — only an adjective (angry).",
        feedback: { 1: "We use <b>Did</b> with a main verb (Did he climb…?). Here there is no main verb, only adjectives." },
        explain: "With adjectives, past questions use <b>Was / Were</b>: Was + he / she / it + adjective?",
      },
    ],
  },

  /* ---------------- 🌟 MASTER THE STORY (final) ---------------- */
  final: [
    {
      type: "mcq", skill: "Vocabulary in context", ref: 4,
      quote: "He could not hold the tree properly, and he slipped down again and again.",
      prompt: "What does <b>properly</b> mean here?",
      options: ["in the right way", "in a quick way", "with just one hand", "for a long time"], answer: 0,
      hint: "The pot was in the way, so he could not hold the tree <i>well</i>.",
      explain: "<b>Properly</b> = correctly, in the right way.",
    },
    {
      type: "mcq", skill: "Simple past", ref: 6,
      prompt: "Just then, a strong wind ___.",
      options: ["blew", "blows", "blowed", "blow"], answer: 0,
      hint: "<i>Blow</i> is irregular. Look at page 6.",
      feedback: { 2: "Blow is irregular — we don’t add -ed." },
      explain: "<b>blow → blew</b>.",
    },
    {
      type: "mcq", skill: "Narrative structure", structureOptions: true, ref: 1,
      quote: "Long ago, in a village in the forests of Ghana, there lived a spider called Anansi.",
      prompt: "Which part of the narrative does this sentence belong to?",
      options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 0,
      hint: "Does it tell us who, where and when?",
      explain: "Who (Anansi), where (a village in Ghana), when (long ago): <b>orientation</b>.",
    },
    {
      type: "order", skill: "Sequence of events",
      prompt: "Put these events in order.",
      items: [
        "Anansi learned how to plant crops and cure illnesses.",
        "Anansi walked quietly into the forest with the pot.",
        "Ntikuma watched his father from behind a bush.",
        "The rivers carried the wisdom to the sea.",
      ],
      hint: "Home → forest → tree → the whole world.",
      explain: "Great timeline memory!",
    },
    {
      type: "mcq", skill: "Main conflict", ref: 4,
      prompt: "Anansi could not climb the tree with the pot. Why is this <b>not</b> the main conflict of the story?",
      options: [
        "It is only part of a bigger problem: his greedy plan.",
        "Anansi never had any problem when he climbed the tree.",
        "The climbing happens at the very end, after the pot breaks.",
        "Ntikuma, not Anansi, was the one who tried to climb.",
      ], answer: 0,
      hint: "Why was Anansi climbing the tree in the first place?",
      feedback: { 1: "Look again at page 4: he slipped down again and again. The climbing was a real problem — but a smaller one." },
      explain: "Anansi only climbed because he wanted to hide the wisdom. The <b>main conflict</b> is his greed: he wanted to keep what Nyame asked him to share.",
    },
    {
      type: "mcq", skill: "Characterization", ref: 4,
      prompt: "Why can Ntikuma be described as <b>observant</b>?",
      options: [
        "He watched his father and saw why he kept slipping.",
        "He took the pot and climbed the tree by himself.",
        "He broke the pot so that everyone could have wisdom.",
        "He told the whole village about his father’s plan.",
      ], answer: 0,
      hint: "Observant people notice things. What did Ntikuma notice?",
      explain: "He watched quietly and <b>noticed</b> the problem: the pot was on the wrong side.",
    },
    {
      type: "mcq", skill: "Cause & effect", ref: 4,
      prompt: "Anansi told no one about his plan. So why was Ntikuma able to give him advice at the tree?",
      options: [
        "He had followed his father into the forest.",
        "His father had told him all about the plan.",
        "Nyame had told him about the pot of wisdom.",
        "He had looked inside the pot of wisdom first.",
      ], answer: 0,
      hint: "Read the end of page 4. Where was Ntikuma while his father was climbing?",
      feedback: { 1: "Look at page 3: Anansi didn’t tell anyone about his plan, not even his family." },
      explain: "Cause: Ntikuma <b>followed</b> his father and watched him → Effect: he saw the problem and could give advice.",
    },
    {
      type: "mcq", skill: "Turning point",
      prompt: "Which event changed the direction of the story <b>most significantly</b>?",
      options: [
        "The pot broke, and the wisdom spread all over the world.",
        "Anansi learned how to plant crops and make tools.",
        "Anansi tied the pot to the front of his body.",
        "Anansi walked quietly into the forest in the morning.",
      ], answer: 0,
      hint: "After which event was it impossible for Anansi to keep all the wisdom?",
      explain: "When the pot broke, Anansi’s plan ended forever and <b>everyone</b> got some wisdom — the story turned completely.",
    },
    {
      type: "mcq", skill: "Inference", ref: 3,
      quote: "He didn’t tell anyone about his plan, not even his family.",
      prompt: "What can we <b>infer</b> from this sentence?",
      options: [
        "Anansi knew that others would not like his plan.",
        "Anansi forgot to talk to his family that day.",
        "Anansi’s family already knew all about his plan.",
        "Anansi wanted to give his family a big surprise.",
      ], answer: 0,
      hint: "Nyame asked him to share. Would people be happy about a plan to hide the wisdom?",
      explain: "He kept his plan secret because he knew it was <b>selfish</b> — others would not agree with it.",
    },
    {
      type: "mcq", skill: "Inference", ref: 6,
      quote: "Anansi looked at the broken pot for a long time. Then, slowly, he began to laugh.",
      prompt: "Why did Anansi probably laugh?",
      options: [
        "He finally saw how foolish his plan had been.",
        "He thought the wind and rain were very funny.",
        "He wanted Ntikuma to feel silly and embarrassed.",
        "He had a new plan to collect all the wisdom again.",
      ], answer: 0,
      hint: "Read what he says next on page 7: “You were right, Ntikuma… I was selfish and proud.”",
      explain: "He looked for a long time and <b>thought</b>. Then he understood his mistake and could laugh at himself.",
    },
    {
      type: "mcq", skill: "Motive", ref: 2,
      prompt: "Why did Anansi <b>decide</b> to hide the pot at the top of the tallest tree?",
      options: [
        "He wanted to be the only one with all the wisdom.",
        "Nyame told him to keep it in a very safe place.",
        "He was afraid that the pot would break at home.",
        "He wanted to give it to his son when he was older.",
      ], answer: 0,
      hint: "Read Anansi’s thoughts on page 2: “If I keep all the wisdom, everyone will…”",
      feedback: { 1: "Look again — Nyame told him to <i>share</i> it, not to hide it." },
      explain: "Anansi wanted everyone to need him — he wanted to be <b>the wisest creature in the world</b>.",
    },
    {
      type: "mcq", skill: "Moral value",
      prompt: "What can readers learn from Anansi’s story?",
      options: [
        "No one knows everything, so we should share and learn from others.",
        "Clever people should keep their best ideas a secret.",
        "Children should never give advice to their parents.",
        "It is dangerous to climb tall trees with heavy things.",
      ], answer: 0,
      hint: "Think about who had the best idea — and about the last sentence of the story.",
      feedback: { 3: "That is true in real life, but it is not the main message of the story." },
      explain: "The moral: <b>no one has all the wisdom</b>. Sharing is better than being selfish, and we can learn from everyone — even the young.",
    },
  ],
});
