/* ==========================================================
   NARRATIVE QUEST — Story file
   King Arthur and the Sword in the Stone (Legend · Britain)
   Retold for A2–B1 readers.
   ========================================================== */
NQ.registerStory({
  id: "king-arthur",
  title: "King Arthur and the Sword in the Stone",
  genre: "legends",
  origin: "world",
  region: "Britain",
  country: "United Kingdom",
  level: "A2–B1",
  minutes: 30,
  cover: "img/stories/king-arthur/king-arthur-cover.webp",
  summary: "Britain has no king, and only the true king can pull a magic sword out of a stone. Who will it be?",

  /* ---------- STORY PAGES ---------- */
  pages: [
    {
      text: "Long ago, Britain had a great king named Uther Pendragon. Not far from his castle lived Sir Ector, a fair and kind knight. He had a son called Kay, and he also raised a young boy named Arthur. Arthur did not know who his real parents were, but Sir Ector loved him like a son. Arthur and Kay grew up together like brothers. Arthur was quiet, helpful and modest.",
      vocab: ["raised", "modest"],
      scene: { art: "img/stories/king-arthur/arthur-kay-childhood.webp", fit: "contain", alt: "arthur kay childhood", tone: "day", fx: [] },
    },
    {
      text: "When King Uther died, Britain had no king. The powerful lords began to argue, and soon they were fighting. Each lord wanted to be king. Then the wise wizard Merlin made a plan. One winter morning, a large stone appeared in a churchyard in London. A sword was stuck deep in the stone, with golden words: “Whoever pulls this sword out of this stone is the true king of all Britain.” Many strong knights tried, but the sword did not move.",
      vocab: ["lords", "argue", "wizard", "stuck"],
      scene: { art: "img/stories/king-arthur/merlin-sword-churchyard.webp", fit: "contain", alt: "merlin sword churchyard", tone: "day", fx: [] },
    },
    {
      text: "On New Year’s Day, there was a great tournament in London. Kay was a new knight, and Arthur was his squire. He carried Kay’s armour and looked after his horse. When they arrived, Kay noticed that he had forgotten his sword. “Arthur, please run back to the inn and get it!” he said. Arthur ran quickly, but the inn was locked because everyone had gone to watch the tournament.",
      vocab: ["tournament", "squire", "inn"],
      scene: { art: "img/stories/king-arthur/tournament-inn-locked.webp", fit: "contain", alt: "tournament inn locked", tone: "day", fx: [] },
    },
    {
      text: "What could he do? Then Arthur remembered the sword in the churchyard. “My brother must not be without a sword today,” he thought. He took the handle and pulled, and the sword slid out easily. He did not stop to read the golden words. He hurried back and gave the sword to Kay. Kay recognised it at once. He ran to his father and shouted, “Look! I pulled the sword from the stone, so I must be king!”",
      vocab: [],
      scene: { art: "img/stories/king-arthur/arthur-pulls-sword.webp", fit: "contain", alt: "arthur pulls sword", tone: "day", fx: [] },
    },
    {
      text: "Sir Ector looked at his son’s face. He took Kay into the church and made him swear on the holy book. “Now tell me the truth. How did you get this sword?” Kay could not lie. “Arthur gave it to me,” he admitted. So they all went back to the churchyard. Arthur put the sword back into the stone and pulled it out again easily.",
      vocab: ["swear", "admitted"],
      scene: { art: "img/stories/king-arthur/ector-questions-kay.webp", fit: "contain", alt: "ector questions kay", tone: "day", fx: [] },
    },
    {
      text: "The lords were surprised and whispered to each other. Some of them refused to accept a young boy as their king, so Arthur did it again and again in front of everyone. Finally, Merlin revealed the secret: Arthur was the son of King Uther Pendragon. The lords stopped arguing, and everyone bowed to their new king.",
      vocab: ["revealed"],
      scene: { art: "img/stories/king-arthur/arthur-pulls-sword-again.webp", fit: "contain", alt: "arthur pulls sword again", tone: "day", fx: [] },
    },
    {
      text: "Arthur was amazed, but he was not proud. When Sir Ector and Kay knelt in front of him, he gently asked them to stand up. “You are still my father and my brother,” he said. He promised to rule fairly and to help rich and poor people alike, and he asked them both to stay by his side. Arthur became one of the most famous kings in British legend. His story shows that true greatness comes from humility, honesty and helping others.",
      vocab: [],
      scene: { art: "img/stories/king-arthur/arthur-asks-them-to-stand.webp", fit: "contain", alt: "arthur asks them to stand", tone: "day", fx: [] },
    },
  ],

  /* ---------- VOCABULARY ---------- */
  vocabulary: [
    { word: "raised", forms: ["raised"], meaning: "looked after a child until he or she grew up" },
    { word: "modest", forms: ["modest"], meaning: "not talking proudly about yourself" },
    { word: "lords", forms: ["lords"], meaning: "important, powerful men who owned land" },
    { word: "argue", forms: ["argue"], meaning: "speak angrily to each other because you disagree" },
    { word: "wizard", forms: ["wizard"], meaning: "a man who can do magic" },
    { word: "stuck", forms: ["stuck"], meaning: "fixed in one place and not able to move" },
    { word: "tournament", forms: ["tournament"], meaning: "a competition where knights fought for sport" },
    { word: "squire", forms: ["squire"], meaning: "a young helper of a knight" },
    { word: "inn", forms: ["inn"], meaning: "a small hotel where travellers eat and sleep" },
    { word: "swear", forms: ["swear"], meaning: "make a very serious promise" },
    { word: "admitted", forms: ["admitted"], meaning: "said that something true (often bad) really happened" },
    { word: "revealed", forms: ["revealed"], meaning: "made something secret known" },
  ],

  /* ---------- CHARACTERS ---------- */
  characters: [
    { id: "kay", name: "Sir Kay", img: "img/stories/king-arthur/sir-kay.webp", role: "Sir Ector’s son; Arthur’s foster brother", traits: ["dishonest (at first)", "honest (in the end)"],
      evidence: "He ran to his father and shouted, “Look! I pulled the sword from the stone, so I must be king!”" },
    { id: "arthur", name: "Arthur", img: "img/stories/king-arthur/arthur.webp", role: "Main character", traits: ["helpful", "humble", "modest"],
      evidence: "“My brother must not be without a sword today,” he thought. He took the handle and pulled." },
    { id: "merlin", name: "Merlin", img: "img/stories/king-arthur/merlin.webp", role: "The wizard", traits: ["wise"],
      evidence: "Then the wise wizard Merlin made a plan." },
    { id: "ector", name: "Sir Ector", img: "img/stories/king-arthur/sir-ector.webp", role: "The knight who raised Arthur", traits: ["fair", "kind"],
      evidence: "He took Kay into the church and made him swear on the holy book." },
    { id: "uther", name: "King Uther Pendragon", img: "img/stories/king-arthur/king-uther.webp", role: "The old king (Arthur’s real father)", traits: ["great"],
      evidence: "Long ago, Britain had a great king named Uther Pendragon." },
  ],

  traitWords: [
    { word: "helpful", meaning: "ready to help other people" },
    { word: "humble", meaning: "not thinking you are better than other people" },
    { word: "modest", meaning: "not talking proudly about yourself" },
    { word: "honest", meaning: "telling the truth" },
    { word: "dishonest", meaning: "not telling the truth" },
    { word: "wise", meaning: "able to make good decisions" },
    { word: "fair", meaning: "treating people equally and in the right way" },
    { word: "proud", meaning: "thinking you are very important" },
    { word: "greedy", meaning: "wanting more than you need" },
    { word: "lazy", meaning: "not wanting to work" },
  ],

  /* ---------- GENERIC STRUCTURE ---------- */
  structure: {
    orientation: { pages: [1], summary: "Long ago in Britain, Sir Ector raised Arthur together with his son Kay. Arthur was quiet, helpful and modest." },
    complication: { pages: [2, 3, 4], summary: "King Uther died and the lords fought. Nobody could pull the sword out of the stone. Arthur pulled it out to help Kay, but Kay said he had pulled it himself." },
    resolution: { pages: [5, 6], summary: "Sir Ector made Kay tell the truth. Arthur pulled the sword out again in front of everyone, and Merlin revealed that Arthur was Uther’s son." },
    coda: { pages: [7], summary: "Arthur became a humble, fair king. True greatness comes from humility, honesty and helping others." },
  },
  mainConflict: "Britain had no king, and the lords fought because nobody could prove who the true king was.",
  sequence: [
    "King Uther died, and the lords began to fight.",
    "Merlin made a plan with a sword in a stone.",
    "Many strong knights tried to pull out the sword.",
    "Arthur pulled out the sword to help Kay.",
    "Sir Ector made Kay swear on the holy book.",
    "Merlin revealed that Arthur was Uther’s son.",
  ],
  grammarExamples: {
    regular: ["raise → raised", "pull → pulled", "promise → promised"],
    irregular: ["give → gave", "take → took", "run → ran"],
    was: "Arthur was quiet, helpful and modest.",
    were: "The lords were surprised.",
    negative: "Arthur did not stop to read the golden words.",
    question: "Did Kay pull the sword out of the stone?",
  },
  guides: { good: "img/stories/king-arthur/arthur.webp", hint: "img/stories/king-arthur/merlin.webp" },
  pastVerbs: [
    { base: "raise", past: "raised", type: "regular" }, { base: "pull", past: "pulled", type: "regular" },
    { base: "notice", past: "noticed", type: "regular" }, { base: "arrive", past: "arrived", type: "regular" },
    { base: "hurry", past: "hurried", type: "regular" }, { base: "promise", past: "promised", type: "regular" },
    { base: "admit", past: "admitted", type: "regular" }, { base: "reveal", past: "revealed", type: "regular" },
    { base: "give", past: "gave", type: "irregular" }, { base: "take", past: "took", type: "irregular" },
    { base: "run", past: "ran", type: "irregular" }, { base: "grow", past: "grew", type: "irregular" },
    { base: "make", past: "made", type: "irregular" }, { base: "slide", past: "slid", type: "irregular" },
    { base: "think", past: "thought", type: "irregular" }, { base: "begin", past: "began", type: "irregular" },
  ],

  /* =========================================================
     CHALLENGES
     ========================================================= */
  challenges: {
    /* ---------------- 🔮 WORD HUNTER ---------------- */
    word: [
      {
        type: "mcq", skill: "Meaning in context", ref: 2,
        quote: "The powerful lords began to argue, and soon they were fighting. Each lord wanted to be king.",
        prompt: "Who were the <b>lords</b>?",
        options: ["important, powerful men who owned land", "young soldiers who guarded the castle", "poor farmers who worked in the fields", "teachers who worked at the church"], answer: 0,
        hint: "The lords were <i>powerful</i>, and each one wanted to be king. Would poor or young people want that?",
        explain: "<b>Lords</b> were important, powerful men with land. That is why each one thought he could be king.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 2,
        quote: "The powerful lords began to argue, and soon they were fighting.",
        prompt: "What does <b>argue</b> mean?",
        options: ["speak angrily because you disagree", "sing together in a happy way", "whisper secrets very quietly", "laugh loudly at a funny story"], answer: 0,
        hint: "Look at what happened <i>soon</i> after: they were fighting. What usually comes before a fight?",
        explain: "To <b>argue</b> = to speak angrily because you disagree. Arguing turned into fighting.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 2,
        quote: "A sword was stuck deep in the stone… Many strong knights tried, but the sword did not move.",
        prompt: "What does <b>stuck</b> mean here?",
        options: ["fixed in one place and not able to move", "shining brightly with golden words", "very old and covered in dust", "lying on top of the stone"], answer: 0,
        hint: "Strong knights pulled, but what happened to the sword?",
        explain: "<b>Stuck</b> = fixed in one place. The sword did not move for the strong knights.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 3,
        quote: "On New Year’s Day, there was a great tournament in London. Kay was a new knight… Kay noticed that he had forgotten his sword.",
        prompt: "What is a <b>tournament</b>?",
        options: ["a competition where knights fight for sport", "a big party with food, music and dancing", "a meeting where lords choose a new king", "a market where people buy and sell horses"], answer: 0,
        hint: "Kay was a knight, and he needed his sword for it. What event needs knights and swords?",
        feedback: { 2: "The story does not say the tournament was for choosing a king. Why did Kay need his sword?" },
        explain: "A <b>tournament</b> was a competition where knights fought each other for sport.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 3,
        quote: "Arthur was his squire. He carried Kay’s armour and looked after his horse.",
        prompt: "What was a <b>squire</b>?",
        options: ["a young helper of a knight", "a knight’s older brother", "a cook who worked at an inn", "a student of a wizard"], answer: 0,
        hint: "Read the next sentence. What jobs did Arthur do for Kay?",
        explain: "A <b>squire</b> was a young helper who carried a knight’s armour and looked after his horse.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 5,
        quote: "Kay could not lie. “Arthur gave it to me,” he admitted.",
        prompt: "Which word is closest in meaning to <b>admitted</b>?",
        options: ["confessed", "shouted", "forgot", "promised"], answer: 0,
        hint: "Kay finally told the truth about something he had done wrong.",
        feedback: { 1: "Kay shouted <i>earlier</i>, when he was not telling the truth. Here he says something different." },
        explain: "<b>Admit</b> = <b>confess</b>: say that something true (and often bad) really happened.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 6,
        quote: "Finally, Merlin revealed the secret: Arthur was the son of King Uther Pendragon.",
        prompt: "Which words are closest in meaning to <b>revealed</b>?",
        options: ["made known", "kept hidden", "forgot about", "guessed at"], answer: 0,
        hint: "Before this moment, nobody knew about Arthur’s father. After it, everyone knew.",
        feedback: { 1: "That is the opposite! A secret is kept hidden <i>before</i> it is revealed." },
        explain: "<b>Reveal</b> = make something secret <b>known</b>.",
      },
      {
        type: "mcq", skill: "Antonym", ref: 1,
        quote: "Arthur was quiet, helpful and modest.",
        prompt: "Which word is the <b>opposite</b> of <b>modest</b>?",
        options: ["humble", "boastful", "quiet", "shy"], answer: 1,
        hint: "A modest person does not talk proudly about himself. Which word describes someone who does?",
        feedback: { 0: "Humble is close in meaning to modest, not the opposite." },
        explain: "A <b>modest</b> person does not praise himself; a <b>boastful</b> person talks proudly about himself all the time.",
      },
      {
        type: "mcq", skill: "Word with two meanings", ref: 1,
        quote: "He had a son called Kay, and he also raised a young boy named Arthur.",
        prompt: "What does <b>raised</b> mean in this sentence?",
        options: ["looked after a child until he grew up", "lifted something up into the air", "made the price of something higher", "collected money to help other people"], answer: 0,
        hint: "Many words have more than one meaning. Here, the object of the verb is <i>a young boy</i>.",
        feedback: { 1: "That is a real meaning (“raise your hand”) — but Sir Ector did not lift Arthur into the air!" },
        explain: "Here, <b>raise</b> a child = look after him until he grows up.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 5, image: "img/book.webp",
        prompt: "Look at the picture. Sir Ector made Kay swear on the holy ___.",
        options: ["book", "sword", "stone", "scroll"], answer: 0,
        hint: "People sometimes promise to tell the truth with their hand on something special. What did Kay swear on?",
        explain: "Kay had to <b>swear on the holy book</b>, so he could not lie.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 2, image: "img/stories/king-arthur/merlin.webp",
        prompt: "Look at the picture. Merlin could do magic because he was a ___.",
        options: ["wizard", "knight", "squire", "lord"], answer: 0,
        hint: "Which of these people uses magic, not a sword?",
        explain: "A <b>wizard</b> is a man who can do magic, like Merlin.",
      },
      {
        type: "sort", skill: "Word–meaning match", layout: "match",
        prompt: "Drag each word to its meaning. <span class='tip'>(Or tap a word, then tap a meaning.)</span>",
        bins: [
          { id: "inn", label: "a small hotel for travellers" },
          { id: "swear", label: "make a very serious promise" },
          { id: "squire", label: "a young helper of a knight" },
          { id: "lords", label: "powerful men who owned land" },
          { id: "stuck", label: "fixed in one place" },
          { id: "revealed", label: "made a secret known" },
        ],
        cards: [
          { text: "inn", bin: "inn" }, { text: "swear", bin: "swear" }, { text: "squire", bin: "squire" },
          { text: "lords", bin: "lords" }, { text: "stuck", bin: "stuck" }, { text: "revealed", bin: "revealed" },
        ],
        capacity: 1,
        hint: "Start with the words you are sure about. Arthur ran back to the <i>inn</i>; the sword was <i>stuck</i> in the stone.",
        explain: "Great word hunting! You matched all six words.",
      },
    ],

    /* ---------------- 🧩 STORY DETECTIVE ---------------- */
    structure: [
      {
        type: "sort", skill: "Sort the story",
        prompt: "Put each event card in the correct part of the narrative.",
        bins: [
          { id: "orientation", label: "Orientation", img: "img/st-orientation.webp", sub: "Who? Where? When?" },
          { id: "complication", label: "Complication", img: "img/st-complication.webp", sub: "What problem happened?" },
          { id: "resolution", label: "Resolution", img: "img/st-resolution.webp", sub: "How was it solved?" },
          { id: "coda", label: "Ending / Coda", img: "img/st-ending.webp", sub: "What happened afterward?" },
        ],
        cards: [
          { text: "Long ago, Sir Ector raised Arthur together with his son, Kay.", bin: "orientation" },
          { text: "Arthur was quiet, helpful and modest.", bin: "orientation" },
          { text: "When King Uther died, the lords began to fight.", bin: "complication" },
          { text: "Kay said that he had pulled the sword from the stone.", bin: "complication" },
          { text: "Kay admitted the truth: Arthur gave him the sword.", bin: "resolution" },
          { text: "Merlin revealed that Arthur was the son of King Uther.", bin: "resolution" },
          { text: "Arthur promised to rule fairly and help rich and poor people.", bin: "coda" },
          { text: "True greatness comes from humility, honesty and helping others.", bin: "coda" },
        ],
        hint: "Orientation introduces the characters and place. Complication = problems. Resolution = the problems are solved. Coda = Arthur as king and the lesson.",
        explain: "The story moves from <b>introduction</b> → <b>problems</b> → <b>the truth comes out</b> → <b>a new, fair king</b>.",
      },
      {
        type: "mcq", skill: "Find the complication", ref: 2,
        prompt: "Which sentence shows the <b>beginning of the complication</b>?",
        options: [
          "“When King Uther died, Britain had no king.”",
          "“Arthur was quiet, helpful and modest.”",
          "“Arthur and Kay grew up together like brothers.”",
          "“Arthur was amazed, but he was not proud.”",
        ], answer: 0,
        hint: "Which sentence describes a big change that causes trouble for the whole country?",
        explain: "Without a king, the lords began to argue and fight. This is where the <b>problem</b> starts.",
      },
      {
        type: "mcq", skill: "Find the main conflict", ref: 2,
        prompt: "What is the <b>main conflict</b> in <i>King Arthur and the Sword in the Stone</i>?",
        options: [
          "Britain had no king, and nobody could prove who the true king was.",
          "Kay forgot his sword and could not take part in the tournament.",
          "Merlin and Sir Ector argued about who should raise young Arthur.",
          "Arthur wanted to become king, but Sir Ector did not allow it.",
        ], answer: 0,
        hint: "The main conflict is the biggest problem. What problem did Merlin’s sword and stone try to solve?",
        feedback: {
          1: "That is a small problem in the middle of the story. What was the problem for the whole country?",
          3: "Look again: Arthur did not try to become king. He only wanted to help Kay.",
        },
        explain: "The central problem: Britain had <b>no king</b>, the lords were fighting, and nobody could <b>prove</b> who the true king was.",
      },
      {
        type: "order", skill: "Story sequence",
        prompt: "Put the events in the correct order. <span class='tip'>Tap an event to add it to the next empty step.</span>",
        items: [
          "King Uther died, and the lords began to fight.",
          "Merlin made a plan with a sword in a stone.",
          "Many strong knights tried to pull out the sword.",
          "Arthur pulled out the sword to help Kay.",
          "Sir Ector made Kay swear on the holy book.",
          "Merlin revealed that Arthur was Uther’s son.",
        ],
        hint: "Follow the story: the old king → Merlin’s plan → the tournament → the truth → the secret.",
        explain: "Perfect timeline! Narratives are told in <b>chronological order</b>.",
      },
      {
        type: "mcq", skill: "Cause & effect", ref: 3,
        prompt: "Why was the inn locked?",
        options: [
          "Everyone had gone to watch the tournament.",
          "It was too early in the morning to open.",
          "The owner did not want Arthur to come in.",
          "Merlin had closed it with his magic.",
        ], answer: 0,
        hint: "Read the last sentence of page 3. Look for the word <i>because</i>.",
        explain: "Cause: everyone had gone to the tournament → Effect: the inn was locked, so Arthur could not get Kay’s sword.",
      },
      {
        type: "sort", skill: "Cause & effect match", layout: "match", capacity: 1,
        prompt: "Match each <b>cause</b> with its <b>effect</b>.",
        bins: [
          { id: "c1", label: "King Uther died.", kicker: "CAUSE" },
          { id: "c2", label: "Kay noticed that he had forgotten his sword.", kicker: "CAUSE" },
          { id: "c3", label: "Sir Ector made Kay swear on the holy book.", kicker: "CAUSE" },
          { id: "c4", label: "Some lords refused to accept a young boy as king.", kicker: "CAUSE" },
        ],
        cards: [
          { text: "Britain had no king.", bin: "c1" },
          { text: "Arthur ran back to the inn.", bin: "c2" },
          { text: "Kay admitted the truth.", bin: "c3" },
          { text: "Arthur pulled the sword out again and again.", bin: "c4" },
        ],
        hint: "Ask “What happened <i>because of</i> this?” for each cause.",
        explain: "Each event causes the next one. That is how a plot works!",
      },
      {
        type: "mcq", skill: "Turning point", ref: 5,
        prompt: "After which event did the <b>truth about the sword</b> finally come out?",
        options: [
          "Sir Ector made Kay swear on the holy book.",
          "Kay ran to his father and shouted loudly.",
          "Arthur hurried back and gave Kay the sword.",
          "The lords whispered to each other in surprise.",
        ], answer: 0,
        hint: "Kay could not lie after something very serious happened. What was it?",
        feedback: { 1: "When Kay shouted, he was <i>not</i> telling the truth." },
        explain: "Swearing on the holy book was serious, so Kay <b>admitted</b> the truth. After that, Arthur could show everyone.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 2, structureOptions: true,
        quote: "When King Uther died, Britain had no king. The powerful lords began to argue, and soon they were fighting. Each lord wanted to be king.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
        hint: "Is a problem starting here, or is a problem being solved?",
        explain: "A big problem starts: no king and fighting lords. This is the <b>complication</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 6, structureOptions: true,
        quote: "Finally, Merlin revealed the secret: Arthur was the son of King Uther Pendragon. The lords stopped arguing, and everyone bowed to their new king.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
        hint: "What happens to the lords’ arguing here?",
        explain: "The lords stop arguing and accept the true king. The problem is <b>solved</b>: this is the <b>resolution</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 7, structureOptions: true,
        quote: "Arthur became one of the most famous kings in British legend. His story shows that true greatness comes from humility, honesty and helping others.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 3,
        hint: "Does this paragraph tell us about a problem, or about what happened afterward and the lesson?",
        explain: "It tells us about Arthur’s future and the lesson: this is the <b>ending / coda</b>.",
      },
    ],

    /* ---------------- 🎭 CHARACTER DETECTIVE ---------------- */
    character: [
      {
        type: "mcq", skill: "Trait → Step 1", character: "arthur", ref: 4,
        prompt: "Character: <b>Arthur</b> (at the tournament). Choose the <b>best</b> trait.",
        options: ["helpful", "proud", "greedy", "lazy"], answer: 0,
        hint: "Kay needed a sword. What did Arthur do about it, even when the inn was locked?",
        feedback: { 1: "Look at page 7: “Arthur was amazed, but he was <i>not</i> proud.”" },
        explain: "Arthur did everything he could to find a sword for Kay: he was <b>helpful</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "arthur", ref: 4,
        prompt: "You chose <b>helpful</b>. Which event <b>best supports</b> your answer?",
        options: [
          "He found another sword because his brother needed one.",
          "He grew up together with Kay like a brother.",
          "He did not know who his real parents were.",
          "He watched the knights at the great tournament.",
        ], answer: 0,
        hint: "Evidence must <i>show</i> the trait through an action. Which action helped someone?",
        explain: "Character → Trait → <b>Evidence</b>. “My brother must not be without a sword today” — he acted to help Kay.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "kay", ref: 4,
        prompt: "Kay shouted, “I pulled the sword from the stone!” At that moment, Kay was…",
        options: ["dishonest", "modest", "patient", "generous"], answer: 0,
        hint: "Who really pulled the sword out of the stone?",
        explain: "Arthur pulled the sword out, not Kay. Kay was <b>dishonest</b> at that moment.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "kay", ref: 5,
        prompt: "Kay’s behaviour changed later in the same day. Which sentence proves that Kay <b>finally told the truth</b>?",
        options: [
          "“Arthur gave it to me,” he admitted.",
          "“Look! I pulled the sword from the stone!”",
          "“Arthur, please run back to the inn!”",
          "Kay recognised the sword at once.",
        ], answer: 0,
        hint: "What did Kay say <i>after</i> he swore on the holy book?",
        explain: "“Arthur gave it to me,” he <b>admitted</b>. After he swore on the holy book, Kay told the <b>truth</b>.",
      },
      {
        type: "multi", skill: "Two best traits", character: "arthur", pick: 2,
        prompt: "Choose <b>TWO</b> traits that best describe <b>Arthur</b>.",
        options: ["humble", "greedy", "helpful", "proud", "lazy", "cruel"], answer: [0, 2],
        hint: "Think about why he pulled out the sword, and what he did when Sir Ector and Kay knelt in front of him.",
        explain: "He helped Kay (<b>helpful</b>), and when he became king, he asked Sir Ector and Kay to stand up — he did not think he was better than them (<b>humble</b>).",
      },
      {
        type: "mcq", skill: "Evidence hunt", character: "merlin", ref: 2,
        prompt: "Merlin is called <b>wise</b>. Which evidence supports this?",
        options: [
          "He planned a fair test to show who the true king was.",
          "He watched the tournament with the lords in London.",
          "He lived in Britain during the rule of King Uther.",
          "He carried Kay’s armour and looked after his horse.",
        ], answer: 0,
        hint: "A wise person makes good decisions. Which action solved a big problem without more fighting?",
        explain: "The sword in the stone was a <b>fair test</b>: only the true king could pass it. That was a wise plan.",
      },
      {
        type: "mcq", skill: "Evidence hunt", character: "ector", ref: 5,
        prompt: "Sir Ector is called <b>fair</b>. Which evidence supports this?",
        options: [
          "He made his own son swear to tell the truth.",
          "He had a son called Kay and lived near a castle.",
          "He bowed to the new king with everyone else.",
          "He went back to the churchyard with the others.",
        ], answer: 0,
        hint: "A fair person wants the truth, even when it is not good for his own family.",
        explain: "He wanted the <b>truth</b>, even though Kay was his own son. That is <b>fair</b>.",
      },
      {
        type: "mcq", skill: "Who am I?",
        prompt: "<b>Who am I?</b><ul class='clues'><li>I raised a boy who was not my own son.</li><li>I looked carefully at my son’s face.</li><li>I wanted to know the truth about the sword.</li></ul>",
        options: ["Sir Ector", "Merlin", "Sir Kay", "King Uther"], answer: 0,
        hint: "Who was the father of Kay?",
        explain: "<b>Sir Ector</b> raised Arthur and made Kay tell the truth.",
      },
      {
        type: "mcq", skill: "Who am I?",
        prompt: "<b>Who am I?</b><ul class='clues'><li>I was a new knight.</li><li>I forgot something important on New Year’s Day.</li><li>At first, I said something that was not true.</li></ul>",
        options: ["Sir Kay", "Sir Ector", "Arthur", "Merlin"], answer: 0,
        hint: "Who needed a squire to run back to the inn?",
        explain: "<b>Sir Kay</b> forgot his sword and at first said he had pulled it from the stone.",
      },
      {
        type: "sort", skill: "Trait match", layout: "match", capacity: 1,
        prompt: "Match each character with the personality adjective that fits best.",
        bins: [
          { id: "arthur", label: "Arthur", img: "img/stories/king-arthur/arthur.webp" },
          { id: "kay", label: "Sir Kay (at first)", img: "img/stories/king-arthur/sir-kay.webp" },
          { id: "merlin", label: "Merlin", img: "img/stories/king-arthur/merlin.webp" },
          { id: "ector", label: "Sir Ector", img: "img/stories/king-arthur/sir-ector.webp" },
        ],
        cards: [
          { text: "humble", bin: "arthur" }, { text: "dishonest", bin: "kay" },
          { text: "wise", bin: "merlin" }, { text: "fair", bin: "ector" },
        ],
        hint: "Remember the evidence: who was not proud, who said something untrue, who made the plan, and who wanted the truth?",
        explain: "Every trait matches evidence from the text. Well done, detective!",
      },
      {
        type: "mcq", skill: "Character comparison",
        prompt: "How were Arthur and Kay <b>different</b> when they had the sword?",
        options: [
          "Arthur gave the sword away, but Kay tried to use it to become king.",
          "Arthur wanted to become king, but Kay only wanted to help his brother.",
          "Arthur told a lie about the sword, but Kay told the truth at once.",
          "Arthur kept the sword for himself, but Kay gave it back to the stone.",
        ], answer: 0,
        hint: "What did Arthur do with the sword? What did Kay shout to his father?",
        explain: "Arthur only wanted to <b>help</b>; Kay wanted to <b>be king</b>. That shows Arthur’s humility.",
      },
      {
        type: "mcq", skill: "Inference: motive", ref: 4,
        prompt: "Why did Kay say that <b>he</b> had pulled the sword from the stone?",
        options: [
          "He wanted to become king himself.",
          "He wanted to protect Arthur from danger.",
          "He really thought that he had pulled it.",
          "He wanted to make his father laugh.",
        ], answer: 0,
        hint: "The story does not say it directly. Read the end of what Kay shouted: “…so I must be ___!”",
        feedback: { 2: "Kay knew Arthur had given him the sword — later he admitted it." },
        explain: "Kay shouted “so I must be king!” He wanted the power that the sword promised.",
      },
    ],

    /* ---------------- ⏳ PAST TENSE LAB ---------------- */
    grammar: [
      {
        type: "verbs", skill: "Verb transform",
        prompt: "Type the <b>simple past</b> form of each verb from the story.",
        verbs: [
          { base: "raise", past: "raised" }, { base: "notice", past: "noticed" }, { base: "pull", past: "pulled" },
          { base: "run", past: "ran" }, { base: "give", past: "gave" }, { base: "take", past: "took" },
        ],
        hint: "Regular verbs add <b>-ed</b> (pull → pulled). Irregular verbs change form (give → g _ v e).",
        explain: "<b>raised, noticed, pulled</b> are regular. <b>ran, gave, took</b> are irregular.",
      },
      {
        type: "verbs", skill: "Verb transform",
        prompt: "More story verbs! Type the <b>simple past</b> form.",
        verbs: [
          { base: "promise", past: "promised" }, { base: "arrive", past: "arrived" }, { base: "hurry", past: "hurried" },
          { base: "grow", past: "grew" }, { base: "make", past: "made" }, { base: "slide", past: "slid" },
        ],
        hint: "Careful with spelling: hurry → hurr<b>ied</b>. The irregular verbs are all on pages 1, 2 and 4.",
        explain: "Regular: <b>promised, arrived, hurried</b>. Irregular: <b>grew, made, slid</b>.",
      },
      {
        type: "mcq", skill: "Choose the correct verb", ref: 4,
        prompt: "Arthur hurried back and ___ the sword to Kay.",
        options: ["give", "gave", "gives", "given"], answer: 1,
        hint: "The first verb is <i>hurried</i> (past). The second verb must be past too.",
        feedback: { 3: "<b>given</b> needs <i>has / had</i> before it. The simple past is different." },
        explain: "<b>give → gave</b> (irregular).",
      },
      {
        type: "mcq", skill: "Was / were", ref: 6,
        prompt: "The lords ___ surprised and whispered to each other.",
        options: ["was", "were", "is", "are"], answer: 1,
        hint: "“The lords” is plural. Which past form goes with plural subjects?",
        explain: "<b>were</b> for plural subjects (they, the lords). <b>was</b> for I / he / she / it.",
      },
      {
        type: "mcq", skill: "Was / were", ref: 7,
        prompt: "Arthur ___ amazed, but he was not proud.",
        options: ["were", "was", "is", "be"], answer: 1,
        hint: "“Arthur” = he (one person).",
        explain: "He / she / it → <b>was</b>.",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 3,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Arthur run quickly to the inn.",
        wrong: 1, options: ["ran", "runned", "running", "runs"], answer: 0,
        hint: "Find the verb. Is it in the past form?",
        stage2: "Now choose the correct form of <b>run</b>:",
        feedback2: { 1: "Run is irregular — we don’t add -ed." },
        explain: "<b>run → ran</b>: “Arthur <b>ran</b> quickly to the inn.”",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 4,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Arthur took the handle, and the sword slide out easily.",
        wrong: 7, options: ["slid", "slided", "sliding", "slides"], answer: 0,
        hint: "There are two verbs. One is correct (took). Check the other one.",
        stage2: "Choose the correct form of <b>slide</b>:",
        feedback2: { 1: "Slide is irregular — we don’t add -ed." },
        explain: "<b>slide → slid</b>. Both verbs in the sentence must be past.",
      },
      {
        type: "fix", skill: "Negative challenge", ref: 2,
        prompt: "This negative sentence has a mistake. Tap the <b>incorrect</b> word.",
        sentence: "The sword didn’t moved for the strong knights.",
        wrong: 3, options: ["move", "moves", "moving", "to move"], answer: 0,
        hint: "After <b>didn’t</b>, we use the base verb (V1).",
        stage2: "After <b>didn’t</b>, which form is correct?",
        explain: "<b>didn’t + base verb</b>: “The sword didn’t <b>move</b> for the strong knights.”",
      },
      {
        type: "mcq", skill: "Negative sentence", ref: 4,
        prompt: "Arthur ___ to read the golden words.",
        options: ["didn’t stop", "didn’t stopped", "doesn’t stop", "wasn’t stop"], answer: 0,
        hint: "Past negative = did not (didn’t) + base verb.",
        feedback: { 1: "Almost! After didn’t, the verb goes back to the base form.", 2: "“doesn’t” is present. The story is in the past." },
        explain: "<b>didn’t + stop</b> (base verb).",
      },
      {
        type: "order", skill: "Sentence builder", inline: true, ref: 1,
        prompt: "Build the sentence in the simple past. <span class='tip'>One word is not needed.</span>",
        items: ["Sir Ector", "raised", "a young boy", "named Arthur."],
        extras: ["raise"],
        hint: "Start with the person. Which verb form shows the past?",
        explain: "“Sir Ector <b>raised</b> a young boy named Arthur.” — Subject + <b>V2</b> + object.",
      },
      {
        type: "order", skill: "Question challenge", inline: true, ref: 4,
        prompt: "Build a simple past <b>question</b>. <span class='tip'>One word is not needed.</span>",
        items: ["Did", "Kay", "pull", "the sword?"],
        extras: ["pulled"],
        hint: "Question pattern: <b>Did + subject + base verb…?</b>",
        explain: "“<b>Did</b> Kay <b>pull</b> the sword?” — No, he didn’t. Arthur did!",
      },
      {
        type: "mcq", skill: "Question challenge", ref: 3,
        prompt: "“___ the inn open?” — “No, it wasn’t.”",
        options: ["Was", "Did", "Were", "Does"], answer: 0,
        hint: "Look at the short answer: “No, it <b>wasn’t</b>.” There is no main verb, only an adjective (open).",
        feedback: { 1: "We use <i>Did</i> with a main verb (Did Arthur run…?). Here there is only an adjective: open." },
        explain: "With adjectives we use <b>Was / Were</b>: Was the inn open? — No, it wasn’t.",
      },
    ],
  },

  /* ---------------- 🌟 MASTER THE STORY (final) ---------------- */
  final: [
    {
      type: "mcq", skill: "Vocabulary in context", ref: 6,
      quote: "The lords stopped arguing, and everyone bowed to their new king.",
      prompt: "Why did everyone <b>bow</b>?",
      options: ["to show respect to the new king", "to look for the sword on the ground", "to rest after the long tournament", "to hide from the angry lords"], answer: 0,
      hint: "What do people do in front of a king? The lords had just <i>stopped arguing</i>.",
      explain: "To <b>bow</b> = to bend your body forward to show <b>respect</b>.",
    },
    {
      type: "mcq", skill: "Simple past", ref: 2,
      prompt: "The powerful lords ___ to argue.",
      options: ["began", "begin", "begun", "begins"], answer: 0,
      hint: "The story is in the past. Be careful: one option needs <i>have / had</i> before it.",
      feedback: { 2: "<b>begun</b> needs <i>has / had</i> before it. The simple past is different." },
      explain: "<b>begin → began</b> (irregular).",
    },
    {
      type: "mcq", skill: "Narrative structure", structureOptions: true, ref: 1,
      quote: "Not far from his castle lived Sir Ector, a fair and kind knight. He had a son called Kay, and he also raised a young boy named Arthur.",
      prompt: "Which part of the narrative do these sentences belong to?",
      options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 0,
      hint: "Do they introduce the characters, or show a problem?",
      explain: "They introduce the characters and the place: <b>orientation</b>.",
    },
    {
      type: "order", skill: "Sequence of events",
      prompt: "Put these events in order.",
      items: [
        "Kay noticed that he had forgotten his sword.",
        "Arthur found that the inn was locked.",
        "Kay shouted that he must be king.",
        "Some lords refused to accept a young boy.",
      ],
      hint: "Tournament morning → the inn → Kay and his father → the lords at the churchyard.",
      explain: "Great timeline memory!",
    },
    {
      type: "mcq", skill: "Main conflict",
      prompt: "Which of these is the <b>central problem</b> of the story?",
      options: [
        "The country needed a true king, but nobody could prove who it was.",
        "Arthur could not find his real parents after many long years.",
        "The inn was locked, so Kay could not get his sword in time.",
        "Merlin could not decide which strong knight should be king.",
      ], answer: 0,
      hint: "Which problem was there from the death of King Uther until the end of the story?",
      feedback: { 2: "That problem was solved quickly — Arthur found another sword. What was the bigger problem?" },
      explain: "Britain needed a <b>true king</b>. The sword in the stone was the test that solved this <b>main conflict</b>.",
    },
    {
      type: "mcq", skill: "Characterization", ref: 7,
      prompt: "Why can Arthur be described as <b>humble</b>?",
      options: [
        "He became king, but he asked Sir Ector and Kay to stand up.",
        "He pulled the sword out of the stone many times.",
        "He grew up together with Kay like a brother.",
        "He ran back quickly to the inn to find a sword.",
      ], answer: 0,
      hint: "A humble person does not think he is better than others. What did Arthur do when he became king?",
      feedback: { 3: "That shows he was <i>helpful</i>. Which option shows humility?" },
      explain: "“Arthur was amazed, but he was <b>not proud</b>.” He asked Sir Ector and Kay to stand up: “You are still my father and my brother.” That is humility.",
    },
    {
      type: "mcq", skill: "Cause & effect", ref: 6,
      prompt: "What happened <b>because</b> Merlin revealed the secret?",
      options: [
        "The lords stopped arguing and bowed to Arthur.",
        "Kay ran to his father and shouted loudly.",
        "Arthur put the sword back into the stone.",
        "The inn was locked for the whole day.",
      ], answer: 0,
      hint: "Read the last sentence of page 6.",
      explain: "Cause: Merlin revealed that Arthur was Uther’s son → Effect: the lords <b>stopped arguing</b> and accepted him.",
    },
    {
      type: "mcq", skill: "Turning point",
      prompt: "Which event changed the direction of the story <b>most significantly</b>?",
      options: [
        "Arthur pulled the sword out of the stone to help Kay.",
        "Kay noticed that he had forgotten his sword that day.",
        "Many strong knights tried to pull out the sword.",
        "Arthur ran back to the inn, but it was locked.",
      ], answer: 0,
      hint: "Before this event, nobody could pass Merlin’s test. After it, Britain had its true king.",
      feedback: { 2: "They all failed, so nothing changed. Which event changed everything?" },
      explain: "When Arthur pulled out the sword, the <b>true king</b> was found. This is the <b>turning point</b>.",
    },
    {
      type: "mcq", skill: "Inference", ref: 5,
      quote: "Sir Ector looked at his son’s face. He took Kay into the church and made him swear on the holy book.",
      prompt: "What can we infer about Sir Ector?",
      options: [
        "He thought Kay was probably not telling the truth.",
        "He was very happy that his son was the new king.",
        "He wanted to show the sword to everyone in the church.",
        "He thought Merlin had given the sword to Kay.",
      ], answer: 0,
      hint: "Why would a father look carefully at his son’s face and then ask for a serious promise?",
      explain: "Kay’s face probably showed he was lying, so Sir Ector made him <b>swear</b> to tell the truth.",
    },
    {
      type: "mcq", skill: "Inference", ref: 4,
      quote: "He did not stop to read the golden words.",
      prompt: "What does this sentence suggest about Arthur?",
      options: [
        "He only wanted to help Kay, not to become king.",
        "He could not read, so he did not understand them.",
        "He was afraid that Merlin would see him there.",
        "He already knew that he was Uther’s son.",
      ], answer: 0,
      hint: "The golden words were about becoming king. Was Arthur thinking about that?",
      feedback: { 3: "Look at page 1: Arthur did not know who his real parents were." },
      explain: "Arthur was thinking only about his brother’s problem. He was <b>helpful</b> and <b>humble</b>, not hungry for power.",
    },
    {
      type: "mcq", skill: "Inference: motive", ref: 2,
      prompt: "Why did Merlin decide to put a sword in a stone?",
      options: [
        "He wanted a fair test to show everyone the true king.",
        "He wanted to keep the sword safe from the lords.",
        "He wanted the strongest knight to become king.",
        "He wanted to start a new tournament in London.",
      ], answer: 0,
      hint: "Read the golden words again. What did the stone tell people?",
      feedback: { 2: "Many strong knights tried and failed. Strength was not what the test was about." },
      explain: "The lords were fighting. Merlin’s test showed the <b>true king</b> in a way everyone could see and accept.",
    },
    {
      type: "mcq", skill: "Moral value",
      prompt: "What can readers learn from Arthur’s story?",
      options: [
        "True greatness comes from humility and helping others.",
        "The strongest person should always become the leader.",
        "It is fine to lie if it helps you become important.",
        "We should never help others before we help ourselves.",
      ], answer: 0,
      hint: "Arthur did not try to become king. Why did he pull out the sword?",
      feedback: { 1: "Many strong knights failed. Arthur was chosen for a different reason." },
      explain: "Arthur became king, but he stayed <b>humble</b>, and he only pulled out the sword to <b>help</b> his brother — not because he wanted power.",
    },
  ],
});
