/* ==========================================================
   NARRATIVE QUEST — Story file
   Malin Kundang (Legend · West Sumatra, Indonesia)
   Same data format as putri-serindang-bulan.js
   ========================================================== */
NQ.registerStory({
  id: "malin-kundang",
  title: "Malin Kundang",
  genre: "legends",
  origin: "indonesia",
  region: "West Sumatra, Indonesia",
  country: "Indonesia",
  level: "A2–B1",
  minutes: 30,
  cover: "img/cover-malin-kundang.webp",
  summary: "A poor boy sails away and becomes a rich merchant. But when he comes home, will he remember the mother who loved him?",

  /* ---------- STORY PAGES ---------- */
  pages: [
    {
      text: "A long time ago, in a small fishing village near Padang, West Sumatra, there lived a poor widow named Mande Rubayah and her only son, Malin Kundang. Malin’s father died when Malin was a baby, so life was hard for them. Every day, Malin helped his mother catch and sell fish. He was a hardworking boy, and he loved his mother very much. Once, he fell on a sharp rock and cut his arm. The cut left a long scar.",
      vocab: ["widow", "hardworking", "scar"],
      scene: { art: "img/stories/malin-kundang/malin-helps-mother-fishing.webp", fit: "contain", alt: "malin helps mother fishing", tone: "day", fx: [] },
    },
    {
      text: "When Malin grew up, a big merchant ship stopped at the village. “Mother, please let me sail with this ship,” Malin said. “I want to work hard and become rich. Then we won’t be poor any more.” Mande Rubayah did not want to lose her only son, but she agreed. With tears in her eyes, she hugged him. “Go, my son,” she said. “But never forget your mother.”",
      vocab: ["merchant", "sail"],
      scene: { art: "img/stories/malin-kundang/malin-leaves-village.webp", fit: "contain", alt: "malin leaves village", tone: "day", fx: [] },
    },
    {
      text: "Years passed. Every day, Mande Rubayah stood on the beach and looked at the sea, but Malin never came home and never sent any news. Meanwhile, Malin worked hard and became a rich merchant with many ships. He married a beautiful woman from a wealthy family. One day, his wife said, “I want to see your hometown.” So Malin sailed back to his old village on his huge ship.",
      vocab: ["wealthy"],
      scene: { art: "img/stories/malin-kundang/mother-waits-on-beach.webp", fit: "contain", alt: "mother waits on beach", tone: "day", fx: [] },
    },
    {
      text: "The villagers ran to the beach to look at the beautiful ship. When Mande Rubayah heard the news, she hurried there. She saw the scar on the rich man’s arm and knew that he was her son. “Malin, my son! You came back!” she cried, and she hugged him. But Malin was ashamed of his old mother in her poor, dirty clothes. His wife and crew were watching. “Go away, old woman!” he shouted. “You are not my mother! My mother isn’t a beggar!” Then he pushed her, and she fell onto the sand.",
      vocab: ["ashamed", "crew"],
      scene: { art: "img/stories/malin-kundang/malin-rejects-mother.webp", fit: "contain", alt: "malin rejects mother", tone: "day", fx: [] },
    },
    {
      text: "Mande Rubayah stood up slowly. “Malin, don’t you remember me?” she asked softly. But Malin did not even look at her, and he ordered his crew to sail away. With a broken heart, the old woman raised her hands and prayed, “Oh God, if he is really my son, punish him.” Suddenly, the sky grew dark, and a terrible storm came. Huge waves hit the ship until it was wrecked. “Mother, forgive me!” Malin cried. But it was too late. Slowly, he turned into stone.",
      vocab: ["punish", "wrecked"],
      scene: { art: "img/stories/malin-kundang/storm-wrecks-ship.webp", fit: "contain", alt: "storm wrecks ship", tone: "day", fx: [] },
    },
    {
      text: "Today, on Air Manis Beach near Padang, people can still see a rock that looks like a man kneeling on the sand. People say it is Malin Kundang, still asking his mother for forgiveness. Parents in West Sumatra often tell this story to their children. The lesson is clear: we must always respect our parents and never forget where we come from, even when we become rich and successful.",
      vocab: ["forgiveness", "respect"],
      scene: { art: "img/stories/malin-kundang/malin-stone-air-manis.webp", fit: "contain", alt: "malin stone air manis", tone: "day", fx: [] },
    },
  ],

  /* ---------- VOCABULARY (highlighted while reading) ---------- */
  vocabulary: [
    { word: "widow", forms: ["widow"], meaning: "a woman whose husband has died" },
    { word: "hardworking", forms: ["hardworking"], meaning: "working a lot and putting effort into your work" },
    { word: "scar", forms: ["scar"], meaning: "a mark that stays on the skin after a cut heals" },
    { word: "merchant", forms: ["merchant"], meaning: "a person who buys and sells goods" },
    { word: "sail", forms: ["sail"], meaning: "travel on water in a ship or boat" },
    { word: "wealthy", forms: ["wealthy"], meaning: "rich; having a lot of money" },
    { word: "ashamed", forms: ["ashamed"], meaning: "feeling embarrassed and bad about someone or something" },
    { word: "crew", forms: ["crew"], meaning: "the people who work on a ship" },
    { word: "punish", forms: ["punish"], meaning: "make someone suffer because they did something wrong" },
    { word: "wrecked", forms: ["wrecked"], meaning: "badly broken and destroyed" },
    { word: "forgiveness", forms: ["forgiveness"], meaning: "the act of stopping being angry with someone" },
    { word: "respect", forms: ["respect"], meaning: "treat someone well because they are important to you" },
  ],

  /* ---------- CHARACTERS ---------- */
  characters: [
    { id: "mother", name: "Mande Rubayah", img: "img/stories/malin-kundang/mande-rubayah.webp", role: "Malin’s mother", traits: ["loving", "patient"],
      evidence: "With tears in her eyes, she hugged him. Every day, she stood on the beach and looked at the sea." },
    { id: "malin", name: "Malin Kundang (as a rich man)", img: "img/stories/malin-kundang/adult-malin.webp", role: "Main character", traits: ["arrogant", "ungrateful"],
      evidence: "“Go away, old woman!” he shouted. “You are not my mother! My mother isn’t a beggar!” Then he pushed her, and she fell onto the sand." },
  ],

  /* Personality words taught in Character Detective */
  traitWords: [
    { word: "hardworking", meaning: "working a lot and putting effort into your work" },
    { word: "loving", meaning: "showing love and care for someone" },
    { word: "patient", meaning: "able to wait calmly for a long time" },
    { word: "arrogant", meaning: "thinking you are better than other people" },
    { word: "ungrateful", meaning: "not thankful for what others did for you" },
    { word: "cruel", meaning: "happy to hurt people or animals" },
    { word: "humble", meaning: "not thinking you are better than others" },
    { word: "generous", meaning: "happy to give money, time or help to others" },
    { word: "honest", meaning: "telling the truth" },
    { word: "lazy", meaning: "not wanting to work or do anything" },
    { word: "regretful", meaning: "feeling sorry about something bad you did" },
  ],

  /* ---------- GENERIC STRUCTURE ---------- */
  structure: {
    orientation: { pages: [1], summary: "Malin Kundang, a hardworking and loving boy, lived with his poor mother, Mande Rubayah, in a fishing village near Padang." },
    complication: { pages: [2, 3, 4], summary: "Malin sailed away and became a rich merchant. When he came back, he was ashamed of his poor mother, said she was not his mother and pushed her away." },
    resolution: { pages: [5], summary: "The heartbroken mother prayed. A terrible storm wrecked Malin’s ship, and Malin turned into stone." },
    coda: { pages: [6], summary: "A rock like a kneeling man can still be seen at Air Manis Beach. We must respect our parents and never forget where we come from." },
  },
  mainConflict: "Malin became rich and was ashamed of his poor mother, so he refused to accept her as his mother.",
  sequence: [
    "A merchant ship stopped at Malin’s village.",
    "Malin sailed away to work and become rich.",
    "Malin sailed back to his old village with his wife.",
    "Mande Rubayah saw the scar and hugged her son.",
    "Malin said she was not his mother and pushed her.",
    "A terrible storm came, and Malin turned into stone.",
  ],
  grammarExamples: {
    regular: ["live → lived", "hurry → hurried", "pray → prayed"],
    irregular: ["fall → fell", "become → became", "see → saw"],
    was: "Malin was ashamed of his old mother.",
    were: "His wife and crew were watching.",
    negative: "Malin didn’t look at his mother.",
    question: "Did Mande Rubayah see the scar?",
  },
  /* Portraits used for feedback bubbles */
  guides: { good: "img/stories/malin-kundang/young-malin.webp", hint: "img/stories/malin-kundang/mande-rubayah.webp" },
  pastVerbs: [
    { base: "live", past: "lived", type: "regular" }, { base: "help", past: "helped", type: "regular" },
    { base: "stop", past: "stopped", type: "regular" }, { base: "marry", past: "married", type: "regular" },
    { base: "hurry", past: "hurried", type: "regular" }, { base: "push", past: "pushed", type: "regular" },
    { base: "pray", past: "prayed", type: "regular" }, { base: "order", past: "ordered", type: "regular" },
    { base: "fall", past: "fell", type: "irregular" }, { base: "grow", past: "grew", type: "irregular" },
    { base: "become", past: "became", type: "irregular" }, { base: "stand", past: "stood", type: "irregular" },
    { base: "see", past: "saw", type: "irregular" }, { base: "know", past: "knew", type: "irregular" },
    { base: "hear", past: "heard", type: "irregular" }, { base: "send", past: "sent", type: "irregular" },
  ],

  /* =========================================================
     CHALLENGES
     ========================================================= */
  challenges: {
    /* ---------------- 🔮 WORD HUNTER ---------------- */
    word: [
      {
        type: "mcq", skill: "Meaning in context", ref: 1,
        quote: "There lived a poor widow named Mande Rubayah and her only son, Malin Kundang. Malin’s father died when Malin was a baby.",
        prompt: "What is a <b>widow</b>?",
        options: ["a woman whose husband has died", "a woman who has never married", "a woman who sells fish every day", "a woman who lives far from the sea"], answer: 0,
        hint: "Read the next sentence. What happened to Malin’s father?",
        feedback: { 1: "Not quite. She had a son and a husband before — so she was married." },
        explain: "A <b>widow</b> is a woman whose husband has died. Malin’s father died when Malin was a baby.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 1,
        quote: "Every day, Malin helped his mother catch and sell fish. He was a hardworking boy.",
        prompt: "What does <b>hardworking</b> mean here?",
        options: ["putting a lot of effort into work", "finding work boring and difficult", "working only when someone is watching", "working hard only for money"], answer: 0,
        hint: "Malin helped his mother <i>every day</i>. What does that tell you about the way he worked?",
        explain: "A <b>hardworking</b> person puts a lot of effort into work, like Malin helping his mother every day.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 1,
        quote: "Once, he fell on a sharp rock and cut his arm. The cut left a long scar.",
        prompt: "What is a <b>scar</b>?",
        options: ["a mark that stays on skin after a cut", "a cloth that covers a cut on the arm", "a sharp rock that can cut your skin", "a pain that you feel for a short time"], answer: 0,
        hint: "The cut <i>left</i> something on his arm. It was still there many years later.",
        explain: "A <b>scar</b> is a mark that stays on the skin after a cut heals. Years later, his mother saw it.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 2, image: "img/stories/malin-kundang/merchant-ship.webp",
        prompt: "Look at the picture. Malin sailed away on a <b>merchant</b> ship. What does a merchant do?",
        options: ["buys and sells goods", "catches fish at sea", "fights enemies at sea", "builds ships for kings"], answer: 0,
        hint: "Later, Malin became a rich merchant. How do people get rich with ships full of goods?",
        explain: "A <b>merchant</b> buys and sells goods. Merchant ships carry goods to other places.",
      },
      {
        type: "mcq", skill: "Word with two meanings", ref: 2,
        quote: "“Mother, please let me sail with this ship,” Malin said.",
        prompt: "What does <b>sail</b> mean in this sentence?",
        options: ["travel on the sea in a ship", "a big cloth that catches the wind", "a time when shops sell things cheaply", "repair an old wooden boat"], answer: 0,
        hint: "Many words have more than one meaning. Here, is <i>sail</i> a thing or an action?",
        feedback: { 1: "That is a real meaning of <i>sail</i> — but here it is an action: “let me sail”.", 2: "That word is <i>sale</i>. It sounds the same but has a different spelling." },
        explain: "Here, <b>sail</b> is a verb: travel on the sea in a ship. As a noun, a sail is the big cloth on a ship.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 3,
        quote: "He married a beautiful woman from a wealthy family.",
        prompt: "Which word is closest in meaning to <b>wealthy</b>?",
        options: ["rich", "kind", "famous", "large"], answer: 0,
        hint: "Malin wanted to become rich. What kind of family did his wife come from?",
        explain: "<b>Wealthy</b> = rich; having a lot of money.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 4,
        quote: "When Mande Rubayah heard the news, she hurried there.",
        prompt: "How did Mande Rubayah go to the beach?",
        options: ["very quickly", "very slowly", "with a friend", "by boat"], answer: 0,
        hint: "Look at the verb <i>hurried</i>. She had waited for years to see her son.",
        explain: "To <b>hurry</b> means to go very quickly.",
      },
      {
        type: "mcq", skill: "Antonym", ref: 4,
        quote: "But Malin was ashamed of his old mother in her poor, dirty clothes.",
        prompt: "Which word is the <b>opposite</b> of <b>ashamed</b>?",
        options: ["proud", "embarrassed", "shy", "guilty"], answer: 0,
        hint: "Three of these words describe bad or uncomfortable feelings. Find the one that is different.",
        feedback: { 1: "Embarrassed is close in meaning to ashamed, not the opposite.", 3: "Guilty is also a bad feeling about yourself — it is not the opposite." },
        explain: "If you are <b>ashamed</b> of someone, you feel bad about them. If you are <b>proud</b> of someone, you feel happy about them.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 4,
        quote: "His wife and crew were watching.",
        prompt: "Who were the <b>crew</b>?",
        options: ["the people who worked on his ship", "the people who lived in the village", "the people in his wife’s family", "the people who sold fish on the beach"], answer: 0,
        hint: "Later, Malin ordered his crew to sail away. Who can sail a ship?",
        explain: "The <b>crew</b> are the people who work on a ship.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 5,
        quote: "Huge waves hit the ship until it was wrecked.",
        prompt: "What does <b>wrecked</b> mean here?",
        options: ["badly broken and destroyed", "cleaned and repaired again", "pushed back to the beach", "full of water but safe"], answer: 0,
        hint: "Huge waves hit the ship <i>again and again</i> in a terrible storm. What happened to the ship?",
        explain: "<b>Wrecked</b> = badly broken and destroyed.",
      },
      {
        type: "sort", skill: "Word–meaning match", layout: "match", capacity: 1,
        prompt: "Drag each word to its meaning. <span class='tip'>(Or tap a word, then tap a meaning.)</span>",
        bins: [
          { id: "merchant", label: "a person who buys and sells goods" },
          { id: "ashamed", label: "feeling embarrassed about someone" },
          { id: "punish", label: "make someone suffer for doing wrong" },
          { id: "forgiveness", label: "stopping being angry with someone" },
          { id: "respect", label: "treat someone as important" },
          { id: "widow", label: "a woman whose husband has died" },
        ],
        cards: [
          { text: "merchant", bin: "merchant" }, { text: "ashamed", bin: "ashamed" }, { text: "punish", bin: "punish" },
          { text: "forgiveness", bin: "forgiveness" }, { text: "respect", bin: "respect" }, { text: "widow", bin: "widow" },
        ],
        hint: "Start with the words you are sure about. Mande Rubayah was a <i>widow</i>; Malin became a rich <i>merchant</i>.",
        explain: "Great word hunting! You matched all six words.",
      },
    ],

    /* ---------------- 🧩 STORY DETECTIVE ---------------- */
    structure: [
      {
        type: "sort", skill: "Sort the story",
        prompt: "Put each event card in the correct part of the narrative.",
        bins: [
          { id: "orientation", label: "Orientation", img: "img/st-orientation.webp", sub: "Who? Where? When?" },
          { id: "complication", label: "Complication", img: "img/st-complication.webp", sub: "What problem happened?" },
          { id: "resolution", label: "Resolution", img: "img/st-resolution.webp", sub: "How was it solved?" },
          { id: "coda", label: "Ending / Coda", img: "img/st-ending.webp", sub: "What happened afterward?" },
        ],
        cards: [
          { text: "A poor widow and her son lived in a fishing village near Padang.", bin: "orientation" },
          { text: "Malin was a hardworking boy who loved his mother.", bin: "orientation" },
          { text: "Malin sailed away and never sent any news to his mother.", bin: "complication" },
          { text: "Malin said the old woman was not his mother and pushed her.", bin: "complication" },
          { text: "The mother prayed, and a terrible storm wrecked the ship.", bin: "resolution" },
          { text: "Malin cried for forgiveness, but he turned into stone.", bin: "resolution" },
          { text: "People can still see the rock at Air Manis Beach today.", bin: "coda" },
          { text: "We must always respect our parents.", bin: "coda" },
        ],
        hint: "Orientation introduces the characters and place. Complication = problems. Resolution = how the problem ends. Coda = today and the lesson.",
        explain: "The story moves from <b>introduction</b> → <b>problem</b> → <b>punishment</b> → <b>lesson</b>.",
      },
      {
        type: "mcq", skill: "Find the problem", ref: 4,
        prompt: "Which sentence shows the moment the <b>problem between Malin and his mother</b> really begins?",
        options: [
          "“But Malin was ashamed of his old mother in her poor, dirty clothes.”",
          "“Malin’s father died when Malin was a baby, so life was hard for them.”",
          "“So Malin sailed back to his old village on his huge ship.”",
          "“Slowly, he turned into stone.”",
        ], answer: 0,
        hint: "Look for the word that tells us the story is changing direction.",
        feedback: { 2: "Coming home is not a problem yet. What did Malin feel when he saw his mother?" },
        explain: "The word <b>But</b> and the feeling <b>ashamed</b> signal that the big problem is starting.",
      },
      {
        type: "mcq", skill: "Find the main conflict", ref: 4,
        prompt: "What is the <b>main conflict</b> in <i>Malin Kundang</i>?",
        options: [
          "Rich Malin was ashamed of his poor mother and refused to accept her.",
          "Malin and his mother argued because she did not want him to leave.",
          "Malin’s wife did not want to visit his poor village near Padang.",
          "Mande Rubayah could not find her son after the terrible storm.",
        ], answer: 0,
        hint: "The main conflict is the biggest problem in the story. What went wrong when Malin met his mother again?",
        feedback: {
          1: "Look again at page 2: she was sad, but she agreed and hugged him. There was no argument.",
          2: "Not quite. His wife <i>asked</i> to see his hometown.",
          3: "Not quite. She found him on the beach — before the storm came.",
        },
        explain: "The central problem: Malin was <b>ashamed</b> of his poor mother and <b>refused</b> to accept her.",
      },
      {
        type: "order", skill: "Story sequence",
        prompt: "Put the events in the correct order. <span class='tip'>Tap an event to add it to the next empty step.</span>",
        items: [
          "A merchant ship stopped at Malin’s village.",
          "Malin sailed away to work and become rich.",
          "Malin sailed back to his old village with his wife.",
          "Mande Rubayah saw the scar and hugged her son.",
          "Malin said she was not his mother and pushed her.",
          "A terrible storm came, and Malin turned into stone.",
        ],
        hint: "Follow Malin: he leaves → he comes back → he meets his mother → he is punished.",
        explain: "Perfect timeline! Narratives are told in <b>chronological order</b>.",
      },
      {
        type: "mcq", skill: "Cause & effect", ref: 4,
        prompt: "How did Mande Rubayah know that the rich man was her son?",
        options: [
          "She saw the scar on his arm.",
          "He told her his name.",
          "The villagers told her.",
          "She knew his beautiful wife.",
        ], answer: 0,
        hint: "Read page 4 again. What did she notice just before she cried, “Malin, my son!”?",
        feedback: { 1: "Look again — Malin did not want her to know him. He did not tell her anything." },
        explain: "Cause: she saw the <b>scar</b> → Effect: she knew he was her son. The scar from page 1 is important later!",
      },
      {
        type: "sort", skill: "Cause & effect match", layout: "match", capacity: 1,
        prompt: "Match each <b>cause</b> with its <b>effect</b>.",
        bins: [
          { id: "c1", label: "Malin and his mother were very poor.", kicker: "CAUSE" },
          { id: "c2", label: "Malin’s wife wanted to see his hometown.", kicker: "CAUSE" },
          { id: "c3", label: "Malin was ashamed of his mother’s poor clothes.", kicker: "CAUSE" },
          { id: "c4", label: "The mother prayed with a broken heart.", kicker: "CAUSE" },
        ],
        cards: [
          { text: "Malin wanted to sail away and become rich.", bin: "c1" },
          { text: "Malin sailed back to his old village.", bin: "c2" },
          { text: "He said she was not his mother.", bin: "c3" },
          { text: "A terrible storm wrecked the ship.", bin: "c4" },
        ],
        hint: "Ask “What happened <i>because of</i> this?” for each cause.",
        explain: "Each event in a narrative causes the next one. That is how a plot works!",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 4, structureOptions: true,
        quote: "But Malin was ashamed of his old mother in her poor, dirty clothes. His wife and crew were watching. “Go away, old woman!” he shouted. “You are not my mother! My mother isn’t a beggar!” Then he pushed her, and she fell onto the sand.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
        hint: "Is the problem starting, getting worse, or ending here?",
        explain: "The problem gets <b>worse</b> — this is the <b>complication</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 5, structureOptions: true,
        quote: "Suddenly, the sky grew dark, and a terrible storm came. Huge waves hit the ship until it was wrecked. “Mother, forgive me!” Malin cried. But it was too late. Slowly, he turned into stone.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
        hint: "What finally happens to Malin because of what he did?",
        explain: "The conflict <b>ends</b>: Malin is punished. This is the <b>resolution</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 6, structureOptions: true,
        quote: "Today, on Air Manis Beach near Padang, people can still see a rock that looks like a man kneeling on the sand.",
        prompt: "Which part of the narrative is this sentence?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 3,
        hint: "The word “Today” takes us out of the old story and into our time.",
        explain: "It tells us what we can see today and leads to the lesson: this is the <b>ending / coda</b>.",
      },
      {
        type: "mcq", skill: "Key event", ref: 2,
        prompt: "Which event <b>first</b> changed Malin’s life from poor to rich?",
        options: [
          "He sailed away with a merchant ship.",
          "He married a woman from a rich family.",
          "He sailed back to his old village.",
          "He helped his mother catch fish.",
        ], answer: 0,
        hint: "Malin could not become rich in his small village. What did he have to do first?",
        feedback: { 1: "That happened later — he was already a rich merchant when he married her." },
        explain: "Sailing with the merchant ship was the <b>first big change</b>: it took Malin away from his poor life.",
      },
    ],

    /* ---------------- 🎭 CHARACTER DETECTIVE ---------------- */
    character: [
      {
        type: "mcq", skill: "Trait → Step 1", character: "malin", ref: 1,
        prompt: "Character: <b>Malin as a boy</b> (page 1). Choose the <b>best</b> trait.",
        options: ["hardworking", "lazy", "ungrateful", "arrogant"], answer: 0,
        hint: "Read page 1 only. What did Malin do every day?",
        feedback: { 2: "That describes Malin later, as a rich man. What was he like as a boy?", 3: "That describes Malin later, as a rich man. What was he like as a boy?" },
        explain: "As a boy, Malin helped his mother every day: he was <b>hardworking</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "malin", ref: 1,
        prompt: "You chose <b>hardworking</b>. Which sentence <b>best supports</b> your answer?",
        options: [
          "Every day, he helped his mother catch and sell fish.",
          "He fell on a sharp rock and cut his arm.",
          "He lived in a fishing village near Padang.",
          "He was the only son of a poor widow.",
        ], answer: 0,
        hint: "Evidence must <i>show</i> the trait. Which sentence shows him working?",
        explain: "Character → Trait → <b>Evidence</b>. Helping every day proves he was hardworking.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "mother", ref: 2,
        prompt: "Character: <b>Mande Rubayah</b> when Malin left. Which trait describes her best?",
        options: ["loving", "selfish", "cruel", "greedy"], answer: 0,
        hint: "How did she say goodbye to her son?",
        feedback: { 1: "A selfish mother would keep her son at home. Did she stop him?" },
        explain: "She let him go and hugged him with tears in her eyes: she was <b>loving</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "mother", ref: 2,
        prompt: "Which evidence <b>best proves</b> that Mande Rubayah was loving?",
        options: [
          "With tears in her eyes, she hugged her son.",
          "She lived in a small village near Padang.",
          "She did not have a husband any more.",
          "She heard the news about a big ship.",
        ], answer: 0,
        hint: "Three of these are just facts. Which one shows her feelings for Malin?",
        explain: "Good evidence shows the trait through an <b>action</b>: tears and a hug show love.",
      },
      {
        type: "multi", skill: "Two best traits", character: "malin", ref: 4, pick: 2,
        prompt: "Choose <b>TWO</b> traits that best describe <b>Malin as a rich man</b>.",
        options: ["arrogant", "patient", "ungrateful", "humble", "honest", "generous"], answer: [0, 2],
        hint: "Think about how he treated the mother who loved him and let him go.",
        explain: "He thought he was better than his poor mother (<b>arrogant</b>) and forgot everything she did for him (<b>ungrateful</b>).",
      },
      {
        type: "mcq", skill: "Evidence hunt", character: "malin", ref: 4,
        prompt: "Which evidence <b>best proves</b> that the rich Malin was <b>arrogant</b>?",
        options: [
          "He shouted, “Go away, old woman! My mother isn’t a beggar!”",
          "He sailed back to his old village on his huge ship.",
          "He married a beautiful woman from a wealthy family.",
          "He became a rich merchant with many different ships.",
        ], answer: 0,
        hint: "Being rich is not the same as being arrogant. Which option shows how he <i>treated</i> someone?",
        feedback: { 3: "Being rich is not a trait. Look for how he treated his mother." },
        explain: "He spoke to his poor mother as if she was worth nothing: that shows he was <b>arrogant</b>.",
      },
      {
        type: "mcq", skill: "Evidence hunt", character: "mother", ref: 3,
        prompt: "Mande Rubayah was <b>patient</b>. Which evidence supports this?",
        options: [
          "Every day for years, she stood on the beach and looked at the sea.",
          "She saw the scar on the rich man’s arm and knew him.",
          "She raised her hands to the sky and prayed to God.",
          "She lived in a fishing village with her only son.",
        ], answer: 0,
        hint: "A patient person can wait calmly for a long time. Who waited, and for how long?",
        explain: "She waited <b>every day</b> for <b>years</b>: that proves she was patient.",
      },
      {
        type: "mcq", skill: "Who am I?",
        prompt: "<b>Who am I?</b><ul class='clues'><li>I come from a wealthy family.</li><li>I married a rich merchant.</li><li>I wanted to see my husband’s hometown.</li></ul>",
        options: ["Malin’s wife", "Mande Rubayah", "a village woman", "a member of the crew"], answer: 0,
        hint: "Who said, “I want to see your hometown”?",
        explain: "<b>Malin’s wife</b> asked to see his hometown, so Malin sailed back to his village.",
      },
      {
        type: "sort", skill: "Trait match", layout: "match", capacity: 1,
        prompt: "Match each character with the adjective that fits best.",
        bins: [
          { id: "boy", label: "Malin as a boy", img: "img/stories/malin-kundang/young-malin.webp" },
          { id: "rich", label: "Malin as a rich man", img: "img/stories/malin-kundang/adult-malin.webp" },
          { id: "mother", label: "Mande Rubayah", img: "img/stories/malin-kundang/mande-rubayah.webp" },
          { id: "end", label: "Malin in the storm", img: "img/stories/malin-kundang/adult-malin.webp" },
        ],
        cards: [
          { text: "hardworking", bin: "boy" }, { text: "arrogant", bin: "rich" },
          { text: "patient", bin: "mother" }, { text: "regretful", bin: "end" },
        ],
        hint: "Remember the evidence: who helped every day, who shouted at a poor old woman, who waited on the beach for years, and who cried, “Forgive me!”?",
        explain: "Every trait matches evidence from the text. Well done, detective!",
      },
      {
        type: "sort", skill: "Character change", layout: "change",
        prompt: "How did <b>Malin</b> change? Put each card in <b>BEFORE</b> or <b>AFTER</b> he became rich.",
        bins: [
          { id: "before", label: "BEFORE", sub: "a poor boy" },
          { id: "after", label: "AFTER", sub: "a rich merchant" },
        ],
        cards: [
          { text: "helped his mother every day", bin: "before" },
          { text: "loved his mother very much", bin: "before" },
          { text: "was ashamed of his mother", bin: "after" },
          { text: "pushed his mother away", bin: "after" },
        ],
        hint: "Before: page 1. After: page 4.",
        explain: "Malin changed from a <b>hardworking, loving</b> boy into an <b>arrogant, ungrateful</b> rich man.",
      },
      {
        type: "mcq", skill: "Inference: motive", ref: 4,
        prompt: "Why did Malin say that the old woman was <b>not</b> his mother?",
        options: [
          "He was ashamed of her in front of his wife and crew.",
          "He really did not know her after so many years.",
          "He was angry because she never sent him any news.",
          "He thought she wanted to take his ship and money.",
        ], answer: 0,
        hint: "Read page 4 again. How did he feel about her poor, dirty clothes? Who was watching?",
        feedback: { 1: "The text says he was ashamed of “his old mother” — so he knew who she was." },
        explain: "He knew she was his mother, but he was <b>ashamed</b> of her poor clothes in front of his rich wife and crew.",
      },
      {
        type: "mcq", skill: "Character comparison",
        prompt: "Which sentence best <b>compares</b> Mande Rubayah and the rich Malin?",
        options: [
          "She was loving and patient, but he was arrogant.",
          "Both of them were patient and very loving.",
          "She was arrogant, but he was hardworking.",
          "Both of them were ashamed of being poor.",
        ], answer: 0,
        hint: "Think of one trait for each character. Are they the same or different?",
        explain: "The mother kept her <b>love</b>, but her rich son became <b>arrogant</b>.",
      },
    ],

    /* ---------------- ⏳ PAST TENSE LAB ---------------- */
    grammar: [
      {
        type: "verbs", skill: "Verb transform",
        prompt: "Type the <b>simple past</b> form of each verb from the story.",
        verbs: [
          { base: "live", past: "lived" }, { base: "help", past: "helped" }, { base: "fall", past: "fell" },
          { base: "stand", past: "stood" }, { base: "stop", past: "stopped" }, { base: "send", past: "sent" },
        ],
        hint: "Regular verbs add <b>-ed</b> (live → lived). Careful: stop → stop<b>p</b>ed. Irregular verbs change form (fall → f _ ll).",
        explain: "<b>lived, helped, stopped</b> are regular. <b>fell, stood, sent</b> are irregular.",
      },
      {
        type: "verbs", skill: "Verb transform",
        prompt: "More story verbs! Type the <b>simple past</b> form.",
        verbs: [
          { base: "hurry", past: "hurried" }, { base: "marry", past: "married" }, { base: "pray", past: "prayed" },
          { base: "grow", past: "grew" }, { base: "know", past: "knew" }, { base: "see", past: "saw" },
        ],
        hint: "Consonant + y → <b>-ied</b> (hurry → hurried). Vowel + y → just add <b>-ed</b> (pray → prayed).",
        explain: "Regular: <b>hurried, married, prayed</b>. Irregular: <b>grew, knew, saw</b>.",
      },
      {
        type: "mcq", skill: "Choose the correct verb", ref: 4,
        prompt: "Mande Rubayah ___ the scar on the rich man’s arm.",
        options: ["saw", "see", "seen", "seeing"], answer: 0,
        hint: "The story happened in the past. What is the simple past of <i>see</i>?",
        feedback: { 2: "<i>Seen</i> is the past participle. It needs <i>has</i> or <i>had</i> before it." },
        explain: "<b>see → saw</b> (irregular).",
      },
      {
        type: "mcq", skill: "Was / were", ref: 4,
        prompt: "His wife and crew ___ watching.",
        options: ["was", "were", "is", "be"], answer: 1,
        hint: "“His wife and crew” = they (more than one person).",
        explain: "<b>were</b> for plural subjects (they, his wife and crew). <b>was</b> for I / he / she / it.",
      },
      {
        type: "mcq", skill: "Was / were", ref: 4,
        prompt: "Malin ___ ashamed of his old mother.",
        options: ["were", "was", "are", "been"], answer: 1,
        hint: "“Malin” = he (one person).",
        explain: "He / she / it → <b>was</b>.",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 1,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Once, Malin fall on a sharp rock and cut his arm.",
        wrong: 2, options: ["fell", "falled", "falls", "felt"], answer: 0,
        hint: "Find the verbs. <i>Cut</i> is the same in the past. Check the other verb.",
        stage2: "Now choose the correct past form of <b>fall</b>:",
        feedback2: { 1: "Fall is irregular — we don’t add -ed.", 3: "Careful! <b>felt</b> is the past of <i>feel</i>." },
        explain: "<b>fall → fell</b>: “Once, Malin <b>fell</b> on a sharp rock and cut his arm.”",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 4,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Mande Rubayah heard the news, and she hurry to the beach.",
        wrong: 7, options: ["hurried", "hurryed", "hurries", "hurrying"], answer: 0,
        hint: "There are two verbs. One is correct (heard). Check the other one.",
        stage2: "Choose the correct past form of <b>hurry</b>:",
        feedback2: { 1: "Almost! Consonant + y → change y to <b>i</b> and add -ed." },
        explain: "<b>hurry → hurried</b>. Both verbs in the sentence must be past.",
      },
      {
        type: "fix", skill: "Negative challenge", ref: 5,
        prompt: "This negative sentence has a mistake. Tap the <b>incorrect</b> word.",
        sentence: "Malin didn’t looked at his mother.",
        wrong: 2, options: ["look", "looks", "looking", "to look"], answer: 0,
        hint: "After <b>didn’t</b>, we use the base verb (V1).",
        stage2: "After <b>didn’t</b>, which form is correct?",
        explain: "<b>didn’t + base verb</b>: “Malin didn’t <b>look</b> at his mother.”",
      },
      {
        type: "mcq", skill: "Negative sentence", ref: 2,
        prompt: "Mande Rubayah ___ to lose her only son.",
        options: ["didn’t want", "didn’t wanted", "doesn’t want", "wasn’t want"], answer: 0,
        hint: "Past negative = did not (didn’t) + base verb.",
        feedback: { 1: "Almost! After didn’t, the verb goes back to the base form.", 2: "“doesn’t” is present. The story is in the past." },
        explain: "<b>didn’t + want</b> (base verb).",
      },
      {
        type: "order", skill: "Sentence builder", inline: true, ref: 3,
        prompt: "Build the sentence in the simple past. <span class='tip'>One word is not needed.</span>",
        items: ["Malin", "married", "a beautiful woman", "from a wealthy family."],
        extras: ["marry"],
        hint: "Start with “Malin…”. Which verb form shows the past?",
        explain: "“Malin <b>married</b> a beautiful woman from a wealthy family.” — Subject + <b>V2</b> + object.",
      },
      {
        type: "order", skill: "Question challenge", inline: true, ref: 4,
        prompt: "Build a simple past <b>question</b>. <span class='tip'>One word is not needed.</span>",
        items: ["Did", "Mande Rubayah", "see", "the scar?"],
        extras: ["saw"],
        hint: "Question pattern: <b>Did + subject + base verb…?</b>",
        explain: "“<b>Did</b> Mande Rubayah <b>see</b> the scar?” — Yes, she did!",
      },
      {
        type: "mcq", skill: "Question challenge", ref: 5,
        prompt: "“___ the storm wreck Malin’s ship?” — “Yes, it did.”",
        options: ["Did", "Was", "Does", "Were"], answer: 0,
        hint: "Look at the short answer: “Yes, it <b>did</b>.”",
        explain: "Past questions with a main verb use <b>Did</b>: Did + subject + base verb?",
      },
    ],
  },

  /* ---------------- 🌟 MASTER THE STORY (final) ---------------- */
  final: [
    {
      type: "mcq", skill: "Vocabulary in context", ref: 5,
      quote: "With a broken heart, the old woman raised her hands and prayed.",
      prompt: "What does “with a broken heart” tell us about Mande Rubayah?",
      options: ["She felt very deep sadness.", "She had a pain in her chest.", "She was too tired to stand.", "She felt calm and peaceful."], answer: 0,
      hint: "Her own son said she was not his mother and pushed her. How did she feel inside?",
      feedback: { 1: "Here, “heart” means feelings, not the body." },
      explain: "A <b>broken heart</b> = very deep sadness.",
    },
    {
      type: "mcq", skill: "Simple past", ref: 3,
      prompt: "Meanwhile, Malin worked hard and ___ a rich merchant.",
      options: ["became", "become", "becomes", "becoming"], answer: 0,
      hint: "Look at the first verb: <i>worked</i>. Both verbs must be past.",
      explain: "<b>become → became</b> (irregular).",
    },
    {
      type: "mcq", skill: "Narrative structure", structureOptions: true, ref: 1,
      quote: "Every day, Malin helped his mother catch and sell fish. He was a hardworking boy, and he loved his mother very much.",
      prompt: "Which part of the narrative do these sentences belong to?",
      options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 0,
      hint: "Is there a problem yet, or is the story introducing the characters?",
      explain: "The story introduces Malin and his life: <b>orientation</b>.",
    },
    {
      type: "order", skill: "Sequence of events",
      prompt: "Put these events in order.",
      items: [
        "Malin fell on a sharp rock and cut his arm.",
        "Malin married a woman from a wealthy family.",
        "Mande Rubayah asked softly, “Don’t you remember me?”",
        "Malin cried, “Mother, forgive me!”",
      ],
      hint: "Boyhood → rich life → meeting his mother → the storm.",
      explain: "Great timeline memory!",
    },
    {
      type: "mcq", skill: "Main conflict",
      prompt: "The main conflict is between Malin and his mother. What is it <b>about</b>?",
      options: [
        "Malin was rich, and he was ashamed of his poor mother.",
        "Malin blamed his mother for his father’s early death.",
        "His mother was angry because he never sent any news.",
        "His mother wanted part of his money and his ships.",
      ], answer: 0,
      hint: "Which problem causes the storm and the punishment at the end?",
      feedback: { 2: "The text never says she was angry about that. She was happy to see him: “You came back!”", 3: "She never asked him for money. She only wanted her son." },
      explain: "Malin’s refusal to accept his mother is the <b>main conflict</b>.",
    },
    {
      type: "mcq", skill: "Characterization", ref: 4,
      prompt: "Why can the rich Malin be described as <b>ungrateful</b>?",
      options: [
        "He pushed away the mother who loved him and let him go.",
        "He worked very hard on a merchant ship for many years.",
        "He married a beautiful woman from a wealthy family.",
        "He sailed his huge ship back to his old village one day.",
      ], answer: 0,
      hint: "Ungrateful = not thankful for what others did for you. What did his mother do for him?",
      explain: "His mother loved him and let him go, but he <b>pushed her away</b>: that is ungrateful.",
    },
    {
      type: "mcq", skill: "Cause & effect", ref: 5,
      prompt: "Why was Malin’s ship wrecked?",
      options: [
        "His mother prayed, and a terrible storm came.",
        "The crew sailed too close to the sharp rocks.",
        "The ship was too old and carried too much.",
        "Malin sailed away at night without any lights.",
      ], answer: 0,
      hint: "What happened just after the mother raised her hands?",
      explain: "Cause: the mother’s prayer → Effect: a terrible storm wrecked the ship.",
    },
    {
      type: "mcq", skill: "Turning point",
      prompt: "Which event <b>changed the direction</b> of the story most significantly?",
      options: [
        "Malin denied his mother and pushed her away.",
        "Malin’s wife asked to see his hometown.",
        "The villagers ran to look at the beautiful ship.",
        "Malin married a woman from a wealthy family.",
      ], answer: 0,
      hint: "After which event did the story move from a happy meeting to punishment?",
      feedback: { 1: "That brought Malin home — but the meeting could still end happily. What turned it into a tragedy?" },
      explain: "When Malin <b>denied his mother</b>, a happy meeting became a tragedy: that is the <b>turning point</b>.",
    },
    {
      type: "mcq", skill: "Inference", ref: 3,
      quote: "Every day, Mande Rubayah stood on the beach and looked at the sea.",
      prompt: "What can we infer about Mande Rubayah?",
      options: [
        "She missed Malin and hoped he would come back.",
        "She wanted to buy a merchant ship of her own.",
        "She was looking for fish to sell at the market.",
        "She was afraid of the big waves and the storms.",
      ], answer: 0,
      hint: "The same sentence says Malin never came home. Why would a mother look at the sea every day?",
      explain: "The text does not say it directly, but she was <b>waiting for her son</b>: she missed him and hoped he would return.",
    },
    {
      type: "mcq", skill: "Inference", ref: 5,
      quote: "“Mother, forgive me!” Malin cried.",
      prompt: "What does this show about Malin at the end?",
      options: [
        "He finally understood that he was wrong.",
        "He still did not believe she was his mother.",
        "He wanted his mother to sail away with him.",
        "He was angry with his mother about the storm.",
      ], answer: 0,
      hint: "He called her “Mother” and asked her to forgive him. What changed in his mind?",
      feedback: { 1: "He called her “Mother” — so now he accepts who she is." },
      explain: "By asking for <b>forgiveness</b>, Malin shows he finally understood his mistake — but it was too late.",
    },
    {
      type: "mcq", skill: "Motive", ref: 2,
      prompt: "Why did Malin decide to <b>sail</b> with the merchant ship?",
      options: [
        "He wanted to become rich so they would not be poor.",
        "He wanted to find his father somewhere at sea.",
        "His mother told him to leave the fishing village.",
        "He was tired of his mother and his small village.",
      ], answer: 0,
      hint: "Read what Malin said to his mother on page 2.",
      feedback: { 2: "No — she did not want to lose him. It was Malin’s idea." },
      explain: "“I want to work hard and become rich. Then we won’t be poor any more.” At first, Malin wanted to help his mother too.",
    },
    {
      type: "mcq", skill: "Moral value",
      prompt: "What can readers learn from <i>Malin Kundang</i>?",
      options: [
        "Respect your parents and never forget your roots.",
        "Rich people should never visit their old villages.",
        "Never leave home to look for a better job.",
        "Mothers should not let their children sail away.",
      ], answer: 0,
      hint: "Read the last sentence of the story again.",
      feedback: { 2: "Malin was not punished for leaving home. What was he punished for?" },
      explain: "The moral: we must always <b>respect our parents</b> and never forget where we come from, even when we are rich.",
    },
  ],
});
