/* ==========================================================
   NARRATIVE QUEST — Story file
   Momotaro, the Peach Boy (Folktale · Japan)
   ========================================================== */
NQ.registerStory({
  id: "momotaro",
  title: "Momotaro, the Peach Boy",
  genre: "myths",
  origin: "world",
  region: "Japan",
  country: "Japan",
  level: "A2",
  minutes: 25,
  cover: "img/covers/momotaro.webp",
  summary: "A boy born from a giant peach sets out with a bag of dumplings to stop the ogres of Onigashima. Who will help him on the way?",

  /* ---------- STORY PAGES ---------- */
  pages: [
    {
      text: "Long ago in Japan, a kind old man and a kind old woman lived in a small village. They loved each other very much, but they were sad because they had no children. One day, the old woman went to the river to wash clothes. Suddenly, she saw a giant peach floating down the river. “What a wonderful peach!” she said. She pulled it out of the water and carried it home carefully for her husband.",
      vocab: ["giant", "floating"],
      scene: { art: "img/stories/momotaro/old-woman-finds-peach.webp", fit: "contain", alt: "old woman finds peach", tone: "day", fx: [] },
    },
    {
      text: "That evening, the old man took a knife to cut the peach. But before he could cut it, the peach opened, and a baby boy came out! The old couple were surprised, but they were also very happy. They named the baby Momotaro, which means “Peach Boy”. Momotaro grew up strong, kind and brave. He always helped his parents and worked hard in the fields.",
      vocab: ["couple"],
      scene: { art: "img/stories/momotaro/baby-from-peach.webp", fit: "contain", alt: "baby from peach", tone: "day", fx: [] },
    },
    {
      text: "But the village had a big problem. Ogres called oni lived on Onigashima, Ogre Island. They often sailed to the villages, stole food and treasure, and frightened the people. One day, Momotaro said, “I will go to Onigashima and stop the oni.” His parents were worried, but they did not stop him. The old woman made kibi-dango, sweet millet dumplings, for his journey.",
      vocab: ["ogres", "stole", "treasure", "dumplings"],
      scene: { art: "img/stories/momotaro/oni-raid-village.webp", fit: "contain", alt: "oni raid village", tone: "day", fx: [] },
    },
    {
      text: "On the way, Momotaro met a dog. “Where are you going?” asked the dog. “To Onigashima, to stop the oni,” answered Momotaro. “Can I have one of your dumplings?” asked the dog. “Then I will come with you.” Momotaro shared a dumpling with him, and the dog joined him. Later, a monkey and a pheasant also asked for dumplings. Momotaro shared with them too, and they became his loyal friends.",
      vocab: ["shared", "pheasant"],
      scene: { art: "img/stories/momotaro/momotaro-shares-dumplings.webp", fit: "contain", alt: "momotaro shares dumplings", tone: "day", fx: [] },
    },
    {
      text: "The four friends sailed across the sea to Onigashima. A high wall and a strong gate protected the oni’s castle. First, the pheasant flew over the wall to look around. Next, the monkey climbed the wall and opened the gate. Then Momotaro and the dog ran inside and fought bravely. The oni were big and scary, but the friends worked together. Soon the oni fell to their knees and cried, “Please stop! We surrender!”",
      vocab: ["protected", "surrender"],
      scene: { art: "img/stories/momotaro/attack-on-onigashima.webp", fit: "contain", alt: "attack on onigashima", tone: "day", fx: [] },
    },
    {
      text: "The oni promised never to attack the villages again, and they gave back all the treasure. Momotaro and his friends sailed home with it, and the whole village cheered. Everyone got back the things the oni had taken, and the village was safe again. From that day on, Momotaro lived happily with his parents and his three loyal friends. Courage, kindness and teamwork won in the end.",
      vocab: ["teamwork"],
      scene: { art: "img/stories/momotaro/momotaro-returns-home.webp", fit: "contain", alt: "momotaro returns home", tone: "day", fx: [] },
    },
  ],

  /* ---------- VOCABULARY (highlighted while reading) ---------- */
  vocabulary: [
    { word: "giant", forms: ["giant"], meaning: "very, very big" },
    { word: "floating", forms: ["floating"], meaning: "moving slowly on top of the water" },
    { word: "couple", forms: ["couple"], meaning: "two people who are married or together" },
    { word: "ogres", forms: ["ogres"], meaning: "big, scary monsters in stories" },
    { word: "stole", forms: ["stole"], meaning: "took something that was not theirs (past of steal)" },
    { word: "treasure", forms: ["treasure"], meaning: "gold, jewels and other valuable things" },
    { word: "dumplings", forms: ["dumplings"], meaning: "small, soft balls of cooked dough" },
    { word: "shared", forms: ["shared"], meaning: "gave part of something to another person" },
    { word: "pheasant", forms: ["pheasant"], meaning: "a large bird with a long tail" },
    { word: "protected", forms: ["protected"], meaning: "kept something safe from danger" },
    { word: "surrender", forms: ["surrender"], meaning: "stop fighting and accept that you have lost" },
    { word: "teamwork", forms: ["teamwork"], meaning: "working together to do something" },
  ],

  /* ---------- CHARACTERS ---------- */
  characters: [
    { id: "momotaro", name: "Momotaro", img: "img/stories/momotaro/momotaro.webp", role: "Main character", traits: ["brave", "kind", "generous"],
      evidence: "Momotaro shared a dumpling with him, and the dog joined him." },
    { id: "monkey", name: "The Monkey", img: "img/stories/momotaro/monkey.webp", role: "Helper", traits: ["helpful", "loyal"],
      evidence: "Next, the monkey climbed the wall and opened the gate." },
    { id: "dog", name: "The Dog", img: "img/stories/momotaro/dog.webp", role: "Helper", traits: ["loyal", "brave"],
      evidence: "Then Momotaro and the dog ran inside and fought bravely." },
    { id: "pheasant", name: "The Pheasant", img: "img/stories/momotaro/pheasant.webp", role: "Helper", traits: ["helpful", "loyal"],
      evidence: "First, the pheasant flew over the wall to look around." },
    { id: "couple", name: "The Old Man and the Old Woman", img: "img/stories/momotaro/old-woman.webp", role: "Momotaro’s parents", traits: ["kind", "loving"],
      evidence: "They loved each other very much. The old woman made kibi-dango for his journey." },
    { id: "oni", name: "The Oni", img: "img/stories/momotaro/oni.webp", role: "The ogres of Onigashima", traits: ["cruel", "greedy"],
      evidence: "They often sailed to the villages, stole food and treasure, and frightened the people." },
  ],

  /* Personality words taught in Character Detective */
  traitWords: [
    { word: "brave", meaning: "not afraid to do something difficult or dangerous" },
    { word: "kind", meaning: "friendly and good to other people" },
    { word: "generous", meaning: "happy to give or share things with others" },
    { word: "helpful", meaning: "happy to help other people" },
    { word: "loyal", meaning: "always faithful to a friend or leader" },
    { word: "loving", meaning: "showing that you love someone" },
    { word: "greedy", meaning: "wanting more than you need" },
    { word: "cruel", meaning: "happy to hurt people or animals" },
    { word: "selfish", meaning: "thinking only about yourself" },
    { word: "cowardly", meaning: "too afraid to do what is right" },
  ],

  /* ---------- GENERIC STRUCTURE ---------- */
  structure: {
    orientation: { pages: [1, 2], summary: "A kind old couple with no children found a giant peach. A baby boy came out, and they named him Momotaro. He grew up strong, kind and brave." },
    complication: { pages: [3], summary: "Ogres called oni often attacked the villages and stole food and treasure. Momotaro decided to go to Onigashima to stop them." },
    resolution: { pages: [4, 5], summary: "Momotaro shared his dumplings with a dog, a monkey and a pheasant. They worked together, and the oni surrendered." },
    coda: { pages: [6], summary: "The oni gave back the treasure, the village was safe, and Momotaro lived happily with his parents and friends." },
  },
  mainConflict: "The oni attacked the villages and stole food and treasure, and Momotaro had to stop them.",
  sequence: [
    "The old woman found a giant peach in the river.",
    "A baby boy came out of the peach.",
    "Momotaro decided to stop the oni.",
    "Momotaro shared his dumplings with three animals.",
    "The friends sailed to Onigashima.",
    "The oni surrendered and gave back the treasure.",
  ],
  grammarExamples: {
    regular: ["wash → washed", "share → shared", "climb → climbed"],
    irregular: ["grow → grew", "fly → flew", "steal → stole"],
    was: "The village was safe again.",
    were: "The old couple were surprised.",
    negative: "His parents did not stop him.",
    question: "Did the monkey open the gate?",
  },
  /* Portraits used for feedback bubbles */
  guides: { good: "img/stories/momotaro/momotaro.webp", hint: "img/stories/momotaro/old-man.webp" },
  pastVerbs: [
    { base: "live", past: "lived", type: "regular" }, { base: "love", past: "loved", type: "regular" },
    { base: "pull", past: "pulled", type: "regular" }, { base: "carry", past: "carried", type: "regular" },
    { base: "name", past: "named", type: "regular" }, { base: "share", past: "shared", type: "regular" },
    { base: "climb", past: "climbed", type: "regular" }, { base: "open", past: "opened", type: "regular" },
    { base: "protect", past: "protected", type: "regular" }, { base: "cheer", past: "cheered", type: "regular" },
    { base: "see", past: "saw", type: "irregular" }, { base: "grow", past: "grew", type: "irregular" },
    { base: "steal", past: "stole", type: "irregular" }, { base: "make", past: "made", type: "irregular" },
    { base: "meet", past: "met", type: "irregular" }, { base: "fly", past: "flew", type: "irregular" },
    { base: "fight", past: "fought", type: "irregular" }, { base: "give", past: "gave", type: "irregular" },
  ],

  /* =========================================================
     CHALLENGES
     ========================================================= */
  challenges: {
    /* ---------------- 🔮 WORD HUNTER ---------------- */
    word: [
      {
        type: "mcq", skill: "Meaning in context", ref: 1,
        quote: "Suddenly, she saw a giant peach floating down the river.",
        prompt: "What does <b>floating</b> mean in this sentence?",
        options: ["moving slowly on top of the water", "sinking slowly to the bottom of the water", "flying quickly high above the water", "hiding quietly under the water"], answer: 0,
        hint: "The old woman could see the peach and pull it out of the water. Where was it?",
        feedback: { 1: "If the peach was sinking, the old woman could not see it easily." },
        explain: "<b>Floating</b> = staying on top of the water and moving slowly with it.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 1,
        quote: "Suddenly, she saw a giant peach floating down the river.",
        prompt: "Which word is closest in meaning to <b>giant</b>?",
        options: ["huge", "tiny", "sweet", "old"], answer: 0,
        hint: "A whole baby was inside this peach! How big was it?",
        explain: "<b>Giant</b> = <b>huge</b>, very, very big.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 2,
        quote: "The old couple were surprised, but they were also very happy.",
        prompt: "Who are <b>the old couple</b>?",
        options: ["the old man and the old woman", "the dog and the monkey", "the baby and his mother", "the oni and their king"], answer: 0,
        hint: "A couple is two people who are married. Who lived together in the small village?",
        explain: "A <b>couple</b> = two people who are married. The old couple = the old man and the old woman.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 3,
        quote: "Ogres called oni lived on Onigashima, Ogre Island. They often sailed to the villages, stole food and treasure, and frightened the people.",
        prompt: "From the sentences, what are <b>ogres</b> probably like?",
        options: ["big, scary monsters", "small, friendly animals", "kind, helpful farmers", "brave, young soldiers"], answer: 0,
        hint: "They stole things and frightened people. Are they good or bad?",
        explain: "<b>Ogres</b> are big, scary monsters in stories. In Japan they are called <i>oni</i>.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 3,
        quote: "They often sailed to the villages, stole food and treasure, and frightened the people.",
        prompt: "The oni <b>stole</b> food. This means they…",
        options: ["took food that was not theirs.", "bought food at the village market.", "cooked food for the village people.", "grew food in their own fields."], answer: 0,
        hint: "The people were frightened after the oni came. Did the oni pay for the food?",
        explain: "<b>Steal → stole</b> = take something that is not yours.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 1, image: "img/stories/momotaro/old-woman-finds-peach.webp",
        prompt: "Look at the picture. The old woman saw a giant ___ floating down the river.",
        options: ["peach", "apple", "melon", "mango"], answer: 0,
        hint: "Look at the colour and shape of the fruit. What does Momotaro’s name mean? (Read page 2.)",
        explain: "It was a <b>peach</b> — that is why his name means “Peach Boy”.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 6, image: "img/stories/momotaro/treasure-cart.webp",
        prompt: "Look at the picture. At the end, the oni gave back all the ___.",
        options: ["treasure", "dumplings", "clothes", "animals"], answer: 0,
        hint: "Look at the gold and jewels in the box.",
        feedback: { 1: "The dumplings were Momotaro’s food. The oni did not have them." },
        explain: "<b>Treasure</b> = gold, jewels and other valuable things.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 4,
        quote: "Momotaro shared a dumpling with him, and the dog joined him.",
        prompt: "What does <b>shared</b> mean here?",
        options: ["gave part of his food to someone", "kept all of his food for himself", "threw his food away in the river", "cooked some new food for his trip"], answer: 0,
        hint: "The dog asked for a dumpling. Did he get one?",
        explain: "To <b>share</b> = to give part of what you have to another person.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 5,
        quote: "Soon the oni fell to their knees and cried, “Please stop! We surrender!”",
        prompt: "What did the oni mean when they said, “We surrender”?",
        options: ["We will stop fighting because we lost.", "We will fight harder because we are strong.", "We will run away and hide in our castle.", "We will call more oni to help us fight."], answer: 0,
        hint: "They fell to their knees and said, “Please stop!” Were they winning?",
        explain: "To <b>surrender</b> = to stop fighting and accept that you have lost.",
      },
      {
        type: "mcq", skill: "Antonym", ref: 5,
        quote: "Then Momotaro and the dog ran inside and fought bravely.",
        prompt: "Which word is the <b>opposite</b> of <b>brave</b>?",
        options: ["cowardly", "strong", "bold", "fearless"], answer: 0,
        hint: "Three of these words are close to <i>brave</i>. Find the one that is different.",
        feedback: { 2: "Bold is close in meaning to brave, not the opposite.", 3: "Fearless means “without fear” — that is close to brave." },
        explain: "A <b>brave</b> person is not afraid; a <b>cowardly</b> person is too afraid to act.",
      },
      {
        type: "sort", skill: "Word–meaning match", layout: "match", capacity: 1,
        prompt: "Drag each word to its meaning. <span class='tip'>(Or tap a word, then tap a meaning.)</span>",
        bins: [
          { id: "dumplings", label: "small, soft balls of cooked dough" },
          { id: "pheasant", label: "a large bird with a long tail" },
          { id: "protected", label: "kept something safe from danger" },
          { id: "journey", label: "a long trip from one place to another" },
          { id: "teamwork", label: "working together to do something" },
          { id: "cheered", label: "shouted happily" },
        ],
        cards: [
          { text: "dumplings", bin: "dumplings" }, { text: "pheasant", bin: "pheasant" }, { text: "protected", bin: "protected" },
          { text: "journey", bin: "journey" }, { text: "teamwork", bin: "teamwork" }, { text: "cheered", bin: "cheered" },
        ],
        hint: "Start with the words you are sure about. The old woman made <i>dumplings</i>; a wall and a gate <i>protected</i> the castle.",
        explain: "Great word hunting! You matched all six words.",
      },
    ],

    /* ---------------- 🧩 STORY DETECTIVE ---------------- */
    structure: [
      {
        type: "sort", skill: "Sort the story",
        prompt: "Put each event card in the correct part of the narrative.",
        bins: [
          { id: "orientation", label: "Orientation", img: "img/st-orientation.webp", sub: "Who? Where? When?" },
          { id: "complication", label: "Complication", img: "img/st-complication.webp", sub: "What problem happened?" },
          { id: "resolution", label: "Resolution", img: "img/st-resolution.webp", sub: "How was it solved?" },
          { id: "coda", label: "Ending / Coda", img: "img/st-ending.webp", sub: "What happened afterward?" },
        ],
        cards: [
          { text: "Long ago, a kind old couple lived in a small village in Japan.", bin: "orientation" },
          { text: "A baby boy came out of a giant peach.", bin: "orientation" },
          { text: "Ogres from Onigashima stole food and treasure from the villages.", bin: "complication" },
          { text: "The people of the villages were frightened of the oni.", bin: "complication" },
          { text: "The pheasant and the monkey helped Momotaro get into the castle.", bin: "resolution" },
          { text: "The oni cried, “Please stop! We surrender!”", bin: "resolution" },
          { text: "The friends sailed home, and the whole village cheered.", bin: "coda" },
          { text: "Momotaro lived happily with his parents and his friends.", bin: "coda" },
        ],
        hint: "Orientation introduces the characters and place. Complication = the problem. Resolution = the problem is solved. Coda = life afterward.",
        explain: "The story moves from <b>introduction</b> → <b>problem</b> → <b>solution</b> → <b>happy ending</b>.",
      },
      {
        type: "mcq", skill: "Find the complication", ref: 3,
        prompt: "Which sentence shows the <b>beginning of the complication</b>?",
        options: [
          "“But the village had a big problem.”",
          "“Momotaro grew up strong, kind and brave.”",
          "“The four friends sailed across the sea.”",
          "“The whole village cheered.”",
        ], answer: 0,
        hint: "Look for the small word and the noun that tell us trouble is coming.",
        explain: "“<b>But</b>… a big <b>problem</b>” signals that the complication is starting.",
      },
      {
        type: "mcq", skill: "Find the main conflict", ref: 3,
        prompt: "What is the <b>main conflict</b> in <i>Momotaro, the Peach Boy</i>?",
        options: [
          "Ogres attacked the villages, and Momotaro had to stop them.",
          "Momotaro could not find enough food for his long journey.",
          "The dog, the monkey and the pheasant fought over dumplings.",
          "The old couple did not want Momotaro to leave the village.",
        ], answer: 0,
        hint: "The main conflict is the biggest problem in the story. Why did Momotaro go on his journey?",
        feedback: {
          1: "Not quite. The old woman made dumplings for him — he had food.",
          2: "Look again: the animals did not fight. They became friends.",
          3: "His parents were worried, but they did not stop him. That was not the biggest problem.",
        },
        explain: "The central problem: the <b>oni</b> were attacking the villages, and Momotaro set out to <b>stop them</b>.",
      },
      {
        type: "order", skill: "Story sequence",
        prompt: "Put the events in the correct order. <span class='tip'>Tap an event to add it to the next empty step.</span>",
        items: [
          "The old woman found a giant peach in the river.",
          "A baby boy came out of the peach.",
          "Momotaro decided to stop the oni.",
          "Momotaro shared his dumplings with three animals.",
          "The friends sailed to Onigashima.",
          "The oni surrendered and gave back the treasure.",
        ],
        hint: "Follow the story from the river → the village → the road → the island.",
        explain: "Perfect timeline! Narratives are told in <b>chronological order</b>.",
      },
      {
        type: "mcq", skill: "Cause & effect", ref: 4,
        prompt: "Why did the dog, the monkey and the pheasant join Momotaro?",
        options: [
          "He shared his dumplings with them.",
          "He paid them with gold and jewels.",
          "The old woman asked them to help.",
          "The oni had stolen their homes.",
        ], answer: 0,
        hint: "Read page 4 again. What did each animal ask for?",
        feedback: { 1: "Momotaro did not have treasure yet — he got it from the oni at the end." },
        explain: "Cause: Momotaro <b>shared</b> his dumplings → Effect: the animals joined him and became his friends.",
      },
      {
        type: "sort", skill: "Cause & effect match", layout: "match", capacity: 1,
        prompt: "Match each <b>cause</b> with its <b>effect</b>.",
        bins: [
          { id: "c1", label: "The old woman went to the river to wash clothes.", kicker: "CAUSE" },
          { id: "c2", label: "The oni stole food and treasure from the villages.", kicker: "CAUSE" },
          { id: "c3", label: "The monkey climbed the wall and opened the gate.", kicker: "CAUSE" },
          { id: "c4", label: "The oni surrendered.", kicker: "CAUSE" },
        ],
        cards: [
          { text: "She saw a giant peach in the water.", bin: "c1" },
          { text: "Momotaro decided to go to Onigashima.", bin: "c2" },
          { text: "Momotaro and the dog ran inside.", bin: "c3" },
          { text: "They promised never to attack again.", bin: "c4" },
        ],
        hint: "Ask “What happened <i>because of</i> this?” for each cause.",
        explain: "Each event in a narrative causes the next one. That is how a plot works!",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 1, structureOptions: true,
        quote: "Long ago in Japan, a kind old man and a kind old woman lived in a small village. They loved each other very much, but they were sad because they had no children.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 0,
        hint: "Does it tell us who, where and when?",
        explain: "It introduces the characters, the place and the time: this is the <b>orientation</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 5, structureOptions: true,
        quote: "The oni were big and scary, but the friends worked together. Soon the oni fell to their knees and cried, “Please stop! We surrender!”",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
        hint: "Is the problem with the oni starting, or is it being solved?",
        explain: "The oni stop fighting — the problem is <b>solved</b>. This is the <b>resolution</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 6, structureOptions: true,
        quote: "From that day on, Momotaro lived happily with his parents and his three loyal friends. Courage, kindness and teamwork won in the end.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 3,
        hint: "“From that day on…” tells us about life <i>after</i> the problem was solved.",
        explain: "It tells us what happened afterward and the lesson: this is the <b>ending / coda</b>.",
      },
      {
        type: "mcq", skill: "Climax", ref: 5,
        prompt: "Which moment is the <b>climax</b> — the most exciting part of the story?",
        options: [
          "Momotaro and the dog ran inside and fought the oni.",
          "The old woman made kibi-dango for the journey.",
          "Momotaro met a dog on the way to the island.",
          "The whole village cheered when the friends came home.",
        ], answer: 0,
        hint: "The climax is the moment of greatest danger, just before the problem is solved.",
        explain: "The <b>fight in the oni’s castle</b> is the climax. Right after it, the oni surrender.",
      },
    ],

    /* ---------------- 🎭 CHARACTER DETECTIVE ---------------- */
    character: [
      {
        type: "mcq", skill: "Trait → Step 1", character: "momotaro", ref: 4,
        prompt: "Character: <b>Momotaro</b>. When he met the animals, which trait did he show <b>best</b>?",
        options: ["generous", "greedy", "lazy", "rude"], answer: 0,
        hint: "Each animal asked for a dumpling. What did Momotaro do?",
        feedback: { 1: "A greedy person keeps everything. Did Momotaro keep his dumplings?" },
        explain: "He gave his food to three animals: he was <b>generous</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "momotaro", ref: 4,
        prompt: "You chose <b>generous</b>. Which event <b>best supports</b> your answer?",
        options: [
          "He shared his dumplings with three hungry animals.",
          "He grew up in a small village in Japan.",
          "He sailed across the sea to Onigashima.",
          "He came out of a giant peach as a baby.",
        ], answer: 0,
        hint: "Evidence must <i>show</i> the trait. Which action shows giving to others?",
        explain: "Character → Trait → <b>Evidence</b>. Sharing his food proves he was generous.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "monkey", ref: 5,
        prompt: "Character: <b>The Monkey</b>. Which trait describes him best at Onigashima?",
        options: ["helpful", "lazy", "cowardly", "selfish"], answer: 0,
        hint: "What did the monkey do at the castle wall?",
        explain: "He climbed the wall and opened the gate for his friends: he was <b>helpful</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "monkey", ref: 5,
        prompt: "Which evidence <b>best proves</b> that the monkey was helpful?",
        options: [
          "He climbed the wall and opened the gate.",
          "He asked Momotaro for a dumpling.",
          "He sailed across the sea with his friends.",
          "He lived with Momotaro after the journey.",
        ], answer: 0,
        hint: "Three of these are just facts. Which action helped the team?",
        explain: "Opening the gate let Momotaro and the dog get inside. That is <b>helpful</b>.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "oni", ref: 3,
        prompt: "Character: <b>The Oni</b>. Which trait describes them best?",
        options: ["greedy", "generous", "gentle", "loyal"], answer: 0,
        hint: "What did the oni take from the villages?",
        explain: "They took food and treasure that were not theirs: they were <b>greedy</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "oni", ref: 3,
        prompt: "Which evidence <b>best proves</b> that the oni were greedy?",
        options: [
          "They stole food and treasure from the villages.",
          "They lived on an island called Onigashima.",
          "They had a castle with a high wall and a gate.",
          "They were big and scary to look at.",
        ], answer: 0,
        hint: "Greedy people want more than they need. Which action shows this?",
        feedback: { 3: "Being big and scary is how they looked — not what they did. Look for an action." },
        explain: "Taking things that belong to other people shows they were <b>greedy</b>.",
      },
      {
        type: "multi", skill: "Two best traits", character: "momotaro", ref: 2, pick: 2,
        prompt: "Choose <b>TWO</b> traits that best describe <b>Momotaro</b>.",
        options: ["brave", "selfish", "kind", "lazy", "greedy", "cruel"], answer: [0, 2],
        hint: "Read page 2: “Momotaro grew up strong, ___ and ___.”",
        explain: "The text says he grew up <b>kind</b> and <b>brave</b> — and his actions prove it.",
      },
      {
        type: "mcq", skill: "Who am I?", layout: "portraits", ref: 5,
        prompt: "<b>Who am I?</b><ul class='clues'><li>I asked Momotaro for a dumpling and became his friend.</li><li>At Onigashima, I went over the wall first.</li><li>I did not open the gate. I only looked around.</li></ul>",
        options: [
          { text: "Momotaro", img: "img/stories/momotaro/momotaro.webp" },
          { text: "The Dog", img: "img/stories/momotaro/dog.webp" },
          { text: "The Monkey", img: "img/stories/momotaro/monkey.webp" },
          { text: "The Pheasant", img: "img/stories/momotaro/pheasant.webp" },
        ], answer: 3,
        hint: "Read page 5 again. Who went over the wall <i>first</i>, and who opened the gate <i>next</i>?",
        feedback: { 2: "The monkey climbed the wall <i>next</i> and opened the gate. Who went over it first?" },
        explain: "The <b>pheasant</b> flew over the wall first to look around. Then the monkey climbed the wall and opened the gate.",
      },
      {
        type: "mcq", skill: "Who am I?", layout: "portraits", ref: 4,
        prompt: "<b>Who am I?</b><ul class='clues'><li>I was the first animal to meet Momotaro.</li><li>I asked, “Where are you going?”</li><li>I ran into the castle with Momotaro.</li></ul>",
        options: [
          { text: "Momotaro", img: "img/stories/momotaro/momotaro.webp" },
          { text: "The Dog", img: "img/stories/momotaro/dog.webp" },
          { text: "The Monkey", img: "img/stories/momotaro/monkey.webp" },
          { text: "The Pheasant", img: "img/stories/momotaro/pheasant.webp" },
        ], answer: 1,
        hint: "Read the beginning of page 4. Which animal did Momotaro meet first?",
        explain: "The <b>dog</b> met Momotaro first and fought beside him in the castle.",
      },
      {
        type: "sort", skill: "Trait match", layout: "match", capacity: 1,
        prompt: "Match each character with the personality adjective that fits best.",
        bins: [
          { id: "momotaro", label: "Momotaro", img: "img/stories/momotaro/momotaro.webp" },
          { id: "couple", label: "The old couple", img: "img/stories/momotaro/old-woman.webp" },
          { id: "oni", label: "The oni", img: "img/stories/momotaro/oni.webp" },
          { id: "animals", label: "The dog, the monkey and the pheasant", img: "img/stories/momotaro/dog.webp" },
        ],
        cards: [
          { text: "brave", bin: "momotaro" }, { text: "loving", bin: "couple" },
          { text: "greedy", bin: "oni" }, { text: "loyal", bin: "animals" },
        ],
        hint: "Who went to fight the oni? Who loved each other and their son? Who stole? Who stayed with Momotaro?",
        explain: "Every trait matches evidence from the text. Well done, detective!",
      },
      {
        type: "mcq", skill: "Character comparison",
        prompt: "How were <b>Momotaro</b> and the <b>oni</b> different?",
        options: [
          "Momotaro shared his food, but the oni stole food.",
          "Momotaro lived on an island, but the oni lived in a village.",
          "Momotaro was big and scary, but the oni were small and kind.",
          "Momotaro was greedy, but the oni were generous.",
        ], answer: 0,
        hint: "Think about what each of them did with food.",
        explain: "Momotaro <b>gave</b> food to others; the oni <b>took</b> food from others. Sharing made friends; stealing made enemies.",
      },
      {
        type: "mcq", skill: "Inference", ref: 3,
        quote: "His parents were worried, but they did not stop him.",
        prompt: "Why were Momotaro’s parents <b>worried</b>?",
        options: [
          "They knew the journey to the oni was dangerous.",
          "They thought Momotaro was too lazy to go.",
          "They did not have enough food for the journey.",
          "They wanted Momotaro to work in the fields.",
        ], answer: 0,
        hint: "The story does not say it directly. Where was Momotaro going, and who lived there?",
        feedback: { 2: "The old woman made dumplings for him, so there was food." },
        explain: "The oni were big and scary. Loving parents worry when their child goes somewhere <b>dangerous</b>.",
      },
    ],

    /* ---------------- ⏳ PAST TENSE LAB ---------------- */
    grammar: [
      {
        type: "verbs", skill: "Verb transform",
        prompt: "Type the <b>simple past</b> form of each verb from the story.",
        verbs: [
          { base: "carry", past: "carried" }, { base: "name", past: "named" }, { base: "pull", past: "pulled" },
          { base: "see", past: "saw" }, { base: "grow", past: "grew" }, { base: "steal", past: "stole" },
        ],
        hint: "Regular verbs add <b>-ed</b> (carry → carried: y becomes i). Irregular verbs change form (steal → s _ _ _ e).",
        explain: "<b>carried, named, pulled</b> are regular. <b>saw, grew, stole</b> are irregular.",
      },
      {
        type: "verbs", skill: "Verb transform",
        prompt: "More story verbs! Type the <b>simple past</b> form.",
        verbs: [
          { base: "share", past: "shared" }, { base: "climb", past: "climbed" }, { base: "open", past: "opened" },
          { base: "make", past: "made" }, { base: "meet", past: "met" }, { base: "fight", past: "fought" },
        ],
        hint: "Three are regular (-ed). For the others, look in the story: “made”, “met” and “fought” all appear there.",
        explain: "Regular: <b>shared, climbed, opened</b>. Irregular: <b>made, met, fought</b>.",
      },
      {
        type: "mcq", skill: "Choose the correct verb", ref: 5,
        prompt: "First, the pheasant ___ over the wall to look around.",
        options: ["flew", "flied", "flies", "flown"], answer: 0,
        hint: "<i>Fly</i> is an irregular verb.",
        feedback: { 1: "Fly is irregular — we don’t add -ed.", 3: "<b>flown</b> is the past participle (has flown). We need the simple past." },
        explain: "<b>fly → flew</b> (irregular).",
      },
      {
        type: "mcq", skill: "Was / were", ref: 1,
        prompt: "The old man and the old woman ___ sad because they had no children.",
        options: ["was", "were", "is", "be"], answer: 1,
        hint: "“The old man and the old woman” = they (two people).",
        explain: "<b>were</b> for plural subjects (they, the old man and the old woman). <b>was</b> for I / he / she / it.",
      },
      {
        type: "mcq", skill: "Was / were", ref: 6,
        prompt: "At the end, the village ___ safe again.",
        options: ["were", "was", "are", "been"], answer: 1,
        hint: "“The village” = it (one place).",
        explain: "He / she / it → <b>was</b>.",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 3,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "The old woman maked sweet dumplings for his journey.",
        wrong: 3, options: ["made", "makes", "making", "maded"], answer: 0,
        hint: "Find the verb. <i>Make</i> is irregular.",
        stage2: "Now choose the correct past form of <b>make</b>:",
        feedback2: { 3: "Make is irregular — the past form does not end in -ed." },
        explain: "<b>make → made</b>: “The old woman <b>made</b> sweet dumplings for his journey.”",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 5,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "The monkey climbed the wall and open the gate.",
        wrong: 6, options: ["opened", "opens", "opening", "is opening"], answer: 0,
        hint: "There are two verbs. One is correct (climbed). Check the other one.",
        stage2: "Choose the correct form of <b>open</b>:",
        explain: "<b>open → opened</b>. Both verbs in the sentence must be in the past.",
      },
      {
        type: "fix", skill: "Negative challenge", ref: 3,
        prompt: "This negative sentence has a mistake. Tap the <b>incorrect</b> word.",
        sentence: "His parents didn’t stopped him.",
        wrong: 3, options: ["stop", "stops", "stopping", "to stop"], answer: 0,
        hint: "After <b>didn’t</b>, we use the base verb (V1).",
        stage2: "After <b>didn’t</b>, which form is correct?",
        explain: "<b>didn’t + base verb</b>: “His parents didn’t <b>stop</b> him.”",
      },
      {
        type: "mcq", skill: "Negative sentence", ref: 1,
        prompt: "The old couple ___ any children.",
        options: ["didn’t have", "didn’t had", "don’t have", "weren’t have"], answer: 0,
        hint: "Past negative = did not (didn’t) + base verb.",
        feedback: { 1: "Almost! After didn’t, the verb goes back to the base form.", 2: "“don’t” is present. The story is in the past." },
        explain: "<b>didn’t + have</b> (base verb): “They didn’t have any children.”",
      },
      {
        type: "order", skill: "Sentence builder", inline: true, ref: 4,
        prompt: "Build the sentence in the simple past. <span class='tip'>One chunk is not needed.</span>",
        items: ["Momotaro", "shared", "a dumpling", "with the dog."],
        extras: ["share"],
        hint: "Start with “Momotaro…”. Which verb form shows the past?",
        explain: "“Momotaro <b>shared</b> a dumpling with the dog.” — Subject + <b>V2</b> + object.",
      },
      {
        type: "order", skill: "Question challenge", inline: true, ref: 5,
        prompt: "Build a simple past <b>question</b>. <span class='tip'>One chunk is not needed.</span>",
        items: ["Did", "the monkey", "open", "the gate?"],
        extras: ["opened"],
        hint: "Question pattern: <b>Did + subject + base verb…?</b>",
        explain: "“<b>Did</b> the monkey <b>open</b> the gate?” — Yes, he did!",
      },
      {
        type: "mcq", skill: "Question challenge", ref: 6,
        prompt: "“___ the oni give back the treasure?” — “Yes, they did.”",
        options: ["Did", "Were", "Was", "Do"], answer: 0,
        hint: "Look at the short answer: “Yes, they <b>did</b>.” There is a main verb (give).",
        feedback: { 1: "We use Were with adjectives or -ing (Were they scary?). Here there is a main verb: give." },
        explain: "Past questions with a main verb use <b>Did</b>: Did + subject + base verb?",
      },
    ],
  },

  /* ---------------- 🌟 MASTER THE STORY (final) ---------------- */
  final: [
    {
      type: "mcq", skill: "Vocabulary in context", ref: 5,
      quote: "The oni were big and scary, but the friends worked together.",
      prompt: "What does “the friends <b>worked together</b>” mean?",
      options: ["They helped each other as a team.", "They each fought alone.", "They worked in the fields.", "They argued about the plan."], answer: 0,
      hint: "Remember what each friend did: the pheasant, the monkey, the dog and Momotaro.",
      explain: "Each friend had a job, and they <b>helped each other</b>. That is <b>teamwork</b>.",
    },
    {
      type: "mcq", skill: "Simple past", ref: 1,
      prompt: "The old woman ___ the peach home carefully.",
      options: ["carried", "carries", "carry", "carryed"], answer: 0,
      hint: "Past time. Careful with the spelling: consonant + <b>y</b> → <b>-ied</b>.",
      feedback: { 3: "Almost! When a verb ends in consonant + y, change y to i and add -ed." },
      explain: "<b>carry → carried</b>.",
    },
    {
      type: "mcq", skill: "Narrative structure", structureOptions: true, ref: 3,
      quote: "Ogres called oni lived on Onigashima, Ogre Island. They often sailed to the villages, stole food and treasure, and frightened the people.",
      prompt: "Which part of the narrative do these sentences belong to?",
      options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
      hint: "Is a problem being created or solved?",
      explain: "The oni cause trouble — this is the <b>complication</b>.",
    },
    {
      type: "order", skill: "Sequence of events",
      prompt: "Put these events in order.",
      items: [
        "Momotaro grew up strong, kind and brave.",
        "The old woman made kibi-dango for the journey.",
        "The monkey opened the castle gate.",
        "The whole village cheered.",
      ],
      hint: "Growing up → getting ready → the castle → coming home.",
      explain: "Great timeline memory!",
    },
    {
      type: "mcq", skill: "Main conflict", ref: 1,
      prompt: "At the start, the old couple were sad because they had no children. Why is this <b>not</b> the main conflict of the story?",
      options: [
        "It is solved early, and most of the story is about the oni.",
        "It was never really a problem for the old man and woman.",
        "It happens at the very end, after the fight with the oni.",
        "It is a problem for the animals, not for the old couple.",
      ], answer: 0,
      hint: "When did the old couple get a child? What is the rest of the story about?",
      feedback: { 1: "The text says they were sad because they had no children — so it was a real problem for them." },
      explain: "Their sadness ends on page 2, when Momotaro comes out of the peach. The <b>main conflict</b> — the oni attacking the villages — fills most of the story.",
    },
    {
      type: "mcq", skill: "Characterization", ref: 5,
      prompt: "Why can the dog be described as <b>loyal</b>?",
      options: [
        "He stayed with Momotaro and fought beside him.",
        "He asked Momotaro for one of his dumplings.",
        "He met Momotaro on the way to the island.",
        "He sailed home with the treasure at the end.",
      ], answer: 0,
      hint: "A loyal friend stays with you, even in danger.",
      feedback: { 1: "Asking for food does not show loyalty. What did he do in the dangerous moment?" },
      explain: "He ran into the castle and fought <b>beside</b> Momotaro — a loyal friend.",
    },
    {
      type: "mcq", skill: "Cause & effect", ref: 5,
      prompt: "What happened <b>because</b> the friends worked together?",
      options: [
        "They beat the big, scary oni.",
        "They lost their way at sea.",
        "They ate all the dumplings.",
        "They built a new castle.",
      ], answer: 0,
      hint: "The oni were big and scary, <i>but</i>… What happened soon after?",
      explain: "Teamwork → the oni <b>surrendered</b>. Together, they were stronger than the oni.",
    },
    {
      type: "mcq", skill: "Turning point",
      prompt: "Which event changed the direction of the story <b>most significantly</b>?",
      options: [
        "The oni surrendered and promised to stop attacking.",
        "The old woman made kibi-dango for Momotaro.",
        "The dog asked Momotaro for a dumpling.",
        "The four friends sailed across the sea.",
      ], answer: 0,
      hint: "After which event were the villages finally safe from danger?",
      feedback: { 3: "Sailing was an important step — but the oni were still dangerous. What changed that?" },
      explain: "When the oni <b>surrendered</b>, the story turned from danger to safety.",
    },
    {
      type: "mcq", skill: "Inference", ref: 5,
      prompt: "Why did the pheasant fly over the wall <b>first</b>?",
      options: [
        "To find out where the oni were.",
        "To eat fruit in the oni’s garden.",
        "To fly home to its own nest.",
        "To ask the oni for some food.",
      ], answer: 0,
      hint: "The story says it flew over the wall “to look around”. Why would that help the team?",
      explain: "It checked what was inside so the friends could plan their attack. The text only says “to look around” — you had to <b>infer</b> why.",
    },
    {
      type: "mcq", skill: "Inference: motives", ref: 3,
      prompt: "Why did Momotaro decide to go to Onigashima?",
      options: [
        "He wanted to protect the people from the oni.",
        "He wanted to find a new home on the island.",
        "He wanted to find more peaches in the river.",
        "He wanted to become rich with the oni’s gold.",
      ], answer: 0,
      hint: "Think about what the oni did to the villages, and what kind of person Momotaro was.",
      feedback: { 3: "He brought the treasure home for everyone — he did not go there to become rich." },
      explain: "Momotaro was kind and brave. He wanted to <b>stop the oni</b> and keep people safe.",
    },
    {
      type: "mcq", skill: "Inference", ref: 2,
      prompt: "Why were the old couple so happy when the baby came out of the peach?",
      options: [
        "They had always wanted a child.",
        "They wanted help to fight the oni.",
        "They thought he was very rich.",
        "They wanted someone to eat the peach.",
      ], answer: 0,
      hint: "Read page 1 again. Why were they sad at the start?",
      explain: "They were sad because they had no children. The baby was their <b>wish come true</b>.",
    },
    {
      type: "mcq", skill: "Moral value",
      prompt: "What can readers learn from Momotaro’s journey?",
      options: [
        "Kindness and teamwork can beat a strong enemy.",
        "It is better to keep all your food for yourself.",
        "Only very big and strong people can be heroes.",
        "We should never leave our home or our family.",
      ], answer: 0,
      hint: "How did Momotaro make his friends? How did they win?",
      feedback: { 2: "Momotaro was a boy, and his helpers were small animals — but they won!" },
      explain: "The moral: <b>sharing</b> makes friends, and <b>courage and teamwork</b> can beat even strong enemies.",
    },
  ],
});
