/* ==========================================================
   NARRATIVE QUEST — Story file
   The Selfish Giant (Fairy tale · Oscar Wilde, Ireland / UK)
   An original, simplified retelling for A2–B1 learners.
   ========================================================== */
NQ.registerStory({
  id: "selfish-giant",
  title: "The Selfish Giant",
  genre: "fairy",
  origin: "world",
  region: "Oscar Wilde · Ireland / UK",
  country: "United Kingdom",
  level: "A2–B1",
  minutes: 30,
  cover: "img/stories/selfish-giant/selfish-giant-cover.webp",
  summary: "A giant builds a wall to keep children out of his garden — and winter never leaves. Can a small boy melt his heart?",

  /* ---------- STORY PAGES ---------- */
  pages: [
    {
      text: "Every afternoon after school, the children played in the Giant’s large, lovely garden. It had soft green grass and twelve peach trees. In spring the trees were covered with pink and white blossoms, and in autumn they gave sweet fruit. Birds sang all day long, and the children laughed and played happily. “What a wonderful place!” they said to each other.",
      vocab: ["blossoms"],
      scene: { art: "img/stories/selfish-giant/children-play-in-garden.webp", fit: "contain", alt: "children play in garden", tone: "day", fx: [] },
    },
    {
      text: "One day, the Giant came home. He had been away for seven years. When he saw the children, he shouted in a loud, angry voice, “What are you doing here? This garden belongs to me! Nobody else may play in it.” The frightened children ran away. The selfish Giant did not want to share. He built a high wall around the garden and put up a big sign: KEEP OUT.",
      vocab: ["frightened", "selfish"],
      scene: { art: "img/stories/selfish-giant/giant-shouts-keep-out.webp", fit: "contain", alt: "giant shouts keep out", tone: "day", fx: [] },
    },
    {
      text: "Now the poor children had nowhere to play. Soon spring brought flowers and birds to the whole country. But in the Giant’s garden it was still winter. The birds didn’t sing there because there were no children. Snow lay thick on the grass, and frost turned the trees silver. The North Wind and the hail came to stay. “Why is spring so late this year?” the Giant asked. He felt lonely and cold, and he could not understand why.",
      vocab: ["frost", "lonely"],
      scene: { art: "img/stories/selfish-giant/winter-garden-giant-window.webp", fit: "contain", alt: "winter garden giant window", tone: "day", fx: [] },
    },
    {
      text: "One morning, the Giant heard some lovely music. A little bird was singing outside his window! He looked out. The children had crept in through a small hole in the wall, and they sat in the branches of the trees. The trees were full of blossoms, and spring had returned. Only one corner was still white with snow. There a very small boy was crying, because he could not climb the tree.",
      vocab: ["crept", "branches"],
      scene: { art: "img/stories/selfish-giant/little-boy-crying-in-snow.webp", fit: "contain", alt: "little boy crying in snow", tone: "day", fx: [] },
    },
    {
      text: "When the Giant saw the little boy, his heart melted. “I was so selfish!” he said. “Now I know why spring did not come here.” He went into the garden. The other children ran away, but the little boy did not see him because his eyes were full of tears. The Giant gently lifted him into the tree, and at once it was covered with blossoms. The boy put his arms around the Giant’s neck and kissed him.",
      vocab: ["melted", "gently"],
      scene: { art: "img/stories/selfish-giant/giant-lifts-boy.webp", fit: "contain", alt: "giant lifts boy", tone: "day", fx: [] },
    },
    {
      text: "When the other children saw that the Giant was kind now, they came back. Then the Giant knocked down the wall. “This garden is yours now, children,” he said. After that, they played there every afternoon. But the little boy never came back. “Where is your little friend?” the Giant often asked. Nobody knew, and the Giant missed him very much.",
      vocab: ["knocked down"],
      scene: { art: "img/stories/selfish-giant/giant-knocks-down-wall.webp", fit: "contain", alt: "giant knocks down wall", tone: "day", fx: [] },
    },
    {
      text: "Many years later, when the Giant was old and weak, he saw the little boy under the tree again. The boy smiled and said, “You let me play in your garden once. Today you will come with me to my garden.” That afternoon, the children found the Giant lying peacefully under the tree, covered with white blossoms.",
      vocab: ["weak", "peacefully"],
      scene: { art: "img/stories/selfish-giant/old-giant-with-children.webp", fit: "contain", alt: "old giant with children", tone: "day", fx: [] },
    },
  ],

  /* ---------- VOCABULARY ---------- */
  vocabulary: [
    { word: "blossoms", forms: ["blossoms"], meaning: "flowers on a tree or bush" },
    { word: "frightened", forms: ["frightened"], meaning: "afraid; full of fear" },
    { word: "selfish", forms: ["selfish"], meaning: "thinking only about yourself, not about others" },
    { word: "frost", forms: ["frost"], meaning: "thin white ice that covers things on very cold days" },
    { word: "lonely", forms: ["lonely"], meaning: "sad because you are alone" },
    { word: "crept", forms: ["crept"], meaning: "moved slowly and quietly (past of creep)" },
    { word: "branches", forms: ["branches"], meaning: "the arm-like parts of a tree" },
    { word: "melted", forms: ["melted"], meaning: "became soft (ice → water); here: became kind and loving" },
    { word: "gently", forms: ["gently"], meaning: "in a soft and careful way" },
    { word: "knocked down", forms: ["knocked down"], meaning: "hit something so that it fell to the ground" },
    { word: "weak", forms: ["weak"], meaning: "not strong; without much power in the body" },
    { word: "peacefully", forms: ["peacefully"], meaning: "in a calm and quiet way" },
  ],

  /* ---------- CHARACTERS ---------- */
  characters: [
    { id: "children", name: "The Children", img: "img/stories/selfish-giant/children.webp", role: "They love the garden", traits: ["playful", "cheerful"],
      evidence: "Birds sang all day long, and the children laughed and played happily." },
    { id: "giant", name: "The Giant", img: "img/stories/selfish-giant/giant.webp", role: "Main character (he changes)", traits: ["selfish", "angry", "generous", "kind"],
      evidence: "He shouted, “This garden belongs to me! Nobody else may play in it.” He built a high wall around the garden and put up a big sign: KEEP OUT." },
    { id: "boy", name: "The Little Boy", img: "img/stories/selfish-giant/little-boy.webp", role: "The Giant’s special friend", traits: ["loving", "grateful"],
      evidence: "The boy put his arms around the Giant’s neck and kissed him. Later he said, “You let me play in your garden once. Today you will come with me to my garden.”" },
  ],

  traitWords: [
    { word: "selfish", meaning: "thinking only about yourself" },
    { word: "unfriendly", meaning: "not kind or pleasant to other people" },
    { word: "angry", meaning: "feeling strong and bad about something; ready to shout" },
    { word: "generous", meaning: "happy to give or share what you have" },
    { word: "kind", meaning: "friendly and good to other people" },
    { word: "caring", meaning: "helping and looking after others" },
    { word: "playful", meaning: "liking to play and have fun" },
    { word: "loving", meaning: "showing love and warm feelings" },
    { word: "grateful", meaning: "wanting to thank someone for something good" },
    { word: "greedy", meaning: "wanting more than you need" },
  ],

  /* ---------- GENERIC STRUCTURE ---------- */
  structure: {
    orientation: { pages: [1], summary: "Every afternoon, the children played happily in the Giant’s beautiful garden." },
    complication: { pages: [2, 3], summary: "The Giant came home, shouted at the children and built a high wall. Spring came everywhere except his garden, where it stayed winter." },
    resolution: { pages: [4, 5, 6], summary: "The children crept back in and spring returned. The Giant’s heart melted, he helped the little boy and knocked down the wall." },
    coda: { pages: [7], summary: "Many years later, the little boy came back for the old Giant, and the Giant was found lying peacefully under the blossoms." },
  },
  mainConflict: "The selfish Giant kept the children out of his garden, so spring did not come there and he was lonely.",
  sequence: [
    "The children played happily in the Giant’s garden.",
    "The Giant came home and shouted at the children.",
    "The Giant built a high wall around his garden.",
    "Spring came everywhere except the Giant’s garden.",
    "The children crept in through a hole in the wall.",
    "The Giant lifted the little boy into the tree.",
  ],
  grammarExamples: {
    regular: ["play → played", "shout → shouted", "knock → knocked"],
    irregular: ["build → built", "creep → crept", "feel → felt"],
    was: "In the Giant’s garden, it was still winter.",
    were: "The trees were full of blossoms.",
    negative: "The birds didn’t sing in the Giant’s garden.",
    question: "Did the Giant knock down the wall?",
  },
  guides: { good: "img/stories/selfish-giant/little-boy.webp", hint: "img/stories/selfish-giant/old-giant.webp" },
  pastVerbs: [
    { base: "play", past: "played", type: "regular" }, { base: "shout", past: "shouted", type: "regular" },
    { base: "knock", past: "knocked", type: "regular" }, { base: "lift", past: "lifted", type: "regular" },
    { base: "kiss", past: "kissed", type: "regular" }, { base: "smile", past: "smiled", type: "regular" },
    { base: "laugh", past: "laughed", type: "regular" }, { base: "miss", past: "missed", type: "regular" },
    { base: "build", past: "built", type: "irregular" }, { base: "creep", past: "crept", type: "irregular" },
    { base: "feel", past: "felt", type: "irregular" }, { base: "see", past: "saw", type: "irregular" },
    { base: "hear", past: "heard", type: "irregular" }, { base: "run", past: "ran", type: "irregular" },
    { base: "sit", past: "sat", type: "irregular" }, { base: "find", past: "found", type: "irregular" },
  ],

  /* =========================================================
     CHALLENGES
     ========================================================= */
  challenges: {
    /* ---------------- 🔮 WORD HUNTER ---------------- */
    word: [
      {
        type: "mcq", skill: "Visual vocabulary", ref: 1, image: "img/stories/selfish-giant/blossom-tree.webp",
        prompt: "Look at the picture. In spring, the Giant’s trees were covered with pink and white ___.",
        options: ["blossoms", "branches", "leaves", "fruit"], answer: 0,
        hint: "These are flowers, and they grow on a tree. Find the word on page 1.",
        feedback: { 1: "Branches are the arm-like parts of a tree. The picture shows flowers." },
        explain: "<b>Blossoms</b> are flowers on a tree. The peach trees had pink and white blossoms in spring.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 1, image: "img/icons/peach.webp",
        prompt: "Look at the picture. The Giant’s garden had twelve ___ trees.",
        options: ["peach", "apple", "banana", "coconut"], answer: 0,
        hint: "Read page 1 again: “It had soft green grass and twelve ___ trees.”",
        explain: "The garden had twelve <b>peach</b> trees. They gave sweet fruit in autumn.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 2,
        quote: "“This garden belongs to me! Nobody else may play in it.” The selfish Giant did not want to share.",
        prompt: "The Giant was <b>selfish</b>. A selfish person…",
        options: ["thinks only about himself.", "is afraid of other people.", "likes to share with others.", "works hard every single day."], answer: 0,
        hint: "Look at the words after “selfish”: he “did not want to share”.",
        feedback: { 2: "That is the opposite! The Giant did <i>not</i> want to share." },
        explain: "A <b>selfish</b> person thinks only about himself and does not want to share.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 2,
        quote: "He shouted in a loud, angry voice. The frightened children ran away.",
        prompt: "What does <b>frightened</b> mean?",
        options: ["afraid", "excited", "tired", "curious"], answer: 0,
        hint: "A huge Giant is shouting at them in an angry voice, and they run away. How do they feel?",
        feedback: { 3: "Curious children want to come closer and find out more. These children ran away." },
        explain: "<b>Frightened</b> = afraid. The children were afraid of the angry Giant, so they ran away.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 3,
        quote: "Snow lay thick on the grass, and frost turned the trees silver.",
        prompt: "What is <b>frost</b>?",
        options: ["thin white ice on cold days", "warm light from the morning sun", "heavy rain that falls in autumn", "fresh green leaves in spring"], answer: 0,
        hint: "It was still winter in the garden, and the trees became silver-white.",
        explain: "<b>Frost</b> is thin white ice that covers things when it is very cold.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 3,
        quote: "He felt lonely and cold, and he could not understand why.",
        prompt: "Which phrase is closest in meaning to <b>lonely</b>?",
        options: ["sad because he was alone", "angry because he was busy", "happy because he was free", "tired because he was old"], answer: 0,
        hint: "The children and the birds were gone. Who was with the Giant?",
        explain: "<b>Lonely</b> = sad because you are alone. Nobody came to his garden any more.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 4,
        quote: "The children had crept in through a small hole in the wall.",
        prompt: "How did the children probably come in?",
        options: ["They moved in slowly and quietly.", "They ran in and shouted loudly.", "They climbed over the high wall.", "They opened the big front gate."], answer: 0,
        hint: "<i>Crept</i> is the past of <i>creep</i>. Think of how a cat moves when it is hunting a bird.",
        feedback: { 2: "Look again: they came in <i>through a small hole</i>, not over the wall." },
        explain: "<b>Creep → crept</b> = move slowly and quietly so that nobody notices you.",
      },
      {
        type: "mcq", skill: "Word with two meanings", ref: 5,
        quote: "When the Giant saw the little boy, his heart melted.",
        prompt: "Snow <b>melts</b> in spring. But what does <b>his heart melted</b> mean here?",
        options: ["He suddenly felt soft and kind.", "He suddenly felt hot and ill.", "He suddenly became very angry.", "He suddenly felt tired and weak."], answer: 0,
        hint: "Many words have two meanings. Hard ice becomes soft water. What happened to the Giant’s hard feelings?",
        feedback: { 1: "Not the body! Here <i>melted</i> is about feelings, not temperature." },
        explain: "Here <b>melted</b> means his hard, selfish feelings became soft, kind and loving.",
      },
      {
        type: "mcq", skill: "Antonym", ref: 5,
        quote: "The Giant gently lifted him into the tree.",
        prompt: "Which word is the <b>opposite</b> of <b>gently</b>?",
        options: ["roughly", "carefully", "softly", "quietly"], answer: 0,
        hint: "Three of these words are close in meaning to <i>gently</i>. Find the one that is different.",
        feedback: { 1: "Carefully is close in meaning to gently, not the opposite.", 2: "Softly is close in meaning to gently, not the opposite." },
        explain: "<b>Gently</b> = in a soft, careful way. The opposite is <b>roughly</b>.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 6,
        quote: "Then the Giant knocked down the wall.",
        prompt: "What did the Giant do to the wall?",
        options: ["He made it fall to the ground.", "He made it taller and stronger.", "He painted it a new colour.", "He knocked on it like a door."], answer: 0,
        hint: "After this, the children could come in any time. Was the wall still there?",
        feedback: { 3: "We knock <i>on</i> a door. <b>Knock down</b> means something different." },
        explain: "<b>Knock down</b> = hit something so that it falls. The wall was gone!",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 7,
        quote: "The children found the Giant lying peacefully under the tree.",
        prompt: "The Giant was lying <b>peacefully</b>. This means he looked…",
        options: ["calm and quiet, with no fear", "angry and loud, ready to shout", "busy and quick, full of work", "cold and wet, under the snow"], answer: 0,
        hint: "Think of the word <i>peace</i>. The tree was covered with white blossoms, not snow.",
        explain: "<b>Peacefully</b> = in a calm and quiet way.",
      },
      {
        type: "sort", skill: "Word–meaning match", layout: "match", capacity: 1,
        prompt: "Drag each word to its meaning. <span class='tip'>(Or tap a word, then tap a meaning.)</span>",
        bins: [
          { id: "selfish", label: "thinking only about yourself" },
          { id: "branches", label: "the arm-like parts of a tree" },
          { id: "weak", label: "not strong; without much power" },
          { id: "crept", label: "moved slowly and quietly" },
          { id: "frightened", label: "full of fear" },
          { id: "lonely", label: "sad because you are alone" },
        ],
        cards: [
          { text: "selfish", bin: "selfish" }, { text: "branches", bin: "branches" }, { text: "weak", bin: "weak" },
          { text: "crept", bin: "crept" }, { text: "frightened", bin: "frightened" }, { text: "lonely", bin: "lonely" },
        ],
        hint: "Start with the words you are sure about. The children sat in the <i>branches</i>; the old Giant was <i>weak</i>.",
        explain: "Great word hunting! You matched all six words.",
      },
    ],

    /* ---------------- 🧩 STORY DETECTIVE ---------------- */
    structure: [
      {
        type: "sort", skill: "Sort the story",
        prompt: "Put each event card in the correct part of the narrative.",
        bins: [
          { id: "orientation", label: "Orientation", img: "img/st-orientation.webp", sub: "Who? Where? When?" },
          { id: "complication", label: "Complication", img: "img/st-complication.webp", sub: "What problem happened?" },
          { id: "resolution", label: "Resolution", img: "img/st-resolution.webp", sub: "How was it solved?" },
          { id: "coda", label: "Ending / Coda", img: "img/st-ending.webp", sub: "What happened afterward?" },
        ],
        cards: [
          { text: "The children played in the Giant’s garden after school.", bin: "orientation" },
          { text: "The garden had soft grass, peach trees and singing birds.", bin: "orientation" },
          { text: "The Giant shouted at the children and built a high wall.", bin: "complication" },
          { text: "Spring came everywhere, but the Giant’s garden stayed cold.", bin: "complication" },
          { text: "The Giant lifted the little boy into the tree.", bin: "resolution" },
          { text: "The Giant knocked down the wall and shared his garden.", bin: "resolution" },
          { text: "Many years later, the little boy came back for the old Giant.", bin: "coda" },
          { text: "The children found the Giant under the tree, covered with blossoms.", bin: "coda" },
        ],
        hint: "Orientation introduces the characters and place. Complication = problems. Resolution = the problem is solved. Coda = what happened much later.",
        explain: "The story moves from <b>a happy garden</b> → <b>a selfish wall and winter</b> → <b>a melted heart</b> → <b>a peaceful ending</b>.",
      },
      {
        type: "mcq", skill: "Find the complication", ref: 2,
        prompt: "Which sentence shows the <b>beginning of the complication</b>?",
        options: [
          "“One day, the Giant came home.”",
          "“Birds sang all day long.”",
          "“The boy put his arms around the Giant’s neck.”",
          "“Then the Giant knocked down the wall.”",
        ], answer: 0,
        hint: "“One day…” often tells us that something new is going to happen. Who arrives and brings a problem?",
        explain: "When the Giant <b>came home</b>, the children’s happy days in the garden ended. The problem starts here.",
      },
      {
        type: "mcq", skill: "Find the main conflict", ref: 3,
        prompt: "What is the <b>main conflict</b> in <i>The Selfish Giant</i>?",
        options: [
          "The selfish Giant kept the children out, so spring never came to his garden.",
          "The children damaged the Giant’s peach trees, so he had to protect them.",
          "The Giant was lonely because he had been away for seven years.",
          "The little boy was lost, and the Giant could not find him anywhere.",
        ], answer: 0,
        hint: "The main conflict is the biggest problem. It starts on page 2 and is solved on pages 4–6.",
        feedback: {
          1: "Look again: the children only played in the garden. The story does not say they damaged anything.",
          3: "The Giant missed the little boy, but that happened after the main problem was solved.",
        },
        explain: "The Giant’s selfishness shut the children out — and with them, spring. That is the <b>main conflict</b>.",
      },
      {
        type: "order", skill: "Story sequence",
        prompt: "Put the events in the correct order. <span class='tip'>Tap an event to add it to the next empty step.</span>",
        items: [
          "The children played happily in the Giant’s garden.",
          "The Giant came home and shouted at the children.",
          "The Giant built a high wall around his garden.",
          "Spring came everywhere except the Giant’s garden.",
          "The children crept in through a hole in the wall.",
          "The Giant lifted the little boy into the tree.",
        ],
        hint: "Happy garden → angry Giant → wall → long winter → children come back → kindness.",
        explain: "Perfect timeline! Narratives are told in <b>chronological order</b>.",
      },
      {
        type: "mcq", skill: "Cause & effect", ref: 3,
        prompt: "According to the story, why did the birds not sing in the Giant’s garden?",
        options: [
          "There were no children in the garden.",
          "The Giant shouted at them every day.",
          "The high wall blocked all the sunshine.",
          "The birds were afraid of the North Wind.",
        ], answer: 0,
        hint: "Read page 3: “The birds didn’t sing there <b>because</b>…”",
        feedback: { 2: "The story does not say this. Look for the word <b>because</b> on page 3." },
        explain: "Cause: no children in the garden → Effect: the birds didn’t sing, and spring didn’t come.",
      },
      {
        type: "sort", skill: "Cause & effect match", layout: "match", capacity: 1,
        prompt: "Match each <b>cause</b> with its <b>effect</b>.",
        bins: [
          { id: "c1", label: "The Giant saw the children in his garden.", kicker: "CAUSE" },
          { id: "c2", label: "The Giant built a high wall.", kicker: "CAUSE" },
          { id: "c3", label: "The Giant lifted the little boy into the tree.", kicker: "CAUSE" },
          { id: "c4", label: "The Giant knocked down the wall.", kicker: "CAUSE" },
        ],
        cards: [
          { text: "He shouted at them in an angry voice.", bin: "c1" },
          { text: "The children had nowhere to play.", bin: "c2" },
          { text: "At once, the tree was covered with blossoms.", bin: "c3" },
          { text: "The children played there every afternoon.", bin: "c4" },
        ],
        hint: "Ask “What happened <i>because of</i> this?” for each cause.",
        explain: "Each event causes the next one. That is how a plot works!",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 3, structureOptions: true,
        quote: "Soon spring brought flowers and birds to the whole country. But in the Giant’s garden it was still winter. The birds didn’t sing there because there were no children.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
        hint: "Is the problem starting, getting worse, or being solved here?",
        explain: "Winter will not leave the garden — the problem is getting <b>worse</b>. This is the <b>complication</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 5, structureOptions: true,
        quote: "The Giant gently lifted him into the tree, and at once it was covered with blossoms. The boy put his arms around the Giant’s neck and kissed him.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
        hint: "What happens to the last cold tree here?",
        explain: "The last cold corner becomes spring and the Giant is kind — the problem is <b>solved</b>: <b>resolution</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 7, structureOptions: true,
        quote: "Many years later, when the Giant was old and weak, he saw the little boy under the tree again.",
        prompt: "Which part of the narrative is this sentence?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 3,
        hint: "“Many years later…” — is this before, during or long after the main problem?",
        explain: "It tells us what happened long after the problem was solved: the <b>ending / coda</b>.",
      },
      {
        type: "mcq", skill: "Key event", ref: 4,
        prompt: "Which event <b>first</b> brought spring back to the Giant’s garden?",
        options: [
          "The children crept in through a small hole in the wall.",
          "The Giant asked, “Why is spring so late this year?”",
          "The North Wind and the hail came to stay in the garden.",
          "The Giant put up a big sign that said KEEP OUT.",
        ], answer: 0,
        hint: "Read page 4. What did the Giant see when he looked out of his window?",
        feedback: { 1: "Asking a question did not change the weather. Something else happened in the garden." },
        explain: "When the <b>children came back</b>, the trees blossomed and spring returned. There were no children before, so there was no spring.",
      },
    ],

    /* ---------------- 🎭 CHARACTER DETECTIVE ---------------- */
    character: [
      {
        type: "mcq", skill: "Trait → Step 1", character: "giant", ref: 2,
        prompt: "Character: <b>The Giant</b> at the <b>start</b> of the story. Choose the <b>best</b> trait.",
        options: ["selfish", "generous", "patient", "shy"], answer: 0,
        hint: "What did he say about his garden? Did he want to share it?",
        feedback: { 1: "Not yet! A generous person shares. At first, the Giant wanted the garden only for himself." },
        explain: "He wanted the garden only for himself: at first he was <b>selfish</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "giant", ref: 2,
        prompt: "You chose <b>selfish</b>. Which event <b>best supports</b> your answer?",
        options: [
          "He built a high wall and put up a KEEP OUT sign.",
          "He came home after seven years away from his garden.",
          "He felt lonely and cold in the long winter.",
          "He had a large garden with twelve peach trees.",
        ], answer: 0,
        hint: "Evidence must <i>show</i> the trait. Which action kept other people away from what he had?",
        explain: "Character → Trait → <b>Evidence</b>. The wall and the sign kept everyone out of his garden.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "giant", ref: 6,
        prompt: "Character: <b>The Giant</b> at the <b>end</b> of the story. Which trait describes him best now?",
        options: ["generous", "greedy", "stubborn", "cruel"], answer: 0,
        hint: "What did he say to the children after the wall came down?",
        explain: "He gave his garden to the children: now he was <b>generous</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "giant", ref: 6,
        prompt: "Which evidence <b>best proves</b> that the Giant became generous?",
        options: [
          "He knocked down the wall and gave the children the garden.",
          "He often asked where the little boy had gone.",
          "He heard a little bird singing outside his window.",
          "He was old and weak when the little boy came back.",
        ], answer: 0,
        hint: "A generous person gives or shares. Which action shows sharing?",
        explain: "“<b>This garden is yours now, children.</b>” He shared everything he once kept for himself.",
      },
      {
        type: "sort", skill: "Character change", layout: "change",
        prompt: "The Giant <b>changed</b>. Put each card in <b>BEFORE</b> or <b>AFTER</b> his heart melted.",
        bins: [
          { id: "before", label: "BEFORE", sub: "selfish and angry" },
          { id: "after", label: "AFTER", sub: "generous and kind" },
        ],
        cards: [
          { text: "shouted at the children", bin: "before" },
          { text: "built a high wall", bin: "before" },
          { text: "wanted the garden only for himself", bin: "before" },
          { text: "missed his little friend very much", bin: "after" },
          { text: "knocked down the wall", bin: "after" },
          { text: "let the children play every afternoon", bin: "after" },
        ],
        hint: "Before: he kept people out. After: he let people in and cared about them.",
        explain: "The Giant changed from <b>selfish and unfriendly</b> → <b>generous, caring and kind</b>. This is a real change of character!",
      },
      {
        type: "mcq", skill: "Cause of change", character: "giant", ref: 5,
        prompt: "What made the Giant’s heart <b>melt</b>?",
        options: [
          "He saw a very small boy crying under a snowy tree.",
          "He heard a little bird singing outside his window.",
          "He saw the children in the branches of the trees.",
          "He saw that the North Wind was still in his garden.",
        ], answer: 0,
        hint: "Read the first sentence of page 5: “When the Giant saw ___, his heart melted.”",
        feedback: { 1: "The bird made him look out of the window — but his heart melted when he saw someone.", 2: "He saw them first, but read page 5: his heart melted when he saw someone else." },
        explain: "Seeing the <b>crying little boy</b> in the last cold corner changed the Giant’s heart.",
      },
      {
        type: "mcq", skill: "Change → Evidence", character: "giant", ref: 5,
        prompt: "Which words show that the Giant <b>understood his mistake</b>?",
        options: [
          "“I was so selfish!”",
          "“What are you doing here?”",
          "“This garden belongs to me!”",
          "“Why is spring so late this year?”",
        ], answer: 0,
        hint: "Find the words where the Giant talks honestly about himself.",
        feedback: { 3: "Here he still did not understand why winter stayed. He learned the answer later." },
        explain: "“I was so selfish!” — he saw his own mistake. After this, he acted with kindness.",
      },
      {
        type: "multi", skill: "Two best traits", character: "boy", ref: 7, pick: 2,
        prompt: "Choose <b>TWO</b> traits that best describe <b>the little boy</b>.",
        options: ["loving", "grateful", "greedy", "rude", "lazy", "boastful"], answer: [0, 1],
        hint: "What did he do after the Giant lifted him into the tree? What did he say many years later?",
        explain: "He kissed the Giant (<b>loving</b>) and remembered the Giant’s kindness: “You let me play in your garden once” (<b>grateful</b>).",
      },
      {
        type: "mcq", skill: "Who am I?",
        prompt: "<b>Who am I?</b><ul class='clues'><li>I did not see the Giant coming because of my tears.</li><li>I put my arms around someone’s neck.</li><li>I came back many years later.</li></ul>",
        options: ["The little boy", "The Giant", "The North Wind", "A little bird"], answer: 0,
        hint: "Who was crying in the cold corner of the garden?",
        explain: "The <b>little boy</b> cried, kissed the Giant and came back when the Giant was old.",
      },
      {
        type: "sort", skill: "Trait match", layout: "match", capacity: 1,
        prompt: "Match each character with the personality adjective that fits best.",
        bins: [
          { id: "giant1", label: "The Giant (at the start)", img: "img/stories/selfish-giant/giant.webp" },
          { id: "giant2", label: "The Giant (at the end)", img: "img/stories/selfish-giant/giant.webp" },
          { id: "children", label: "The Children", img: "img/stories/selfish-giant/children.webp" },
          { id: "boy", label: "The Little Boy", img: "img/stories/selfish-giant/little-boy.webp" },
        ],
        cards: [
          { text: "selfish", bin: "giant1" }, { text: "generous", bin: "giant2" },
          { text: "playful", bin: "children" }, { text: "loving", bin: "boy" },
        ],
        hint: "Who built a wall? Who gave the garden away? Who laughed and played? Who kissed the Giant?",
        explain: "Every trait matches evidence from the text. Well done, detective!",
      },
      {
        type: "mcq", skill: "Character comparison",
        prompt: "At the <b>start</b> of the story, how were the children and the Giant <b>different</b>?",
        options: [
          "The children were happy and playful; the Giant was selfish and angry.",
          "The children were selfish and angry; the Giant was happy and playful.",
          "The children were lazy and rude; the Giant was kind and generous.",
          "The children were shy and quiet; the Giant was calm and patient.",
        ], answer: 0,
        hint: "Compare page 1 (the children in the garden) with page 2 (the Giant comes home).",
        explain: "The children <b>laughed and played happily</b>; the Giant <b>shouted</b> and kept everyone out.",
      },
      {
        type: "mcq", skill: "Inference: motives", ref: 4,
        quote: "The children had crept in through a small hole in the wall.",
        prompt: "Why did the children probably creep in quietly?",
        options: [
          "They did not want the angry Giant to see them.",
          "They wanted to surprise the Giant with a present.",
          "The Giant told them to use the small hole.",
          "They were too tired to run into the garden.",
        ], answer: 0,
        hint: "The story does not say this directly. Remember how the Giant treated them on page 2.",
        explain: "The Giant had shouted at them before, so they came in <b>quietly and secretly</b>. This is an inference.",
      },
    ],

    /* ---------------- ⏳ PAST TENSE LAB ---------------- */
    grammar: [
      {
        type: "verbs", skill: "Verb transform",
        prompt: "Type the <b>simple past</b> form of each verb from the story.",
        verbs: [
          { base: "play", past: "played" }, { base: "shout", past: "shouted" }, { base: "build", past: "built" },
          { base: "see", past: "saw" }, { base: "feel", past: "felt" }, { base: "run", past: "ran" },
        ],
        hint: "Regular verbs add <b>-ed</b> (play → played). Irregular verbs change form (build → bu _ _ t).",
        explain: "<b>played, shouted</b> are regular. <b>built, saw, felt, ran</b> are irregular.",
      },
      {
        type: "verbs", skill: "Verb transform",
        prompt: "More story verbs! Type the <b>simple past</b> form.",
        verbs: [
          { base: "lift", past: "lifted" }, { base: "kiss", past: "kissed" }, { base: "smile", past: "smiled" },
          { base: "hear", past: "heard" }, { base: "sit", past: "sat" }, { base: "find", past: "found" },
        ],
        hint: "Three are regular (-ed). The other three are irregular — you can find them in the story.",
        explain: "Regular: <b>lifted, kissed, smiled</b>. Irregular: <b>heard, sat, found</b>.",
      },
      {
        type: "mcq", skill: "Choose the correct verb", ref: 2,
        prompt: "The Giant ___ a high wall around the garden.",
        options: ["built", "build", "builded", "building"], answer: 0,
        hint: "The story happened in the past. <i>Build</i> is an irregular verb.",
        feedback: { 2: "Build is irregular — we don’t add -ed." },
        explain: "<b>build → built</b> (irregular).",
      },
      {
        type: "mcq", skill: "Was / were", ref: 4,
        prompt: "The trees ___ full of blossoms again.",
        options: ["was", "were", "is", "be"], answer: 1,
        hint: "“The trees” is plural (more than one). Which past form goes with plural subjects?",
        explain: "<b>were</b> for plural subjects (they, the trees). <b>was</b> for I / he / she / it.",
      },
      {
        type: "mcq", skill: "Was / were", ref: 3,
        prompt: "In the Giant’s garden, it ___ still winter.",
        options: ["were", "was", "are", "be"], answer: 1,
        hint: "The subject is <i>it</i> (one thing).",
        explain: "He / she / it → <b>was</b>.",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 4,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "The children creeped in through a small hole in the wall.",
        wrong: 2, options: ["crept", "creep", "creeping", "creeps"], answer: 0,
        hint: "Find the verb. Is <i>creep</i> a regular verb?",
        stage2: "Now choose the correct past form of <b>creep</b>:",
        explain: "<b>creep → crept</b>: “The children <b>crept</b> in through a small hole.”",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 5,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "The Giant lifted the boy into the tree, and the boy kiss him.",
        wrong: 11, options: ["kissed", "kisses", "kissing", "to kiss"], answer: 0,
        hint: "There are two verbs. One is correct (lifted). Check the other one.",
        stage2: "Choose the correct form of <b>kiss</b>:",
        explain: "<b>kiss → kissed</b>. Both verbs in the sentence must be in the past.",
      },
      {
        type: "fix", skill: "Negative challenge", ref: 3,
        prompt: "This negative sentence has a mistake. Tap the <b>incorrect</b> word.",
        sentence: "The birds didn’t sang in the Giant’s garden.",
        wrong: 3, options: ["sing", "sung", "singing", "sings"], answer: 0,
        hint: "After <b>didn’t</b>, we use the base verb (V1).",
        stage2: "After <b>didn’t</b>, which form is correct?",
        feedback2: { 1: "<b>sung</b> is the past participle (have sung). After didn’t, use the base verb." },
        explain: "<b>didn’t + base verb</b>: “The birds didn’t <b>sing</b> in the Giant’s garden.”",
      },
      {
        type: "mcq", skill: "Negative sentence", ref: 3,
        prompt: "For a long time, spring ___ to the Giant’s garden.",
        options: ["didn’t come", "didn’t came", "doesn’t come", "wasn’t come"], answer: 0,
        hint: "Past negative = did not (didn’t) + base verb.",
        feedback: { 1: "Almost! After didn’t, the verb goes back to the base form.", 2: "“doesn’t” is present. The story is in the past." },
        explain: "<b>didn’t + come</b> (base verb).",
      },
      {
        type: "order", skill: "Sentence builder", inline: true, ref: 4,
        prompt: "Build the sentence in the simple past. <span class='tip'>One word is not needed.</span>",
        items: ["The children", "sat", "in the branches", "of the trees."],
        extras: ["sit"],
        hint: "Start with “The children…”. Which verb form shows the past?",
        explain: "“The children <b>sat</b> in the branches of the trees.” — <b>sit → sat</b> (irregular).",
      },
      {
        type: "order", skill: "Question challenge", inline: true, ref: 6,
        prompt: "Build a simple past <b>question</b>. <span class='tip'>One word is not needed.</span>",
        items: ["Did", "the Giant", "knock down", "the wall?"],
        extras: ["knocked down"],
        hint: "Question pattern: <b>Did + subject + base verb…?</b>",
        explain: "“<b>Did</b> the Giant <b>knock down</b> the wall?” — Yes, he did!",
      },
      {
        type: "mcq", skill: "Question challenge", ref: 3,
        prompt: "“___ the Giant lonely in the long winter?” — “Yes, he was.”",
        options: ["Was", "Did", "Were", "Does"], answer: 0,
        hint: "Look at the short answer: “Yes, he <b>was</b>.” There is no main verb — <i>lonely</i> is an adjective.",
        feedback: { 1: "We use <b>Did</b> with a main verb (Did he feel…?). Here there is only an adjective." },
        explain: "With adjectives, past questions use <b>Was / Were</b>: “<b>Was</b> the Giant lonely?”",
      },
    ],
  },

  /* ---------------- 🌟 MASTER THE STORY (final) ---------------- */
  final: [
    {
      type: "mcq", skill: "Vocabulary in context", ref: 5,
      quote: "The Giant gently lifted him into the tree, and at once it was covered with blossoms.",
      prompt: "What does <b>at once</b> mean here?",
      options: ["immediately", "one day later", "very slowly", "once a year"], answer: 0,
      hint: "Did the tree wait, or did it blossom right after the boy sat in it?",
      feedback: { 3: "<i>Once</i> can mean one time, but <b>at once</b> is different." },
      explain: "<b>At once</b> = immediately, right away.",
    },
    {
      type: "mcq", skill: "Simple past", ref: 4,
      prompt: "One morning, the Giant ___ some lovely music.",
      options: ["heard", "hears", "hear", "hearing"], answer: 0,
      hint: "Past time: “One morning…”",
      explain: "<b>hear → heard</b> (irregular).",
    },
    {
      type: "mcq", skill: "Narrative structure", structureOptions: true, ref: 2,
      quote: "He built a high wall around the garden and put up a big sign: KEEP OUT.",
      prompt: "Which part of the narrative does this sentence belong to?",
      options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
      hint: "Does this sentence create a problem for the children, or solve one?",
      explain: "The wall takes the garden away from the children — a problem: <b>complication</b>.",
    },
    {
      type: "order", skill: "Sequence of events",
      prompt: "Put these events in order.",
      items: [
        "The frightened children ran away.",
        "The Giant asked, “Why is spring so late?”",
        "A little bird sang outside the Giant’s window.",
        "The Giant asked the children about their little friend.",
      ],
      hint: "Angry Giant → long winter → spring comes back → missing the boy.",
      explain: "Great timeline memory!",
    },
    {
      type: "mcq", skill: "Main conflict",
      prompt: "Which problem continues from the <b>complication</b> until the <b>resolution</b>?",
      options: [
        "The Giant’s selfishness keeps the children and spring out.",
        "The children cannot find a way home from their school.",
        "The North Wind wants to take the garden from him.",
        "The birds are too frightened to fly over the wall.",
      ], answer: 0,
      hint: "Which problem starts with the wall and ends when the wall comes down?",
      explain: "The <b>main conflict</b>: selfishness keeps the children out, so winter stays in the garden.",
    },
    {
      type: "mcq", skill: "Characterization", ref: 5,
      prompt: "Why can the Giant at the end be described as <b>caring</b>?",
      options: [
        "He gently lifted the crying boy into the tree.",
        "He felt lonely and cold during the long winter.",
        "He heard the music of a little bird one morning.",
        "He asked why spring was so late that year.",
      ], answer: 0,
      hint: "A caring person helps someone who has a problem. Who had a problem?",
      explain: "He saw the boy’s problem and helped him <b>gently</b> — that is <b>caring</b>.",
    },
    {
      type: "mcq", skill: "Cause & effect", ref: 6,
      prompt: "Why did the other children come back to the garden?",
      options: [
        "They saw that the Giant was kind now.",
        "They heard that the Giant was very ill.",
        "They wanted to find their little friend.",
        "The North Wind had left the garden.",
      ], answer: 0,
      hint: "Read the first sentence of page 6.",
      explain: "Cause: they saw the Giant was <b>kind</b> now → Effect: they came back.",
    },
    {
      type: "mcq", skill: "Turning point",
      prompt: "Which event changed the direction of the story <b>most significantly</b>?",
      options: [
        "The Giant saw the crying boy and lifted him into the tree.",
        "The Giant built a high wall and put up a KEEP OUT sign.",
        "The North Wind and the hail came to stay in the garden.",
        "The little boy came back when the Giant was old and weak.",
      ], answer: 0,
      hint: "Think: after which event did the Giant stop being selfish and start being kind?",
      feedback: { 1: "The wall started the problem. Which event turned the story toward kindness?" },
      explain: "When the Giant helped the boy, the story turned from <b>winter and anger</b> to <b>spring and kindness</b>.",
    },
    {
      type: "mcq", skill: "Inference", ref: 3,
      quote: "“Why is spring so late this year?” the Giant asked. He felt lonely and cold, and he could not understand why.",
      prompt: "What does this tell us about the Giant at this point?",
      options: [
        "He did not see that his selfishness was the problem.",
        "He knew the children were the reason, but he was proud.",
        "He wanted winter to stay because he liked the snow.",
        "He thought the birds had taken spring away.",
      ], answer: 0,
      hint: "The answer is not written directly. Later he says, “Now I know why spring did not come here.” What did he <i>not</i> know before?",
      explain: "He <b>could not understand</b> — he did not yet see that shutting out the children kept spring away.",
    },
    {
      type: "mcq", skill: "Inference", ref: 7,
      quote: "That afternoon, the children found the Giant lying peacefully under the tree, covered with white blossoms.",
      prompt: "What does the ending most likely suggest about the Giant?",
      options: [
        "The Giant’s long life came to a calm and happy end.",
        "The Giant was hiding from the children in the garden.",
        "The Giant was angry again and waiting for the boy.",
        "The Giant was working hard to plant new flowers.",
      ], answer: 0,
      hint: "He was old and weak, the boy invited him to “my garden”, and he looked peaceful. The story does not say it directly.",
      explain: "The gentle words (peacefully, white blossoms) suggest the Giant’s life ended <b>calmly and happily</b>, as a reward for his kindness.",
    },
    {
      type: "mcq", skill: "Decision", ref: 6,
      prompt: "Why did the Giant decide to <b>knock down the wall</b>?",
      options: [
        "He wanted to share his garden with the children.",
        "The wall was old and was falling down anyway.",
        "He was angry that the children got in again.",
        "He wanted to make the wall higher and stronger.",
      ], answer: 0,
      hint: "What did he say right after the wall came down?",
      explain: "“<b>This garden is yours now, children.</b>” He wanted to share it.",
    },
    {
      type: "mcq", skill: "Moral value",
      prompt: "What can readers learn from the Giant’s story?",
      options: [
        "Sharing and kindness bring happiness to everyone.",
        "A high wall is the best way to protect a garden.",
        "Children should never play in someone’s garden.",
        "It is better to live alone than with other people.",
      ], answer: 0,
      hint: "When was the Giant lonely and cold? When did spring come back?",
      feedback: { 3: "The Giant lived alone during the long winter — and he was lonely and cold, not happy." },
      explain: "The moral: <b>selfishness</b> brings a cold, lonely life; <b>sharing and kindness</b> bring spring and friends.",
    },
  ],
});
