/* ==========================================================
   NARRATIVE QUEST — Story file
   Tangkuban Perahu (Legend · West Java, Indonesia)
   School-friendly retelling of the Sundanese legend of
   Sangkuriang and Dayang Sumbi.
   ========================================================== */
NQ.registerStory({
  id: "tangkuban-perahu",
  title: "Tangkuban Perahu",
  genre: "legends",
  origin: "indonesia",
  region: "West Java, Indonesia",
  country: "Indonesia",
  level: "A2–B1",
  minutes: 30,
  cover: "img/stories/tangkuban-perahu/tangkuban-perahu-cover.webp",
  summary: "A quick-tempered young hunter must build a lake and a giant boat in one night. Why does a clever princess not want him to finish?",

  /* ---------- STORY PAGES ---------- */
  pages: [
    {
      text: "A long time ago, in West Java, there lived a beautiful princess named Dayang Sumbi. She loved weaving cloth, and she was clever and wise. She lived in the forest with her son, Sangkuriang, and their loyal dog, Tumang. Tumang was not an ordinary dog. He was really a god under a curse, and he was Sangkuriang’s father. But Sangkuriang did not know this secret.",
      vocab: ["weaving", "loyal"],
      scene: { art: "img/stories/tangkuban-perahu/dayang-sumbi-weaving.webp", fit: "contain", alt: "dayang sumbi weaving", tone: "day", fx: [] },
    },
    {
      text: "Sangkuriang grew into a strong boy who loved hunting. One day, he went into the forest with Tumang to hunt a deer for his mother. They searched all day, but they could not find one. At last, Sangkuriang saw a deer, but Tumang did not want to chase it. Sangkuriang lost his temper. In his anger, he shot Tumang with an arrow, and the loyal dog died.",
      vocab: ["chase", "lost his temper"],
      scene: { art: "img/stories/tangkuban-perahu/sangkuriang-hunts-with-tumang.webp", fit: "contain", alt: "sangkuriang hunts with tumang", tone: "day", fx: [] },
    },
    {
      text: "When Sangkuriang came home, he told his mother what he had done. Dayang Sumbi was shocked and very angry. “How could you hurt Tumang?” she cried. She hit his head with a wooden rice spoon, and it left a scar. Sangkuriang felt hurt and ashamed, so he left home and wandered far away. Dayang Sumbi was sorry and prayed every day. The gods kept her young and beautiful.",
      vocab: ["scar"],
      scene: { art: "img/stories/tangkuban-perahu/dayang-sumbi-angry.webp", fit: "contain", alt: "dayang sumbi angry", tone: "day", fx: [] },
    },
    {
      text: "Many years passed. Sangkuriang became a strong and handsome young man. One day, he met a beautiful woman in the forest, and they fell in love. But one evening, the woman saw a scar on his head, and she was shocked. She was Dayang Sumbi, and the young man was her own son! She told him the truth, but Sangkuriang did not believe her. He was stubborn and still wanted to marry her.",
      vocab: ["stubborn"],
      scene: { art: "img/stories/tangkuban-perahu/dayang-sumbi-sees-scar.webp", fit: "contain", alt: "dayang sumbi sees scar", tone: "day", fx: [] },
    },
    {
      text: "Dayang Sumbi thought carefully. Then she set a condition: “Dam the Citarum River to make a lake, and build a big boat for us. You must finish everything in one night, before sunrise.” Sangkuriang agreed. That night, he called the spirits of the forest to help him. The spirits were very strong, and they worked fast. Before dawn, the lake was almost full and the boat was nearly finished.",
      vocab: ["condition", "dam", "dawn"],
      scene: { art: "img/stories/tangkuban-perahu/spirits-build-boat.webp", fit: "contain", alt: "spirits build boat", tone: "day", fx: [] },
    },
    {
      text: "Dayang Sumbi was worried. She spread a long red cloth in the east, and she asked the village women to pound rice. The sky looked red like sunrise, and the pounding sounded like morning work. The roosters crowed. The spirits thought the sun was rising, so they ran away. Sangkuriang could not finish in time. He was furious and kicked the boat. It flew into the air and landed upside down.",
      vocab: ["furious"],
      scene: { art: "img/stories/tangkuban-perahu/red-cloth-dawn-trick.webp", fit: "contain", alt: "red cloth dawn trick", tone: "day", fx: [] },
    },
    {
      text: "The upturned boat became a mountain. People call it Tangkuban Perahu, which means “upturned boat” in Sundanese. The dammed river became a huge lake, and many people believe the land around Bandung was once this lake. Today, visitors still climb the mountain and look into its smoky crater. The legend reminds us to control our anger, to respect our parents and to listen to the truth.",
      vocab: ["upturned", "crater"],
      scene: { art: "img/stories/tangkuban-perahu/boat-becomes-mountain.webp", fit: "contain", alt: "boat becomes mountain", tone: "day", fx: [] },
    },
  ],

  /* ---------- VOCABULARY ---------- */
  vocabulary: [
    { word: "weaving", forms: ["weaving"], meaning: "making cloth by crossing threads over and under each other" },
    { word: "loyal", forms: ["loyal"], meaning: "always staying with and supporting someone" },
    { word: "chase", forms: ["chase"], meaning: "run after something to catch it" },
    { word: "lost his temper", forms: ["lost his temper"], meaning: "suddenly became very angry" },
    { word: "scar", forms: ["scar"], meaning: "a mark that stays on the skin after an injury" },
    { word: "stubborn", forms: ["stubborn"], meaning: "not willing to change your mind" },
    { word: "condition", forms: ["condition"], meaning: "something that must happen before another thing can happen" },
    { word: "dam", forms: ["dam"], meaning: "build a wall across a river to hold the water back" },
    { word: "dawn", forms: ["dawn"], meaning: "the time early in the morning when the sky starts to get light" },
    { word: "furious", forms: ["furious"], meaning: "extremely angry" },
    { word: "upturned", forms: ["upturned"], meaning: "turned upside down" },
    { word: "crater", forms: ["crater"], meaning: "the big round hole at the top of a volcano" },
  ],

  /* ---------- CHARACTERS ---------- */
  characters: [
    { id: "sangkuriang", name: "Sangkuriang", img: "img/stories/tangkuban-perahu/adult-sangkuriang.webp", role: "Main character (the son)", traits: ["quick-tempered", "stubborn", "determined"],
      evidence: "Sangkuriang lost his temper. In his anger, he shot Tumang with an arrow." },
    { id: "dayangsumbi", name: "Dayang Sumbi", img: "img/stories/tangkuban-perahu/dayang-sumbi.webp", role: "The mother (a princess)", traits: ["clever", "wise"],
      evidence: "She spread a long red cloth in the east, and she asked the village women to pound rice." },
    { id: "tumang", name: "Tumang", img: "img/stories/tangkuban-perahu/tumang.webp", role: "The loyal dog (Sangkuriang’s father under a curse)", traits: ["loyal"],
      evidence: "She lived in the forest with her son, Sangkuriang, and their loyal dog, Tumang." },
  ],

  traitWords: [
    { word: "quick-tempered", meaning: "becoming angry very quickly and easily" },
    { word: "stubborn", meaning: "not willing to change your mind" },
    { word: "determined", meaning: "not giving up when something is difficult" },
    { word: "clever", meaning: "quick at thinking and finding good ideas" },
    { word: "wise", meaning: "able to make good decisions" },
    { word: "loyal", meaning: "always staying with and supporting someone" },
    { word: "even-tempered", meaning: "staying calm; not getting angry easily" },
    { word: "patient", meaning: "able to wait calmly without getting angry" },
    { word: "lazy", meaning: "not wanting to work" },
    { word: "cowardly", meaning: "easily frightened; not brave" },
  ],

  /* ---------- GENERIC STRUCTURE ---------- */
  structure: {
    orientation: { pages: [1], summary: "Dayang Sumbi, a clever princess, lived in a West Java forest with her son Sangkuriang and their loyal dog Tumang." },
    complication: { pages: [2, 3, 4], summary: "Sangkuriang shot Tumang in anger and left home. Years later, he fell in love with a woman who was really his own mother, and he did not believe the truth." },
    resolution: { pages: [5, 6], summary: "Dayang Sumbi set an impossible condition and made it look like morning, so the spirits ran away and Sangkuriang failed. He kicked the boat, and it landed upside down." },
    coda: { pages: [7], summary: "The upturned boat became Mount Tangkuban Perahu. The legend teaches us to control our anger and respect our parents." },
  },
  mainConflict: "Sangkuriang wanted to marry Dayang Sumbi, but she was really his own mother, and he refused to believe the truth.",
  sequence: [
    "Sangkuriang shot Tumang with an arrow.",
    "Sangkuriang left home and wandered far away.",
    "Sangkuriang met a beautiful woman in the forest.",
    "Dayang Sumbi set a condition that seemed impossible.",
    "The spirits ran away before the work was finished.",
    "The upturned boat became a mountain.",
  ],
  grammarExamples: {
    regular: ["love → loved", "agree → agreed", "kick → kicked"],
    irregular: ["shoot → shot", "leave → left", "meet → met"],
    was: "Dayang Sumbi was shocked and very angry.",
    were: "The spirits were very strong.",
    negative: "Sangkuriang did not believe her.",
    question: "Did the spirits finish the boat?",
  },
  guides: { good: "img/stories/tangkuban-perahu/tumang.webp", hint: "img/stories/tangkuban-perahu/dayang-sumbi.webp" },
  pastVerbs: [
    { base: "live", past: "lived", type: "regular" }, { base: "love", past: "loved", type: "regular" },
    { base: "search", past: "searched", type: "regular" }, { base: "agree", past: "agreed", type: "regular" },
    { base: "kick", past: "kicked", type: "regular" }, { base: "crow", past: "crowed", type: "regular" },
    { base: "pray", past: "prayed", type: "regular" }, { base: "call", past: "called", type: "regular" },
    { base: "shoot", past: "shot", type: "irregular" }, { base: "leave", past: "left", type: "irregular" },
    { base: "meet", past: "met", type: "irregular" }, { base: "hit", past: "hit", type: "irregular" },
    { base: "fly", past: "flew", type: "irregular" }, { base: "think", past: "thought", type: "irregular" },
    { base: "grow", past: "grew", type: "irregular" }, { base: "spread", past: "spread", type: "irregular" },
  ],

  /* =========================================================
     CHALLENGES
     ========================================================= */
  challenges: {
    /* ---------------- 🔮 WORD HUNTER ---------------- */
    word: [
      {
        type: "mcq", skill: "Meaning in context", ref: 1,
        quote: "She lived in the forest with her son, Sangkuriang, and their loyal dog, Tumang.",
        prompt: "What does <b>loyal</b> mean in this sentence?",
        options: ["always staying with and supporting someone", "always running away from other people", "always hungry and looking for food", "always noisy and barking at night"], answer: 0,
        hint: "Tumang lived with the family and went hunting with Sangkuriang. What does this tell you about him?",
        explain: "A <b>loyal</b> dog always stays with its family and supports them.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 2,
        quote: "Sangkuriang lost his temper. In his anger, he shot Tumang with an arrow.",
        prompt: "What does <b>lost his temper</b> mean?",
        options: ["suddenly became very angry", "suddenly felt very tired", "could not find his arrow", "forgot where he was going"], answer: 0,
        hint: "Read the next sentence. It begins “In his …”. That word is your clue.",
        feedback: { 2: "Careful! Here <i>lost</i> is not about losing a thing. The next sentence says “In his anger…”." },
        explain: "To <b>lose your temper</b> = to suddenly become very angry. The clue is “In his anger”.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 3,
        quote: "She hit his head with a wooden rice spoon, and it left a scar.",
        prompt: "What is a <b>scar</b>?",
        options: ["a mark on the skin after an injury", "a small hat worn on the head", "a piece of wood from a spoon", "a bad dream after a fight"], answer: 0,
        hint: "The spoon hit his head. What can stay on the skin for many years after that?",
        explain: "A <b>scar</b> is a mark that stays on the skin after an injury. Later, this scar is very important in the story!",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 4,
        quote: "She told him the truth, but Sangkuriang did not believe her. He was stubborn and still wanted to marry her.",
        prompt: "What does <b>stubborn</b> mean here?",
        options: ["not willing to change his mind", "not strong enough to fight", "not able to hear very well", "not interested in getting married"], answer: 0,
        hint: "He heard the truth, but what did he <i>still</i> want?",
        feedback: { 3: "Look again: he <i>still</i> wanted to marry her." },
        explain: "<b>Stubborn</b> = not willing to change your mind, even when you hear the truth.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 5,
        quote: "“Dam the Citarum River to make a lake…”",
        prompt: "What did Sangkuriang have to do to the river?",
        options: ["block it with a wall so the water stays", "cross it quickly in a small wooden boat", "clean it so the water becomes clear", "catch all the fish that live in it"], answer: 0,
        hint: "The goal was to <i>make a lake</i>. How can a river become a lake?",
        explain: "To <b>dam</b> a river = build a wall across it. The water cannot flow away, so it becomes a lake.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 6,
        quote: "He was furious and kicked the boat.",
        prompt: "Which words are closest in meaning to <b>furious</b>?",
        options: ["extremely angry", "extremely tired", "extremely scared", "extremely proud"], answer: 0,
        hint: "His plan failed, and then he kicked the boat. How did he feel?",
        explain: "<b>Furious</b> = extremely angry.",
      },
      {
        type: "mcq", skill: "Antonym", ref: 5,
        quote: "Before dawn, the lake was almost full and the boat was nearly finished.",
        prompt: "Which word is the <b>opposite</b> of <b>dawn</b>?",
        options: ["sunrise", "dusk", "daybreak", "morning"], answer: 1,
        hint: "Three of these words are about the start of the day. Find the one about the end of the day.",
        feedback: { 0: "Sunrise is close in meaning to dawn, not the opposite.", 2: "Daybreak means almost the same as dawn." },
        explain: "<b>Dawn</b> is when the day begins; <b>dusk</b> is when the day ends and it gets dark.",
      },
      {
        type: "mcq", skill: "Word with two meanings", ref: 5,
        quote: "Dayang Sumbi thought carefully. Then she set a condition.",
        prompt: "What does <b>condition</b> mean in this sentence?",
        options: ["something that must happen before another thing", "the state of something, for example old or new", "the weather in a place at a certain time", "a health problem that a person has for a long time"], answer: 0,
        hint: "Many words have more than one meaning. What did Sangkuriang have to do <i>before</i> he could marry her?",
        feedback: { 1: "That is a real meaning (“The car is in good condition”) — but not in this story." },
        explain: "Here, a <b>condition</b> is something that must happen first: he could marry her only if he finished the lake and the boat.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 7, image: "img/stories/tangkuban-perahu/boat-becomes-mountain.webp",
        prompt: "Look at the picture. The name <i>Tangkuban Perahu</i> means “<b>upturned</b> boat”. An upturned boat is…",
        options: ["upside down", "broken in half", "full of water", "sailing away"], answer: 0,
        hint: "Read page 6: how did the boat land after Sangkuriang kicked it?",
        explain: "<b>Upturned</b> = turned upside down. The mountain looks like a boat lying upside down.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 7, image: "img/icons/volcano.webp",
        prompt: "Look at the picture. Visitors look into the smoky ___ at the top of the mountain.",
        options: ["crater", "cave", "tower", "valley"], answer: 0,
        hint: "Tangkuban Perahu is a volcano. What do we call the big hole at its top?",
        feedback: { 1: "A cave is a hole in the side of a hill or under the ground, not at the top of a volcano." },
        explain: "A <b>crater</b> is the big round hole at the top of a volcano.",
      },
      {
        type: "sort", skill: "Word–meaning match", layout: "match",
        prompt: "Drag each word to its meaning. <span class='tip'>(Or tap a word, then tap a meaning.)</span>",
        bins: [
          { id: "weaving", label: "making cloth from threads" },
          { id: "chase", label: "run after something to catch it" },
          { id: "loyal", label: "always staying with and supporting someone" },
          { id: "dawn", label: "early morning, when the sky gets light" },
          { id: "crater", label: "the big hole at the top of a volcano" },
          { id: "condition", label: "something that must happen first" },
        ],
        cards: [
          { text: "weaving", bin: "weaving" }, { text: "chase", bin: "chase" }, { text: "loyal", bin: "loyal" },
          { text: "dawn", bin: "dawn" }, { text: "crater", bin: "crater" }, { text: "condition", bin: "condition" },
        ],
        capacity: 1,
        hint: "Start with the words you are sure about. Dayang Sumbi loved <i>weaving</i> cloth; Tumang did not want to <i>chase</i> the deer.",
        explain: "Great word hunting! You matched all six words.",
      },
    ],

    /* ---------------- 🧩 STORY DETECTIVE ---------------- */
    structure: [
      {
        type: "sort", skill: "Sort the story",
        prompt: "Put each event card in the correct part of the narrative.",
        bins: [
          { id: "orientation", label: "Orientation", img: "img/st-orientation.webp", sub: "Who? Where? When?" },
          { id: "complication", label: "Complication", img: "img/st-complication.webp", sub: "What problem happened?" },
          { id: "resolution", label: "Resolution", img: "img/st-resolution.webp", sub: "How was it solved?" },
          { id: "coda", label: "Ending / Coda", img: "img/st-ending.webp", sub: "What happened afterward?" },
        ],
        cards: [
          { text: "A long time ago, a princess named Dayang Sumbi lived in West Java.", bin: "orientation" },
          { text: "She lived in the forest with her son and their loyal dog, Tumang.", bin: "orientation" },
          { text: "In his anger, Sangkuriang shot Tumang with an arrow.", bin: "complication" },
          { text: "Sangkuriang did not believe the truth and still wanted to marry her.", bin: "complication" },
          { text: "Dayang Sumbi spread a red cloth, and the roosters crowed.", bin: "resolution" },
          { text: "The spirits ran away, and Sangkuriang could not finish in time.", bin: "resolution" },
          { text: "The upturned boat became Mount Tangkuban Perahu.", bin: "coda" },
          { text: "The legend reminds us to control our anger.", bin: "coda" },
        ],
        hint: "Orientation introduces the characters and place. Complication = problems. Resolution = how the problem ends. Coda = the mountain today and the lesson.",
        explain: "The story moves from <b>introduction</b> → <b>problems</b> → <b>the problem is stopped</b> → <b>the mountain and the lesson</b>.",
      },
      {
        type: "mcq", skill: "Find the complication", ref: 2,
        prompt: "Which sentence shows the <b>first problem</b> in the story?",
        options: [
          "“They searched all day, but they could not find one.”",
          "“She loved weaving cloth, and she was clever and wise.”",
          "“Sangkuriang grew into a strong boy who loved hunting.”",
          "“Today, visitors still climb the mountain.”",
        ], answer: 0,
        hint: "Look for the word that tells us something went wrong.",
        explain: "The word <b>but</b> shows the first problem: they could not find a deer. Soon after, Sangkuriang lost his temper.",
      },
      {
        type: "mcq", skill: "Find the main conflict", ref: 4,
        prompt: "What is the <b>main conflict</b> in <i>Tangkuban Perahu</i>?",
        options: [
          "Sangkuriang wanted to marry his own mother and did not believe the truth.",
          "Sangkuriang and Tumang could not find a deer after searching all day.",
          "The spirits of the forest refused to help Sangkuriang build the boat.",
          "Dayang Sumbi wanted to leave the forest and live near the Citarum River.",
        ], answer: 0,
        hint: "The main conflict is the biggest problem. What problem does the rest of the story try to stop?",
        feedback: {
          1: "That is the first small problem, but it is not the central one. What happened many years later?",
          2: "Look again: the spirits <i>did</i> help him. They were strong and worked fast.",
          3: "The story never says that. Think about the scar and the truth.",
        },
        explain: "The central problem: Sangkuriang wanted to <b>marry his own mother</b>, and he <b>refused to believe</b> her.",
      },
      {
        type: "order", skill: "Story sequence",
        prompt: "Put the events in the correct order. <span class='tip'>Tap an event to add it to the next empty step.</span>",
        items: [
          "Sangkuriang shot Tumang with an arrow.",
          "Sangkuriang left home and wandered far away.",
          "Sangkuriang met a beautiful woman in the forest.",
          "Dayang Sumbi set a condition that seemed impossible.",
          "The spirits ran away before the work was finished.",
          "The upturned boat became a mountain.",
        ],
        hint: "Follow Sangkuriang: hunting → leaving home → many years later → one long night → the mountain today.",
        explain: "Perfect timeline! Narratives are told in <b>chronological order</b>.",
      },
      {
        type: "mcq", skill: "Cause & effect", ref: 6,
        prompt: "Why did the spirits run away?",
        options: [
          "They thought the sun was rising.",
          "They were afraid of Dayang Sumbi.",
          "They had finished all the work.",
          "Sangkuriang told them to go home.",
        ], answer: 0,
        hint: "Read page 6 again. What did the spirits think when they saw the red sky and heard the roosters?",
        feedback: { 2: "Look again: the boat was only <i>nearly</i> finished." },
        explain: "Cause: the red sky, the pounding and the roosters → Effect: the spirits thought it was morning and ran away.",
      },
      {
        type: "sort", skill: "Cause & effect match", layout: "match", capacity: 1,
        prompt: "Match each <b>cause</b> with its <b>effect</b>.",
        bins: [
          { id: "c1", label: "Tumang did not want to chase the deer.", kicker: "CAUSE" },
          { id: "c2", label: "Dayang Sumbi hit Sangkuriang with a wooden rice spoon.", kicker: "CAUSE" },
          { id: "c3", label: "Dayang Sumbi saw the scar on the young man’s head.", kicker: "CAUSE" },
          { id: "c4", label: "Sangkuriang kicked the boat.", kicker: "CAUSE" },
        ],
        cards: [
          { text: "Sangkuriang lost his temper.", bin: "c1" },
          { text: "It left a scar on his head.", bin: "c2" },
          { text: "She realised he was her own son.", bin: "c3" },
          { text: "It landed upside down.", bin: "c4" },
        ],
        hint: "Ask “What happened <i>because of</i> this?” for each cause.",
        explain: "Each event causes the next one. Notice how the scar connects the beginning and the middle of the story!",
      },
      {
        type: "mcq", skill: "Key moment", ref: 4,
        prompt: "Which moment turned the love story into a <b>serious problem</b>?",
        options: [
          "Dayang Sumbi saw the scar on the young man’s head.",
          "Sangkuriang became a strong and handsome young man.",
          "Sangkuriang met a beautiful woman in the forest.",
          "The gods kept Dayang Sumbi young and beautiful.",
        ], answer: 0,
        hint: "At which moment did Dayang Sumbi discover who the young man really was?",
        feedback: { 2: "Meeting her was the start of the love story. But when did it become a problem?" },
        explain: "When she saw the <b>scar</b>, she knew he was her son. From that moment, she had to stop the marriage.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 2, structureOptions: true,
        quote: "At last, Sangkuriang saw a deer, but Tumang did not want to chase it. Sangkuriang lost his temper. In his anger, he shot Tumang with an arrow, and the loyal dog died.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
        hint: "Is a problem starting here, or is a problem being stopped?",
        explain: "Something goes badly wrong — this is part of the <b>complication</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 6, structureOptions: true,
        quote: "The roosters crowed. The spirits thought the sun was rising, so they ran away. Sangkuriang could not finish in time.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
        hint: "Could the marriage still happen after this?",
        explain: "Sangkuriang failed, so the marriage could not happen. The main problem is stopped: this is the <b>resolution</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 7, structureOptions: true,
        quote: "Today, visitors still climb the mountain and look into its smoky crater. The legend reminds us to control our anger, to respect our parents and to listen to the truth.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 3,
        hint: "The word “Today” takes us out of the old story. What else does this paragraph give us?",
        explain: "It tells us about the mountain today and gives the lesson: this is the <b>ending / coda</b>.",
      },
    ],

    /* ---------------- 🎭 CHARACTER DETECTIVE ---------------- */
    character: [
      {
        type: "mcq", skill: "Trait → Step 1", character: "sangkuriang", ref: 2,
        prompt: "Character: <b>Sangkuriang</b> (on the hunting day). Choose the <b>best</b> trait.",
        options: ["quick-tempered", "even-tempered", "cowardly", "lazy"], answer: 0,
        hint: "Tumang did not want to chase the deer. How fast did Sangkuriang become angry?",
        feedback: { 1: "An even-tempered person stays calm. Did Sangkuriang stay calm?" },
        explain: "He became angry very quickly and hurt Tumang: he was <b>quick-tempered</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "sangkuriang", ref: 2,
        prompt: "You chose <b>quick-tempered</b>. Which event <b>best supports</b> your answer?",
        options: [
          "He shot Tumang because the dog did not chase a deer.",
          "He went into the forest to hunt a deer for his mother.",
          "He searched all day with Tumang but found nothing.",
          "He grew into a strong boy who loved hunting.",
        ], answer: 0,
        hint: "Evidence must <i>show</i> the trait. Which action happened in anger?",
        explain: "Character → Trait → <b>Evidence</b>. Shooting Tumang in anger proves he was quick-tempered.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "dayangsumbi", ref: 6,
        prompt: "Character: <b>Dayang Sumbi</b> (on the night of the boat). Which trait describes her best?",
        options: ["clever", "careless", "greedy", "lazy"], answer: 0,
        hint: "She had a problem: the work was nearly finished. How did she solve it without fighting?",
        explain: "She found a smart way to make it look like morning: she was <b>clever</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "dayangsumbi", ref: 6,
        prompt: "Which evidence <b>best proves</b> that Dayang Sumbi was clever?",
        options: [
          "She made it look and sound like morning to stop the work.",
          "She loved weaving cloth when she lived in the forest.",
          "She met a handsome young man in the forest one day.",
          "She hit her son with a wooden rice spoon in anger.",
        ], answer: 0,
        hint: "Three of these do not show quick thinking. Which one shows a smart plan?",
        explain: "The red cloth and the pounding rice were a <b>clever plan</b> that tricked the spirits.",
      },
      {
        type: "mcq", skill: "Evidence hunt", character: "sangkuriang", ref: 4,
        prompt: "The story says Sangkuriang was <b>stubborn</b>. Which evidence supports this?",
        options: [
          "He did not believe the truth and still wanted to marry her.",
          "He called the spirits of the forest to help him that night.",
          "He met a beautiful woman in the forest, and they fell in love.",
          "He felt hurt and ashamed, so he left home and wandered away.",
        ], answer: 0,
        hint: "A stubborn person does not change his mind. Which action shows that?",
        explain: "Even after she told him the truth, he did not change his mind: that is <b>stubborn</b>.",
      },
      {
        type: "mcq", skill: "Evidence hunt", character: "sangkuriang", ref: 5,
        prompt: "Sangkuriang was also <b>determined</b>: he did not give up easily. Which evidence shows this?",
        options: [
          "He agreed to the hard task and called the spirits to help.",
          "He told his mother what he had done to Tumang that day.",
          "He became a strong and handsome young man after many years.",
          "He went hunting in the forest with his dog, Tumang.",
        ], answer: 0,
        hint: "The task seemed impossible. What did he do instead of saying no?",
        explain: "He accepted an almost impossible task and worked to finish it in one night: he was <b>determined</b>.",
      },
      {
        type: "multi", skill: "Two best traits", character: "sangkuriang", pick: 2,
        prompt: "Choose <b>TWO</b> traits that best describe <b>Sangkuriang</b>.",
        options: ["stubborn", "patient", "quick-tempered", "cowardly", "lazy", "gentle"], answer: [0, 2],
        hint: "Think about the hunting day and the day his mother told him the truth.",
        explain: "He lost his temper with Tumang (<b>quick-tempered</b>) and did not believe the truth (<b>stubborn</b>).",
      },
      {
        type: "mcq", skill: "Who am I?",
        prompt: "<b>Who am I?</b><ul class='clues'><li>I lived in the forest with my family.</li><li>I did not want to chase a deer.</li><li>I was really a god under a curse.</li></ul>",
        options: ["Tumang", "Sangkuriang", "Dayang Sumbi", "a forest spirit"], answer: 0,
        hint: "Who went hunting with Sangkuriang?",
        explain: "<b>Tumang</b>, the loyal dog, was really a god under a curse — and Sangkuriang’s father.",
      },
      {
        type: "sort", skill: "Trait match", layout: "match", capacity: 1,
        prompt: "Match each character with the personality adjective that fits best.",
        bins: [
          { id: "sangkuriang", label: "Sangkuriang (on the hunting day)", img: "img/stories/tangkuban-perahu/young-sangkuriang.webp" },
          { id: "sangkuriang2", label: "Sangkuriang (after hearing the truth)", img: "img/stories/tangkuban-perahu/adult-sangkuriang.webp" },
          { id: "dayangsumbi", label: "Dayang Sumbi", img: "img/stories/tangkuban-perahu/dayang-sumbi.webp" },
          { id: "tumang", label: "Tumang", img: "img/stories/tangkuban-perahu/tumang.webp" },
        ],
        cards: [
          { text: "quick-tempered", bin: "sangkuriang" }, { text: "stubborn", bin: "sangkuriang2" },
          { text: "clever", bin: "dayangsumbi" }, { text: "loyal", bin: "tumang" },
        ],
        hint: "Remember the evidence: who lost his temper, who did not change his mind, who made a clever plan, and who is called loyal?",
        explain: "Every trait matches evidence from the text. Well done, detective!",
      },
      {
        type: "mcq", skill: "Character comparison",
        prompt: "How were Dayang Sumbi and Sangkuriang <b>different</b> when they had a problem?",
        options: [
          "She thought carefully, but he often acted in anger.",
          "She acted in anger, but he always thought carefully.",
          "She did not believe the truth, but he listened to it.",
          "She called the spirits, but he did not ask for help.",
        ], answer: 0,
        hint: "Compare how Dayang Sumbi solved her problem on page 5 with what Sangkuriang did on pages 2 and 6.",
        explain: "Dayang Sumbi <b>thought carefully</b>; Sangkuriang <b>lost his temper</b> and later kicked the boat when he was furious.",
      },
      {
        type: "mcq", skill: "Inference", ref: 3,
        quote: "Dayang Sumbi was sorry and prayed every day.",
        prompt: "What was Dayang Sumbi probably sorry about?",
        options: [
          "She hit her son, and then he left home.",
          "She did not go hunting with her son.",
          "She loved weaving more than hunting.",
          "She lived far away from the village.",
        ], answer: 0,
        hint: "The story does not say it directly. What happened just before this sentence?",
        explain: "She hit Sangkuriang in anger, and he left home. She was probably sorry that she had lost her son.",
      },
    ],

    /* ---------------- ⏳ PAST TENSE LAB ---------------- */
    grammar: [
      {
        type: "verbs", skill: "Verb transform",
        prompt: "Type the <b>simple past</b> form of each verb from the story.",
        verbs: [
          { base: "love", past: "loved" }, { base: "search", past: "searched" }, { base: "agree", past: "agreed" },
          { base: "shoot", past: "shot" }, { base: "leave", past: "left" }, { base: "meet", past: "met" },
        ],
        hint: "Regular verbs add <b>-ed</b> (love → loved). Irregular verbs change form (meet → m _ t).",
        explain: "<b>loved, searched, agreed</b> are regular. <b>shot, left, met</b> are irregular.",
      },
      {
        type: "verbs", skill: "Verb transform",
        prompt: "More story verbs! Type the <b>simple past</b> form.",
        verbs: [
          { base: "kick", past: "kicked" }, { base: "crow", past: "crowed" }, { base: "pray", past: "prayed" },
          { base: "grow", past: "grew" }, { base: "think", past: "thought" }, { base: "hit", past: "hit" },
        ],
        hint: "Three are regular (-ed). The other three are irregular — you can find their past forms on pages 2, 3 and 6.",
        explain: "Regular: <b>kicked, crowed, prayed</b>. Irregular: <b>grew, thought, hit</b> (hit does not change!).",
      },
      {
        type: "mcq", skill: "Choose the correct verb", ref: 3,
        prompt: "When Sangkuriang came home, he ___ his mother what he had done.",
        options: ["tell", "told", "tells", "telling"], answer: 1,
        hint: "The first verb is <i>came</i> (past). The second verb must be past too.",
        explain: "<b>tell → told</b> (irregular).",
      },
      {
        type: "mcq", skill: "Was / were", ref: 5,
        prompt: "The spirits ___ very strong, and they worked fast.",
        options: ["was", "were", "is", "are"], answer: 1,
        hint: "“The spirits” is plural. Which past form goes with plural subjects?",
        explain: "<b>were</b> for plural subjects (they, the spirits). <b>was</b> for I / he / she / it.",
      },
      {
        type: "mcq", skill: "Was / were", ref: 3,
        prompt: "Dayang Sumbi ___ shocked and very angry.",
        options: ["were", "was", "is", "be"], answer: 1,
        hint: "“Dayang Sumbi” = she (one person).",
        explain: "He / she / it → <b>was</b>.",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 2,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Sangkuriang shoot Tumang with an arrow.",
        wrong: 1, options: ["shot", "shooted", "shooting", "shoots"], answer: 0,
        hint: "Find the verb. Is it in the past form?",
        stage2: "Now choose the correct form of <b>shoot</b>:",
        feedback2: { 1: "Shoot is irregular — we don’t add -ed." },
        explain: "<b>shoot → shot</b>: “Sangkuriang <b>shot</b> Tumang with an arrow.”",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 6,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Sangkuriang kicked the boat, and it fly into the air.",
        wrong: 6, options: ["flew", "flied", "flown", "flying"], answer: 0,
        hint: "There are two verbs. One is correct (kicked). Check the other one.",
        stage2: "Choose the correct form of <b>fly</b>:",
        feedback2: { 2: "Careful! <b>flown</b> needs <i>has / had</i> before it. The simple past is different." },
        explain: "<b>fly → flew</b>. Both verbs in the sentence must be past.",
      },
      {
        type: "fix", skill: "Negative challenge", ref: 4,
        prompt: "This negative sentence has a mistake. Tap the <b>incorrect</b> word.",
        sentence: "Sangkuriang didn’t believed his mother.",
        wrong: 2, options: ["believe", "believes", "believing", "to believe"], answer: 0,
        hint: "After <b>didn’t</b>, we use the base verb (V1).",
        stage2: "After <b>didn’t</b>, which form is correct?",
        explain: "<b>didn’t + base verb</b>: “Sangkuriang didn’t <b>believe</b> his mother.”",
      },
      {
        type: "mcq", skill: "Negative sentence", ref: 2,
        prompt: "Tumang ___ to chase the deer.",
        options: ["didn’t want", "didn’t wanted", "doesn’t want", "wasn’t want"], answer: 0,
        hint: "Past negative = did not (didn’t) + base verb.",
        feedback: { 1: "Almost! After didn’t, the verb goes back to the base form.", 2: "“doesn’t” is present. The story is in the past." },
        explain: "<b>didn’t + want</b> (base verb).",
      },
      {
        type: "order", skill: "Sentence builder", inline: true, ref: 4,
        prompt: "Build the sentence in the simple past. <span class='tip'>One word is not needed.</span>",
        items: ["Sangkuriang", "met", "a beautiful woman", "in the forest."],
        extras: ["meet"],
        hint: "Start with the person. Which verb form shows the past?",
        explain: "“Sangkuriang <b>met</b> a beautiful woman in the forest.” — Subject + <b>V2</b> + object + place.",
      },
      {
        type: "order", skill: "Question challenge", inline: true, ref: 6,
        prompt: "Build a simple past <b>question</b>. <span class='tip'>One word is not needed.</span>",
        items: ["Did", "the spirits", "finish", "the boat?"],
        extras: ["finished"],
        hint: "Question pattern: <b>Did + subject + base verb…?</b>",
        explain: "“<b>Did</b> the spirits <b>finish</b> the boat?” — No, they didn’t!",
      },
      {
        type: "mcq", skill: "Question challenge", ref: 3,
        prompt: "“___ Dayang Sumbi angry with her son?” — “Yes, she was.”",
        options: ["Was", "Did", "Were", "Does"], answer: 0,
        hint: "Look at the short answer: “Yes, she <b>was</b>.” There is no main verb, only an adjective (angry).",
        feedback: { 1: "We use <i>Did</i> with a main verb (Did she hit…?). Here there is only an adjective: angry." },
        explain: "With adjectives we use <b>Was / Were</b>: Was she angry? — Yes, she was.",
      },
    ],
  },

  /* ---------------- 🌟 MASTER THE STORY (final) ---------------- */
  final: [
    {
      type: "mcq", skill: "Vocabulary in context", ref: 3,
      quote: "Sangkuriang felt hurt and ashamed, so he left home and wandered far away.",
      prompt: "What does <b>wandered</b> mean here?",
      options: ["walked from place to place with no clear plan", "ran quickly to a place he knew very well", "travelled by boat along the Citarum River", "hid in a small house near his old home"], answer: 0,
      hint: "He left home feeling hurt. Did he have a clear place to go?",
      explain: "To <b>wander</b> = to walk from place to place without a clear plan.",
    },
    {
      type: "mcq", skill: "Simple past", ref: 6,
      prompt: "The roosters ___, and the spirits ran away.",
      options: ["crowed", "crow", "crows", "crowing"], answer: 0,
      hint: "The second verb, <i>ran</i>, is past. The first verb must be past too.",
      explain: "<b>crow → crowed</b> (regular).",
    },
    {
      type: "mcq", skill: "Narrative structure", structureOptions: true, ref: 1,
      quote: "A long time ago, in West Java, there lived a beautiful princess named Dayang Sumbi.",
      prompt: "Which part of the narrative does this sentence belong to?",
      options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 0,
      hint: "Does it tell us <i>who</i>, <i>where</i> and <i>when</i>?",
      explain: "It introduces the character, the place and the time: <b>orientation</b>.",
    },
    {
      type: "order", skill: "Sequence of events",
      prompt: "Put these events in order.",
      items: [
        "Dayang Sumbi hit Sangkuriang with a rice spoon.",
        "Dayang Sumbi saw the scar on the young man’s head.",
        "Sangkuriang called the spirits of the forest.",
        "Sangkuriang kicked the boat in anger.",
      ],
      hint: "Think about what caused the scar, when the scar became important, and what happened at the end of the night.",
      explain: "Great timeline memory!",
    },
    {
      type: "mcq", skill: "Main conflict",
      prompt: "The main conflict is between Sangkuriang and Dayang Sumbi. What is it <b>about</b>?",
      options: [
        "He wanted to marry her, but she was really his mother.",
        "He wanted to go hunting, but she wanted him at home.",
        "She wanted a big boat, but he did not want to build it.",
        "He wanted to live in a village, but she loved the forest.",
      ], answer: 0,
      hint: "Which problem does Dayang Sumbi try to stop with her condition?",
      feedback: { 2: "She did not really want a boat. She set the task to stop something. What?" },
      explain: "The <b>main conflict</b> is the marriage that must not happen: Sangkuriang wanted to marry his own mother.",
    },
    {
      type: "mcq", skill: "Characterization", ref: 5,
      prompt: "Why can Dayang Sumbi be described as <b>wise</b>?",
      options: [
        "She thought carefully and found a way to stop the marriage.",
        "She hit her son with a spoon when he told her about Tumang.",
        "She stayed young and beautiful for many, many years.",
        "She lived in the forest with her son and a loyal dog.",
      ], answer: 0,
      hint: "A wise person makes good decisions. Which option shows careful thinking?",
      feedback: { 2: "The gods kept her young — that was not her own decision." },
      explain: "She <b>thought carefully</b> and chose a peaceful plan: that is <b>wise</b>.",
    },
    {
      type: "mcq", skill: "Cause & effect", ref: 6,
      prompt: "What happened <b>because</b> Sangkuriang kicked the boat?",
      options: [
        "It landed upside down and became a mountain.",
        "It sailed across the new lake to the village.",
        "It broke into pieces and fell into the river.",
        "It frightened the roosters, and they crowed.",
      ], answer: 0,
      hint: "Read the end of page 6 and the start of page 7.",
      explain: "Cause: he kicked the boat → Effect: it landed upside down and became <b>Tangkuban Perahu</b>.",
    },
    {
      type: "mcq", skill: "Turning point",
      prompt: "Which event changed the direction of the story <b>most significantly</b>?",
      options: [
        "Dayang Sumbi made it look and sound like morning.",
        "Sangkuriang called the spirits of the forest to help.",
        "Sangkuriang agreed to the condition that night.",
        "The spirits worked fast, and the lake was almost full.",
      ], answer: 0,
      hint: "Before this event, Sangkuriang was going to win. After it, he failed. Which event was it?",
      feedback: { 3: "At that moment, Sangkuriang was still winning. What changed everything?" },
      explain: "The fake morning was the <b>turning point</b>: the spirits ran away, and the marriage could not happen.",
    },
    {
      type: "mcq", skill: "Inference", ref: 6,
      quote: "She asked the village women to pound rice.",
      prompt: "Why did the pounding of rice help Dayang Sumbi’s plan?",
      options: [
        "People usually pounded rice early in the morning.",
        "The noise was loud enough to wake up Tumang.",
        "The spirits were hungry and wanted to eat rice.",
        "The rice was needed for the wedding the next day.",
      ], answer: 0,
      hint: "The story says the pounding “sounded like morning work”. What does that tell us?",
      explain: "Pounding rice was <b>morning work</b> in the village, so the sound made the spirits think the day had begun.",
    },
    {
      type: "mcq", skill: "Inference",
      prompt: "Many years later, why did Sangkuriang <b>not recognise</b> his mother?",
      options: [
        "She still looked young, and he had been away for years.",
        "She wore a red cloth that covered her face and hair.",
        "She told him a different name when they first met.",
        "He met her at night, so he could not see her clearly.",
      ], answer: 0,
      hint: "The answer is not in one sentence. Put page 3 and page 4 together: what did the gods do, and how long was he away?",
      feedback: { 2: "The story never says that. Think about what the gods did for her." },
      explain: "The gods <b>kept her young</b>, and <b>many years passed</b>. So she did not look like an older mother.",
    },
    {
      type: "mcq", skill: "Inference: motive", ref: 5,
      prompt: "Why did Dayang Sumbi decide to set such a <b>difficult</b> condition?",
      options: [
        "She hoped he would fail, so the marriage could not happen.",
        "She wanted a lake and a boat for her village to use.",
        "She wanted to see how strong the forest spirits were.",
        "She wanted to travel far away on a big, new boat.",
      ], answer: 0,
      hint: "She knew he was her son, but he did not believe her. What did she need?",
      explain: "She could not marry her own son, so she chose a task that seemed <b>impossible</b> to finish.",
    },
    {
      type: "mcq", skill: "Moral value",
      prompt: "What can readers learn from Sangkuriang’s story?",
      options: [
        "Anger can lead to terrible choices, so we must control it.",
        "Strong people can always get what they want in the end.",
        "We should never ask anyone else to help us with our work.",
        "It is better to live alone in the forest than with family.",
      ], answer: 0,
      hint: "Think about what Sangkuriang did to Tumang and to the boat. What made him do those things?",
      feedback: { 1: "Look again: Sangkuriang was strong, but he did not get what he wanted." },
      explain: "The legend reminds us to <b>control our anger</b>, respect our parents and listen to the truth.",
    },
  ],
});
