/* ==========================================================
   NARRATIVE QUEST — Story file
   Timun Mas (Fairy tale / Folktale · Central Java, Indonesia)
   ----------------------------------------------------------
   Question types: mcq, multi, sort, order, fix, verbs
   (see stories/putri-serindang-bulan.js for the full notes)
   ========================================================== */
NQ.registerStory({
  id: "timun-mas",
  title: "Timun Mas",
  genre: "fairy",
  origin: "indonesia",
  region: "Central Java, Indonesia",
  country: "Indonesia",
  level: "A2–B1",
  minutes: 30,
  cover: "img/covers/timun-mas.webp",
  summary: "A lonely widow makes a dangerous promise to a green giant. Years later, her clever daughter must run for her life with four magic bags.",

  /* ---------- STORY PAGES ---------- */
  pages: [
    {
      text: "Long ago, in a small village in Central Java, there lived a widow named Mbok Srini. Her husband had died many years before, and she had no children. Every day she worked hard in her rice field, but her little house was quiet and she was lonely. Every night she prayed, “Please give me a child to love.”",
      vocab: ["widow", "lonely"],
      scene: { art: "img/stories/timun-mas/mbok-srini-prays.webp", fit: "contain", alt: "mbok srini prays", tone: "day", fx: [] },
    },
    {
      text: "One evening, the ground shook, and a huge green giant appeared in front of her house. It was Buto Ijo. “I can give you a child,” he said in a deep voice. “But when the child is seventeen, you must give the child to me.” Mbok Srini was afraid, but she wanted a child very much, so she promised. The giant gave her a cucumber seed and disappeared into the forest.",
      vocab: ["promised"],
      scene: { art: "img/stories/timun-mas/buto-ijo-gives-seed.webp", fit: "contain", alt: "buto ijo gives seed", tone: "day", fx: [] },
    },
    {
      text: "Mbok Srini planted the seed, and it grew very quickly. Soon a big golden cucumber hung from the plant. When she cut it open carefully, she found a beautiful baby girl inside! She named the baby Timun Mas, which means “golden cucumber”. Timun Mas grew up kind and clever. She helped her mother every day, and Mbok Srini loved her more than anything.",
      vocab: ["clever"],
      scene: { art: "img/stories/timun-mas/baby-in-golden-cucumber.webp", fit: "contain", alt: "baby in golden cucumber", tone: "day", fx: [] },
    },
    {
      text: "Many years passed, and Timun Mas was almost seventeen. Mbok Srini became more and more worried. She knew that the greedy giant wanted to take her daughter away to be his meal. She could not sleep at night. At last, she climbed Mount Gundul to visit a wise old hermit. He listened carefully and gave her four small bags with cucumber seeds, needles, salt and terasi (shrimp paste) inside.",
      vocab: ["greedy", "hermit"],
      scene: { art: "img/stories/timun-mas/hermit-gives-bags.webp", fit: "contain", alt: "hermit gives bags", tone: "day", fx: [] },
    },
    {
      text: "A few days later, Buto Ijo came back. “Where is the girl?” he roared. “Give her to me now!” Mbok Srini hugged her daughter and whispered, “Run, my child! Be brave!” Timun Mas took the four bags and ran into the forest. Soon the giant was close behind her. She threw the cucumber seeds, and a thick cucumber field grew around him. The hungry giant stopped to eat, and Timun Mas ran on.",
      vocab: ["roared"],
      scene: { art: "img/stories/timun-mas/cucumber-field-stops-giant.webp", fit: "contain", alt: "cucumber field stops giant", tone: "day", fx: [] },
    },
    {
      text: "But Buto Ijo soon caught up with her again. Timun Mas threw the needles. The needles were small, but they became a dense bamboo forest. The sharp bamboo hurt the giant’s feet, but he pushed through. Next, she threw the salt, and a wide sea appeared. The giant had to swim across it. He was tired now, but he still didn’t stop. Timun Mas did not panic. She took a deep breath and opened the last bag.",
      vocab: ["dense", "panic"],
      scene: { art: "img/stories/timun-mas/sea-blocks-giant.webp", fit: "contain", alt: "sea blocks giant", tone: "day", fx: [] },
    },
    {
      text: "She threw the terasi, and the ground turned into a hot, sticky swamp of mud. The giant stepped into it and began to sink. The mud pulled him down, and Buto Ijo was never seen again. Timun Mas ran home, and she and her mother hugged and cried with joy. From that day on, they lived happily and safely together. Mbok Srini never made a dangerous promise again.",
      vocab: ["swamp", "sink"],
      scene: { art: "img/stories/timun-mas/giant-sinks-mother-hugs.webp", fit: "contain", alt: "giant sinks mother hugs", tone: "day", fx: [] },
    },
  ],

  /* ---------- VOCABULARY (highlighted while reading) ---------- */
  vocabulary: [
    { word: "widow", forms: ["widow"], meaning: "a woman whose husband has died" },
    { word: "lonely", forms: ["lonely"], meaning: "sad because you are alone" },
    { word: "promised", forms: ["promised"], meaning: "said that you would really do something" },
    { word: "clever", forms: ["clever"], meaning: "quick to learn and understand" },
    { word: "greedy", forms: ["greedy"], meaning: "wanting more than you need" },
    { word: "hermit", forms: ["hermit"], meaning: "a person who lives alone, far from other people" },
    { word: "roared", forms: ["roared"], meaning: "shouted in a very loud, deep voice, like a lion" },
    { word: "dense", forms: ["dense"], meaning: "thick; with many things close together" },
    { word: "panic", forms: ["panic"], meaning: "suddenly become so afraid that you cannot think clearly" },
    { word: "swamp", forms: ["swamp"], meaning: "an area of wet, soft land full of mud" },
    { word: "sink", forms: ["sink"], meaning: "go down slowly under water or mud" },
  ],

  /* ---------- CHARACTERS ---------- */
  characters: [
    { id: "mbok", name: "Mbok Srini", img: "img/stories/timun-mas/mbok-srini.webp", role: "Timun Mas’s mother", traits: ["loving", "protective", "worried"],
      evidence: "Mbok Srini became more and more worried. At last, she climbed Mount Gundul to visit a wise old hermit." },
    { id: "timun", name: "Timun Mas", img: "img/stories/timun-mas/timun-mas.webp", role: "Main character", traits: ["calm", "brave", "clever", "loving"],
      evidence: "Timun Mas did not panic. She took a deep breath and opened the last bag." },
    { id: "buto", name: "Buto Ijo", img: "img/stories/timun-mas/buto-ijo.webp", role: "The green giant", traits: ["greedy", "cruel", "frightening"],
      evidence: "The hungry giant stopped to eat, and Timun Mas ran on." },
    { id: "hermit", name: "The Hermit", img: "img/stories/timun-mas/hermit.webp", role: "Helper on Mount Gundul", traits: ["wise", "helpful"],
      evidence: "He listened carefully and gave her four small bags." },
  ],

  /* Personality words taught in Character Detective */
  traitWords: [
    { word: "brave", meaning: "not afraid to do something difficult or dangerous" },
    { word: "calm", meaning: "quiet and relaxed, not nervous" },
    { word: "clever", meaning: "quick to learn and understand" },
    { word: "loving", meaning: "showing a lot of love and care" },
    { word: "protective", meaning: "wanting to keep someone safe" },
    { word: "greedy", meaning: "wanting more than you need" },
    { word: "cruel", meaning: "happy to hurt people or animals" },
    { word: "wise", meaning: "able to make good decisions" },
    { word: "helpful", meaning: "happy to help other people" },
    { word: "generous", meaning: "happy to give things to others" },
  ],

  /* ---------- GENERIC STRUCTURE ---------- */
  structure: {
    orientation: { pages: [1], summary: "A lonely widow, Mbok Srini, lived in a village in Central Java and prayed for a child." },
    complication: { pages: [2, 3, 4], summary: "She promised to give her child to the giant Buto Ijo at seventeen. Timun Mas was born from a golden cucumber, and her mother grew more and more worried." },
    resolution: { pages: [5, 6, 7], summary: "Buto Ijo came for Timun Mas. She ran away and threw the hermit’s four bags. The last one made a swamp of mud, and the giant sank." },
    coda: { pages: [7], summary: "Timun Mas and her mother lived happily and safely. Mbok Srini never made a dangerous promise again." },
  },
  mainConflict: "The greedy giant Buto Ijo came to take Timun Mas away, so she had to escape from him.",
  sequence: [
    "Mbok Srini prayed for a child.",
    "Buto Ijo gave her a cucumber seed.",
    "Mbok Srini found a baby girl inside a golden cucumber.",
    "The hermit gave Mbok Srini four small bags.",
    "Timun Mas threw the needles, and a bamboo forest grew.",
    "The giant sank into a swamp of mud.",
  ],
  grammarExamples: {
    regular: ["pray → prayed", "plant → planted", "climb → climbed"],
    irregular: ["grow → grew", "throw → threw", "find → found"],
    was: "Mbok Srini was afraid of the giant.",
    were: "The needles were small.",
    negative: "Timun Mas did not panic.",
    question: "Did Timun Mas escape from the giant?",
  },
  /* Portraits used for feedback bubbles */
  guides: { good: "img/stories/timun-mas/timun-mas.webp", hint: "img/stories/timun-mas/hermit.webp" },
  pastVerbs: [
    { base: "live", past: "lived", type: "regular" }, { base: "pray", past: "prayed", type: "regular" },
    { base: "promise", past: "promised", type: "regular" }, { base: "plant", past: "planted", type: "regular" },
    { base: "climb", past: "climbed", type: "regular" }, { base: "hug", past: "hugged", type: "regular" },
    { base: "roar", past: "roared", type: "regular" }, { base: "step", past: "stepped", type: "regular" },
    { base: "cry", past: "cried", type: "regular" },
    { base: "give", past: "gave", type: "irregular" }, { base: "grow", past: "grew", type: "irregular" },
    { base: "find", past: "found", type: "irregular" }, { base: "throw", past: "threw", type: "irregular" },
    { base: "catch", past: "caught", type: "irregular" }, { base: "take", past: "took", type: "irregular" },
    { base: "run", past: "ran", type: "irregular" }, { base: "shake", past: "shook", type: "irregular" },
    { base: "know", past: "knew", type: "irregular" },
  ],

  /* =========================================================
     CHALLENGES
     ========================================================= */
  challenges: {
    /* ---------------- 🔮 WORD HUNTER ---------------- */
    word: [
      {
        type: "mcq", skill: "Meaning in context", ref: 1,
        quote: "There lived a widow named Mbok Srini. Her husband had died many years before.",
        prompt: "What is a <b>widow</b>?",
        options: ["a woman whose husband has died", "a woman who has never had children", "a woman who lives near a forest", "a woman who works in a rice field"], answer: 0,
        hint: "Read the next sentence. What happened to Mbok Srini’s husband?",
        feedback: { 1: "It is true that she had no children — but that is not what <i>widow</i> means." },
        explain: "A <b>widow</b> is a woman whose husband has died.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 1,
        quote: "Every day she worked hard in her rice field, but her little house was quiet and she was lonely.",
        prompt: "Why was Mbok Srini <b>lonely</b>?",
        options: ["She lived alone, with no husband or children.", "She lived far away from the other villages.", "She was too busy to talk to her friends.", "She did not like the people in the village."], answer: 0,
        hint: "Her house was <i>quiet</i>. Who lived in the house with her?",
        explain: "<b>Lonely</b> = sad because you are alone. Her husband had died and she had no children.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 2,
        quote: "Mbok Srini was afraid, but she wanted a child very much, so she promised.",
        prompt: "What did Mbok Srini <b>promise</b>?",
        options: ["to give the child to the giant at seventeen", "to give the giant her rice field", "to plant cucumbers for the giant", "to leave the village with the giant"], answer: 0,
        hint: "Read what Buto Ijo said just before: “But when the child is seventeen…”",
        explain: "To <b>promise</b> = to say you will really do something. She promised to give the child to Buto Ijo.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 3,
        quote: "Timun Mas grew up kind and clever.",
        prompt: "Which word is closest in meaning to <b>clever</b>?",
        options: ["smart", "strong", "shy", "rich"], answer: 0,
        hint: "A clever person learns quickly and has good ideas.",
        explain: "<b>Clever</b> = <b>smart</b>: quick to learn and understand.",
      },
      {
        type: "mcq", skill: "Context clue", ref: 4,
        quote: "At last, she climbed Mount Gundul to visit a wise old hermit.",
        prompt: "What is a <b>hermit</b>?",
        options: ["a person who lives alone, far from others", "a king who rules a large kingdom", "a farmer who grows cucumbers", "a soldier who protects a village"], answer: 0,
        hint: "Mbok Srini had to <i>climb a mountain</i> to find him. Did he live in the village with other people?",
        explain: "A <b>hermit</b> lives alone, far from other people — like this wise old man on Mount Gundul.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 5, image: "img/stories/timun-mas/buto-ijo.webp",
        quote: "“Where is the girl?” he roared. “Give her to me now!”",
        prompt: "Look at the giant. He didn’t speak quietly. He <b>roared</b>. How did his voice sound?",
        options: ["very loud and deep", "soft and gentle", "quiet and sad", "slow and tired"], answer: 0,
        hint: "Think of the sound a lion makes. And the giant was angry and impatient: “Give her to me now!”",
        explain: "To <b>roar</b> = to shout in a very loud, deep voice, like a lion.",
      },
      {
        type: "mcq", skill: "Synonym", ref: 6,
        quote: "The needles were small, but they became a dense bamboo forest.",
        prompt: "Which word is closest in meaning to <b>dense</b>?",
        options: ["thick", "empty", "short", "bright"], answer: 0,
        hint: "The giant had to push through the bamboo. Were the bamboo plants far apart or close together?",
        feedback: { 1: "Opposite! An empty forest would be easy to walk through." },
        explain: "<b>Dense</b> = <b>thick</b>, with many things very close together.",
      },
      {
        type: "mcq", skill: "Word with two meanings", ref: 7,
        quote: "The giant stepped into it and began to sink.",
        prompt: "What does <b>sink</b> mean in this sentence?",
        options: ["go down slowly into the mud", "a bowl for washing dishes", "stay on top of the mud", "jump high into the air"], answer: 0,
        hint: "Many words have more than one meaning. Here, <i>sink</i> is a verb. What happens to a heavy giant in soft mud?",
        feedback: { 1: "That is a real meaning of <i>sink</i> (a noun, in the kitchen) — but not in this sentence.", 2: "Opposite! Staying on top is to <i>float</i>." },
        explain: "Here, <b>sink</b> = go down slowly under water or mud.",
      },
      {
        type: "mcq", skill: "Antonym", ref: 4,
        prompt: "Which word is the <b>opposite</b> of <b>greedy</b>?",
        options: ["generous", "selfish", "hungry", "cruel"], answer: 0,
        hint: "A greedy person wants to keep everything. Find the word for someone who happily gives things to others.",
        feedback: { 1: "Selfish is close in meaning to greedy, not the opposite." },
        explain: "A <b>greedy</b> person wants more and more; a <b>generous</b> person gives to others.",
      },
      {
        type: "mcq", skill: "Meaning in context", ref: 6,
        quote: "Timun Mas did not panic. She took a deep breath and opened the last bag.",
        prompt: "“Timun Mas did not <b>panic</b>” means she…",
        options: ["stayed calm and could think clearly.", "screamed and dropped all the bags.", "stopped running and sat down.", "ran back home to her mother."], answer: 0,
        hint: "Look at the next sentence: she took a deep breath. What do people do when they want to stay calm?",
        explain: "To <b>panic</b> = to become so afraid that you can’t think. She did <i>not</i> panic: she stayed calm.",
      },
      {
        type: "mcq", skill: "Visual vocabulary", ref: 2, image: "img/stories/timun-mas/buto-ijo-gives-seed.webp",
        prompt: "Look at the picture. Buto Ijo gave Mbok Srini a cucumber ___. She planted it, and it grew very quickly.",
        options: ["seed", "field", "flower", "bag"], answer: 0,
        hint: "What do you put in the ground to grow a new plant?",
        feedback: { 3: "The bags came later, from the hermit. What did the giant give her?" },
        explain: "A <b>seed</b> is the small thing you plant to grow a new plant.",
      },
      {
        type: "sort", skill: "Word–meaning match", layout: "match", capacity: 1,
        prompt: "Drag each word to its meaning. <span class='tip'>(Or tap a word, then tap a meaning.)</span>",
        bins: [
          { id: "widow", label: "a woman whose husband has died" },
          { id: "lonely", label: "sad because you are alone" },
          { id: "greedy", label: "wanting more than you need" },
          { id: "hermit", label: "a person who lives alone, far from others" },
          { id: "swamp", label: "an area of wet, soft land full of mud" },
          { id: "clever", label: "quick to learn and understand" },
        ],
        cards: [
          { text: "widow", bin: "widow" }, { text: "lonely", bin: "lonely" }, { text: "greedy", bin: "greedy" },
          { text: "hermit", bin: "hermit" }, { text: "swamp", bin: "swamp" }, { text: "clever", bin: "clever" },
        ],
        hint: "Start with the words you are sure about. The giant sank in a <i>swamp</i>; the old man on Mount Gundul was a <i>hermit</i>.",
        explain: "Great word hunting! You matched all six words.",
      },
    ],

    /* ---------------- 🧩 STORY DETECTIVE ---------------- */
    structure: [
      {
        type: "sort", skill: "Sort the story",
        prompt: "Put each event card in the correct part of the narrative.",
        bins: [
          { id: "orientation", label: "Orientation", img: "img/st-orientation.webp", sub: "Who? Where? When?" },
          { id: "complication", label: "Complication", img: "img/st-complication.webp", sub: "What problem happened?" },
          { id: "resolution", label: "Resolution", img: "img/st-resolution.webp", sub: "How was it solved?" },
          { id: "coda", label: "Ending / Coda", img: "img/st-ending.webp", sub: "What happened afterward?" },
        ],
        cards: [
          { text: "A lonely widow named Mbok Srini lived in a village in Central Java.", bin: "orientation" },
          { text: "Every night, Mbok Srini prayed for a child.", bin: "orientation" },
          { text: "Mbok Srini promised to give her child to Buto Ijo at seventeen.", bin: "complication" },
          { text: "Mbok Srini knew the greedy giant wanted to take her daughter away.", bin: "complication" },
          { text: "Timun Mas threw the magic bags one by one.", bin: "resolution" },
          { text: "The giant sank into a hot, sticky swamp of mud.", bin: "resolution" },
          { text: "Timun Mas and her mother lived happily and safely.", bin: "coda" },
          { text: "Mbok Srini never made a dangerous promise again.", bin: "coda" },
        ],
        hint: "Orientation introduces the character and place. Complication = the problem. Resolution = how the problem was solved. Coda = life afterward.",
        explain: "The story moves from <b>introduction</b> → <b>a dangerous promise</b> → <b>a clever escape</b> → <b>a safe, happy ending</b>.",
      },
      {
        type: "mcq", skill: "Find the complication", ref: 2,
        prompt: "Which sentence shows the <b>beginning of the complication</b>?",
        options: [
          "“One evening, the ground shook, and a huge green giant appeared…”",
          "“Every day she worked hard in her rice field.”",
          "“Timun Mas grew up kind and clever.”",
          "“From that day on, they lived happily and safely together.”",
        ], answer: 0,
        hint: "Look for the moment when something frightening and unexpected arrives.",
        explain: "The giant’s arrival starts the problem: soon Mbok Srini makes her dangerous promise.",
      },
      {
        type: "mcq", skill: "Find the main conflict", ref: 5,
        prompt: "What is the <b>main conflict</b> in <i>Timun Mas</i>?",
        options: [
          "Buto Ijo wanted to take Timun Mas away, so she had to escape.",
          "Mbok Srini and the hermit argued about the four magic bags.",
          "Timun Mas got lost in the forest and could not find her home.",
          "The villagers were angry because the cucumber grew so quickly.",
        ], answer: 0,
        hint: "The main conflict is the biggest problem the main character faces. Who was a danger to Timun Mas?",
        feedback: {
          1: "Not quite. The hermit helped Mbok Srini — they did not argue.",
          2: "Look again: she ran home safely at the end. Getting lost was not the problem.",
          3: "The villagers are not in this story. Think about the giant.",
        },
        explain: "The central problem: the <b>greedy giant</b> came to take Timun Mas, and she had to <b>escape</b>.",
      },
      {
        type: "order", skill: "Story sequence",
        prompt: "Put the events in the correct order. <span class='tip'>Tap an event to add it to the next empty step.</span>",
        items: [
          "Mbok Srini prayed for a child.",
          "Buto Ijo gave her a cucumber seed.",
          "Mbok Srini found a baby girl inside a golden cucumber.",
          "The hermit gave Mbok Srini four small bags.",
          "Timun Mas threw the needles, and a bamboo forest grew.",
          "The giant sank into a swamp of mud.",
        ],
        hint: "A prayer → a seed → a baby → help from the mountain → the escape → the end of the giant.",
        explain: "Perfect timeline! Narratives are told in <b>chronological order</b>.",
      },
      {
        type: "mcq", skill: "Cause & effect", ref: 4,
        prompt: "Why did Mbok Srini become <b>more and more worried</b>?",
        options: [
          "Timun Mas was almost seventeen.",
          "Her rice field was too small.",
          "Timun Mas was very ill.",
          "The hermit told her bad news.",
        ], answer: 0,
        hint: "Remember her promise. What would happen when the child was seventeen?",
        explain: "Cause: Timun Mas was almost <b>seventeen</b> → Effect: Mbok Srini knew the giant would come soon.",
      },
      {
        type: "sort", skill: "Cause & effect match", layout: "match", capacity: 1,
        prompt: "Match each <b>cause</b> with its <b>effect</b>.",
        bins: [
          { id: "c1", label: "Timun Mas threw the cucumber seeds.", kicker: "CAUSE" },
          { id: "c2", label: "Timun Mas threw the needles.", kicker: "CAUSE" },
          { id: "c3", label: "Timun Mas threw the salt.", kicker: "CAUSE" },
          { id: "c4", label: "Timun Mas threw the terasi.", kicker: "CAUSE" },
        ],
        cards: [
          { text: "The hungry giant stopped to eat.", bin: "c1" },
          { text: "Sharp bamboo hurt the giant’s feet.", bin: "c2" },
          { text: "The giant had to swim across a wide sea.", bin: "c3" },
          { text: "The giant sank into a swamp of mud.", bin: "c4" },
        ],
        hint: "Think about what each thing became: seeds → a field, needles → bamboo, salt → the sea, terasi → mud.",
        explain: "Each bag caused a new obstacle. The last one finally stopped the giant!",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 2, structureOptions: true,
        quote: "“But when the child is seventeen, you must give the child to me.” Mbok Srini was afraid, but she wanted a child very much, so she promised.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
        hint: "Is a problem being created here, or is it being solved?",
        explain: "The dangerous promise creates the problem — this is the <b>complication</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 7, structureOptions: true,
        quote: "She threw the terasi, and the ground turned into a hot, sticky swamp of mud. The giant stepped into it and began to sink.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 2,
        hint: "What happens to the giant — the source of the danger — here?",
        explain: "The danger ends: the giant sinks. The problem is <b>solved</b> — this is the <b>resolution</b>.",
      },
      {
        type: "mcq", skill: "Structure hunt", ref: 7, structureOptions: true,
        quote: "From that day on, they lived happily and safely together. Mbok Srini never made a dangerous promise again.",
        prompt: "Which part of the narrative is this paragraph?",
        options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 3,
        hint: "“From that day on…” tells us about life <i>after</i> the problem was solved.",
        explain: "It tells us what happened afterward and the lesson: this is the <b>ending / coda</b>.",
      },
      {
        type: "mcq", skill: "Climax", ref: 6,
        prompt: "Which moment is the <b>climax</b> — the most exciting and dangerous moment of the story?",
        options: [
          "Timun Mas opened the last bag with the giant close behind.",
          "Mbok Srini cut open the golden cucumber very carefully.",
          "Mbok Srini climbed Mount Gundul to visit the hermit.",
          "Timun Mas and her mother hugged and cried with joy.",
        ], answer: 0,
        hint: "At the climax, the danger is greatest and we don’t know what will happen next.",
        feedback: { 3: "That is a happy moment after the danger is over." },
        explain: "Only one bag was left and the giant was still coming — the <b>climax</b>. After it, the danger ends.",
      },
    ],

    /* ---------------- 🎭 CHARACTER DETECTIVE ---------------- */
    character: [
      {
        type: "mcq", skill: "Trait → Step 1", character: "timun", ref: 5,
        prompt: "Character: <b>Timun Mas</b>. Choose the <b>best</b> trait.",
        options: ["brave", "selfish", "lazy", "rude"], answer: 0,
        hint: "What did she do when the huge giant came for her?",
        explain: "She ran alone into the forest and faced the giant: she was <b>brave</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "timun", ref: 5,
        prompt: "You chose <b>brave</b>. Which event <b>best supports</b> your answer?",
        options: [
          "She ran alone into the forest with the giant behind her.",
          "She was born inside a big golden cucumber.",
          "She helped her mother in the house every day.",
          "She hugged her mother when she came home.",
        ], answer: 0,
        hint: "Evidence must <i>show</i> the trait. Which action was dangerous?",
        feedback: { 2: "That shows she was loving and helpful — but not brave." },
        explain: "Character → Trait → <b>Evidence</b>. Running from a giant with only four small bags shows courage.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "buto", ref: 4,
        prompt: "Character: <b>Buto Ijo</b>. Which trait describes him best?",
        options: ["greedy", "generous", "wise", "gentle"], answer: 0,
        hint: "What did he want to do with the girl?",
        explain: "He wanted to take a child away from her mother: he was <b>greedy</b> (and cruel).",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "buto", ref: 5,
        prompt: "Which evidence <b>best proves</b> that Buto Ijo was greedy?",
        options: [
          "Even during the chase, he stopped to eat the cucumbers.",
          "He appeared in front of the house one evening.",
          "He spoke to Mbok Srini in a deep voice.",
          "He had to swim across a wide sea.",
        ], answer: 0,
        hint: "Three of these are just facts. Which action shows that he wanted more and more food?",
        explain: "He was chasing Timun Mas, but he still <b>stopped to eat</b> — that shows greed.",
      },
      {
        type: "mcq", skill: "Trait → Step 1", character: "mbok", ref: 4,
        prompt: "Character: <b>Mbok Srini</b> (when Timun Mas was almost seventeen). Choose the best trait.",
        options: ["protective", "cruel", "lazy", "arrogant"], answer: 0,
        hint: "What did she do when she knew the giant would come for her daughter?",
        explain: "She tried hard to keep her daughter safe: she was <b>protective</b>.",
      },
      {
        type: "mcq", skill: "Evidence → Step 2", character: "mbok", ref: 4,
        prompt: "You chose <b>protective</b>. Which event <b>best supports</b> your answer?",
        options: [
          "She climbed Mount Gundul to ask the hermit for help.",
          "She planted the cucumber seed in her garden.",
          "She worked hard in her rice field every day.",
          "She prayed every night for a child to love.",
        ], answer: 0,
        hint: "Protective = wanting to keep someone safe. Which action was done to save Timun Mas?",
        feedback: { 3: "That shows she was lonely and wanted a child — Timun Mas wasn’t born yet." },
        explain: "She made a long, hard trip to get help against the giant. That shows she was <b>protective</b>.",
      },
      {
        type: "multi", skill: "Two best traits", character: "timun", ref: 6, pick: 2,
        prompt: "Choose <b>TWO</b> more traits that describe <b>Timun Mas</b>.",
        options: ["clever", "calm", "greedy", "lazy", "cruel", "rude"], answer: [0, 1],
        hint: "Read how page 3 describes her as she grew up, and what she did <i>not</i> do on page 6.",
        explain: "The text says she was <b>clever</b>, and she stayed <b>calm</b>: she did not panic and took a deep breath.",
      },
      {
        type: "mcq", skill: "Evidence hunt", character: "hermit", ref: 4,
        prompt: "The hermit is described as <b>wise</b>. Which evidence supports this?",
        options: [
          "He gave her four bags that could stop the giant.",
          "He lived on Mount Gundul, far from the village.",
          "He was an old man who lived all alone.",
          "He met Buto Ijo in the forest many times.",
        ], answer: 0,
        hint: "A wise person knows how to solve difficult problems. Which action solved a problem?",
        explain: "He knew exactly what could stop a giant — a <b>wise</b> plan.",
      },
      {
        type: "mcq", skill: "Who am I?",
        prompt: "<b>Who am I?</b><ul class='clues'><li>I lived on a mountain.</li><li>I listened carefully to a worried mother.</li><li>I gave her four small bags.</li></ul>",
        options: ["The hermit", "Mbok Srini", "Buto Ijo", "Timun Mas"], answer: 0,
        hint: "Who did Mbok Srini visit on Mount Gundul?",
        explain: "The wise old <b>hermit</b> on Mount Gundul gave her the four bags.",
      },
      {
        type: "sort", skill: "Trait match", layout: "match", capacity: 1,
        prompt: "Match each character with the personality adjective that fits best.",
        bins: [
          { id: "timun", label: "Timun Mas", img: "img/stories/timun-mas/timun-mas.webp" },
          { id: "mbok", label: "Mbok Srini", img: "img/stories/timun-mas/mbok-srini.webp" },
          { id: "buto", label: "Buto Ijo", img: "img/stories/timun-mas/buto-ijo.webp" },
          { id: "hermit", label: "The Hermit", img: "img/stories/timun-mas/hermit.webp" },
        ],
        cards: [
          { text: "brave", bin: "timun" }, { text: "protective", bin: "mbok" },
          { text: "greedy", bin: "buto" }, { text: "wise", bin: "hermit" },
        ],
        hint: "Remember the evidence: who ran from the giant, who looked for help, who wanted to take a child, and who gave the bags?",
        explain: "Every trait matches evidence from the text. Well done, detective!",
      },
      {
        type: "mcq", skill: "Character comparison",
        prompt: "How were Timun Mas and Buto Ijo <b>different</b>?",
        options: [
          "Timun Mas was kind and clever; Buto Ijo was greedy and cruel.",
          "Timun Mas was greedy and cruel; Buto Ijo was kind and clever.",
          "Timun Mas was lazy and rude; Buto Ijo was wise and helpful.",
          "Timun Mas was shy and quiet; Buto Ijo was calm and patient.",
        ], answer: 0,
        hint: "Page 3 describes Timun Mas. Page 4 describes the giant.",
        explain: "The <b>kind, clever</b> girl is the opposite of the <b>greedy, cruel</b> giant.",
      },
      {
        type: "mcq", skill: "Inference: motive", character: "mbok", ref: 2,
        prompt: "Why did Mbok Srini agree to the giant’s dangerous deal?",
        options: [
          "She was lonely and wanted a child very much.",
          "She was not afraid of the huge green giant.",
          "She wanted the giant to help in her rice field.",
          "She thought the giant was kind and friendly.",
        ], answer: 0,
        hint: "Read page 1 again. What did she pray for every night?",
        feedback: { 1: "Look again: the text says she <i>was</i> afraid." },
        explain: "Her wish for a child was stronger than her fear. That is why she <b>promised</b>.",
      },
    ],

    /* ---------------- ⏳ PAST TENSE LAB ---------------- */
    grammar: [
      {
        type: "verbs", skill: "Verb transform",
        prompt: "Type the <b>simple past</b> form of each verb from the story.",
        verbs: [
          { base: "pray", past: "prayed" }, { base: "plant", past: "planted" }, { base: "climb", past: "climbed" },
          { base: "grow", past: "grew" }, { base: "find", past: "found" }, { base: "throw", past: "threw" },
        ],
        hint: "Regular verbs add <b>-ed</b> (pray → prayed). Irregular verbs change form (grow → gr _ w).",
        explain: "<b>prayed, planted, climbed</b> are regular. <b>grew, found, threw</b> are irregular.",
      },
      {
        type: "verbs", skill: "Verb transform",
        prompt: "More story verbs! Type the <b>simple past</b> form.",
        verbs: [
          { base: "hug", past: "hugged" }, { base: "cry", past: "cried" }, { base: "step", past: "stepped" },
          { base: "give", past: "gave" }, { base: "catch", past: "caught" }, { base: "take", past: "took" },
        ],
        hint: "Careful with spelling: hug → hug<b>g</b>ed, cry → cr<b>ied</b>. For the irregular verbs, look in the story.",
        explain: "Regular: <b>hugged, cried, stepped</b>. Irregular: <b>gave, caught, took</b>.",
      },
      {
        type: "mcq", skill: "Choose the correct verb", ref: 2,
        prompt: "One evening, the ground ___, and a huge green giant appeared.",
        options: ["shook", "shaked", "shakes", "shaking"], answer: 0,
        hint: "The story happened in the past. <i>Shake</i> is an irregular verb.",
        feedback: { 1: "<i>Shake</i> is irregular — we don’t add -ed." },
        explain: "<b>shake → shook</b> (irregular): “One evening, the ground <b>shook</b>.”",
      },
      {
        type: "mcq", skill: "Was / were", ref: 6,
        prompt: "The needles ___ small, but they became a dense bamboo forest.",
        options: ["was", "were", "are", "is"], answer: 1,
        hint: "“The needles” is plural (more than one). Which past form goes with plural subjects?",
        explain: "<b>were</b> for plural subjects (they, the needles). <b>was</b> for I / he / she / it.",
      },
      {
        type: "mcq", skill: "Was / were", ref: 2,
        prompt: "Mbok Srini ___ afraid of the huge green giant.",
        options: ["were", "was", "is", "be"], answer: 1,
        hint: "“Mbok Srini” = she (one person).",
        explain: "He / she / it → <b>was</b>.",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 6,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Timun Mas throwed the salt, and a wide sea appeared.",
        wrong: 2, options: ["threw", "throw", "thrown", "throws"], answer: 0,
        hint: "Find the verb that is not a real English word. Is <i>throw</i> regular?",
        stage2: "Now choose the correct past form of <b>throw</b>:",
        feedback2: { 2: "<b>thrown</b> needs <i>has</i> or <i>had</i> before it. Here we need the simple past." },
        explain: "<b>throw → threw</b> (irregular): “Timun Mas <b>threw</b> the salt.”",
      },
      {
        type: "fix", skill: "Fix the sentence", ref: 3,
        prompt: "Tap the <b>incorrect</b> word.",
        sentence: "Mbok Srini planted the seed, and it grow very quickly.",
        wrong: 7, options: ["grew", "growed", "grown", "grows"], answer: 0,
        hint: "There are two verbs. One is correct (planted). Check the other one.",
        stage2: "Choose the correct past form of <b>grow</b>:",
        feedback2: { 1: "<b>Grow</b> is irregular — we don’t add -ed." },
        explain: "<b>grow → grew</b>. Both verbs in the sentence must be past: planted … <b>grew</b>.",
      },
      {
        type: "fix", skill: "Negative challenge", ref: 6,
        prompt: "This negative sentence has a mistake. Tap the <b>incorrect</b> word.",
        sentence: "The tired giant still didn’t stopped.",
        wrong: 5, options: ["stop", "stops", "stopping", "to stop"], answer: 0,
        hint: "After <b>didn’t</b>, we use the base verb (V1).",
        stage2: "After <b>didn’t</b>, which form is correct?",
        explain: "<b>didn’t + base verb</b>: “The tired giant still didn’t <b>stop</b>.”",
      },
      {
        type: "mcq", skill: "Negative sentence", ref: 4,
        prompt: "Mbok Srini was so worried that she ___ at night.",
        options: ["couldn’t sleep", "couldn’t slept", "can’t sleeps", "didn’t slept"], answer: 0,
        hint: "After <i>couldn’t</i> or <i>didn’t</i>, the verb goes back to the base form.",
        feedback: { 1: "Almost! After couldn’t, use the base verb.", 3: "After didn’t, the verb must be the base form, not <i>slept</i>." },
        explain: "<b>couldn’t + sleep</b> (base verb) — the past of <i>can’t sleep</i>.",
      },
      {
        type: "order", skill: "Sentence builder", inline: true, ref: 5,
        prompt: "Build the sentence in the simple past. <span class='tip'>One chunk is not needed.</span>",
        items: ["Timun Mas", "took", "the four bags", "and ran", "into the forest."],
        extras: ["taked"],
        hint: "Start with “Timun Mas…”. <i>Take</i> is irregular.",
        explain: "“Timun Mas <b>took</b> the four bags and <b>ran</b> into the forest.” — two past verbs joined by <i>and</i>.",
      },
      {
        type: "order", skill: "Question challenge", inline: true, ref: 6,
        prompt: "Build a simple past <b>question</b>. <span class='tip'>One chunk is not needed.</span>",
        items: ["Did", "the giant", "swim", "across the sea?"],
        extras: ["swam"],
        hint: "Question pattern: <b>Did + subject + base verb…?</b>",
        explain: "“<b>Did</b> the giant <b>swim</b> across the sea?” — Yes, he did.",
      },
      {
        type: "mcq", skill: "Question challenge", ref: 6,
        prompt: "“___ Timun Mas throw the salt?” — “Yes, she did.”",
        options: ["Did", "Was", "Does", "Were"], answer: 0,
        hint: "Look at the short answer: “Yes, she <b>did</b>.” And <i>throw</i> is a main verb.",
        feedback: { 1: "<b>Was</b> is used without a main verb (e.g. Was she brave?). Here we have <i>throw</i>." },
        explain: "Past questions with a main verb use <b>Did</b>: Did + subject + base verb?",
      },
    ],
  },

  /* ---------------- 🌟 MASTER THE STORY (final) ---------------- */
  final: [
    {
      type: "mcq", skill: "Vocabulary in context", ref: 6,
      quote: "The sharp bamboo hurt the giant’s feet, but he pushed through.",
      prompt: "What does “he pushed through” tell us?",
      options: ["He kept moving through the bamboo.", "He went back to the village.", "He sat down because of the pain.", "He waited for the bamboo to die."], answer: 0,
      hint: "The word <b>but</b> shows a contrast: the bamboo hurt him, <i>but</i>… Did he stop?",
      explain: "He did not stop: he <b>kept moving</b> through the bamboo, even with sore feet.",
    },
    {
      type: "mcq", skill: "Simple past", ref: 7,
      prompt: "After the giant disappeared, Timun Mas ___ home to her mother.",
      options: ["ran", "runs", "run", "running"], answer: 0,
      hint: "Past time: “After the giant disappeared…”",
      explain: "<b>run → ran</b> (irregular).",
    },
    {
      type: "mcq", skill: "Narrative structure", structureOptions: true, ref: 4,
      quote: "Mbok Srini became more and more worried. … She could not sleep at night.",
      prompt: "Which part of the narrative do these sentences belong to?",
      options: ["Orientation", "Complication", "Resolution", "Ending / Coda"], answer: 1,
      hint: "Is the danger growing here, or has it ended?",
      explain: "The worry and danger are growing: this is the <b>complication</b>.",
    },
    {
      type: "order", skill: "Sequence of events",
      prompt: "Put these events in order.",
      items: [
        "Buto Ijo came back and asked for the girl.",
        "A thick cucumber field grew around the giant.",
        "The giant swam across a wide sea.",
        "Timun Mas and her mother hugged and cried with joy.",
      ],
      hint: "The giant arrives → the first bag → the third bag → home again.",
      explain: "Great timeline memory!",
    },
    {
      type: "mcq", skill: "Main conflict",
      prompt: "Which of these is the <b>central problem</b> of the story?",
      options: [
        "A giant came to take a girl away because of her mother’s promise.",
        "A hermit did not want to give his magic bags to anyone.",
        "A widow could not grow cucumbers in her rice field.",
        "A girl wanted to leave her village to see the sea.",
      ], answer: 0,
      hint: "Which problem connects the promise at the start to the chase at the end?",
      feedback: { 1: "The hermit gave the bags gladly — he was helpful." },
      explain: "The promise brought the giant back for Timun Mas — the <b>main conflict</b>.",
    },
    {
      type: "mcq", skill: "Characterization", character: "mbok", ref: 5,
      prompt: "Mbok Srini was <b>loving</b>. Which action <b>best shows</b> this when the giant came back?",
      options: [
        "She hugged her daughter and told her to run.",
        "She planted the seed and watched it grow.",
        "She worked hard in her rice field every day.",
        "She agreed to give the child to Buto Ijo.",
      ], answer: 0,
      hint: "Loving = showing a lot of love and care. What did she do when Buto Ijo roared, “Give her to me now!”?",
      feedback: { 3: "That was a dangerous promise, made years before. What did she do when the giant came back?" },
      explain: "“Mbok Srini <b>hugged her daughter</b> and whispered, ‘Run, my child! Be brave!’” She wanted to save her child.",
    },
    {
      type: "mcq", skill: "Cause & effect", ref: 5,
      prompt: "What happened <b>because</b> Mbok Srini made a promise to Buto Ijo?",
      options: [
        "The giant came back years later for Timun Mas.",
        "The hermit refused to help Mbok Srini.",
        "Mbok Srini had to leave her village.",
        "Timun Mas went into the forest to find the giant.",
      ], answer: 0,
      hint: "The promise was about what would happen when the child was seventeen.",
      explain: "Cause: the promise → Effect: when Timun Mas was almost seventeen, <b>the giant came back</b> for her.",
    },
    {
      type: "mcq", skill: "Turning point",
      prompt: "Which event <b>changed the direction</b> of the story most significantly, from hopeless to hopeful?",
      options: [
        "The hermit gave Mbok Srini four small bags.",
        "Timun Mas grew up kind and clever.",
        "Mbok Srini planted the cucumber seed.",
        "A thick cucumber field grew around the giant.",
      ], answer: 0,
      hint: "Before this event, Mbok Srini could not sleep and had no way to fight a giant. After it, she had a plan.",
      feedback: { 3: "That was one result of an earlier, bigger change. Where did the seeds come from?" },
      explain: "The hermit’s bags were the <b>turning point</b>: without them, Timun Mas could not escape.",
    },
    {
      type: "mcq", skill: "Inference", ref: 5,
      quote: "The hungry giant stopped to eat, and Timun Mas ran on.",
      prompt: "What does this tell us about Buto Ijo?",
      options: [
        "He cared more about food than about the chase.",
        "He wanted to help Timun Mas to escape.",
        "He was too tired to walk any more.",
        "He was afraid of the cucumber field.",
      ], answer: 0,
      hint: "The story doesn’t say it directly. He was chasing the girl — so why did he stop?",
      explain: "He could not stop himself from eating, even during the chase. His <b>greed</b> gave Timun Mas time to run.",
    },
    {
      type: "mcq", skill: "Inference: decision", ref: 4,
      prompt: "Why did Mbok Srini <b>decide</b> to visit the hermit?",
      options: [
        "She hoped he could help her protect Timun Mas.",
        "She wanted to ask him for another child.",
        "She wanted to give him a golden cucumber.",
        "She hoped he would find her a new husband.",
      ], answer: 0,
      hint: "Read what she knew and felt just before she climbed Mount Gundul.",
      explain: "She was worried about the giant, so she looked for a <b>wise</b> person who could help her <b>protect</b> her daughter.",
    },
    {
      type: "mcq", skill: "Inference", ref: 7,
      quote: "Mbok Srini never made a dangerous promise again.",
      prompt: "Why do you think Mbok Srini never made a dangerous promise again?",
      options: [
        "Her promise almost cost her daughter’s life.",
        "The hermit told her never to make promises.",
        "The giant came back for a second child.",
        "She moved to a new village far away.",
      ], answer: 0,
      hint: "Think about what her first promise caused. The story doesn’t say it directly.",
      feedback: { 1: "The hermit gave her bags and advice about the giant — not about promises." },
      explain: "Her promise put Timun Mas in terrible danger. She <b>learned</b> from it.",
    },
    {
      type: "mcq", skill: "Moral value",
      prompt: "What can readers learn from this story?",
      options: [
        "Stay calm and think clearly when you are in danger.",
        "Strong giants always win against small children.",
        "Never visit old people who live on mountains.",
        "Always give people everything they ask for.",
      ], answer: 0,
      hint: "How did Timun Mas escape? Was it strength, or something else?",
      feedback: { 1: "The giant was strong — but he lost! What helped Timun Mas win?" },
      explain: "Timun Mas won with <b>courage, cleverness and a calm mind</b> — and her mother’s love and the hermit’s help. Also: be careful with dangerous promises.",
    },
  ],
});
